### ISSUE TITLE
How to expose popper options in v9 components that use popper

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#19144] opened 2021-07-27 08:54 UTC
How to expose popper options in v9 components that use popper

**Comment by gouttierre** [comment] 2021-08-06 18:10
@ling1726 - Reopening this as the bot closed it.

cc @miroslavstastny , @Hotell , @behowell

**Comment by behowell** [comment] 2021-08-06 23:39
This looks like it might be a duplicate of #19145. I'm going to close it, but @ling1726 please re-open if I missed something.

**Closed by behowell** 2021-08-06 23:39 UTC
