### ISSUE TITLE
X and Y Axis within LineChart do not theme

### ISSUE THREAD

**Issue by brandonthomas** [microsoft/fluentui#13098] opened 2020-05-12 00:08 UTC
### Environment Information

- **Package version(s)**: @uifabric/charting

### Please provide a reproduction of the bug in a codepen:
- Instantiate a LineChart with data
- Inject theme into the app or feature and change from the default

Style file: https://github.com/microsoft/fluentui/blob/master/packages/charting/src/components/LineChart/LineChart.styles.ts

#### Actual behavior:
the x and y axis don't theme. Nor do the ticks.

#### Expected behavior:
They theme properly

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: (if applicable) Any using LineChart

**Comment by aneeshack4** [comment] 2020-05-12 15:24
@brandonthomas Thanks for reaching out to us. Can you please provide a codepen that shows exactly what you're trying to do? cc @Raghurk charting package owner - Raghu, was allowing the x and y axis to be themed intended behavior?

**Comment by Raghurk** [comment] 2020-05-12 19:53
@brandonthomas  we are working on fixing this.

**Comment by RajeshGoriga** [comment] 2020-05-13 11:57
Raise a PR for this #13140

**Comment by ecraig12345** [comment] 2020-05-18 17:03
Fixed by #13140

**Closed by ecraig12345** 2020-05-18 17:03 UTC
Labels: Needs: Actionable Feedback :female_detective:, Needs: Discussion 🙋, Package: charting
