### ISSUE TITLE
Narrator reads invalid information when selecting months in the DatePicker

### ISSUE THREAD

**Issue by lucas-stanford** [microsoft/fluentui#18184] opened 2021-05-13 23:25 UTC
Environment Information
Version: 2004 (OS Build: 20236.1005)
Browser: Edge chromium
Screen Reader: Narrator
Bug id: 8787914

Describe the issue:
Narrator is announcing readonly while navigating on "Jan" and other months of Calendar pop up.

Please provide a reproduction of the issue in a codepen:
Reproable here: https://fabricweb.z5.web.core.windows.net/oufr/7.157.1/#/examples/datepicker

Actual behavior:
Narrator is announcing "January 2020 **readonly** column 1 row 1 item" while navigating on "Jan" button of Calendar pop up.

Expected behavior:
Narrator is announcing "January 2020 column 1 row 1 item" while navigating on "Jan" button of Calendar pop up.

Documentation describing expected behavior
N/A

![](https://user-images.githubusercontent.com/3011776/106051807-c23f6a80-609d-11eb-86e3-36aeb1d423ba.png)

**Comment by lucas-stanford** [comment] 2021-05-14 00:24
This was closed: https://github.com/microsoft/fluentui/issues/16673

I just verified this here:  https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker
and here: https://fabricweb.z5.web.core.windows.net/oufr/8.14.7/#/examples/datepicker

Note: it's edge and narrator and the month panel on the right only.

**Comment by gouttierre** [comment] 2021-06-15 14:50
@lucas-stanford - thank you for proving details into the issue you are facing with the DatePicker.

@miroslavstastny / @smhigley   - Would you be able to confirm if this is a regression, or if this behavior is an issue? I am not sure if you will require to revisit item #16673.

**Comment by smhigley** [comment] 2021-06-28 17:01
Narrator's not really wrong here in announcing it as readonly, because it's not editable. The basic issue essentially centers around poor spec definitions for how grid interactivity works, and the resulting variations in implementation between screen readers.

If we don't explicitly mark gridcells readonly, NVDA will incorrectly announce them as "editable", and if we do mark them readonly, Narrator announces "readonly". We made a choice to prioritize the NVDA experience, and if things change in the future, we could remove the explicit readonly on the gridcells. There isn't really a single right answer here, and I don't think it makes sense to change our current approach now.

This is definitely something we should revisit in the future, if support changes or more user feedback comes in. I actually think it's likely better in the long run to not specify readonly, even if it doesn't make sense to change now.

**Comment by smhigley** [comment] 2021-06-28 17:03
I'm closing the issue now, but feel free to re-open if you think there's something I've missed! :)

**Closed by smhigley** 2021-06-28 17:03 UTC
Labels: Area: Accessibility, Area: Narrator, Component: DatePicker, Fluent UI react, Needs: Investigation, Platform: Microsoft Edge
