### ISSUE TITLE
Breadcrumb item does not constraint to parent's width

### ISSUE THREAD

**Issue by PatoBeltran** [microsoft/fluentui#8187] opened 2019-03-04 23:45 UTC
### Environment Information 
 
- __Package version(s)__: 6.149.0

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/PatoBeltran/pen/BbLpoJ

#### Actual behavior:
 
When an item in the breadcrumb is too big, the `li` won't constraint to its parent width, so the content inside the breadcrumb item will never be constrained to the actual size of the breadcrumb.

To fix this you need to give an explicit `min-width` to the `li` so that flexbox can correctly constraint the element. I advice to use the width of the overflow ellipsis as the min-width value (it can also be set to 0)
 
#### Expected behavior:

The `li` item should constraint to the parent's width, not just display all of it's content.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yeah!

**Comment by PatoBeltran** [comment] 2019-03-04 23:50
Also, if the last item is super long, the breadcrumb by default will hide all the items (thus only displaying "...")... consider adding a flag (or updating the default behavior), to not hide the last item in the breadcrumb, so it will always show at least one, and truncate the text if it's too long, see this behavior in the same codepen.

**Comment by aftab-hassan** [comment] 2019-03-08 02:44
@PatoBeltran thanks for submitting this issue. This does seem like a bug in the case of large text.

Would you be a willing to submit a fix for this issue?

**Comment by KevinTCoughlin** [comment] 2019-03-14 05:07
@aftab-hassan might be good to connect with @Vitalius1 here for design and implementation insight

**Comment by Vitalius1** [comment] 2019-03-14 18:56
![Screen Shot 2019-03-14 at 11 49 10 AM](https://user-images.githubusercontent.com/29514833/54383425-4675d980-464f-11e9-8419-ae25e544da08.png)
![Screen Shot 2019-03-14 at 11 49 37 AM](https://user-images.githubusercontent.com/29514833/54383429-483f9d00-464f-11e9-86eb-0a9f3067af04.png)

**Comment by Vitalius1** [comment] 2019-03-14 18:58
Here are some specs form the fluent toolkit as the MDL2 toolkit there is not much info. So it looks like by fluent design there are some min-widths for all parent nodes but they are not implemented or documented in the MDL2 toolkit.

**Comment by Vitalius1** [comment] 2019-03-14 19:01
For reference, this is what we have in MDL2 toolkit.
![Screen Shot 2019-03-14 at 12 00 39 PM](https://user-images.githubusercontent.com/29514833/54384158-d5372600-4650-11e9-9bf4-8bc4a58019d1.png)

**Comment by Vitalius1** [comment] 2019-03-14 19:05
@betrue-final-final looking at the codepen indeed there is an issue if the last node has a very long name in the current implementation it will collapse all the the parent nodes. In the fluent toolkit there are actually min-widths for each of those parent nodes but they've never been implemented. Should we bring some of that behaviour into current default styles?

**Comment by Vitalius1** [comment] 2019-03-14 19:10
For even more context there was a PR https://github.com/OfficeDev/office-ui-fabric-react/pull/7881 which changed some of the behaviour of the breadcrumb nodes `max-width` and needs investigated if it brought this regression... or it was always like that.

**Comment by satish-singh** [comment] 2019-10-31 09:46
@aftab-hassan @msft-github-bot  I am suffering from the same issue while using react fabric. Is this fixed?

**Comment by mokshithpyla** [comment] 2021-06-25 12:01
In case of dynamically changing breadrumb items, if any item exceeds the initial width of the complete breadcrumb, all items are being collapsed. Can this issue be prioritised?

**Comment by ayuspark** [comment] 2021-11-16 18:42
Any updates on the issue?
Our product from dynamics are being impacted.

**Closed** 2022-04-15 19:00 UTC
Labels: Type: Bug :bug:, Component: Breadcrumb, Resolution: Soft Close
