### ISSUE TITLE
[Bug]: Toggle control is not focusable using tab key on iOS

### ISSUE THREAD

**Issue by lutorre** [microsoft/fluentui#32115] opened 2024-07-25 22:47 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
iOS 18.0
Browser: Safari
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/toggle

## Actual Behavior
The toggle control is not focusable using the tab key while using a keyboard

## Expected Behavior
The toggle control should be part of the navigation cycle using the tab key

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment] 2024-07-29 18:40
The Toggle buttons do get focus, but the v8 focus outlines do not show up by default on iOS with a bluetooth keyboard, since iOS + keyboard does not send through keyboard events to the page.

We have this documented, as well as a workaround, on our [known issues wiki](https://dev.azure.com/microsoftdesign/fluent-ui/_wiki/wikis/fluent-ui.wiki/332/Fluent-v8-known-issues?anchor=no-focus-outlines-on-ios-with-an-external-keyboard).

I'm resolving marking this issue as by design, since changing the entire focus outline approach on v8 would unfortunately be a breaking change.

**Closed** 2024-08-01 19:43 UTC
Labels: Resolution: By Design, Component: Toggle, Fluent UI react (v8)
