### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'length') on useCardHeader_unstable

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [microsoft/fluentui#26679] opened 2023-02-05 17:08 UTC
### Library

Fluent UI React / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 104.89 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 109.0
    Safari: 16.3
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/divine-resonance-gl0x5v?file=/src/App.js

## Actual Behavior

after upgrading to version "@fluentui/react-components": "^9.13.0"
this code 
``` <Card className={styles.card}>
      <CardHeader
        header={<div className="text-sm font-semibold">{title}</div>}
        description={subtitle}
        action={
          <Button appearance="transparent" icon={<MoreHorizontal20Filled />} />
        }
      />
      
      ....```
 throws the below error only when i keep `header` prop, if i leave it out the error goes away but i can't show a header
<img width="709" alt="Screenshot 2023-02-05 at 11 58 09 AM" src="https://user-images.githubusercontent.com/36244069/216833123-319d20b0-62f9-4dd0-8d6e-da5ff149fcf6.png">


## Expected Behavior
to work as normal

### Logs

```shell
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'length')

Call Stack
React
useCardHeader_unstable
node_modules/@fluentui/react-card/lib/components/CardHeader/useCardHeader.js (29:2)
eval
node_modules/@fluentui/react-card/lib/components/CardHeader/CardHeader.js (9:38)
React
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by yiqing-zhao** [comment] 2023-02-06 05:49
Same error from my side as well. With "@fluentui/react-components": "^9.13.0" and code below:
``` tsx
<CardHeader header="Microsoft Teams UI Kit" />
```

**Comment by elliot-huffman** [comment] 2023-02-06 17:03
Duplicate of #26653 .
Same error is present in my repro.

**Comment by micahgodbolt** [comment] 2023-02-06 17:04
Duplicate of #26653

**Closed by micahgodbolt** 2023-02-06 17:04 UTC
Labels: Needs: Triage :mag:, Fluent UI react-components (v9)
