### ISSUE TITLE
Dropdown inside of Dialog doesn't work in landspace format in mobile devices

### ISSUE THREAD

**Issue by txalvita** [microsoft/fluentui#21748] opened 2022-02-15 11:13 UTC
### Environment Information

- **Package version(s)**: 
-   "dependencies": {
    "@microsoft/sp-core-library": "1.11.0",
    "@microsoft/sp-lodash-subset": "1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "1.11.0",
    "@microsoft/sp-property-pane": "1.11.0",
    "@microsoft/sp-webpart-base": "1.11.0",
    "@pnp/sp": "^2.1.1",
    "@pnp/spfx-controls-react": "2.4.0",
    "@pnp/spfx-property-controls": "^2.5.0",
    "autobind-decorator": "^2.4.0",
    "file-saver": "^2.0.5",
    "html2canvas": "^1.1.1",
    "jspdf": "^2.3.1",
    "office-ui-fabric-react": "6.214.0",
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "xlsx": "^0.16.9"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/sp-build-web": "1.11.0",
    "@microsoft/sp-module-interfaces": "1.11.0",
    "@microsoft/sp-tslint-rules": "1.11.0",
    "@microsoft/sp-webpart-workbench": "1.11.0",
    "@types/chai": "3.4.34",
    "@types/es6-promise": "0.0.33",
    "@types/mocha": "2.2.38",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "prettier": "2.2.1"
  }
- **Browser and OS versions**: Chrome and Safari in IOS and Android devices

### Please provide a reproduction of the bug in a codepen:

When you have a Dropdown inside a Dialog it has an errant behaviour when scrolling.
<Dialog>
  <Dropdown />
</Dialog>

#### Actual behavior:

When mobile device is in portrait mode, you can scroll down or up in the content of the Dropdown
When mobile device is in landscape mode, you cannot scroll down or up in the content of the Dropdown. Content is blocked.

#### Expected behavior:

When mobile device is in landscape mode, you can scroll down or up in the content of the Dropdown

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Normal)

Products/sites affected: All mobile devices

**Comment by micahgodbolt** [comment] 2022-03-01 22:14
Duplicate of https://github.com/microsoft/fluentui/issues/12845

Check out https://github.com/microsoft/fluentui/pull/11339 for full explanation

Add `allowTouchBodyScroll` to Modal if you need touch scrollable elements inside of it.

**Closed** 2022-03-05 00:00 UTC
Labels: Component: Dropdown, Component: Dialog, Resolution: Duplicate
