### ISSUE TITLE
[Bug]: There's no way to know when a Dialog or Drawer has finished animating in and out

### ISSUE THREAD

**Issue by Weffe** [microsoft/fluentui#30453] opened 2024-02-01 06:52 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 10.00 GB / 31.60 GB
  Browsers:
    Chrome: 121.0.6167.87
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

n/a

### Bug Description

Back in https://github.com/microsoft/fluentui/issues/8562 for Fluent 8, a PR was made to address this issue to add some callback props to know when the panel/dialog, etc was done animating in or out. There is no equivalent callback props for Fluent 9 Dialog and Drawer.

## Expected Behavior

Expose the `useMotion()` state's `type` as callback props so that consumers can know when the component is done animating in and out. 

This is useful, for example, if I want to wait for a Drawer to animate out before showing some new content to the user.

### Requested priority

High

### Products/sites affected

https://dataexplorer.azure.com/

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment] 2024-02-01 09:55
This is not a bug, it's a feature. To provide context, `Dialog` & `Drawer` have motions implemented differently: `Dialog` using `react-transition-group`, `Drawer` using `useMotion()`.  There is also a wider discussion on how motions should be implemented in Fluent at all, #29958. We should reach an agreement there before any callbacks will be exposed.

---

Anyway, there is a standard way built-in into the platform to handle animation events:
- https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionend_event
- https://developer.mozilla.org/en-US/docs/Web/API/Element/animationend_event

For `Dialog` & `Drawer` it could be done by `backdrop.onTransitionEnd`:
- `Dialog` - https://stackblitz.com/edit/stackblitz-starters-wwhi31
- `Drawer` - https://stackblitz.com/edit/stackblitz-starters-tcvegp

**Comment by Weffe** [comment] 2024-02-01 20:30
Oh nice, I missed that in the backdrop so I'd probably close this bug and instead just update the docs to be more clear about when to know the Dialog/Drawer is done animating.

**Comment by ValentinaKozlova** [comment] 2024-02-02 14:55
Closing, as it's not a bug

**Closed by ValentinaKozlova** 2024-02-02 14:55 UTC
Labels: Fluent UI react-components (v9), Component: Drawer
