### ISSUE TITLE
[Bug]: Accessibility Issue -Split button 

### ISSUE THREAD

**Issue by ChithiraMG** [microsoft/fluentui#26882] opened 2023-02-17 03:24 UTC
### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 3.55 GB / 15.78 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

Run fastpass in Acceessibility Insights for web (chrome extension) for split button in fluent ui

## Actual Behavior
Fluent ui image
![image](https://user-images.githubusercontent.com/101738825/219538971-1019a133-96ea-4210-b07d-dd2d4bb80fdc.png)
Focusing on the element using tab stops.
AT: Accessibility Insights for web -->Fastpass
Not able to remove negative tab index from split button menuProps items
### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment] 2023-02-17 19:09
duplicate of #26883

**Closed by micahgodbolt** 2023-02-17 19:09 UTC
Labels: Needs: Triage :mag:
