### ISSUE TITLE
Group selection is only shown on hover

### ISSUE THREAD

**Issue by jbzdarkid** [microsoft/fluentui#23381] opened 2022-06-02 22:17 UTC
### Environment Information

- **Package version(s)**: 7.185.6

### Describe the issue:

When a group is entirely selected, there's an auxiliary checkbox that becomes checked. However, it only appears on hover, which makes it especially hard to see group state when the group is collapsed.

![no hover](https://user-images.githubusercontent.com/5459085/171746584-baa912d1-0f00-4e3d-8429-12cfadc46756.png)
![on hover](https://user-images.githubusercontent.com/5459085/171746641-6441e30d-6912-41e5-bdab-5663954bed54.png)

#### Actual behavior:

The checkbox only appears on hover

#### Expected behavior:

The checkbox appears at all times
I would also expect a horizontal line (or some other indicator) if the group is *partially* selected.

### If applicable, please provide a codepen repro:

I am not familiar enough with Fluent to build a minimal repro. This is affecting a feature that's currently in development -- once it reaches public preview I can put in screenshots with more information. If you contact me through teams, I can demonstrate this at PPE.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Azure Portal

CC @brfabian-msft

**Comment by gouttierre** [comment] 2022-06-27 09:42
@jbzdarkid - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@bsunderhus  - This is V7 and I am not sure if the issue (if confirmed) was addressed in the later version. Would you be able to review the issue with [jbzdarkid](https://github.com/jbzdarkid) as the problem is not on a code-pen but in their development environment. 


cc @paulgildea - Azure

**Comment by spmonahan** [comment] 2022-10-10 21:36
Hi @jbzdarkid, you should be able to use existing props to have the checkboxes always appear.

I've put together a [Codepen example showing how to achieve this](https://codepen.io/seanms/pen/QWrJrNv). The two things that need to be done are to set check styles for the headers (L8 and L73) and to set `checkboxVisibility` for all other rows (L49).

The partial selection behavior is not currently supported. If you'd like that as a feature please file a [new feature proposal](https://github.com/microsoft/fluentui/issues/new?assignees=&labels=Type%3A+Feature%2CNeeds%3A+Triage+%F0%9F%94%8D&template=feature-request.yml&title=%5BFeature%5D%3A+) so we can look at it separately.

PS - in this case a good minimal repro would be to link to the [GroupedList docs](https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/controls/web/groupedlist) as they demonstrate the behavior you reported.

**Comment by jbzdarkid** [comment] 2022-10-10 23:48
@brfabian-msft Can you please take a look at this?

**Closed** 2022-10-19 20:00 UTC
Labels: Component: DetailsList, Component: GroupedList, Status: No Recent Activity, Needs: Author Feedback, Partner Ask, Fluent UI react (v7)
