### ISSUE TITLE
[Bug]: Dropdown control doesn't rerender with null/undefined value

### ISSUE THREAD

**Issue by WildTiger404** [microsoft/fluentui#24057] opened 2022-07-25 12:39 UTC
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 13.10 GB / 31.87 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codesandbox.io/s/controled-select-dropdown-forked-sh0o85

### Bug Description

The only way to clear dropdown field with button is to use value props and use State to rerender this props. When you use clearable props there only case when icon is hidden is when value === undefined.
When you try to setState({value: undefined}) state would be updated, but the control doesn't rerender.

https://codesandbox.io/s/controled-select-dropdown-forked-sh0o85

## Actual Behavior
after setState({value: undefined}) the component doesn't rerender

## Expected Behavior
after setState({value: undefined}) the component rerenders

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment] 2022-08-08 14:43
@WildTiger404 to provide context: it works in the same way as in React (link [controlled components](https://reactjs.org/docs/uncontrolled-components.html)) where `undefined` does not reset state - it makes a component uncontrolled. `@fluentui/react-northstar` and `@fluentui/react-components` follow React's behavior.

In your case you need to do `setState('')` or, for example, `setState(initialValue)`. I modified your sandbox how this (https://codesandbox.io/s/controled-select-dropdown-forked-4hquqq?file=/example.js). But, please read below ⬇️

---

The problem is that `""` (empty string) forces the clear indicator to be visible always which is not expected (https://github.com/microsoft/fluentui/issues/24273). And I think that it's the source of confusion 🐱 

As a workaround you can pass `[]`, https://codesandbox.io/s/controled-select-dropdown-forked-xzxhr0?file=/example.js. I am closing this issue, but will fix #24273 immediately 🚀

**Closed by layershifter** 2022-08-08 14:43 UTC
Labels: Needs: Triage :mag:
