### ISSUE TITLE
Dynamic creation of the DetailsList columns cause TypeScript error ts(2740)

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/fluentui#12331] opened 2020-03-17 13:00 UTC
### Environment Information

- **Package version(s)**: (office-ui-fabric-react": "6.189.2")
#### Actual behavior:
when creating the DetailsList's "columns" Array in a function that uses array push to create the columns based on the components props, Typescript errors with:
"Type '() => any[]' is missing the following properties from type 'IColumn[]': pop, push, concat, join, and 15 more. ts(2740)"

I made the function return IColumn[] and it did not help.

#### Expected behavior:

I should be able to build the columns array dynamically based on the props of the component.
### Priorities and help requested:

Are you willing to submit a PR to fix? ( No, I would not know how)
Requested priority: (Blocking)
Products/sites affected: (SPFx web part)

**Comment by aneeshack4** [comment] 2020-03-17 23:00
@Ofer-Gal Thanks for reaching out to us. Can you please provide a codepen with an isolated repro of this TS error? That will help this be actionable.

**Comment by Ofer-Gal** [comment] 2020-03-17 23:30
1.   Fabric component "DetailsList" of office-ui-fabric-react 6.189.2
2.   The "columns" property should accept an array of objects no matter how it was created.
3.  I create an array using push for example `_columns.push({ key: "Title", name: "Job", fieldName: "Title", maxWidth: 90, minWidth: 70, isResizable: true });` and few others.  The Tslint claims "Type '() => any[]' is missing the following properties from type 'IColumn[]': pop, push, concat, join, and 15 more. ts(2740)"
If I create the columns with `const _columns = [
    { key: "Title", name: "Job", fieldName: "Title", maxWidth: 90, minWidth: 70, isResizable: true },
    ` etc.. It is Ok. But then I can't have different sets of columns for diverent props values. 
4. What does it mean "that the problem reproduces in isolation"?
Thank you in advance.

**Comment by aneeshack4** [comment] 2020-03-17 23:41
@Ofer-Gal Here's a sample DetailsList Codepen to get you started: https://codepen.io/aneeshack4/pen/abOKpWK?editable=true - please use it to reproduce your issue so that we can understand and debug it.

**Comment by Ofer-Gal** [comment] 2020-03-18 12:18
Thanks! I saved it as https://codepen.io/ofergal/pen/KKpeZeG?editors=1010
You can see I created a function buildColumns to create the columns array.
The Pen's TSlint did not complain like the one I have ("@microsoft/sp-tslint-rules": "1.10.0",)  If there is something I can do in the tslint.json, please let me know.
In any case In my pen code buildColumns function, the name column ('column2') should not show because the statement (1===2)  is not true.

While you are at it, can you show me how to color the entire value cell green if the FileType is xlsx?
This is another thing I am trying to do and I was able to only apply background to the text itsef not the entire cell.
Thank you in advance

**Comment by aneeshack4** [comment] 2020-03-31 04:00
@Ofer-Gal  I still don't see this Typescript error when I try - I even tried to paste your code locally but there were too many other unrelated errors to resolve because the code was so different. And there are no Typescript error in the DetailsList code... I suggest you isolate this error so that it can be repro'd more generically. Perhaps it's a problem with Typescript itself in which case I suggest you create an issue in their repro. You could also consider adding a tslint disable rule. 

To color an entire cell green to match Excel I would use hex value: 217346 as stated in https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/products. You can use our [theme designer](aka.ms/themedesigner) to get a theme object that has all of the slot values based off this green (input that hex value into the primary color picker).

Going to close this issue now but please feel free to reach out to us if you can better show a repro.

**Closed by aneeshack4** 2020-03-31 04:00 UTC
Labels: Component: DetailsList, Needs: Attention :wave:
