### ISSUE TITLE
[Bug]: Unable to close the MenuList from fluent UI React (V9) when using closeOnScroll props on Menu component

### ISSUE THREAD

**Issue by AvedisDemirdjianTR** [microsoft/fluentui#29671] opened 2023-10-27 09:08 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/nervous-gauss-m2397g?file=/index.tsx

## Actual Behavior
Using closeOnScroll props on Menu component is not closing the MenuList component when scrolling using the scroll bar(click and drag) , or using the arrows of the existing scroll bar. The MenuList component remains open in this case

## Expected Behavior
When using closeOnScroll props on Menu component, it should close the MenuList  when scrolling using the scroll bar or using the arrows of the scroll bar.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by YuanboXue-Amber** [comment] 2023-10-30 16:06
Duplicate of #28938
We haven't found a good way to figure out how to identify scrollbar click/drag.

**Closed** 2024-03-28 18:12 UTC
Labels: Fluent UI react-components (v9), Component: Menu, Resolution: Soft Close
