### ISSUE TITLE
[Bug]: Split button accessibility issue in fluent ui  v9

### ISSUE THREAD

**Issue by ChithiraMG** [microsoft/fluentui#30004] opened 2023-12-06 07:19 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 3.55 GB / 15.78 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://github.com/microsoft/fluentui/issues/26883

### Bug Description

I had raised a ticket https://github.com/microsoft/fluentui/issues/26883 and in the closing comment it was mentioned that the issue is fixed in v9
![image](https://github.com/microsoft/fluentui/assets/101738825/3d184c42-6bfe-4997-87b8-ad63421dabab)
While I am running a fastpass accessibility check via accessibility insights for windows, fluent ui v9 split button  is still showing accessibility error
![image](https://github.com/microsoft/fluentui/assets/101738825/c4d6b73e-b2c5-4fa3-b56a-d6600d439cb5)
![image](https://github.com/microsoft/fluentui/assets/101738825/fc7fc0cf-884d-4a6d-bb08-ad7e848ad459)

### Requested priority

Blocking

### Products/sites affected

https://github.com/microsoft/fluentui/issues/26883

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ChithiraMG** [comment] 2024-01-11 04:50
Can you please tell me if there is any update on this ticket

**Comment by khmakoto** [comment] 2024-01-11 19:05
Hi @ChithiraMG, the issue you're reporting here and the one in #26883 are different.

In the original one in #26883, accessibility insights is indeed reporting an accessibility violation caused by having a one-tab stop on a two-button group and assigning a negative tab index to the inner buttons. We unfortunately could not fix this in v8 as it would mean a breaking change to the component DOM rendering, but we did fix it in v9 as @smhigley explained in her comment.

The one you are reporting here is about focus landing on elements having `aria-hidden` set to `true` once the menu opens. However, this is effectively a false positive because these elements are just bumper dummy elements that allow us to have circular navigation on the menu. Neither a sighted user, nor a user using assistive tech should be aware of these elements, hence why they are hidden visually and assigned `aria-hidden`.

You can even see both are different since the fast pass warnings on the bug reported in #26883 appear every time and the ones here only when you open the `SplitButton`. As this is effectively a false positive, I will be resolving this as "Not an issue".

**Comment by smhigley** [comment] 2024-01-11 19:32
Yup, exactly what @khmakoto said! We also document this automated issue in [our wiki](https://dev.azure.com/microsoftdesign/fluent-ui/_wiki/wikis/fluent-ui.wiki/334/Fluent-v9-known-issues?anchor=%60aria-hidden-focus%60-on-elements-with-%60data-tabster-dummy%60), if you have access (all microsoft employees should be able to see it)

**Closed** 2024-01-13 11:39 UTC
Labels: Resolution: Not An Issue, Fluent UI react-components (v9), Component: SplitButton
