### ISSUE TITLE
ChoiceGroups/radio buttons don't use the new style and strangely, the dot appears off-center

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/fluentui#14040] opened 2020-07-15 07:26 UTC
### Environment Information

- **Package version(s)**: idk, just whatever the fluent ui website and outlook use?
- **Browser and OS versions**: Edge 83 (why on earth does content in internal pages have to load in?!), Chrome 83, Win10 2004.

#### Actual behavior:
![image](https://user-images.githubusercontent.com/51363864/87515727-9c351880-c6bf-11ea-8f22-152a3368da5e.png)
from fluent ui website https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup

#### Expected behavior:
![image](https://user-images.githubusercontent.com/51363864/87515851-d2729800-c6bf-11ea-85ee-7e6075e97da9.png)
from xaml controls gallery

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Outlook, Fluent UI. Probably the internal pages in Edge if it does use Fluent UI?

**Comment by paulgildea** [comment] 2020-07-15 15:37
Thanks for the issue @Poopooracoocoo !

Currently, according to the design toolkits - both Fluent UI React and WinUI are implemented to the design spec. I'll bring this up with the design team to understand the difference in the Radio Button design. 
Web Toolkit: https://aka.ms/fluenttoolkits/web/figma
WinUI Toolkit: https://aka.ms/figmatoolkit

As far as the dot - I'm unable to reproduce the issue on my side using Edge 83 on masOS:
![image](https://user-images.githubusercontent.com/33229964/87565318-54d66a00-c676-11ea-9950-a20868d157a5.png)

I'll ask @xugao to see if she can repo the issue. 

But I'm going to be marking this as by design.

**Comment by xugao** [comment] 2020-07-15 19:27
@Poopooracoocoo - see same issue #10573. this is related to screen resolution and browser subpixel rendering. I don't have a great idea how to address this. also given the impact of this issue is small. We will go ahead mark this as not an issue

**Comment by Poopooracoocoo** [comment] 2020-07-16 08:53
@paulgildea 
>both Fluent UI React and WinUI are implemented to the design spec

I'm super confused. If they're both to spec, then why do they look different?!

@xugao What about the design of the radio buttons? Isn't that still an issue? I don't know what other frameworks do but they don't have off centre dots.

**Closed** 2020-07-17 10:00 UTC
Labels: Component: ChoiceGroup, Resolution: Not An Issue

**Comment by Poopooracoocoo** [comment] 2020-07-18 06:28
argh. What on earth? No one answered my questions. My main point in this issue was the design.

**Comment by Poopooracoocoo** [comment] 2020-07-24 07:56
@paulgildea um. any updates on the design?

**Comment by paulgildea** [comment] 2020-07-24 16:04
At this time the design are to spec. Yes they are different and currently that is what the design teams have specified for now. Fluent Design doesn't necessarily have the exact pixel perfect UI across all platforms and is a evolving design language that changes over time and the teams are working to reconcile design differences across the various platforms the Fluent Design Language supports.

Hope that helps with some of the design clarity.

**Comment by Poopooracoocoo** [comment] 2020-07-24 16:29
I'm still pretty confused. Why would the design teams specify two different styles for the same control?!

**Comment by Poopooracoocoo** [comment] 2020-08-18 04:26
Well Edge Canary (I think it's version 86) is finally using the new radio button style in their React* pages but they unfortunately changed it to be greyscale and they haven't changed the HTML control. where oh where is the consistency... 

* by the way does Edge use FluentUI?

**Comment by Poopooracoocoo** [comment] 2020-09-14 06:10
um i can still see this issue in edge. :/
