### ISSUE TITLE
[Bug]: Facepile Overflow Dropdown root callout menu is not styleable

### ISSUE THREAD

**Issue by anenger** [microsoft/fluentui#26006] opened 2022-12-15 00:36 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz 
    Memory: 103.40 GB / 127.71 GB
Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.42)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/anenger/pen/yLEmOVP?editors=0010

## Actual Behavior
Callout menu root component is not styleable

<img width="160" alt="image" src="https://user-images.githubusercontent.com/23532007/207744966-2d10986c-27af-489e-905d-4074b5373a80.png">

Observe that the border radius attribute applies to the area inside of the menu, but not the outer boundaries. This is made more evident by adding padding, margin, etc. 

## Expected Behavior
Menu styles from the button would apply to the callout

### Requested priority

Normal

### Products/sites affected

Microsoft Loop 

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment] 2023-01-30 14:10
@anenger you need to apply styles to `Callout` in this case which is a host of `ContextMenu`, something like that:

```ts
  const overflowButtonProps = {
      calloutProps: {
        styles: {
          calloutMain: {
            border: "1px solid red",
            borderRadius: "8px"
          },
          root: {
            borderRadius: "8px"
          }
        }
      }
    }
  };
```

I moved it to CodeSandbox, so you check how styles are applied: https://codesandbox.io/s/condescending-wind-kjoleu?file=/src/App.tsx.

Closing as it's not a bug and already works.

**Closed by layershifter** 2023-01-30 14:10 UTC
Labels: Needs: Triage :mag:, Fluent UI react (v8)
