### ISSUE TITLE
PresenceBadge: Missing presence icon sizes

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#20650] opened 2021-11-18 13:58 UTC
Follow up from #20627

Since the presence badges are implemented fully as icons in the system icons package (@fluentui/react-icons), there are missing sizes from the design ramp which are:
* tiny - 6px
* ~large - 20px~
* ~extra-large - 28px~

If resizable icons become a reality, this should be easily mitigated

**Comment by tomi-msft** [comment] 2021-11-18 21:55
#20563 will add the resizeable icons to our repo. #20630 should add the latest beta version of react-icons (2.0.151-beta.2) and resizeable icons will be available for react-badge

**Comment by tomi-msft** [comment] 2022-04-05 00:09
I think for `PresenceBadge` it makes sense to use specifically sized icons, since scaling down the icons too small would make them lose visual integrity

**Comment by ling1726** [comment] 2022-04-05 06:13
@tomi-msft  in this case we should have icons for all the sizes that are possible for the presence badge

**Comment by jurokapsiar** [comment] 2023-01-16 09:23
@tomi-msft could you please look into this? Using unsized icons would save bundle size. Let's compare how it looks. and if there is degradaion, we can at least use the unsised icons for missing sizes.

**Comment by khmakoto** [comment] 2023-03-27 20:19
Large icons are now the correct size in the repo, we are still missing the correct tiny and extra-large icons though.

**Comment by tomi-msft** [comment] 2023-08-14 20:20
The size 28 px badge is available now, I will create an issue to update the `PresenceBadge` with the new value. The 6px is not going to be able to be buily by design, so we the current workaround will still work

**Comment by tomi-msft** [comment] 2023-09-26 04:57
Here is a PR that uses the `unsized` icons: #29288

**Comment by tomi-msft** [comment] 2024-01-09 22:25
Closing this issue as resolved, see comment in #29288

**Closed by tomi-msft** 2024-01-09 22:25 UTC
Labels: Needs: Design, Priority 2: Normal, Area: Icons, Status: In PR, Component: PresenceBadge
