### ISSUE TITLE
When tab is used to focus the the Dropdown component, it selects the first option from options list automatically

### ISSUE THREAD

**Issue by tanisha2710** [microsoft/fluentui#14160] opened 2020-07-22 06:18 UTC
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

### Describe the issue:
when we use the tab from keyBoard to navigate through the Dropdown, it automatically selects the the first option if nothing is selected.

#### Expected behavior:
when using tab button from the keyBoard it should not select the first element from the options list if nothing is selected, it should just focus the component and not fire any onChange event

**Comment by xugao** [comment] 2020-07-23 17:51
I need to check with folks if this is by design. Tracking the same issue in #13266. Will close this one as dup

**Closed by xugao** 2020-07-23 17:51 UTC
Labels: Component: Dropdown, Resolution: Duplicate

**Comment by xugao** [comment] 2020-07-23 17:55
@tanisha2710 - see [my comment here](https://github.com/microsoft/fluentui/issues/13266#issuecomment-663147394)
