### ISSUE TITLE
Looking forward to Fluent UI based on Vue.js

### ISSUE THREAD

**Issue by yn-tadpole** [microsoft/fluentui#16389] opened 2021-01-06 08:23 UTC
#### Looking forward to Fluent UI based on Vue.js.

Vue.js Compared with react, it should be a more potential framework. I hope the project team can consider the development of Vue.js Version of.

**Comment by layershifter** [comment] 2021-01-14 14:46
@yn-tadpole it's a duplicate of https://github.com/microsoft/fluentui/issues/14334. @paulgildea have already provided there a great reply: https://github.com/microsoft/fluentui/issues/14334#issuecomment-671592447.

**Closed by layershifter** 2021-01-14 14:46 UTC
Labels: Resolution: Duplicate
