### ISSUE TITLE
[Bug]: Clicking a Checkbox label inside a dialog is triggering the focus styles. 

### ISSUE THREAD

**Issue by jwccit** [microsoft/fluentui#27913] opened 2023-05-19 09:55 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 3.85 GB / 15.74 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)  
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/xenodochial-night-0f3bfs?file=/src/App.js

## Actual Behavior
Clicking multiple times on a Checkbox component label text in different places is causing the focus outline to appear only when the Checkbox is rendered inside a Dialog component 

## Expected Behavior
The outline to not show unless the user uses keyboard navigation to match the Checkbox behavior when not rendered inside a Dialog component 
![checkboxfocus](https://github.com/microsoft/fluentui/assets/74728196/f2249fee-cb8c-48bf-97b5-f661ad21405c)
 

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment] 2023-07-11 13:33
Duplicate of #27807

**Closed by ling1726** 2023-07-11 13:33 UTC
Labels: Type: Bug :bug:, Component: Dialog, Fluent UI react-components (v9), tabster
