### ISSUE TITLE
Surfaces need easy way to apply border when dropshadow isn't sufficient

### ISSUE THREAD

**Issue by mizeljko** [microsoft/fluentui#11542] opened 2019-12-23 21:14 UTC
### Environment Information

- **Package version(s)**: 7.74.1
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/mizeljko/pen/RwNVEKv

#### Actual behavior:

When applying a dark theme to surfaces like dropdown/combobox/tooltip, the borders don't show up because they were originally just dropshadows.

There is no easy way to apply borders to all of those controls even with Customizer scopedSettings. Adding a border value in semanticColors would make it easier to modify this value when using a dark theme.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Azure for Machine Learning

**Comment by micahgodbolt** [comment] 2019-12-23 23:40
Does this repro in Edge, or just chrome?

**Comment by cliffkoh** [comment] 2019-12-24 00:09
@micahgodbolt If you click on the codepen repro @mizeljko in Microsoft Edge, you can see it repros in Edge :)

**Comment by micahgodbolt** [comment] 2019-12-26 16:59
Oh sorry, i thought this was a high contrast question.

**Comment by micahgodbolt** [comment] 2019-12-26 17:32
At the heart of this issue is that our controls are not guaranteed to work with any theme you apply to them. They simply aren't that smart. If you pass an inaccessible theme into customizer, you are responsible for tweaking the theme to make those new colors work.

We typically do this customizing through the 'scopedSettings' of the customizer. Here you can pass through specific component customizations to make controls work in the given theme. 

Since combobox and dropdowns containers only use shadows to show elevation, changing everything to black will take some additional styling on your part. Dropdown looks like this:

```
const customize = {
  Dropdown: {
    styles: {
      dropdownItemsWrapper: {
        border: "2px solid #e008fc"
      }
    }
  },
};

<Customizer scopedSettings={customize} > ...
```

Combobox was not built with this customizer control unfortunately (something we hope to resolve with a full rewrite of dropdown/combobox), so you'd need to apply custom stylings either through css:

```css
.ms-ComboBox-optionsContainerWrapper {
  border: 2px solid #e008fc
}
```

or apply them directly to the control via the `styles` prop and possibly wrap/export that customized control for use in your app. 

### Possible improvements

This is how you can resolve the issue today.

Considering this issue affects several surfaces that use dropshadow to denote a border, I think a good solution going forward would be to create a semantic slot to apply surface border, that's currently set to nothing. This would make it easier to update all of the controls without targeting each of them via customizer.

**Comment by mizeljko** [comment] 2019-12-30 16:30
The suggestion above doesn't seem to be what we need. If you have too many items in the combo box and you need to scroll, the bottom border is not visible (until reaching the end of the list). We need it to be around the box at all times.

**Comment by micahgodbolt** [comment] 2019-12-30 16:39
Ok, adjusted which parent the border was applied to. works for combobox and dropdown now.

**Comment by JustSlone** [comment] 2020-09-21 02:51
Closing this issue as a workaround exists and this is more general feedback. This should also be at least partially address by design tokens going forward. 

Thanks for the feedback, sorry there isn't a more concrete fix!

**Closed by JustSlone** 2020-09-21 02:51 UTC
Labels: Area: Theming, Component: ComboBox, Component: Dropdown, Component: Tooltip, Priority 3: Fit and finish, Type: Feature
