### ISSUE TITLE
[Bug]: AddRegular is not aligned vertically

### ISSUE THREAD

**Issue by rocketBANG** [microsoft/fluentui#31905] opened 2024-07-02 19:46 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 36.15 GB / 63.95 GB
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/basphv?file=src%2Fexample.tsx

## Actual Behavior
The + icon is not aligned with the text. It looks like it has more padding below than above which causes it not to line up

![image](https://github.com/microsoft/fluentui/assets/2422566/75ba73ab-0388-49c8-8dee-9e83877137fe)
![image](https://github.com/microsoft/fluentui/assets/2422566/9d42c003-9562-4716-99d8-7368590c5538)

## Expected Behavior
The + icon is aligned

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment] 2024-07-08 07:13
This might be an issue with the icon itself, in that case it's probably for this repo https://github.com/microsoft/fluentui-system-icons

**Comment by behowell** [comment] 2024-07-22 21:28
Closing as a duplicate of https://github.com/microsoft/fluentui-system-icons/issues/733

**Closed by behowell** 2024-07-22 21:28 UTC
Labels: Component: Button, Fluent UI react-components (v9)
