### ISSUE TITLE
[Bug]: Closed modal is retained as a detached element

### ISSUE THREAD

**Issue by AndrewBarzu** [microsoft/fluentui#25093] opened 2022-10-05 13:47 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 25.08 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 16.0
```

### Reproduction

https://codesandbox.io/s/z388du?file=/src/index.tsx

## Actual Behavior
In edge: 

1. Open Modal
2. Close Modal
3. Look into detached elements
4. Press "Get Detached Elements" 
5. Press "Analyze" 
6. Press again "Get Detached Elements" 
7. The modal is left in detached elements

<img width="1728" alt="Screenshot 2022-10-05 at 15 45 52" src="https://user-images.githubusercontent.com/37110918/194076106-d8bd7470-4606-4af4-906f-b6a9cf9efc7c.png">

## Expected Behavior
The modal should not be retained as a detached element. Even though this does not cause a bad memory leak (memory does not continue bloating) it's still bad because sensitive information can still be leaked from the modal.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment] 2022-10-14 13:38
This is actually React working as intended and there's nothing we can actually do about it.
Also this is not what we've considered a real leak since the detached HTML element count does not actually increase. React will keep two separate trees in memory for optimization purposes and there is an open issue on their end stating that detached elements in alternate trees won't be fixed any time soon https://github.com/facebook/react/issues/16087.

fyi @ling1726

**Closed by miroslavstastny** 2022-10-14 13:38 UTC
Labels: Needs: Triage :mag:, Fluent UI react (v8)
