### ISSUE TITLE
Details List: Narrator is not reading giving any information about sorting.

### ISSUE THREAD

**Issue by zhr1130** [microsoft/fluentui#12807] opened 2020-04-22 04:42 UTC
### Environment Information

- **Package version(s)**: 7.104.0
- **Browser and OS versions**: Chrome, Windows10

### Describe the issue:

User Experience:
Screen reader is not giving information about detail list head sorting. User who are depend on screen reader might get effected and will not able to get there is any sorting button present on table header..

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns

#### Actual behavior:

Screen reader is not giving any information about sorting on detail list table header.

#### Expected behavior:

Screen reader should give complete information about sorting on detail list table header.

**Comment by joschect** [comment] 2020-04-23 00:25
@zhr1130  Thanks for the submission! I'm able to reproduce the behavior you're talking about. However, it looks like we're adding all of the appropriate roles, ara-sort="none" is on the sortable headers. Additionally I tried narrator and edge on this aria example and sortable was not read out either. This seems to be a problem with narrator and edge.

The only solution would be to provide some sort of label to provide that information which is something that you the details list allows for.

This issue has been submitted a few times and it looks like narrator/edge is aware of it according to this issue #4870 , #11564

**Comment by xugao** [comment] 2020-07-23 22:31
closing as this is an external issue

**Closed by xugao** 2020-07-23 22:31 UTC
Labels: Resolution: External
