### ISSUE TITLE
[Bug]: Slots API types do not work correctly in React 18

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#31482] opened 2024-05-25 05:35 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
React 18
@fluentui/react-components@latest
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/vitejs-vite-gek5ur?file=src%2FTest.ts

### Bug Description

The type above is React 17 and the one below is React 18:
```ts
    // 17
    type ReactFragment = {} | Iterable<ReactNode>;
    type ReactChild = Reactlement | ReactText;
    type ReactNode = ReactChild | ReactFragment | ReactPortal | boolean | null | undefined;

    // 18
    type ReactNode =
        | ReactElement
        | string
        | number
        | Iterable<ReactNode>
        | ReactPortal
        | boolean
        | null
        | undefined
        | DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_REACT_NODES[
            keyof DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_REACT_NODES
        ];
```

The error shows the following:

![image](https://github.com/microsoft/fluentui/assets/5953191/96b1c3e8-d4ad-441e-b83a-4023f46f1f86)

which further inspecting, the problem is not really where we thought. The problem comes from here:

![image](https://github.com/microsoft/fluentui/assets/5953191/7f162720-4199-4b46-908c-f891688381a2)

Where we are checking that the provided slots follow the SlotPropsRecord type, this is where we get errors. So poking further takes us here

![image](https://github.com/microsoft/fluentui/assets/5953191/1088755b-18b3-4c37-b65c-6321398f5801)

input is of type intrinsic slot therefore follows UnknownSlotProps and this is where things go south:

![image](https://github.com/microsoft/fluentui/assets/5953191/133c7ddf-91d4-43c1-983e-1d068b58a012)

We are getting the children from HTMLAttributes<HTMLElement> but with the React 18 update there were breaking changes to this and as outlined at the beginning ReactNode clashes due to ReactElement being different. which makes sense based on the error we are getting:

![image](https://github.com/microsoft/fluentui/assets/5953191/c1330502-a316-4786-8996-41ad8fdade2d)

What I would propose is to have stricter types for children, I've tested this and the following update and works correctly. While ideally we would prefer to keep using what we have, this breaking change in React 18 will sadly stop us from doing so :/ One thing to note is that I would say we should be careful adding this to our types, if we decide to move back to relying on HTMLAttributes<HTMLElement> we will be introducing a breaking change, so this could possibly more of a "shim" for react 18 like Justin mentioned. 

Finally, here's the update I mentioned that worked:

```ts

// our current types
export declare type UnknownSlotProps = Pick<React_2.HTMLAttributes<HTMLElement>, 'children' | 'className' | 'style'> & {
    as?: keyof JSX.IntrinsicElements;
};

// proposed change, notice this is what R17 resolves to, so we are just making sure it receives the expected type
export declare type UnknownSlotProps = Pick<Omit<React_2.HTMLAttributes<HTMLElement>, 'children'>, 'className' | 'style'> & {
    as?: keyof JSX.IntrinsicElements;
    children?:ReactChild | React.ReactFragment | React.ReactPortal | boolean;
};
```

### Requested priority

Blocking

### Products/sites affected

OOUI

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment] 2024-05-27 08:28
It's been known for quite a while that there are breaking cases for React 17 in our slot API. thanks for the investigation @sopranopillow, I'd appreciate any further collaboration to solve those issues!

**Comment by layershifter** [comment] 2024-11-18 15:23
Duplicate of [#29578](https://github.com/microsoft/fluentui/issues/29578)

**Closed by layershifter** 2024-11-18 15:23 UTC
Labels: Package: utilities, Status: In PR, Fluent UI react-components (v9), React 18
