### ISSUE TITLE
[Bug]: Button-like Anchor text is not vertically centered

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#32914] opened 2024-09-25 17:31 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
n/a
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/button

## Actual Behavior

Anchor button text is not vertically centered
![msedge_3cnkc1yVGp](https://github.com/user-attachments/assets/b650b18c-2324-4f12-9dcc-d90df4bb7a60)

## Expected Behavior
Anchor button text should be vertically centered.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment] 2024-10-14 20:32
duplicate of [32378](https://github.com/microsoft/fluentui/issues/32378)

**Closed by sopranopillow** 2024-10-14 20:32 UTC
Labels: Type: Bug :bug:, Component: Button, Fluent UI react (v8)
