### ISSUE TITLE
When upgraded to version 7 (FluentUI). Grids stop working. 

### ISSUE THREAD

**Issue by Faisal-developer** [microsoft/fluentui#14950] opened 2020-09-09 09:33 UTC
Previously, everything was working but with updation Grid is not working.Columns are showing in next line instead of coming on same row.

**Comment by paulgildea** [comment] 2020-09-09 17:09
@Faisal-developer Can you provide a reduced codepen of the issue you are seeing? This will help the team to better understand the issue you are encountering. Thanks!

**Comment by JustSlone** [comment] 2020-09-09 17:12
@Faisal-developer a codepen showing the issue is really important, especially for a complex component like details list. Also if you can share the version you were upgrading from that would be super helpful, thanks!

**Comment by Faisal-developer** [comment] 2020-09-13 17:05
Previous version : 6.112.0
Current version : 7.133.0

**Comment by JustSlone** [comment] 2020-09-14 05:17
@Faisal-developer 
I took a look at this, didn't see any major issues between 6 and 7 on DetailsList. It also looks like this wasn't an expected break given the changes in 7. 

[DetailsList example on Fabric version 6](https://codepen.io/justslone-the-encoder/pen/abNKJyO?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F)
[DetailsList example on Fabric version 7](https://codepen.io/justslone-the-encoder/pen/JjXZWyG?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F)

Unfortunately without more specifics and really a codepen showing repro we won't be able to tackle this issue. Sorry!

**Comment by Faisal-developer** [comment] 2020-09-28 06:32
All, Issue was fixed by adding dir="ltr" to parent div.

Thank you all for the help.

**Comment by behowell** [comment] 2020-11-30 20:19
Closing, as it appears this was resolved.

**Closed by behowell** 2020-11-30 20:19 UTC
Labels: Fluent UI react, Issue Pinged, Needs: Attention :wave:
