### ISSUE TITLE
ComboBox is dismissed / closed as keyboard opens on mobile (Android)

### ISSUE THREAD

**Issue by areyesms** [microsoft/fluentui#18763] opened 2021-06-29 19:08 UTC
### Environment Information

- **Package version(s)**: 8.21.1 (latest)
- **Browser and OS versions**: Google Chrome - Android 11

### Please provide a reproduction of the bug in a codepen:
This reproes out of the box by simply navigating to the ComboBox demos:
[Fluent UI - ComboBox](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox)
[Fluent UI React 8.21.1 - ComboBox](https://fabricweb.z5.web.core.windows.net/oufr/8.21.1/#/examples/ComboBox)

https://user-images.githubusercontent.com/86681944/123853328-304cbf80-d8d2-11eb-9440-7de1b93ac156.mp4

#### Actual behavior:

ComboBox is momentarily shown and quickly dismissed after first tap.

#### Expected behavior:

ComboBox is not dismissed or it is intentionally not shown on first tap.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)
Every ComboBox used in a mobile (Android) setting, specifically in my work it affects Field Service and all other Dynamics 365 solutions and Power Apps Platform apps where the Fluent UI ComboBox is used for dropdowns.

**Comment by gouttierre** [comment] 2021-08-10 15:00
@areyesms - Thanks for filing this issue with us.

@smhigley - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by GeoffCoxMSFT** [comment] 2021-09-17 16:31
@miroslavstastny I'm having trouble reproducing the issue in Edge and Chrome using the emulation for mobile.  I also cannot reproduce on my iPhone.  Did you reproduce in an emulator or on a device? There have been some updates to ComboBox since your last post, can you still reproduce?

**Comment by miroslavstastny** [comment] 2021-09-18 05:39
@GeoffCoxMSFT  I was not able to repro in Chrome. But I was able to repro in Android emulator as well as on a physical Android phone.

Tested again, still broken in 8.34.2.

**Comment by GeoffCoxMSFT** [comment] 2021-09-20 22:41
I chatted a bit with @smhigley and saw a repro on an Android device. Sarah demonstrated this is likely caused by the close on scroll behavior and mentioned this is desired behavior in many other scenarios. 

- The scroll is likely caused by the appearance of the keyboard causing a resize and slight scroll on Android. 
- The iPhone overlays the keyboard and so doesn't cause the scroll.  The keyboard can be closed by clicking the 'Done' button and then the items can be seen.
- Other controls like DropDown expose Callout attributes to allow control over behavior, which ComboBox does not.  We could consider adding this, but expanding the API surface may not be the right change.

**Comment by RoelVB** [comment] 2021-12-14 11:02
@GeoffCoxMSFT This is caused by resizing of the view. Selecting the combobox causes to keyboard to popup, which resizes the browser view. So you can also reproduce this on desktop by resizing.

# Workaround
You can prevent the callout from closing on a resize event:
```tsx
<ComboBox
    {/* Your props */}
    calloutProps={{preventDismissOnResize: true}}
/>
```

**Closed** 2022-11-05 19:00 UTC
Labels: Needs: Discussion, Component: ComboBox, Platform: Chrome Android, Help Wanted ✨, Fluent UI react (v8), Resolution: Soft Close
