### ISSUE TITLE
Dropdown control not showing message when no results found or searched after all items are added

### ISSUE THREAD

**Issue by MaheshakaMudli** [microsoft/fluentui#14231] opened 2020-07-29 09:21 UTC
### Environment Information

- **Package version(s)**:  0.49
- **Browser and OS versions**: Chrome browser and windows OS

### Please provide a reproduction of the bug in a codepen:
![image](https://user-images.githubusercontent.com/23700986/88769352-eaefb180-d199-11ea-95fb-7a1452132dda.png)

#### Actual behavior:

https://user-images.githubusercontent.com/23700986/88762088-1e2c4380-d18e-11ea-85e8-64a9821a1870.png

#### Expected behavior:

https://user-images.githubusercontent.com/8545105/81657278-09b29780-9438-11ea-9b18-2665b4cd8bbd.png

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: (if applicable)

**Comment by assuncaocharles** [comment] 2020-07-30 12:50
Hi @MaheshakaMudli 

Can you provide an small reproduction on codesandbox with the problem?
I tried it here: https://codesandbox.io/s/lingering-resonance-85x3l?file=/example.js 
And it seems to be working as expected

**Comment by MaheshakaMudli** [comment] 2020-07-30 13:01
Hi @assuncaocharles ,
I checked the version in which it was working. Currently it works fine in 0.51.0 version but teams generator supports 0.49.0 as of now.

**Comment by assuncaocharles** [comment] 2020-07-30 13:04
I don't think so, it's fixed in version 0.50 and as far as I remember there's no workaround for that in 0.49. @layershifter, @miroslavstastny  or @jurokapsiar any idea?

**Closed** 2021-04-26 14:02 UTC
Labels: Component: Dropdown, Fluent UI react-northstar, Needs: Investigation, Resolution: Soft Close
