### ISSUE TITLE
Dropdown component should adjust his callout width according to the longest option

### ISSUE THREAD

**Issue by ilanbd** [microsoft/fluentui#16181] opened 2020-12-08 17:37 UTC
I have an issue with the FluentUI Dropdown.
I would like the callout of the dropdown to adjust its size to fit his longest option.
This issue has already been discussed several times (see links below) but didn't get fixed yet.
https://github.com/microsoft/fluentui/issues/3263
https://github.com/microsoft/fluentui/issues/2228
https://github.com/microsoft/fluentui/issues/11996
https://github.com/microsoft/fluentui/issues/1521
 
I am aware that we can set the dropdown callout width but It means that we need to calculate the width in pixel of the strings which isn't ideal.

In the image below you can see that the last option is cut before the end of the string.
I would expect the callout width to fit the width of the longest option.( not the dropdown itself, only the callout)
![image](https://user-images.githubusercontent.com/19327745/101519368-c5668600-398b-11eb-84c3-5bb629010279.png)

Thanks!

**Comment by JustSlone** [comment] 2020-12-11 04:09
Thanks for filing this @ilanbd. 

Question. If the callout expands to the size of the text, what then would you expect the result to be once you select that value? Would it get truncated or would the dropdown expand to accommodate the length of the value?

**Comment by ilanbd** [comment] 2020-12-13 09:07
@JustSlone, I would expect it to truncate the string and add "..."

**Comment by JustSlone** [comment] 2020-12-13 21:23
Interesting question, I wonder why you are not seeing the ellipse with the html tooltip in your example. I see this, which would be a bit better experience. 
![image](https://user-images.githubusercontent.com/40304143/102023898-4e424080-3d43-11eb-907e-945bb6508c4a.png)

I'll follow up with an investigation into the issue below as well.

**Comment by JustSlone** [comment] 2020-12-13 21:33
So reading through the issues, and looking a prior art, it seems like feature space here is as follows. 
- Options for dropdown itself
   - Expand to fit text
   - [status quo] Truncate text with ellipse - Note we likely need to add a title attribute for the truncated text
- Options for callout
   - Expand to fit text
   - [status quo] Truncate text with ellipse + title attribute for html tooltip

Here's a codepen exploring this space: [Dropdown with long options - CodePen](https://codepen.io/justslone-the-encoder/pen/XWjpYmX?editors=1010)

Btw also the line of code we are discussing is this: https://github.com/microsoft/fluentui/blob/32a158fd2c7fca8dc308a3e41f692817e6c26c44/packages/react/src/components/Dropdown/Dropdown.base.tsx#L620
This prevents callout width from being cleared, we also don't seem able to override it with styles.

## One Possible fix
One would expect that calloutProps={{ calloutWidth: undefined }}  would clear out the calloutWidth value resulting in it not being set on Callout thus resulting in callout having automatic width.  This combined with calloutMaxWidth (and a new calloutMinWidth property) could allow the setting of the upper and lower bounds of the callout, while leaving it to respond to the dropdown content. 

We can achieve this by moving this line:
https://github.com/microsoft/fluentui/blob/32a158fd2c7fca8dc308a3e41f692817e6c26c44/packages/react/src/components/Dropdown/Dropdown.base.tsx#L620

above this line:
https://github.com/microsoft/fluentui/blob/32a158fd2c7fca8dc308a3e41f692817e6c26c44/packages/react/src/components/Dropdown/Dropdown.base.tsx#L614

Now, the one issue here is that callout does not have a calloutMinWidth property, so this would result in a poor experience where the callout shrinks to smaller than the dropdown width. 
To prevent this we we have two options:
1. add the calloutMinWidth prop to Callout which would allow it to be controlled by calloutProps on Dropdown
2. apply the minWidth style using {callout: {minWidth: ###px}}  via the styles prop on Dropdown. This has the benefit of it being the same method that is used to set the dropdown width itself.

This fix is good if we consider this use case to be advanced, as we don't have to expose a prop on dropdown directly to control the callout component. If we think it's a common case for Dropdown to set the callout behavior to auto size we should just add a prop instead of depend on calloutWidth: undefined.

**Comment by JustSlone** [comment] 2020-12-14 05:32
P.S. this is what the fix would look like visually
![image](https://user-images.githubusercontent.com/40304143/102043941-a3ee0b80-3d8a-11eb-9540-f2612727a361.png)

**Comment by ilanbd** [comment] 2020-12-17 15:53
Hi @JustSlone, Thanks for the elaborate response,
Do you need any more input from me on this issue? when do you think this change could be available?

**Comment by JustSlone** [comment] 2020-12-17 16:08
I just confirmed with the owner of dropdown on the proposed fix, it looks good to them. 

@ilanbd, no more input needed I think the issue is understood. Not sure when we'll get to this. If you are interested in a fix soon we would welcome a PR and someone from the team will review it. Fix 1 above should unblock you and is pretty straightforward. Fix 2 is a good idea as well if you are feeling adventurous. Note, if you add calloutMinWidth as part of fix 2, make sure to add a test for it's behavior.

**Comment by SamuelQZQ** [comment] 2020-12-21 08:12
@JustSlone 
For Fix 1, I think the `calloutProps={{ calloutWidth: undefined }}` is too weird. It seems that the user should have some knowledge about your implementation. 

I prefer Fix 3. And we should add the `calloutMinWidth` you mentioned in Fix 2. When `dropdownWidthAuto={true}`, when will set the `calloutWidth` to be undefined, and set the `calloutMinWidth` to be the width of Dropdown input control. Otherwise, it would be like this:
![example](https://user-images.githubusercontent.com/19623228/102753635-9d711c80-43a6-11eb-8640-78716dacad76.png)

After this change, users will use it simply like this
```Jsx
<Dropdown
  placeholder="Select an option"
  label="Basic uncontrolled example"
  options={options}
  styles={dropdownStyles}
  dropdownWidthAuto={true} // Fix #3 (instead of #1) - probably need a better name
/>
```
The `calloutMinWidth` and `calloutMaxWidth` can still be overwritten by users.

What do you think? I can make a PR.

**Comment by JustSlone** [comment] 2020-12-21 20:46
@SamuelQZQ Yeah! A PR would be great here. I agree fix #2 and #3 are better, just more complicated to make. Also, the fact that calloutWidth: undefined doesn't work is a bug. Now it's not a good api, but it should work. So we probably should reorder those two lines in callout. 

I'm out on vacation right now so response might be delayed, but yeah we'd be happy to review a PR here. 

Take a look at combobox for what it does and try to align with the pattern if you can. However, the new API on drop down needs to be backwards compatible (no breaking changes). Also check out this line below for warning on exclusive props. 

https://github.com/microsoft/fluentui/blob/588ce795462bbc96d1df7407ad50daace76e7f7e/packages/react/src/components/ComboBox/ComboBox.tsx#L260

If you have questions on the design let us know, or just spin a PR and we can iterate on that. 

CC: @ilanbd @joschect

**Comment by SamuelQZQ** [comment] 2020-12-28 12:20
@JustSlone I have created the PR. Have a look when you have time.

**Comment by JustSlone** [comment] 2020-12-28 18:01
@SamuelQZQ awesome thanks! @joschect is around this week and also owns dropdown, so he can take a look. I'll look if I find some spare time, but generally I'm out this week.

**Comment by joschect** [comment] 2020-12-29 00:08
@SamuelQZQ I had one suggestion but I have approved. I think that we should consider naming the new prop something else but other than that it looks good!

Thanks for submitting this fix!

**Closed** 2020-12-30 21:47 UTC
Labels: Component: Dropdown, Fluent UI react, Good First Issue 🏆, Help Wanted ✨, Status: Fix Proposed, Status: In PR

**Comment by ilanbd** [comment] 2021-01-06 11:58
Thanks for the quick fix!! could we get this change in version 7 instead of 8?

**Comment by ecraig12345** [comment] 2021-01-06 14:23
All changes are supposed to go to master first at this point, but we can cherry-pick to 7 if needed. @joschect will you have time to do that?

**Comment by ilanbd** [comment] 2021-01-17 08:27
Hi :) Any update on whether we can have it in version 7? 
Thanks!

**Comment by joschect** [comment] 2021-01-21 18:22
@ecraig12345 Yeah we should be able to get the cherry pick.

**Comment by JustSlone** [comment] 2021-02-04 05:09
@joschect, @ecraig12345 was this cherry picked to 7.0? I can't seem to find the cherry pick PR

**Comment by ecraig12345** [comment] 2021-02-04 05:10
@JustSlone Not that I know of

**Comment by ilanbd** [comment] 2021-02-11 16:16
Hi @joschect, @ecraig12345  :) Any update on whether it could be included in version 7? Thanks!

**Comment by joschect** [comment] 2021-02-11 16:27
@ilanbd Thanks for the question! I'll be cherry picking this so it will get included in 7!

**Comment by dawolff-ms** [comment] 2021-03-11 00:43
@joschect I hate to bother you again on this, but did this ever get included in version 7?

**Comment by joschect** [comment] 2021-03-12 21:33
@dawolff-ms Yes! This made it into 7. Here is [the associated pr!](https://github.com/microsoft/fluentui/pull/16959)
