### ISSUE TITLE
Escape key does not work with `gridCellMultipleFocusableBehavior`

### ISSUE THREAD

**Issue by thure** [microsoft/fluentui#18518] opened 2021-06-10 18:44 UTC
### Environment Information

- **Package version(s)**: `@fluentui/react-northstar@0.56`
- **Browser and OS versions**: Chrome 91

### Describe the issue:

When a GridCell is given the behavior `gridCellMultipleFocusableBehavior`, users should be able to return focus to the parent GridCell by pressing Escape after pressing Enter to focus on elements within the cell. Instead, nothing happens.

### Please provide a reproduction of the issue in a codepen:

Currently our CI pipe is broken, but as soon as it is fixed the current behavior can be seen in this part of our Storybook: https://dev-int.teams.microsoft.com/storybook/table-content-3/index.html?path=/story/components-table--kitchen-sink

#### Actual behavior:

Pressing Escape while focus is on content inside a GridCell with `gridCellMultipleFocusableBehavior` does nothing.

#### Expected behavior:

Pressing Escape while focus is on content inside a GridCell with `gridCellMultipleFocusableBehavior` causes the parent GridCell to receive focus.

### Documentation describing expected behavior

The Fluent UI docs claim the expected behavior is how this accessibility behavior should work: https://fluentsite.z22.web.core.windows.net/0.56.0/components/table/accessibility#grid-cell-multiple-focusable-behavior-ts

**Comment by gouttierre** [comment] 2021-07-12 12:34
@thure - thanks for reaching out to us.

@kolaps33 - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by chassunc** [comment] 2021-08-12 11:48
As agreed offline with @thure... I can't reproduce this error and I see the behavior working as expected, so I am closing this for now. @thure feel free to reopen it at any moment if you can reproduce it again and please provide use a codesandbox with steps to reproduce :)

**Closed by chassunc** 2021-08-12 11:48 UTC
Labels: Platform: Chrome, Fluent UI react-northstar, Needs: Investigation, Component: Grid
