### ISSUE TITLE
react@">=16.8.0 <17.0.0" from @fluentui/react@7.156.0

### ISSUE THREAD

**Issue by dev3thoughts** [microsoft/fluentui#16547] opened 2021-01-20 20:54 UTC
Hi, i am using react 17, i can not install fluentui?

**Comment by layershifter** [comment] 2021-01-25 15:11
@dev3thoughts are you using NPM v7? Do you have React 17 in your dependencies?

---

@ecraig12345 should we consider changing `peerDependencies` for v8? It creates issues with NPM v7 (https://github.com/Semantic-Org/Semantic-UI-React/issues/4129) - it's really impossible to install packages 😨

**Comment by dev3thoughts** [comment] 2021-01-25 18:24
@layershifter I am using Node -V12.18.3 and React-17 yes.

**Comment by ecraig12345** [comment] 2021-01-25 18:30
@layershifter We're tracking React 17 support in #15732. I think we were hesitant to add it to the peer deps range until we were at least able to run tests against it to do basic verification, but considering that 8 is a beta version it would probably be okay to go ahead and add it to the range and tell people to report any bugs they find.

**Comment by ecraig12345** [comment] 2021-02-26 08:30
We just released version 8 which includes React 17 in its peer deps range, so if you want to use React 17 I'd recommend upgrading to version 8. 

Once we're able to test version 8 against React 17 (see #15732), the number and difficulty of bugs we find will determine whether we can consider adding React 17 to the peer deps range for version 7.

**Comment by layershifter** [comment] 2021-03-29 10:49
Closing as a duplicate of #15732, v8 supports React 17 in its `peerDependencies`, #17048.

**Closed** 2021-03-29 10:49 UTC
Labels: Area: Build System, React 17, Resolution: Duplicate
