### ISSUE TITLE
DatePicker text input causes day to move to 1 day before

### ISSUE THREAD

**Issue by mikeybkats** [microsoft/fluentui#16774] opened 2021-02-02 22:45 UTC
### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.155.3
- **Browser and OS versions**: chrome / 88.0.4324.96 / mac

### Please provide a reproduction of the bug in a codepen:
using code sandbox hope that is okay
https://codesandbox.io/s/fluent-react-date-picker-manual-entry-issue-c1z08?file=/src/DatePicker.tsx

#### Actual behavior:
User selects the date with the mouse cursor. (works fine).
Now user changes date by clicking on text field to change the date. The change the day to a new day.
The day in the date picker moves to the day before what the user entered in the text box. –> 
11 becomes 10 
21 becomes 20

#### Expected behavior:
if the user enters a new date by text entry the date is as they entered it (does not move to a different day).

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes, I can certainly try!

Requested priority: (Blocking, High, Normal, Low) High – our users have complained.

Products/sites affected: (if applicable)

**Comment by joschect** [comment] 2021-02-17 22:10
@mikeybkats Thanks for the submission and including the code sandbox. I'm able to reproduce it with the codesandbox that you provided. We'll get this looked at.

**Comment by lorejoh12** [comment] 2021-02-19 21:45
Interesting. This looks like a really, really weird timezone conversion issue. When clicking, all squares in the grid are created using backing dates in the user's current time zone, so no issues there. However, when you type text, in DatePicker.base.tsx, we're calling `parseDateFromString`, which just calls the default javascript Date.parse(string) function.

From my local testing, calling `new Date("2021-2-19")` correctly returns Feb 19, 2021 at GMT-8 (my current timezone). However, if you call  `new Date("2021-02-19")`, it instead interprets that as a date in GMT, so it creates Feb 19, 2021 at GMT-0. This then gets converted to your local timezone, so for me it turns it to Feb 18, 2021 at 4pm, GMT-8, and we lose a day.

I'm not sure about the best fix for this. For most consumers, defining a new override for the parameter `parseDateFromString` is usually recommended because it doesn't leave as much up to chance, and libraries like momentjs are a lot more consistent than default javascript. But this is a really bad default case that I'd like to fix if possible.

Perhaps checking to see if the given string has a "T" in it, and if not, adding a Time. This way, something like `new Date("2021-02-19")` is instead `new Date("2021-02-19T00:00:00")`, which forces is back to the local time zone.

Another possibility is to use the fact that the date timezone offset is always less than 24 hours, and assume that the user is not purposefully typing a date with a time in it. Then we can just add minutes to the given time = the time zone offset. If it was interpreted as GMT-0, it'll set it back to midnight. If it was interpreted in local time, since the timezone offset is < 24 hours, it'll still keep the same day/month/year. Something like 
```
let d = Date.parse(string);
d.setHours(d.getHours() + d.getTimezoneOffset() / 60); // if hours >= 24, updates the date as well
d.setHours(0); // reset it back to zero if it wasn't already
```

I'm open to suggestions either way. The fastest fix is to have the consumer specify a new parseDateFromString function that does whatever they want it to to prevent running into this bug at all, but this does need to be looked at more carefully.

**Comment by mikeybkats** [comment] 2021-02-22 17:51
Thank you for your response. I have defined an override for parseDateFromString as you have suggested. This has solved my problem for the time being.

**Comment by mingfang** [comment] 2021-07-14 20:35
The correct way to fix this problem is to make Fluent UI local sensitive.
I want to able to set a timezone in global property(with ability to override on a per component basis).
The components should then apply the timezone whenever it handles Date.

**Closed** 2021-12-11 23:00 UTC
Labels: Type: Bug :bug:, Needs: Backlog review, Resolution: Soft Close
