### ISSUE TITLE
TooltipHost with ToogleButton accessibility narratoring issue

### ISSUE THREAD

**Issue by KevinYingWeiYeh** [microsoft/fluentui#21013] opened 2021-12-14 00:42 UTC
Environment Information

Package version(s): FluentUI/react 8.45

Browser and OS versions: Edition:	
Windows 10 Pro
Version	20H2
Installed on	‎6/‎30/‎2021
OS build	19042.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

Microsoft Edge
Version 96.0.1054.53 (Official build) (64-bit)

Describe the issue:
When Toggle-button has a Tooltiphost in the front Narrator scan mode adding one unknow tab-step and narrator "empty", and focus on both Tooltiphost and toggle-button. The toggle has two tab-step instead of one.

Please provide a reproduction of the issue in a codepen:
Issue is reproducible in example from the docs. On this page: https://fabricweb.z5.web.core.windows.net/oufr/8.47.1/#/examples/toggle
Enable Narrator.
Go to "Toggles with Custom Labels" section
Click narrow-key up and down in between the tooltiphost and toggle-button
Observe that the button narrates "empty", if press one more time of the narrow-key again, it changes back to narrate normal again. 

Alternatively, perform the same steps in this codepen:
https://codepen.io/KevinYeh/pen/mdBRVWN

Actual behavior:
When TooltipHost and ToggleButton in the same scope, it adds new stop in scan mode and narrate "empty"

Expected behavior:
When TooltipHost and ToggleButton in the same scope, it shouldn't add extra stop and narrate "empty"

**Comment by gouttierre** [comment] 2022-01-18 13:06
@KevinYingWeiYeh - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue? 
cc @smhigley

**Comment by smhigley** [comment] 2022-05-27 19:15
The behavior I'm getting in that codepen is that Narrator will hit a blank scan mode item when using up/down arrows, but not when using Caps + left/right arrows, and not when tabbing.

Narrator reaching "blank" items is extremely common in scan mode with unmodified up/down arrows, and isn't a bug. It can occur for any reason, often because of whitespace characters. This isn't an issue, just part of normal screen reader experience. I'd also suggest navigating with caps + left/right arrows in general when moving item-by-item, since it's much less buggy than up/down arrows.

**Closed by smhigley** 2022-05-27 19:15 UTC
Labels: Area: Accessibility, Component: Toggle, Area: Narrator, Needs: Investigation, Fluent UI react (v8)
