### ISSUE TITLE
[Accessibility][Dropdown][Fluentui]: Accessibility issues when using options with dividers and headers

### ISSUE THREAD

**Issue by levymsft** [microsoft/fluentui#17517] opened 2021-03-22 22:46 UTC
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.165.0"
- **Browser and OS versions**: Edge Version 89.0.774.57 (Official build) (64-bit)
Windows Version 10.0.19042 Build 19042

### Describe the issue:

The dropdown component is causing accessibility issues when used with options containing headers and dividers.
To reproduce:
1-render the code bellow
2-select the dropdown so that all options will be listed
3-run [Microsoft accessibility test](https://microsoftedge.microsoft.com/addons/detail/accessibility-insights-fo/ghbhpcookfemncgoinjblecnilppimih) 
4- aria-allowed-attr and aria-required-parent issues will be shown on the errors list

```
const Content = () => {
  const options = [
      {
        key: 'all',
        text: 'All builds'
      },
      {
        key: 'all-divider',
        text: '-',
        itemType: DropdownMenuItemType.Divider
      },
      {
        key: 'CurrentChannel-divider',
        text: '-',
        itemType: DropdownMenuItemType.Divider
      },
      {
        key: 'Currentchannel-header',
        text: 'CurrrentChannel',
        itemType: DropdownMenuItemType.Header
      },
      {
        key: 'CurrentChannel-16.0.13901.20066',
        text: '2020 16.0.13901.20066',
      },
      {
        key: 'CurrentChannel-17.0.13901.20066',
        text: '2020 17.0.13901.20066',
      },
  ];
  
  return (
    <Dropdown
      label='Test'
      id='DropDownTest'
      multiSelect={true}
      options={options}
      />
  );
};
```
#### Actual behavior:

After the test accessibility issues are found.

#### Expected behavior:

No accessibility issues.

### If applicable, please provide a codepen repro:

https://codepen.io/lmoreira/pen/QWdWvYP

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High (breaking accessibility)

Products/sites affected: (config.office.com)

**Comment by gouttierre** [comment] 2021-05-25 10:12
@levymsft - thanks for filing this item and sharing the details around the accessibility issue.

@TristanWatanabe - Would you be able to confirm if this is a regression, or if this behavior is an accessibility issue?
cc @smhigley

**Comment by TristanWatanabe** [comment] 2021-05-26 19:54
@levymsft @gouttierre this is a duplicate of #17838 and is actually an issue with axe-core as further explained here: https://github.com/microsoft/fluentui/issues/17838#issuecomment-824442277

**Closed** 2022-02-04 19:04 UTC
Labels: Area: Accessibility, Component: Dropdown, Resolution: External, Fluent UI react (v8), Resolution: Soft Close
