### ISSUE TITLE
@fluentui/react-components: React 18 support

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#22581] opened 2022-04-21 09:36 UTC
React 18 was released.
Test with React 18, create list of issues, triage them.

**Comment by denis-sokolov** [comment] 2022-06-08 10:12
This might be a duplicate of #22241.

**Comment by layershifter** [comment] 2022-06-08 10:23
@denis-sokolov it's not, this issue is dedicated to `@fluentui/react-components`.

**Comment by micahgodbolt** [comment] 2022-10-13 20:26
This was fixed in #22592 V9 is currently working in React 18. Upgrading the repo to use v18 is a whole nother story though.

**Closed by micahgodbolt** 2022-10-13 20:26 UTC
Labels: Fluent UI react-components (v9), React 18
