### ISSUE TITLE
Deleting selected option which length is 1 of the combobox is blocked

### ISSUE THREAD

**Issue by TadasMil** [microsoft/fluentui#16300] opened 2020-12-28 11:07 UTC
Version used:
- "office-ui-fabric-react": "^6.214.1",

I found a bug on the version mentioned above. This is based with combo box. When you select one of the options with the option length which is equal to 1, I'm not able to delete the selected option. Once I select an option, which length is above 1, I can easily delete the selected option. 

I'm attaching a simple code.

Once I install version "7.155.3", the issue is being resolved. But the latest version brakes a lot of my components in the application.

Any suggestions?

```
import React from 'react';
import {
  ComboBox,
  IComboBoxOption,
  SelectableOptionMenuItemType,
} from 'office-ui-fabric-react/lib/index';
import './App.css';

const comboBoxBasicOptions: IComboBoxOption[] = [
  { key: 'Header1', text: 'First heading', itemType: SelectableOptionMenuItemType.Header },
  { key: 'A', text: 'Option A' },
  { key: 'B', text: '1' },
  { key: 'C', text: 'Option C' },
  { key: 'D', text: 'Option D' },
  { key: 'E', text: 'Option E' },
  { key: 'F', text: 'Option F', disabled: true },
  { key: 'G', text: 'Option G' },
  { key: 'H', text: '2' },
  { key: 'I', text: 'Option I' },
  { key: 'J', text: 'Option J' },
];

function App() {
  return (
    <div className="App">
      <ComboBox
        defaultSelectedKey="C"
        label="Basic ComboBox"
        allowFreeform
        autoComplete="on"
        options={comboBoxBasicOptions}
      />
    </div>
  );
}
```

**Comment by gouttierre** [comment] 2021-03-03 18:11
@TadasMil - thank you for the feedback!

I have gone through the issue you shared. You are right, version 6.214.1 does have a problem with items with a length == 1 when trying to remove them.  Could you share why you have breaking changes when moving to the higher version where the issue has been resolved? 

To set expectations - Due to the complexity and dependencies of our List components, we are actively trying to minimize risk of regressions. We may not be able to fix this issue with a low risk solution. if a reasonable workaround is available.

@khmakoto -  Can you determine if this is a regression or if this behavior is an issue? I noticed if a length  == 1 and the user adds a single character (i.e. length > 1), then they are able to remove the line item.

**Comment by ecraig12345** [comment] 2021-03-03 21:47
@TadasMil Especially now that we've released version 8, we're very unlikely to fix issues that are specific to version 6, sorry (though if you wanted to submit a fix we'd consider it). The [version 7 release notes](https://github.com/microsoft/fluentui/wiki/Fabric-7) and [version 8 release notes](https://github.com/microsoft/fluentui/wiki/Version-8-release-notes) may be helpful with updating.

**Closed** 2021-03-07 22:00 UTC
Labels: Component: ComboBox, Fluent UI react, Needs: Author Feedback, Resolution: Won't Fix, Type: Bug :bug:, v6
