### ISSUE TITLE
[Bug]: SplitButton opens the dropdown menu instead of invoking the onClick action when used with touch.

### ISSUE THREAD

**Issue by romanisa** [microsoft/fluentui#23711] opened 2022-06-23 21:09 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.07 GB / 15.60 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.44), ChromiumDev (104.0.1293.1)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/button

## Actual Behavior
When the SplitButton is used with touch, the dropdown menu appears even if user touches on the left portion of the split button. This is reproducible on https://developer.microsoft.com/en-us/fluentui#/controls/web/button sample controls for the SplitButton component as well. 

## Expected Behavior
Behavior with touch should be same as behavior with mouse click. i.e. when user touches the left portion of the split button, it should invoke the onClick function rather than opening the dropdown.

### Requested priority

Normal

### Products/sites affected

Outlook Web

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment] 2022-08-01 16:39
@romanisa closing this as this was done by design (see this [PR](https://github.com/microsoft/fluentui/pull/4353) for details)

**Closed by TristanWatanabe** 2022-08-01 16:39 UTC
Labels: Resolution: By Design, Fluent UI react (v8), Component: SplitButton
