### ISSUE TITLE
Detail List [Power Automate] : Narrator is not announcing any information about Sorting when focused on the Header

### ISSUE THREAD

**Issue by Puyush6889** [microsoft/fluentui#12718] opened 2020-04-15 23:50 UTC
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Microsoft edge, Windows

### Describe the issue:

The issue happens on Detail List Column Header. When the Narrator is turned on and we focus on the element. The Narrator doesn't announce if we are able to sort on the column header. 

### Please provide a reproduction of the issue in a codepen:

I was able to repro the issue on the codepen from (https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic)

https://codepen.io/sdasdasdas/pen/ExVPLEj

#### Actual behavior:

When Focusing on the element with Narrator, the Narrator doesn't announce anything information regarding that Column is sortable. It will only announce it once we press enter and the column is sorted.
ex, 
![image](https://user-images.githubusercontent.com/14367457/79399706-ed0a6900-7f38-11ea-8f12-88e7729d4d92.png)

#### Expected behavior:

The Expected behavior should be that when focusing on the column header we should announce if the column header is sortable.

**Comment by joschect** [comment] 2020-04-17 01:28
@Puyush6889 Thanks for the submission! I'm able to reproduce the behavior you're talking about. However, it looks like we're adding all of the appropriate roles, `ara-sort="none"` is on the sortable headers. Additionally I tried narrator and edge on [this aria example](https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html) and sortable was not read out either. This seems to be a problem with narrator and edge. 

This issue has been submitted a few times and it looks like narrator/edge is aware of it according to this issue #4870 , #11564

**Comment by xugao** [comment] 2020-07-23 22:30
closing as this is an external issue

**Closed by xugao** 2020-07-23 22:30 UTC
Labels: Component: DetailsList, Resolution: External
