### ISSUE TITLE
[Bug]: TimePicker component does not allow for default text to be set for the comboBox

### ISSUE THREAD

**Issue by nipothar** [microsoft/fluentui#25882] opened 2022-12-02 20:58 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 15.98 GB / 31.59 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/pen?&prefill_data_id=9166bd21-6524-402c-9a36-f42eb0894a54

## Actual Behavior
There is no way to set the default text value to be for example: "7:32" for the comboBox while the dropdown has 30min increments. Neither is the "text" properties exposed as a property for the TimePicker component.  

## Expected Behavior
We should have "text" or the "defaultValue" property of the comboBox exposed or some otherway to set the initial comboBox text value to be set.

### Requested priority

Blocking

### Products/sites affected

Fidalgo

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment] 2023-01-31 12:48
`defaultValue` does not work in examples, too, https://developer.microsoft.com/en-us/fluentui#/controls/web/timepicker.

This looks like a duplicate of #25730.

**Closed** 2023-01-31 12:48 UTC
Labels: Resolution: Duplicate, Fluent UI react (v8)
