### ISSUE TITLE
SplitButton - glitchy button border

### ISSUE THREAD

**Issue by RoelVB** [microsoft/fluentui#14969] opened 2020-09-10 13:20 UTC
### Environment Information

- **Package version(s)**: 7.137.0 (if the documentation site uses the latest version, tested it locally on 7.134.1)
- **Browser and OS versions**: Chromium

### Please provide a reproduction of the bug in a codepen:

This can be reproduced through the [documentation site](https://developer.microsoft.com/en-us/fluentui#/controls/web/button).

#### Actual behavior:

First, the disabled main action is missing a border, this looks strange:
![image](https://user-images.githubusercontent.com/10999128/92733631-1f998000-f378-11ea-8251-70073144e466.png)

For some reason, if you choose to "show code" and wait for two seconds, the button borders change:
![image](https://user-images.githubusercontent.com/10999128/92733799-3fc93f00-f378-11ea-82fb-69660f86cf36.png)

I get another variant in my own code:
![image](https://user-images.githubusercontent.com/10999128/92734455-d85fbf00-f378-11ea-92d2-5f0a56a3aba3.png)
It looks like the first screenshot from the documentation, but this time the main action isn't disabled.

#### Expected behavior:

I would expect the border to be always there. Maybe except when the button is completely disabled (main action and subitems).

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Low

**Comment by paulgildea** [comment] 2020-09-10 16:08
@RoelVB Thanks for the feedback.

@khmakoto - Have we made any changes to SplitButton that would be impacting the current version of it?

**Comment by miroslavstastny** [comment] 2020-09-17 14:13
The disabled button gets styles from `rootDisabled` in `BaseButton.styles.ts` which sets the border color to the background color:
https://github.com/microsoft/fluentui/blob/4eef39d7498c16082b380c71779204a3483d329e/packages/office-ui-fabric-react/src/components/Button/BaseButton.styles.ts#L70

Split button is considered disabled if the primary button is disabled, there is no logic to have different border based on secondary button state:
https://github.com/microsoft/fluentui/blob/cc72899b69926f902d68f3164a7845401f1dc700/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L135

**Comment by khmakoto** [comment] 2021-03-19 18:54
@RoelVB, I think this would be considered by design in the current version, so I'll be resolving it as such for now. We're actively working on our next version of the `Button` component though and we'll take this into account when developing it. I've already added this issue to #16819 to have it in mind!

**Closed** 2021-03-20 19:00 UTC
Labels: Component: Button, Fluent UI react, Platform: Chrome, Platform: Microsoft Edge, Resolution: By Design, Resolution: Not An Issue
