### ISSUE TITLE
aria-required-Children: Ensure elements with a ARIA role that require child roles contain them

### ISSUE THREAD

**Issue by Jashwatnth** [microsoft/fluentui#17981] opened 2021-04-28 06:46 UTC
**Environment Information**
**Package version(s)**: 8.9.4 and 8.13.0
**Browser and OS versions**: Google Chrome
**Describe the issue**:  When ran fast pass on the page which contains the fluent UI Dropdown control, we have received aria-required-children issue.
suggesting as Required ARIA child role not present: textbox
Please provide a reproduction of the issue in a codepen:
Actual behavior:
Expected behavior:
Documentation describing expected behavior

![image](https://user-images.githubusercontent.com/76465899/116358709-91491000-a81b-11eb-8d7b-394cb32b2b05.png)

**Comment by chnldw** [comment] 2021-04-30 20:04
https://github.com/microsoft/fluentui/issues/17838

**Comment by smhigley** [comment] 2021-08-04 05:19
This is a false positive from Accessibility Insights, and a dupe of #17838, #18333, and #19014. The false positive has already been fixed in axe-core (where Accessibility Insights' rules set comes from): dequelabs/axe-core#2505.

@max-zheng to your question specifically: adding textbox (whether through a role or otherwise) as a child of a combobox results in significantly worse real-world support, so I definitely wouldn't recommend adding that role to the child span :)

**Closed by smhigley** 2021-08-04 05:19 UTC
Labels: Resolution: External
