### ISSUE TITLE
[Bug]: Chosen date in the V9 DatePicker does not respect user's language settings. It always shows in English.

### ISSUE THREAD

**Issue by dylandong12** [microsoft/fluentui#31236] opened 2024-04-30 18:01 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 13.19 GB / 63.95 GB
  Browsers:
    Edge: Chromium (124.0.2478.67)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/afm5s9?file=src%2Fexample.tsx

## Actual Behavior
Change the language of the Teams client or the browser. Select a date. The chosen date is always in English.

## Expected Behavior
The chosen date should respect user's language settings. 

I see there is a [localized example](https://react.fluentui.dev/?path=/docs/compat-components-datepicker--default#localized)
but it is not what I am looking for. It translates each month and reformats the date manually through the formatDate method. However, this is not what client side can do, we cannot determine the order of the day, month, year because for some language, people read from right to left. **We do not need to do anything when we use the old date picker, the chosen date is automatically translated, but after the migration, the chosen date is always in English**. This is the last piece of our migration, we are blocked by this until we can find a solution.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment] 2024-05-07 15:33
I don't have proper context but I'm curious how `We do not need to do anything when we use the old date picker, the chosen date is automatically translated, but after the migration, the chosen date is always in English` is actually working, as that needs to be done within application code based on language setting fetched from user browser. 

Briefly looked at the v8 and v9 format/value implementation and it is the same so I'm not sure the behaviour that "just works" is actually what is happening.

I'll leave this to the SME on this control @sopranopillow 

ty

**Comment by layershifter** [comment] 2024-05-09 10:09
We had conversation about this in offline.

For context, v0 DatePicker used `strings` prop to also localize the input, v9 one requires to use `onFormatDate` as documented in the examples. Both datepickers don't have built-in localization by design. Closing it.

**Closed by layershifter** 2024-05-09 10:09 UTC
Labels: Component: DatePicker, Needs: Author Feedback, Partner Ask, Fluent UI react-components (v9)

**Comment by Hotell** [comment] 2024-05-09 11:41
> v0 DatePicker 

? v8 no ?
