### ISSUE TITLE
Webpack complains ./unstable is not exported from @fluentui/react-components package

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#21953] opened 2022-03-04 08:14 UTC
### Environment Information

- **Package version(s)**: @fluentui/react-components@9.0.0-rc.5
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

```ts
import { Input, Label } from '@fluentui/react-components/unstable';
```

#### Actual behavior:
The following error is reported by Webpack (v5.70.0):
```
ERROR in [js file path]
Module not found: Error: Package path ./unstable is not exported from package [root]\node_modules\@fluentui\react-components
(see exports field in [root]\node_modules\@fluentui\react-components\package.json)
 @ ./src/[js file path] 6:0-85 68:19-38
...
...
...
 @ ./src/index.ts 19:37-57
```

Now even if I replace `@fluentui/react-components/unstable` with `@fluentui/react-components/lib/unstable`, the import still won't succeed, as `lib` is not defined in `exports` field in `package.json`, either.

#### Expected behavior:

The import should succeed.

If I apply the following patch to `@fluentui/react-components/package.json`, Webpack won't have any trouble finding the `unstable` sub-package.

```diff
@@ -82,6 +82,7 @@
       "import": "./lib/index.js",
       "require": "./lib-commonjs/index.js"
     },
+    "./unstable": "./unstable",
     "./package.json": "./package.json"
   }
 }
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Not yet.

Requested priority: Blocking (This blocks us from consuming v9.0.0-rc.5 and later versions of fluent UI react packages.)

Products/sites affected: (if applicable)

**Comment by qq240814476** [comment] 2022-03-04 08:31
I have the same problem.

**Comment by micahgodbolt** [comment] 2022-03-04 18:29
Have you tried using RC4? Does it have the same issue? Curious if this is a regression in 5, or a long standing issue.

**Comment by micahgodbolt** [comment] 2022-03-04 18:41
Ok yeah. We JUST made some changes to make exports more explicit in RC5

https://github.com/microsoft/fluentui/pull/21508

Looks like we need to fix this unstable export and cut a new release.

**Comment by micahgodbolt** [comment] 2022-03-04 18:48
@qq240814476 @chenxinyanc we'll work on a fix for this in RC6. Until then, you can manually install any of the unstable packages directly

`@fluentui/react-label, @fluentui/react-input`

**Closed** 2022-03-04 19:22 UTC
Labels: Type: Bug :bug:, Status: In PR

**Comment by dzearing** [comment] 2022-03-04 20:05
This should now be resolved in `@fluentui/react-components_v9.0.0-rc.6`. Sorry for the trouble!

**Comment by chenxinyanc** [comment] 2022-03-07 05:35
`rc.6` works. Thanks for the fast resolution!
