### ISSUE TITLE
Dropdown container is using incorrect role attribute

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#13067] opened 2020-05-08 13:50 UTC
### Environment Information

- **Package version(s)**: 7.110.5
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/xinychen/pen/JjYLrOg

#### Actual behavior:
The role of `Dropdown` container is `listbox`.
![image](https://user-images.githubusercontent.com/50703224/81402150-6fb2cc80-9163-11ea-8daf-6cc6318a2504.png)

#### Expected behavior:
The dropdown container should have `role="button"` and `aria-haspopup="listbox"`. See: https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html .

As a reference, see the implementation of dropdown (`Select`) in MUI: https://material-ui.com/components/selects/#simple-select .

### Priorities and help requested:

Are you willing to submit a PR to fix? Not currently.

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment] 2020-05-08 15:40
@chenxinyanc This is a dupe of #11180 - see [comment](https://github.com/microsoft/fluentui/issues/11180#issuecomment-554062574) there for resolution.

**Closed** 2020-05-11 18:00 UTC
Labels: Component: Dropdown, Needs: Author Feedback, Resolution: By Design, Resolution: Duplicate
