### ISSUE TITLE
[Bug]: V9 Menu has no animation

### ISSUE THREAD

**Issue by raymeskhoury** [microsoft/fluentui#24016] opened 2022-07-21 04:30 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
NA
```

### Reproduction

https://react.fluentui.dev/?path=/docs/components-menu-menu--default

### Bug Description

Currently the menu just appears, even when it's attached to a button. Ideally it would animate down, just as the menus do on the Windows 11 file explorer.
<img width="191" alt="image" src="https://user-images.githubusercontent.com/8130584/180130053-9af51d1e-ca58-4364-9e34-9016a1525d5e.png">

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment] 2022-08-04 10:08
Duplicate of #24133.

**Closed by miroslavstastny** 2022-08-04 10:08 UTC
Labels: Type: Feature
