### ISSUE TITLE
Responsive Pivot:  I have solution working with minor css to resolve

### ISSUE THREAD

**Issue by mikezimm** [microsoft/fluentui#15002] opened 2020-09-11 20:45 UTC
### Tagged users:
@paulgildea , @badsyntax, @khmakoto 

First, this is 

1. Partly a **Feature request**
2. But also **possible implementation** concept for the request
3. And Short Term looking for like minded person who knows CSS who might be able to **assist with my** current solution.

## Describe the feature that you would like added
Responsive **[FluentUI Pivot ](https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot)** that handles **overflow**.
It doesn't necessarily need to be the actual pivot component but something that looks and feels like the current one that handles overflow for smaller screens.

## What component or utility would this be added to
[FluentUI Pivot ](https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot) or really anything that can work like a pivot with overflow

## What I have done so far:
I took the [FluentUI ResizeGroup ](https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2F) sample, reverse engineered the css so that it looks like the [FluentUI Pivot ](https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot) which was no small feat for my skills.

In my current working solution shown in the video below, I have a toggle that just switches between a real pivot and my command bar implementation.

This is currently in SPFx since that's all I know.  My only challenge is minor CSS so that it doesn't "shift" when you click on a button and animating the pivot underline.

Thanks for any help!

## [Short Youtube showing what I have done in SPFx](https://youtu.be/zZPuasVtwho)
![image](https://user-images.githubusercontent.com/49648086/92970983-a1a7a880-f44d-11ea-9600-163ec1905648.png)

**Comment by mikezimm** [comment] 2020-09-12 23:44
I was able to band-aid it so it doesn't shift by:

changing my css from
```css
font-weight: 600;
```
to 
```css
//Credit for using text-shadow instead of bold to prevent shift:  https://stackoverflow.com/a/14978871
text-shadow: 0px 0px 1px black;
```
However, it does look slightly blurry so I was going to the option below suggested on [stack exchange](https://stackoverflow.com/a/32570813).  Unfortunately I can't figure out how to get the right text content with the command buttons.  There is no title attribute right on the label to reference.  Any ideas?

```css
::before {
    display: block;
    content: attr(title);
    font-weight: bold;
    height: 0;
    overflow: hidden;
    visibility: hidden;
}
```
Here's what it looks like with the text-shadow:
![image](https://user-images.githubusercontent.com/49648086/93006921-48647580-f530-11ea-8a6c-ba3e5fd7b7e8.png)

**Comment by paulgildea** [comment] 2020-09-18 14:11
@mikezimm Thanks for the feedback.

@JustSlone - Does the new behavior with the Tab component address this issue?

**Comment by badsyntax** [comment] 2020-09-18 14:50
Somewhat related, although taking a different approach: https://github.com/microsoft/fluentui/issues/14429

**Comment by behowell** [comment] 2020-09-18 21:45
Hi @mikezimm, the next major release (v8) will have support for a Pivot overflow menu that's similar to what you suggested (enabled using the `overflowBehavior="menu"` property). The updated Pivot is also available now in a standalone package `@fluentui/react-tabs`, if you want to try it before v8 is released.

Here's a demo of the overflow functionality: https://codesandbox.io/s/pivot-overflow-menu-demo-grrgg

**Comment by behowell** [comment] 2020-09-18 21:46
Duplicate of #4066

**Closed by behowell** 2020-09-18 21:46 UTC
Labels: Component: Pivot, Needs: Backlog review, Type: Feature

**Comment by mikezimm** [comment] 2020-09-21 17:44
Cool thanks @behowell , I think since I'm putting it in SharePoint online, I may have to wait to use it in an SPFx since it's usually a version or 2 behind.

I was curious... I can't see how to play your codesandbox or I'd probably be able to see...

How do you handle displaying what was clicked if it was in the overflow?
Does it highlight it in the overflow menu or does it somehow show on the page visible when the menu is not in dropdown mode?

Thanks again and can't wait to try it!

**Comment by behowell** [comment] 2020-09-21 19:14
@mikezimm If you select a tab from the overflow menu, it will replace the last-visible tab*, so that the selected tab is always visible, and the previous last-visible tab is now in the overflow.

So for example, if you have a bunch of tabs and they overflow like this:
<ins>`One`</ins> | `Two` | `Three` | `Four` | `[...]`
_Overflow menu:
`Five`
`Six`_

If you pick tab Five, it'll be:
`One` | `Two` | `Three` | <ins>`Five`</ins> | `[...]`
_Overflow menu:
`Four`
<ins>`Five`</ins>
`Six`_

 (* more accurately, it'll move as many tabs as necessary into the overflow menu in order to fit in the available space. So if the new selected tab label is very long, it could replace multiple tabs).
