### ISSUE TITLE
[north-star] dropdown item header customization error

### ISSUE THREAD

**Issue by wills2133** [microsoft/fluentui#19555] opened 2021-08-29 22:15 UTC
### Environment Information

- **Package version(s)**:  @fluentui/react-northstar@0.57.0

### Please provide a reproduction of the bug in a codepen:
[example](https://codesandbox.io/s/fluent-ui-example-forked-ewgrq?file=/example.js)

#### Actual behavior:

when set
```
const inputItems = [
  {
    header: {
      content: <h1>Robert Tolbert</h1>
    },
    content: "Robert Tolbert"
  }
];
```
got compile error:
```
TypeError
itemToString(...).toLowerCase is not a function
```
#### Expected behavior:

DropdownItem props header and content are the same type, so
```
const inputItems = [
  {
    header: {
      content: <h1>Robert Tolbert</h1>
    },
    content: "Robert Tolbert"
  }
];
```
should work like
```
const inputItems = [
  {
    header: "Robert Tolbert",
    content: {
      content: <h1>Robert Tolbert</h1>
    }
  }
];
```
### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by gouttierre** [comment] 2021-09-07 12:34
@wills2133 - thanks for filing this issue with us. 

@jurokapsiar -  Would your team be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by layershifter** [comment] 2021-11-30 15:36
As in Northstar we use CSS-in-JS you can apply `opacity` to content via `styles`:

```tsx
  <Popup
    trigger={<Button icon={<MoreIcon />} title="Show popup" />}
    content={{ content: "Hello from popup!", styles: { opactity: '0.5' }}
  />
```

If you want to use plain CSS, you should pass it to `content` slot:

```tsx
  <Popup
    trigger={<Button icon={<MoreIcon />} title="Show popup" />}
    content={{ content: "Hello from popup!", className: styles.popupOpacity }}
  />
```

[🗃️ CodeSandbox](https://codesandbox.io/s/fluent-ui-example-forked-xhi09?file=/example.js:237-393)

---

`className` prop on `Popup` ~~does not exist~~ is not handled, I will create a PR to remove it. Thanks for reaching us 👍

**Comment by layershifter** [comment] 2021-12-07 12:48
Thanks for reporting, let me clarify why it happens. For filtering purposes `Dropdown` uses `itemToString()`, that function transforms passed items to strings. It defaults to:

https://github.com/microsoft/fluentui/blob/01af9776cc9d5b54b7d5992c0b3e3777ae19582b/packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx#L1753-L1760

If you don't use filtering you define this function as noop:

```tsx
const customItemToString = (item) => "";
```

https://codesandbox.io/s/fluent-ui-example-forked-skhdw?file=/example.js

If you still want use filtering you need to identify a property on item that could be used for this purpose, for example `itemAsString`:

```tsx
const customItemToString = (item) => item?.itemAsString;
```

https://codesandbox.io/s/fluent-ui-example-forked-8x74g?file=/example.js

---

As this is a behavior by design - I am closing this issue.

**Closed by layershifter** 2021-12-07 12:48 UTC
Labels: Component: Dropdown, Fluent UI react-northstar, Needs: Investigation
