### ISSUE TITLE
Nav Component: Selected Information Not Convey in Edge Chromium  As well same for High light not say it is not selected   

### ISSUE THREAD

**Issue by v-jashr** [microsoft/fluentui#13160] opened 2020-05-14 12:19 UTC
Nav Component:  selected / not selected  Information not Convey in Edge Chromium.
**Browser**
 Edge Chromium (any)

Screen Reader
Narrator 

Expected Result
When Focus Jumps to Any Nav item and if it is already selected message should Convey to Narrator in Edge Chromium  that it is selected along with text. Similar case in not selected situation. 

Actual Result
It is not convey message of Selected / not selected nav item.

![image](https://user-images.githubusercontent.com/50479173/81933160-8d23e280-960a-11ea-8137-57408a536bb0.png)

**Comment by aneeshack4** [comment] 2020-05-14 15:49
This seems to be a dupe of #11788 and should've been fixed in PR #11811... but I do repro this behavior:

**Comment by smhigley** [comment] 2021-09-21 00:27
This is an Edge issue (and potentially Narrator as well). The current link has `aria-current="page"` on it, which is the correct property for indicating the current-page link within a set of links. It appears that Edge is not mapping `aria-current` to UIA's AriaProperties bucket.

Edge would need to update the mapping, and it would need to be respected by Narrator (it's currently unclear whether the second is true, since the mapping doesn't exist).

There's nothing we can do from Fluent's side; any "fix" like appending the information to the accessible name would likely be making the experience worse overall :/

**Closed by smhigley** 2021-09-21 00:27 UTC
Labels: Type: Bug :bug:, Area: Accessibility, Component: Nav, Needs Dev Input
