### ISSUE TITLE
[DatePicker] Narrator is reading incorrect information while entering the date picker table.

### ISSUE THREAD

**Issue by ketaniyengar-msft** [microsoft/fluentui#19536] opened 2021-08-26 13:31 UTC
### Environment Information

- **Package version(s)**: 8.21.1
- **Browser and OS versions**: Microsoft Edge Version 92.0.902.78 (Official Build) (64-bit)

### Describe the issue:

While entering the date picker component after changing the month using the up and down arrows provided, the narrator reads out "Enter table month year" where month and year refer to the previous state of the date picker instead of the current one which it ideally should. For example initially the date picker was at August 2021 and the month is then changed to March 2021 and then entered again, the narrator says, "Enter table August 2021 ...{and proceeds to say the correct information afterwards}".

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/ketaniyengar-msft/pen/NWgqNxw

#### Actual behavior:

The narrator is reading "Enter Table August 2021" with the example stated above.
![image](https://user-images.githubusercontent.com/87801215/130971405-cbd55db8-ef97-4391-be94-975578cd82f1.png)

#### Expected behavior:

The narrator should read "Enter table month year" where month and year is the currently open one in the date picker in the above case is March 2021.

**Comment by gouttierre** [comment] 2021-09-07 13:34
@ketaniyengar-msft  - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@bsunderhus -  Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by smhigley** [comment] 2021-09-07 17:20
The table is actually getting its name directly from the visible month/year text, so if that text is correct then the table name is also correct. You can verify this by directly observing the accessibility properties of the table as you change months. I would guess that this error is caused by some sort of caching issue either in Edge or Narrator, possibly also related to how powerful your machine is, since I can't repro on my computer.

Unfortunately, since this isn't related to Fluent's code, there's nothing we can do in our library to change the behavior. And since I can't reproduce it, I can't tell if it's an issue with Edge or Narrator. I'd suggest trying on different versions of Edge, and on different computers to see if there's any pattern in where it reproduces. If you can, I'd use Accessibility Insights for Windows to check if the actual mapped UIA tree for the table is correctly updating the accessible name.

**Comment by smhigley** [comment] 2021-09-07 17:21
I'm closing the issue because there's nothing we can do in Fluent, but feel free to re-open or follow up if you find something I've missed.

**Closed by smhigley** 2021-09-07 17:21 UTC
Labels: Area: Accessibility, Component: DatePicker, Platform: Microsoft Edge, Area: Narrator, Needs: Investigation, Fluent UI react (v8)
