### ISSUE TITLE
Drag and Drop between people pickers

### ISSUE THREAD

**Issue by alex3683** [microsoft/fluentui#10451] opened 2019-09-16 09:09 UTC
#### Describe the feature that you would like added

I would like to have the possibility to move people between two PeoplePicker instances by using drag and drop. The current version of OWA for Exchange Online implements this, probably using the Fabric component, to move people between required and optional participants in a calendar entry. So I guess there may be some way to implement this, but it isn't quite obvious and not directly exposed as API of the component.

#### What component or utility would this be added to

PeoplePicker (probably other similar pickers too)

#### Have you discussed this feature with our team, and if so, who

Nope

#### Additional context/screenshots

![grafik](https://user-images.githubusercontent.com/768322/64945985-2fb87580-d872-11e9-9bcb-1037fa3b6af9.png)
![grafik](https://user-images.githubusercontent.com/768322/64946009-3941dd80-d872-11e9-95ad-1c0f6cc847b2.png)
![grafik](https://user-images.githubusercontent.com/768322/64946024-3f37be80-d872-11e9-991a-a5892ec7affc.png)

Screenshots of the Drag and Drop Operation in different stages as taken on https://outlook.office365.com/calendar

**Comment by aneeshack4** [comment] 2019-09-16 18:48
@alex3683 Our PeoplePicker is a shared component used in many different situations and this drag & drop feature could fit differently into each of those. It's also something that could be implemented by the consumer. Basically, we don't believe this should be a feature on the native shared component. Its owner @joschect can chime in more on this.

**Comment by alex3683** [comment] 2019-09-17 06:26
You said
> It's also something that could be implemented by the consumer.

It would be ok for me to implement this myself using the Fabric components without the need to change their source code. But it would be great if you have any hints on how to inject for example the draggable attribute into the component, or to listen on drag stop events. The updating of the model isn't that hard then.
Perhaps it would be sufficient to give the possibility to enable such attributes on the pickers, because you're absolutely right, this should be a part of the common base component. Just take some time, to think about how to implement this in a perhaps lightweight fashion 🙂

**Comment by aneeshack4** [comment] 2019-09-24 00:18
@alex3683 Apologies for the delayed response we had a lot of issues roll in last week. To be clear, I said in the previous comment we believe this is not something that should be a part of the common base component. As for suggestions for implementing this, I think it would depend a lot on the context of your use case - can you provide more details?

@joschect Have you seen examples of such implementations and have ideas for alex?

**Comment by alex3683** [comment] 2019-09-24 06:28
@aneeshack4 @joschect It's actually exactly the thing from current OWA in Exchange Online (screenshots in my first post): Dragging people from one category of people to another, like the dragging from required to optional and vice versa. Nothing very sophisticated :-)
If I'm correct  (I'm not that firm in regard to drag and drop either), I only need some way to attach the draggable attribute on the single Picker items (correct me if I'm wrong).

**Comment by aneeshack4** [comment] 2019-10-09 00:08
@alex3683 I'm not familiar with the OWA implementation but it sounds like you're on the right track. @joschect might have more to say on this. The fabric implementation not having the drag and drop baked in is by design though so I'm going to close this for now. If you have further questions please feel free to ping us again.

**Comment by alex3683** [comment] 2019-10-15 08:31
@aneeshack4 @joschect  Hm, I hoped to get some advice from you regarding on how to hook into the component to make it draggable 😕

**Closed** 2020-05-16 00:00 UTC
Labels: Component: PeoplePicker, Resolution: By Design, Type: Feature
