### ISSUE TITLE
[Bug]: FluentUI popover does not work in Next@14.2.X, but it does work in next@14.1.X

### ISSUE THREAD

**Issue by Dejvovo** [microsoft/fluentui#32821] opened 2024-09-12 07:52 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/nextjs-bzkxez

### Bug Description

Link to the code that reproduces this issue
https://stackblitz.com/edit/nextjs-bzkxez

To Reproduce
Link to stackblitz with version next 14.2:
https://stackblitz.com/edit/nextjs-bzkxez
Link to stackblitz with version next 14.1:
https://stackblitz.com/edit/nextjs-5igbub

Both projects are completely same. They are clean next.js projects with added fluentui/react-components.

In next version 14.1.X fluentui popover does work in version 14.2.X it doesnt.

Current vs. Expected behavior
Current behavior: Popover does not popoup as expected.

Expected behavior: Popover will popup.

Provide environment information
node: 18.20.3,
npm: 10.2.3

Also tried with newest node version
node: 22.2.0,
yarn: 4.2.2
Which area(s) are affected? (Select all that apply)
Not sure

Which stage(s) are affected? (Select all that apply)
Other (Deployed)

Additional context
Tried with yarn, pnpm, npm different versions. The only difference seems to be next version.
What I dont understand is that next app with fluentui must be used with dozens of people, yet i havent found any issue on this topic.

This is my first public issue, if I did something wrong Im ready for feedback.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ewylie25** [comment] 2024-09-12 14:41
I've noticed similar behavior and was just researching similar issues to decided where to report it... We're seeing the following:

- linux containerized envs work for both production builds and nextjs dev mode
- windows envs do not render the popover in nextjs dev node 

When the popover does not render it appears that the fluent provider which contains the react portal is just missing from the DOM. The popover state indicates the popover is open so it's something about the react portals and surfaces not the event handlers. 

Next 14.2 looks like it contains changes to the swc core packages which are OS dependent so I was thinking it had something to do with linux versus windows swc packages but sounds like you're seeing similar behavior on a linux OS so not sure.

I was planning to report this over here since I'd suspect it's more to do with this plugin than fluent itself - https://github.com/sopranopillow/fluentui-nextjs-appdir-plugin

**Comment by LYXOfficial** [comment] 2024-09-13 03:05
I found the same bug, in Windows 10, Next.js 14.2 dev could not pop up the dialog window properly, when I downgraded to 14.1.0, the problem was solved, which delayed me for two days to debug.

**Comment by layershifter** [comment] 2024-09-23 08:35
Duplicate of #31930, see https://github.com/microsoft/fluentui/issues/31930#issuecomment-2231549193.

**Closed by layershifter** 2024-09-23 08:35 UTC
Labels: Component: Popover, Fluent UI react-components (v9)
