### ISSUE TITLE
Grouped Details List not observing changes to groups and items

### ISSUE THREAD

**Issue by dps88** [microsoft/fluentui#15312] opened 2020-09-30 01:19 UTC
### Environment Information

- **Package version(s)**: (7.143.0)
- **Browser and OS versions**: (n/a)

### Please provide a reproduction of the bug in a codepen:
[Codepen](https://codepen.io/duschroe/pen/XWdyPZE)

#### Actual behavior:

Grouped Details List is not observing changes to groups or items.  Demo simplified to switching between different sets of groups and items.  Switching to a non-grouped list between swapping group sets is 'working', but that's obviously not ideal.

Non-Grouped & Changing Items
![image](https://user-images.githubusercontent.com/50461997/94632369-27fe2000-027f-11eb-9dcb-db596115b5bf.png)

Grouped and Changing Groups
![image](https://user-images.githubusercontent.com/50461997/94632518-a8bd1c00-027f-11eb-8418-d87e73106aa0.png)

Grouped and Changing Items
![image](https://user-images.githubusercontent.com/50461997/94632616-ef127b00-027f-11eb-8839-042e187c0851.png)

#### Expected behavior:

Different groups should update the GroupedList with the new set of groups.  Updating the items in the same group set, should update the nested items.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking)

**Comment by paulgildea** [comment] 2020-09-30 16:11
@dps88 Thanks for the issue. 

This might be by design, diffing a complex data structure can be perf sensitive, so @dzearing is this something the `GroupList` does automagically? or is this something the author needs to help with.

**Comment by BreakfastMaintenance** [comment] 2020-09-30 16:47
I've noticed this too, I think it's down to the new `getDerivedStateFromProps()` method in `GroupedList.base.tsx` ([PR #14980](https://github.com/microsoft/fluentui/pull/14980)).

It destructures `groups` from `nextProps`, but then does a comparison `groups` with `nextProps.groups`, which as far as I can see will always match, hence a change to groups on the `GroupedList` doesn't trigger a re-render:

``` typescript
    const { groups, selectionMode, compact } = nextProps;
    let shouldForceUpdates = false;

    ...

    if (nextProps.groups !== groups) {
      nextState = {
        ...nextState,
        groups: nextProps.groups,
      };
    }
```

Is this a bug, or have I misunderstood the way it's meant to work? I can't even use the `version` object to force an update, since this only resets the `version` object itself in state and the `groups` collection remains as is:

``` typescript
    nextState = {
      ...previousState,
      listProps: nextProps.listProps,
    };

    ...

    if (shouldForceUpdates) {
      nextState = {
        ...nextState,
        version: {},
      };
    }
```

If my groups haven't loaded on the first render, this means my grouped list never actually renders anything.

**Comment by dps88** [comment] 2020-09-30 16:56
I doubt it is by design.  The Grouped Details List was working as described as of 7.137.3, so this change has happened quite recently.  I suspect it was introduced with #14980

**Comment by dps88** [comment] 2020-09-30 17:00
> I've noticed this too, I think it's down to the new `getDerivedStateFromProps()` method in `GroupedList.base.tsx` ([PR #14980](https://github.com/microsoft/fluentui/pull/14980)).
> 
> It destructures `groups` from `nextProps`, but then compares `groups` with `nextProps.groups` to see if the groups have changed, which as far as I can see will always match, hence a change to groups on the `GroupedList` doesn't trigger a re-render:
> 
> ```ts
>     const { groups, selectionMode, compact } = nextProps;
>     let shouldForceUpdates = false;
> 
>     ...
> 
>     if (nextProps.groups !== groups) {
>       nextState = {
>         ...nextState,
>         groups: nextProps.groups,
>       };
>     }
> ```
> 
> Is this a bug, or have I misunderstood the way it's meant to work? I can't even use the `version` object to force an update, since this only resets the `version` object itself in state and the `groups` collection remains as is:
> 
> ```ts
>     nextState = {
>       ...previousState,
>       listProps: nextProps.listProps,
>     };
> 
>     ...
> 
>     if (shouldForceUpdates) {
>       nextState = {
>         ...nextState,
>         version: {},
>       };
>     }
> ```
> 
> If my groups haven't loaded on the first render, this means my grouped list never actually renders anything.

**Comment by dzearing** [comment] 2020-09-30 20:40
It is definitely not by design. Thanks for reporting @dps88 . There were recent changes which busted this.

Should be addressed here: https://github.com/microsoft/fluentui/pull/15321

+ unit tests.

**Comment by BerserkerDotNet** [comment] 2020-09-30 23:35
@dzearing, I'm having a similar issue with nested groups. When expending a nested group (2nd level) it does not update the list. Resulting in the group not being expanded. When I do any action that triggers props change it re-renders and shows the group correctly (expanded). Will this be fixed by your PR?

**Comment by BreakfastMaintenance** [comment] 2020-10-01 12:50
Just checked with version 7.144.1 and it's working again for me now. Also the issue which @BerserkerDotNet mentioned appears to be fixed too :) thanks for hopping on this so quickly!

**Closed** 2020-10-01 16:16 UTC
Labels: Component: GroupedList, Fluent UI react, Needs: Investigation

**Comment by BerserkerDotNet** [comment] 2020-10-01 17:36
I can confirm that the issue with multi-level expand is fixed :) Thank you!

**Comment by xieofxie** [comment] 2020-10-11 13:38
Hi @dzearing in the codepen above, 'Grouped and Changing Items' is not working. Is there something wrong? Thanks~
