### ISSUE TITLE
[Bug]: Drawer and Dialog have some compatibility problem with SharePoint Online

### ISSUE THREAD

**Issue by jcoolsen** [microsoft/fluentui#32253] opened 2024-08-07 14:24 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 10.79 GB / 31.73 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://github.com/jcoolsen/SampleForStylingIssue

## Actual Behavior
When using the Drawer or Dialog components in a SharePoint Online context, like a web part in a site or in the workbench, they are missing their base styling variable definitions. This appears to be because they refer to the wrong fui-FluentProvider# class. Often they refer to "fui-FluentProvider1" but should point to a different number in the class attribute. As far as I can see, this is not caused by any change in the Fluent UI components themselves, but rather by some unknown (recent?) change in the SharePoint Online platform that somehow breaks compatibility.
The effect is that the rendering becomes bad, nearly unreadable.

This is what we see:
![image](https://github.com/user-attachments/assets/65a884a7-a4c3-417a-8a76-e610e2de1797)
Underlying HTML from above:
![image](https://github.com/user-attachments/assets/d393e832-b430-49f7-8fff-d55f3e5afa68)

## Expected Behavior
I expect the components to display properly.

This is what we want:
![image](https://github.com/user-attachments/assets/d076ff24-2955-4aeb-b8aa-799c9948dd47)
(the thick black border is caused by the Windows snipping tool)
Underlying HTML from above:
![image](https://github.com/user-attachments/assets/e4675873-ff08-4fe3-a08b-ebc16adc005e)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by emmayjiang** [comment] 2024-08-07 16:35
Unfortunately, this is a bug in SharePoint, often due to mismatch of context versions; there's nothing we can do to resolve this.

**Comment by jcoolsen** [comment] 2024-08-07 17:36
Thank you for responding, @emmayjiang .

What would be your recommendation? Should we avoid using Fluent UI, since I’m sure that our clients will not be satisfied with no resolution.

**Comment by emmayjiang** [comment] 2024-08-07 19:11
Hi @jcoolsen -- sorry we can't help you because this is not a Fluent UI issue. Please consider redirecting your SharePoint inquiries to SharePoint -- [this link](https://github.com/SharePoint/sp-dev-docs?tab=readme-ov-file#questions--help) may be a good place to start!

**Comment by jcoolsen** [comment] 2024-08-09 12:30
As you can see above, I have reported the issue at sp-dev-docs as suggested, but it has received zero attention so far.
Again, considering how this affects our clients, I asked our IT-support to create a ticket with Microsoft to get some traction on the issue. Some emails and screen sharing later, the Microsoft 365 support engineer unfortunately was not able to help with the issue, but did provide some input on what I could do.

Please see below message, and note the highlighted statement that the Fluent UI team should contact Microsoft:

> Having understood the issue from your demonstration, I had to promptly manage your expectations by clarifying that this falls beyond my support capabilities, as my team lacks the expertise in this area, and escalation is not an option. For your reference, I’ve attached the relevant documentation [Support limitations for issues with Microsoft 365 Apps - Microsoft 365 | Microsoft Learn](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoft-365%2Ftroubleshoot%2Fmiscellaneous%2Fissue-support-limitations&data=05%7C02%7Cjco%40zensai.com%7C3fddc137a02348d9c84808dcb86abc21%7C15b0dcd229de4d8789c05e2e6a8ff7d6%7C0%7C0%7C638588015786339411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=i8TJa%2Bc29zt46o8PB45NJTztGJZVhNp6PKNOhVQp17U%3D&reserved=0) that outlines limitations to support framework.
>  
>  
> ![image](https://github.com/user-attachments/assets/02110e8e-ead5-40c8-b871-c5bf6b530634)
> 
>  
> **To address your concerns, I suggested that the Fluent UI 9 team should contact Microsoft directly via the provided channels, to report the bug for potential resolution and ensuring the tool's compatibility.**
>  
> Additionally, I provided a support link where you can connect with Microsoft partners [https://www.microsoft.com/en-us/solution-providers/home](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fsolution-providers%2Fhome&data=05%7C02%7Cjco%40zensai.com%7C3fddc137a02348d9c84808dcb86abc21%7C15b0dcd229de4d8789c05e2e6a8ff7d6%7C0%7C0%7C638588015786344595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=KZ1LfHiQbH%2FZMTc0RMImE4EbT%2BbMAbxmnMseKUvAJ8k%3D&reserved=0) who are equipped to handle developer issues such as this.

The more I think about it, the harder it is for me to understand why I should spend so much time on troubleshooting Microsoft components and when someone are going to take responsibility for their products.

**Comment by emmayjiang** [comment] 2024-08-12 05:53
Again, this is a compatibility issue, not a Fluent issue.

Your issue is caused by the `@fluentui/react-component` version differing from the one SharePoint is currently using, as they are currently using 9.51.0 and will upgrade to 9.54.4 in two weeks, while you are using 9.54.4.
 
SharePoint provided [this workaround](https://github.com/microsoft/fluentui/pull/26496): add idPrefixProvider outside the FluentProvider, so it will not conflict with SharePoint's FluentProvider name.

**Comment by jcoolsen** [comment] 2024-08-12 06:35
Thank you for your insights, @emmayjiang . Much appreciated.

In fact, in our real project (not the reproduction) we currently use version 9.53.0. As I understand you, if we were using the same version as SharePoint always (which would be somewhat tricky to coordinate), the problem would not manifest. But on top of this there must have been a recent change in SharePoint which means that those two package references cannot co-exist peacefully? Since this must be a pretty common scenario, I'm just frustrated that I cannot get the SharePoint team to do something about that.

You suggestion for a workaround is super helpful and we will start implementing this immediately. Thanks a bunch.

**Comment by bsunderhus** [comment] 2024-08-12 08:54
I believe the problem is not related of using the exact same version as SharePoint does always @jcoolsen, it's rather to avoid the possibility of having multiple versions of the same package in your dependencies.

I suggest using some auditing tool in your CI pipelines to ensure no dependency (at least no FluentUI one) is duplicated, we have a lot of internal logic that requires conversation between multiple packages and if by any chance there's versioning conflicts, this conversation might be compromised.

Another possible solution is forcing [resolutions](https://yarnpkg.com/configuration/manifest#resolutions) (if you're using a package manager that allows that)


### TLDR;

It doesn't necessarily matter if you're using `9.51.0`, `9.54.4` nor `9.53.0` what matters is ensuring there's only **ONE** of those versions running in your application

**Comment by jcoolsen** [comment] 2024-08-12 17:25
Thanks for the input, @bsunderhus . I can share that it was working nicely without problems for months when something (in SharePoint) changed. Whether a conflict could occur if one SP component uses one version while another uses a different version in the same SP page, I cannot say. I can say for sure that in my web part and it's dependencies, there is just one reference to @fluentui/react-components.

**Comment by bsunderhus** [comment] 2024-11-18 15:43
I'll be closing this as resolved externally! let me know if we need to open it again @jcoolsen , @emmayjiang

**Closed by bsunderhus** 2024-11-18 15:43 UTC
Labels: Component: Dialog, Resolution: External, Fluent UI react-components (v9)

**Comment by bobixaboxa** [comment] 2025-04-30 09:55
@emmayjiang how do you know what Fluent UI version is being used in SharePoint Online currently?
