### ISSUE TITLE
Checkbox label doesn't show when printing in IE 11

### ISSUE THREAD

**Issue by cph11** [microsoft/fluentui#10756] opened 2019-10-09 09:04 UTC
### Environment Information

- **Package version(s)**: 
"office-ui-fabric-core": "9.6.1-fluent2"
"office-ui-fabric-react": "6.189.2"
- **Browser and OS versions**: IE 11  Windows 10

### Please provide a reproduction of the bug in a codepen:
Unable to reproduce in codepen as IE not supported.

Issue can be replicated by printing the documentation page in IE 11.

https://developer.microsoft.com/en-us/fabric#/controls/web/checkbox

Example Print to PDF: [cb.pdf](https://github.com/OfficeDev/office-ui-fabric-react/files/3706300/cb.pdf)

Issue only affects checkboxes after the first page.

#### Actual behavior:

Label associated with checkbox is not printed, unless on the first page.

#### Expected behavior:

The whole label associated with the checkbox should be visible regardless of page.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment] 2019-10-09 23:40
Interesting... Does this happen in your site/app as well, or just on the website? I can also repro the issue on the website, but not in a codepen (if you sign in and save a pen, codepen offers a "debug view" option which works in IE 11).

Codepen debug view: https://cdpn.io/ecraig12345/debug/YzzXbVJ/LQkExyVvxmqA
(if this expires, fork the original codepen https://codepen.io/ecraig12345/pen/YzzXbVJ?editors=0010 and generate a debug view link from that)

**Comment by ecraig12345** [comment] 2019-10-11 00:11
I tried updating the codepen to push the checkbox down onto a subsequent page using a really tall div, but the label still printed. 

I also tried disabling this CSS reset style on the website, and I'm pretty sure that made the labels print properly once, but I haven't been able to reproduce it since then. (Adding the same style in the codepen had no effect, even if I set `box-sizing` on the parent div.)
```
*, *:before, *:after {
  box-sizing: inherit;
}
```

**Comment by cph11** [comment] 2019-10-16 08:40
I've now managed to replicate the issue in codepen

Codepen debug view:  https://cdpn.io/cph11/debug/NWWGPYE/vPMKKedYNqxM
Codepen original:   https://codepen.io/cph11/pen/NWWGPYE?editors=0010

The issue occurs when the Nav component is also used.  If the Nav
component is commented out the checkboxes render correctly.

**Comment by ecraig12345** [comment] 2019-10-16 23:58
I tried the codepen but the labels still print fine for me in that case, at least when printing to PDF (which is what I've used for all the other testing). In case it makes a difference, when you repro'd the issue with that codepen, was it with print to PDF or a real printer? And did you use "Microsoft Print to PDF" or something else?

**Comment by cph11** [comment] 2019-10-17 07:13
I tested used the Print Preview feature.  But using "Microsoft Print to
PDF" gives the same result (on page 2).

**Comment by cph11** [comment] 2019-10-24 16:31
I'd sent a copy of the PDF produced by the "Microsoft Print to PDF" with my last comment, but I can't see it attached anywhere, so I'm including it here.  

[codepen.pdf](https://github.com/OfficeDev/office-ui-fabric-react/files/3768580/codepen.pdf)

**Comment by ecraig12345** [comment] 2021-12-08 03:01
Closing due to this being an extremely obscure issue and IE 11 nearing extended end of support (so this is not something we'd fix at this point)

**Closed by ecraig12345** 2021-12-08 03:01 UTC
Labels: Type: Bug :bug:, Component: Checkbox, Priority 3: Low, Status: Not on Roadmap
