### ISSUE TITLE
Remove MWF styles from website

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#10911] opened 2019-10-18 18:18 UTC
UPDATE: There's now an option (in internal developer.microsoft.com bootstrap code) to remove MWF styles from the website. Pending a quick look over the site to ensure nothing breaks, we're going to enable this option to fix some current issues caused by MWF and prevent future breaks.

-----

*original text:*

This is a meta issue to track other issues indicating ~~UHF~~ MWF styles in our website messing with our component styling. The first path of action is to try to mitigate things, just like before, but for things that we can't do much about this will serve as a place to put and reference them until we can move to our own site.

- #8359 (fixed, possibly regressed since then) - Buttons in high contrast mode do not render as expected
- #10778 - Button A11y: text is not visible in High Contrast Black Mode while navigating using Tab key

**Comment by khmakoto** [comment] 2019-10-18 18:19
FYI @Jahnp @kenotron @micahgodbolt

**Comment by smhigley** [comment] 2021-03-02 08:10
The most obvious visual regression is with the footer:
![unstyled follow and share text with icons](https://user-images.githubusercontent.com/3819570/109617681-8871e180-7aeb-11eb-9a2e-456246e66378.png)

Is that something we could separately add styles for ourselves? @TristanWatanabe is helping go through the rest of the pages to look for any other visual regressions.

**Comment by ecraig12345** [comment] 2021-03-02 17:41
@smhigley Hmm that’s not good... Can you tell whether that’s caused by any of our CSS normalization, or just by the absence of MWF? If needed we can talk to the owning team internally and get them to fix it.

**Comment by smhigley** [comment] 2021-03-02 17:42
@ecraig12345 it's just caused by the absence of MWF. If we have an option to add our own styles for it, that would be great :)

**Comment by ecraig12345** [comment] 2021-03-02 20:53
@smhigley We can add overrides in apps/public-docsite/src/styles/_base.scss if needed, but I think we should also get in contact with the owning team for the footer and let them know it's broken without MWF.

**Comment by ecraig12345** [comment] 2021-03-02 21:37
Proposed fix is to just hide the footer: add `#socialMediaContainer` to the list of selectors on this style.
https://github.com/microsoft/fluentui/blob/2bea597b1bbfdc20f4ca070342a7f076d40a90c0/apps/public-docsite/src/styles/_base.scss#L95-L100

**Comment by TristanWatanabe** [comment] 2021-03-02 22:06
These are some other visual changes I've noticed when the MWF stylesheet is removed:

**1) Sign in modal is visible at the bottom of every page:** 
![modal](https://user-images.githubusercontent.com/8649804/109720083-78471a00-7b5e-11eb-807e-79aa27ddd311.JPG)

**2) Links are underlined in all pages under Get Started, Styles and Resources tabs and also in the individual components docs under the Controls tab:** 
![link-underlines-in-get-started-styles-and-resources-pages](https://user-images.githubusercontent.com/8649804/109720576-218e1000-7b5f-11eb-986d-861f27279211.JPG)

![link-underlines-in-controls-pages](https://user-images.githubusercontent.com/8649804/109720601-29e64b00-7b5f-11eb-845c-63ba60509756.JPG)

**3) Hyperlinks do not change color after link has been visited:**
![link-text-color-does-not-change-after-being-visited](https://user-images.githubusercontent.com/8649804/109720944-98c3a400-7b5f-11eb-94cb-b2f4d60cdf7d.JPG)
![hyperlinks](https://user-images.githubusercontent.com/8649804/109721400-2606f880-7b60-11eb-96ca-b372c9fb1aab.JPG)

**Comment by ecraig12345** [comment] 2021-03-02 22:16
Both hyperlink changes are correct, and some of the reasons we wanted to get rid of MWF (I should have mentioned this, sorry). 

Does the sign-in modal have an ID we can use to hide it?

**Comment by TristanWatanabe** [comment] 2021-03-02 22:28
There is a signInPrompt id that we can use

![image](https://user-images.githubusercontent.com/8649804/109723779-69169b00-7b63-11eb-92b9-045ada8a7b9a.png)

**Comment by smhigley** [comment] 2021-03-02 23:25
Maybe something like this?
```
#signInPrompt[aria-hidden=true] {
  display: none;
}
```

I dunno if our styles would ever be present on a page where the sign-in prompt is needed, so maybe the `[aria-hidden=true]` selector isn't needed

**Comment by ecraig12345** [comment] 2021-03-02 23:31
These styles are just for our website, and sign-in isn't really relevant there. So I think it's okay to just always hide `#signInPrompt`.

**Comment by ecraig12345** [comment] 2021-03-11 18:51
All the PRs to this repo and the internal one have been merged, so MWF is finally gone! :tada:

**Closed by ecraig12345** 2021-03-11 18:51 UTC
Labels: Area: Website, Status: Fixed, Type: Feature
