### ISSUE TITLE
Contextual menu item position is not read out by Narator

### ISSUE THREAD

**Issue by srinivasNithin** [microsoft/fluentui#16455] opened 2021-01-13 04:56 UTC
This works on Edge Chromium with Narrator - reading out all the headers in the menu properly. 
![image](https://user-images.githubusercontent.com/4161791/82231719-2d238980-98f3-11ea-8cf7-efad477b971a.png)
Unless you see a gap in the control's accessibility hookups wrt it following the ARIA spec, I don't see how this is actionable to us. This is likely a Chrome specific issue on that browser's end.

_Originally posted by @aneeshack4 in https://github.com/microsoft/fluentui/issues/13202#issuecomment-630264173_

**Comment by srinivasNithin** [comment] 2021-01-13 04:58
Even you comment the menu item is read out but position of menuitem is not read out.

**Comment by srinivasNithin** [comment] 2021-01-18 12:18
Any update on it?

**Comment by srinivasNithin** [comment] 2021-01-19 04:12
Environment:

Windows Version: Windows10
Chrome Version Version 87.0.4280.141 (Official Build) (64-bit)

Reproduction steps:

Open Url https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu
Go to ContextualMenu with section headers
Export to codepen
Open Narrator or NVDA
User Experience:
Screen reader user won’t get proper information about Menu Items like which menu items are related to which sections

Fluent UI: 7.152.0

Actual:
Narrator doesn’t announce menu items positioning

Expected:
Narrator should announce the Position for particular section like 1/3 2/3 and 3/3 etc...and not as whole if multiple sections are there in the menu

Please let me know if you need any additional details

**Comment by layershifter** [comment] 2021-01-19 14:10
@srinivasNithin thanks for providing all details, it looks like a duplicate of https://github.com/microsoft/fluentui/issues/12594. Let me know if I am wrong.

**Closed by layershifter** 2021-01-19 14:10 UTC
Labels: Needs: Attention :wave:

**Comment by srinivasNithin** [comment] 2021-01-19 14:44
yes it is same. Thanks,
