### ISSUE TITLE
DetailsList: Narrator is reading blank column separator in new Edge

### ISSUE THREAD

**Issue by zhr1130** [microsoft/fluentui#13239] opened 2020-05-20 06:56 UTC
### Environment Information

- **Package version(s)**: 7.104.0
- **Browser and OS versions**:
OS Version: 2004 (OS Build: 19588.1000)
Browser: Edge chromium(Version 83.0.461.1 (Official build) dev (64-bit))
### Describe the issue:

While navigating in scan mode of narrator it announce on every header column separation as Blank.

### Please provide a reproduction of the issue in a codepen:
I can repro it on the official example : https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

Repro steps:
1. Focus on the search input box and start narrator.
2. Use tab to switch to list header and turn on scan mode.
3. Use down arrow to scan on header. 

#### Actual behavior:

Narrator reads all column separation as "Blank" in new edge. 

#### Expected behavior:

Shouldn't read separation. 

### Documentation describing expected behavior

MAS 1.3.1 - Info and Relationships

**Comment by aneeshack4** [comment] 2020-05-20 15:35
Hi @zhr1130, thanks for reaching out to us. I believe this is actually a dupe and already reported... I confirmed repro again just in case and I'm not able to repro:
![image](https://user-images.githubusercontent.com/4161791/82465903-64c23b00-9a85-11ea-8d71-c0b21691b1f6.png)
Also scan mode in Narrator is unpredictable and quite buggy and it's a known problem - we're waiting on the Narrator team to fix it and can't do much about Scan Mode gaps on our end.

**Comment by zhr1130** [comment] 2020-05-20 22:40
Thanks @aneeshack4 , I can repro it and here is a codepen that has more columns and easier to repro the issue. I understand scan mode is such a pain, however this bug was reported by accessibility testing team and it's already out of SLA :( 
Codepen: https://codepen.io/zhr1130/pen/yLYGWmB?editors=1010
![repro](https://user-images.githubusercontent.com/18317674/82504408-2d1cb880-9ab0-11ea-815f-8719ed614162.png)
![repro 1](https://user-images.githubusercontent.com/18317674/82504424-36a62080-9ab0-11ea-8e6b-ad9530edbd3e.png)

**Comment by zhr1130** [comment] 2021-02-05 18:54
Hello, 

Is there any update on this bug ?

**Comment by cschlechty** [comment] 2021-02-05 20:22
I am not seeing this behavior anymore with narrator and edge. It's likely been fixed with recent Windows versions.

**Closed** 2021-02-05 22:43 UTC
Labels: Area: Accessibility, Area: Narrator, Component: DetailsList, Type: Bug :bug:
