### ISSUE TITLE
[Bug]: In Safari Dropdown doesn't support keyboard "Up", "Down" and "Enter"

### ISSUE THREAD

**Issue by SiriratS** [microsoft/fluentui#31342] opened 2024-05-13 06:32 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.2.1
  Browsers:
    Safari: 16.3
  npmPackages:
    @fluentui/react-components: ^9.47.1
    @fluentui/react-icons: ^2.0.232
    react: ^18.2.0
    react-dom: ^18.2.0
    react-router-dom: ^6.22.3
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-dropdown--default

## Actual Behavior
When opening the dropdown can't use the keyboard "Up/Down" to select an item and "Enter" to select/deselect

## Expected Behavior
support keyboard "Up/Down" to select an item and "Enter" to select/deselect

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by marcosmoura** [comment] 2024-05-19 23:16
@SiriratS We cannot reproduce this issue on Safari 16 or 17. Could you please provide a recording or something that can show the steps to reproduce this issue?

**Comment by layershifter** [comment] 2024-08-13 08:20
Closing as the issue does not have a repro case.

**Closed by layershifter** 2024-08-13 08:20 UTC
Labels: Component: Dropdown, Resolution: Can't Repro, Fluent UI react-components (v9), Needs: Repro
