### ISSUE TITLE
[Bug]: Dropdown callout renders to the right when list content exceeds vertical space

### ISSUE THREAD

**Issue by nipope** [microsoft/fluentui#28954] opened 2023-08-22 19:24 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 16.38 GB / 31.59 GB
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/nipope1/pen/PoXqPbQ

## Actual Behavior
Callout renders to the right of dropdown when list content exceeds vertical space. When the width of the dropdown is equal to the width of the screen, the callout takes up the entire screen when opened (2nd example in attached Codepen).

## Expected Behavior
Callout should render below or (if necessary) above dropdown with a scrollbar if content exceeds vertical space

### Requested priority

Blocking

### Products/sites affected

Azure Deployment Environments (Azure Portal extension)

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment] 2023-08-25 21:12
I see it happening:
![image](https://github.com/microsoft/fluentui/assets/5953191/a3834a9e-f4ed-4f03-962c-77dec6e9a262)

It does seem like this was by design https://github.com/microsoft/fluentui/issues/9508. The sizing should stay as is, otherwise there's no way to close it according to the issue linked.

**Comment by nipope** [comment] 2023-08-28 20:13
@sopranopillow The screenshot you provided appears to be the small-width screen / mobile view, where the dropdown options render in a panel instead of a callout. The issue I am seeing is in the full screen view. Here are screenshots of the two scenarios in my codepen:

Fixed width dropdown: 
![image](https://github.com/microsoft/fluentui/assets/87452624/6f88d2c7-138a-494f-9f1b-2c3157995f79)

Full screen width dropdown: 
![image](https://github.com/microsoft/fluentui/assets/87452624/0c2de861-3ed8-47a4-aabf-09549ada3361)

As you can see in the screenshots, the callout renders to the right of the dropdown for the fixed-width dropdown, and covers the entire screen when the dropdown is the full width of the page. I think this behavior has changed somewhat recently (in the last 6 months or so), although I don't recall exactly when.

Also, to clarify, we are not requesting a change in sizing of the callout, just a change in positioning (should be either below or above the dropdown, not to the right / overtop of the dropdown).

**Comment by spmonahan** [comment] 2023-08-30 23:38
@nipope You can use `directionalHintFixed` to force the behavior: https://codepen.io/seanms/pen/GRPZeyo

> I think this behavior has changed somewhat recently (in the last 6 months or so), although I don't recall exactly when.

I looked through the history for `Callout` and `positioning` and t[his looks like it might have changed the behavior](https://github.com/microsoft/fluentui/pull/27558) but when I reverted the Codepen to the version just before this change I observed the same behavior.

I've also rolled back to a version from January 2023 and the behavior does not seem to have changed: https://codepen.io/seanms/pen/abPNMqP?editors=1011

Do you by chance have a previous version I could look into to confirm that the rendering behavior has changed?

**Comment by nipope** [comment] 2023-08-31 17:23
@spmonahan Do you know if there is a way to set directionalHintFixed to either above or below the dropdown? We were hoping to take advantage of the previous behavior where, when the space between the dropdown and the bottom of the page was too small, the callout would instead render above the dropdown, but would never render to the right. 

I unfortunately didn't catch this issue for a little while, so I don't know exactly when the behavior changed - it must have been longer than I thought if the version from January still has this behavior. It's possible that it changed when we upgraded from Fluent V7 to Fluent V8?

**Comment by spmonahan** [comment] 2023-08-31 17:43
> Do you know if there is a way to set directionalHintFixed to either above or below the dropdown?

I don't think so. `directionalHintFixed` just forces the positioning algorithm to treat `directionalHint` as "law" rather than a hint for where to start.

> It's possible that it changed when we upgraded from Fluent V7 to Fluent V8?

That's certainly possible. If that's the case then this would be a behavioral difference between major version and be how Fluent v8 works 🙂 Using git blame it doesn't look like the positioning code has had any significant work in some time, though I didn't thoroughly look into it so a v7 --> 8 difference may be the root.

If the behavior you described is something you want we can chat about how the implementation will look and are happy to accept a PR.

**Comment by nipope** [comment] 2023-08-31 18:23
@spmonahan I'm willing to submit a PR to get this behavior! I will ping you to chat about implementation.

**Comment by sopranopillow** [comment] 2023-09-25 16:48
Hi @nipope, I see you have a draft PR, is the PR ready to review?

**Comment by nipope** [comment] 2023-09-27 19:36
Opened a related issue: https://github.com/microsoft/fluentui/issues/29319

**Comment by spmonahan** [comment] 2023-09-28 17:13
Thanks @nipope ! My 2c is that we should address #29319 first as it seems like a bug in the current implementation while your initial PR is adding a new feature.

**Comment by nipope** [comment] 2023-09-28 22:06
@spmonahan That sounds good to me!

**Comment by 15MariamS** [comment] 2023-09-29 17:04
Is there a way to always fix the position to `below` in fluent v9? I'm having a similar problem there where I'm using `<Dropdown />` and I've set `positioning="below"` but on small screens the dropdown shows to the top of the button rather than below it.

**Comment by spmonahan** [comment] 2023-09-29 17:16
> Is there a way to always fix the position to `below` in fluent v9? I'm having a similar problem there where I'm using `<Dropdown />` and I've set `positioning="below"`, but on vertically small screens the dropdown shows to the top of the button rather than below it.

I think you want the `pinned` prop. Sorry, I cannot link directly to the prop but it's on this page: https://react.fluentui.dev/?path=/docs/concepts-developer-positioning-components--default

Here's an example: https://codesandbox.io/s/pinned-dropdown-4cvhyf?file=/example.tsx

**Closed** 2023-12-11 22:57 UTC
Labels: Status: In PR, Fluent UI react (v8)
