### ISSUE TITLE
ScrollablePane doesn't show every record

### ISSUE THREAD

**Issue by arnoldnemedi** [microsoft/fluentui#22141] opened 2022-03-17 14:22 UTC
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

Go to [https://developer.microsoft.com/en-us/fluentui#/controls/web/scrollablepane](url) and scroll down to DetailsList Fixed Header without ScrollablePane.
Click in the list and start scrolling. After 70-80 records no records are displayed, however there should be a lot.

#### Expected behavior:

Evey records is displayed when scrolling.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Blocking

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment] 2022-04-11 19:30
duplicate of #22447

**Closed by micahgodbolt** 2022-04-11 19:30 UTC
Labels: Needs: Triage :mag:
