### ISSUE TITLE
[Bug]: Portal does not propagate fluent styling (tokens)

### ISSUE THREAD

**Issue by rocketBANG** [microsoft/fluentui#32319] opened 2024-08-16 00:28 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 24.92 GB / 63.95 GB
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/6jsxth?file=index.html

## Actual Behavior
Using a `<Portal>` and then rendering some fluent component (e.g. `<Select>`) inside it does not propagate the tokens needed for styling the fluent component correctly. It only works if the mountNode is already located under a `<FluentProvider>` (which removes the need for a portal in the first place)

![image](https://github.com/user-attachments/assets/f87742db-48c1-466a-91f5-19ca80de1a01)

## Expected Behavior
`<Portal>` would propagate the styles needed for fluent components and correctly render them under the given DOM node

![image](https://github.com/user-attachments/assets/343c0997-3830-4f32-9e14-4456d7ec7961)

From the [docs](https://react.fluentui.dev/?path=/docs/components-portal-portal--docs)
> Portal component is a thin wrapper around React's [ReactDOM.createPortal()](https://reactjs.org/docs/portals.html) that propagates Fluent styling (allows to use tokens) and text-direction handling to the content. You can identify DOM created by Portal by looking for the data-portal-node attribute.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment] 2024-08-16 09:19
@rocketBANG it's not propagating when custom `mountNode` is used and it's intentional: we don't know how the node is created and naive assignment of classes could break something.

- Without `mountNode` - https://stackblitz.com/edit/6jsxth-qjz69j?file=src%2Fexample.tsx
- You can do a custom effect using and assign `className` from `useThemeClassName()`:
   ```ts
  React.useLayoutEffect(() => {
    if (mountNode) {
      mountNode.className = className;

      return () => {
        mountNode.className = '';
      };
    }
  }, [className, mountNode]);
   ```
   https://stackblitz.com/edit/6jsxth-ahzhfj?file=src%2Fexample.tsx

---

Closing as it's by design.

**Closed by layershifter** 2024-08-16 09:19 UTC
Labels: Needs: Triage :mag:, Fluent UI react-components (v9)
