### ISSUE TITLE
Invalid ARIA attribute value(aria-activedescendant="ComboBox61-listundefined") is defined for CSEO coherence combo box.

### ISSUE THREAD

**Issue by naraffou** [microsoft/fluentui#12963] opened 2020-05-01 15:57 UTC
### Environment Information

- **Package version(s)**: latest version
- **Browser and OS versions**: latest chrome and windows 10

### Describe the issue:

We are using your combobox and getting this error in our accessibility reports:

**Invalid ARIA attribute value(aria-activedescendant="ComboBox61-listundefined") is defined for  combo box.**

There needs to be an active descendant aria attribute for the default option on the combobox, when nothing is selected.

![image](https://user-images.githubusercontent.com/47798670/80819295-8ff1f280-8b89-11ea-9095-280a80021a7d.png)

Please fix this or give us a means of doing so.

#### Actual behavior:

Getting an aria a11y flag

#### Expected behavior:

Not getting an a11y flag

### Documentation describing expected behavior

please review the screenshot, error message and description, we're just using your basic combobox

**Comment by joschect** [comment] 2020-05-01 16:28
@naraffou thanks for the submission! Can you confirm which version of Fabric you're using? This was a known issue that was fixed in https://github.com/microsoft/fluentui/issues/12556 and released in 7.106.0. Additionally, I am not able to reproduce this on our site using the basic combobox.

**Comment by naraffou** [comment] 2020-05-01 16:31
I am using
    "office-ui-fabric-react": "^7.102.0",
I will update it and retry, thank you.

**Closed** 2020-05-11 20:00 UTC
Labels: Component: ComboBox, Needs: Author Feedback, Status: No Recent Activity
