### ISSUE TITLE
Tooltip is not defined for close button in search field

### ISSUE THREAD

**Issue by yueou1995** [microsoft/fluentui#15602] opened 2020-10-20 00:19 UTC
### Environment Information

Windows Version - Win10
Chromium Edge - Version 85.0.564.51 (Official build) (64-bit)

### Describe the issue:

Tooltip is not defined for close button in search field

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/yueou/pen/XWKKvbx?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

#### Actual behavior:

Tooltip is not defined for close button in search field

#### Expected behavior:

Tooltip should be defined for close button in search field

### Documentation describing expected behavior

MAS1.3.3

https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={1823da5a-e8fb-4e63-b881-7eccb312c358}

**Comment by paulgildea** [comment] 2020-10-21 15:46
@yueou1995 Thanks for filling this issue.

@JustSlone / @dzearing / @ecraig12345 - It's unclear to me if we provide a `Tooltip` built-in for this instance or if it's up to the app developer to provide a custom icon button wrapped with a `TooltipHost`. If so then this is by design I'm assuming?

**Comment by dzearing** [comment] 2020-10-21 15:47
No we do not, and no we should not. This is not a MAS violation. Paging @smhigley .

**Comment by smhigley** [comment] 2020-10-21 20:07
Yup, not a MAS/WCAG violation, and probably not even a good idea :)

**Comment by JustSlone** [comment] 2020-10-23 05:17
I agree, the MAS/WCAG rule here is misleading. It seems to imply tooltips are needed on all icons, when in-fact they are not and actually can do more harm than good for accessibility. 

Feel free to follow up with me offline if this is a product requirement. 
Closing out this issue (as always feel free to re-open if there is something we're missing).

**Closed by JustSlone** 2020-10-23 05:17 UTC
Labels: Component: SearchBox, Fluent UI react, Needs: Investigation
