### ISSUE TITLE
[Bug]: Accessibility Issue -Split button [Using a negative tabindex on an element inside an interactive control does not prevent assistive technologies from focusing the element (even with 'aria-hidden=true')]

### ISSUE THREAD

**Issue by ChithiraMG** [microsoft/fluentui#26127] opened 2022-12-29 10:46 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 3.55 GB / 15.78 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

Run fastpass in Acceessibility Insights for web (chrome extension) for split button in fluent ui

## Actual Behavior
![image](https://user-images.githubusercontent.com/101738825/209940365-a8da37c9-3136-4182-a28e-d0dc9a8cb1fc.png)
## Expected Behavior
Kindly help to solve the above mentioned fast pass accessibility issue

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment] 2022-12-29 23:42
Dupe of #26042

**Closed by smhigley** 2022-12-29 23:42 UTC
Labels: Needs: Triage :mag:, Fluent UI react (v8)
