### ISSUE TITLE
[Accessibility] Combobox control : Windows Narrator is not reading the changed options in combox using arrow keys.

### ISSUE THREAD

**Issue by v-sagsah** [microsoft/fluentui#12885] opened 2020-04-27 17:46 UTC
**Browser Details:**
**OS:** Windows 10 (Version 10.0.18363 Build 18363)
Microsoft Edge Beta Version 81.0.416.50 (Official build) beta (64-bit)
Screen Reader: Narrator

**Issue:**
Windows Narrator is not reading the changed options in combobox. When changing the options in combobox, using up and down arrows, screen reader is reading only alternative options.

**Repro Steps :**

1. Start Narrator. Hit the URL "https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox".
2. Tab till any combox control under usage section.
3. Now change the options using up and down arrow keys.
4. Verify whether screen reader is reading the changed option or not.

**Below is a snapshot of the issue**
![Screenshot (92)](https://user-images.githubusercontent.com/64409491/80403317-0c13de00-88dd-11ea-9479-6d2e9accb9d3.png)

**Actual Result:**
Screen reader is not reading the changed options in combobox. When changing the options in combobox, using up and down arrows, screen reader is reading only alternative options.

**Expected Result:**
Screen reader should read the changes in the page. It should read the option to end user while changing the options using up and down arrow keys in the combobox.

**Comment by aneeshack4** [comment] 2020-04-28 15:08
Dupe of #12498.

**Closed by aneeshack4** 2020-04-28 15:08 UTC
Labels: Needs: Triage :mag:

**Comment by v-sagsah** [comment] 2020-04-29 05:55
@aneeshack4 Please find the difference between my case #12885 and other case #12498.

**my case #12885**
1. In this case the autocomplete = off.
2. In this case the windows narrator is reading options, but only the the alternate ones.
3. In this case, we are using the up and down arrow keys, to select the items in Combobox 

**Other case #12498.**
1. In this case the autocomplete = on.
2. In this case the windows narrator is not reading any items within the Combobox .
3. In this case, user is typing the preferred letters, and based on the like match, items from the combobox are getting selected.

I am able to repro the same issue, by setting autocomplete  = on as well in the fluent UI site 
https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox

**Below is a snapshot for reference**
![image](https://user-images.githubusercontent.com/64409491/80564311-1f24cc00-8a0b-11ea-8ddf-bde877ea6e33.png)

**User Impact:**
Screen reader users may find it difficult to know the changes occurring in the dropdown when using up and down arrow keys.

_**It seems to be a different accessibility issue, with the same Combobox control**_

**Comment by v-sagsah** [comment] 2020-05-18 16:46
@aneeshack4  could you please provide your comments ?
