### ISSUE TITLE
public-docsite renders v6.164.8 components when "Show Code" is toggled on

### ISSUE THREAD

**Issue by jcmoore** [microsoft/fluentui#15689] opened 2020-10-24 22:53 UTC
### Environment Information

- **Package version(s)**: fabric-website/v7_20201023.1
- **Browser and OS versions**: MS Edge 86.0.622.0.43

### Please provide a reproduction of the bug in a codepen:

Observable at https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield#TextField456 -- the "Controlled TextFields" example.

#### Actual behavior:

When the "Show Code" tab is toggled on to show the monaco editor, after waiting 15 or so seconds for the example to rerender (presumably with an [`<EditorWrapper />`](https://github.com/microsoft/fluentui/blob/820f5a34d43c6a573ffa8a9191f03b73e5d29666/packages/react-docsite-components/src/components/ExampleCard/ExampleCard.tsx#L175-L185)), typing more than 5 characters in the input will result in a value length longer than 5 -- which is not what the example advertises (which seems to be because the `<TextField />` in this scenario is actually coming from https://cdn.graph.office.net/prod/vendor/node_modules/office-ui-fabric-react/dist/v6.164.8/office-ui-fabric-react.min.js -- search for "this._onRenderDescription" to get close)

#### Expected behavior:

When the "Show Code" tab is toggled off to hide the monaco editor, typing more than 5 characters will leave the value length limited to 5 -- as advertised (which seems to be because the the `<TextField />` in this scenario is instead coming from https://fabricweb.azureedge.net/fabric-website/v7_20201023.1/fabric-sitev5-7.15.37-0-1603455506228.min.js -- search for "this._onRenderDescription" to get close)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes -- but would need guidance because I can't sort out how the old version is being tied in...

Requested priority: Normal

Products/sites affected: public-docsite -- https://developer.microsoft.com/en-us/fluentui

**Comment by paulgildea** [comment] 2020-10-26 16:41
@jcmoore Thanks for the find!

@tomi-msft feel free to coordinate with @jcmoore if you can find a straightforward root cause. I'd suggest bringing in @ecraig12345 for insight on the doc site.

**Comment by ecraig12345** [comment] 2020-10-26 20:32
Yikes, good catch and thanks for the great repro information! I don't think our code is what's causing that to be loaded--it looks like it's being written on the page by the server for some reason, so the fix will be in some internal code. I'll contact the team that owns the server code and see about getting this fixed.

**Comment by ecraig12345** [comment] 2020-10-27 02:55
Tracked down the issue and it will probably be fixed sometime tomorrow.

**Comment by ecraig12345** [comment] 2020-10-29 22:05
This is fixed now. Thanks again for noticing @jcmoore!

**Closed by ecraig12345** 2020-10-29 22:05 UTC
Labels: Area: Documentation, Component: TextField, Fluent UI react, Needs: Investigation
