### ISSUE TITLE
[Bug]: SearchBox is not clickable when Modal with isModeless=true is opened

### ISSUE THREAD

**Issue by vkoman** [microsoft/fluentui#23363] opened 2022-06-02 06:48 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
"react": "^17.0.2",
"@fluentui/react": "^8.6.1",
```

### Reproduction

https://codepen.io/vkoman/pen/MWQGLPL

### Bug Description

When using the `Modal` component with `isModeless={true}` option, the `SearchBox` which is placed on the main page is not clickable.
But for example, the simple `TextField` component works properly
here is my demo example attached
https://codepen.io/vkoman/pen/MWQGLPL

## Actual Behavior
Cannot click on the `SearchBox` when modal is opened

## Expected Behavior
It is possible to use the `SearchBox` component when `Modal` with  `isModeless={true}`  is opened

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment] 2022-06-27 09:16
@vkoman  - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@bsunderhus  - Would you be able to confirm if this is a regression, or if this behavior is an issue when using the `SearchBox` component when `Modal` with `isModeless={true}` is opened?

**Comment by layershifter** [comment] 2022-08-12 12:30
This problem was fixed by #22500 for v8, I created a CodeSandbox to verify and it works as expected (https://codesandbox.io/s/busy-wilbur-juxcdr).

The problem is still present in v7 (https://codesandbox.io/s/condescending-mirzakhani-dgtvd2), but as the issue related to v8 I don't a reason (or actually request) to backport them. Closing the issue.

**Closed by layershifter** 2022-08-12 12:30 UTC
Labels: Component: SearchBox, Resolution: Can't Repro, Fluent UI react (v8)
