### ISSUE TITLE
Disabling tab on non interactive lists.

### ISSUE THREAD

**Issue by KishorePatel2005** [microsoft/fluentui#18863] opened 2021-07-08 10:43 UTC
Environment Information
Package version(s): 7.134
Browser and OS versions: Browser- Version 85.0.564.44 (Official build) (64-bit) & OS 19041.450
Describe the issue:
Upon Tabbing through the DetailList component, the Tab passes through the first row in list. This is not needed if the rows are non interactive. As a result the tab resulting in the row selection is redundant, since no action can be performed on it.

Please provide a reproduction of the issue in a codepen:
The mentioned behavior is reproducible in the documentation URL itself: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist . Try to navigate the list by tabbing through. The focus moves to the first row and then leaves the component. Since the row is non interactive, actions such as entering or pressing space will result in nothing.

Actual behavior:
The DetailList allows tab to focus on first row despite the row being non interactive.

Expected behavior:
If the list is non interactive, the focus should not appear on them upon tabbing to the list.

Previous Bug was close due to inactivity.
Bug Link :-  https://github.com/microsoft/fluentui/issues/14953

**Comment by ling1726** [comment] 2021-07-08 17:33
@paulgildea @khmakoto has there been any movement on this issue ? It seems that it's not possible to:
* Configure the focuszones  used in `DetailsList`
* Pass any DOM attributes directly to the row through `items`

@KishorePatel2005 here is a workaround you can do to make each row unfocusable:

```js
import { DetailsRow } from '@fluentui/react';

<DetailsList
  {...otherProps}
  onRenderRow={(props) => <DetailsRow {...props} data-is-focusable={false} />}
/>
```

**Comment by ling1726** [comment] 2021-07-08 17:36
Setting low priority since it can be worked around

**Comment by ecraig12345** [comment] 2021-07-15 18:40
This is also basically a duplicate of #18611.

**Closed** 2022-07-13 13:01 UTC
Labels: Type: Question ❔, Priority 3: Low, Help Wanted ✨, Resolution: Soft Close
