### ISSUE TITLE
[Bug]: DataGrid / Table: Row border does not extend horizontally when rows overflow horizontally

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#27570] opened 2023-04-14 08:43 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
"@fluentui/react-components": "9.18.6"
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluent-ui-v9-datagrid-h13r52?file=/example.tsx

## Actual Behavior
![Recording_20230414T164059](https://user-images.githubusercontent.com/50703224/231992122-d3ee732b-c554-43be-a8c0-e711e5c69ab7.gif)
![image](https://user-images.githubusercontent.com/50703224/231992384-f9fa065d-ea75-4ba1-829c-d44513827745.png)

## Expected Behavior
The row borders should extend horizontally.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment] 2023-04-14 19:45
@chenxinyanc as a temporary fix, are you able to set a `min-width` to the entire table, based on the min-widths you're setting on the cells?

@ling1726 it looks like this is caused by the table having `width: 100%` while providing options for `min-width`/`width` on cells. Adding `min-width: fit-content` to the table looks like it would solve this, and looks like that should be OK on support: https://caniuse.com/mdn-css_properties_width_fit-content

Do you have any concerns with that approach?

**Comment by ling1726** [comment] 2023-06-07 08:19
@smhigley  `min-width: fit-content` will fix this issue. There actually is no `width: 100%` being applied here because the layout being used by default by `DataGrid` is flex and not the native table layout

**Comment by Huahuafanta** [comment] 2023-06-14 09:42
The column is not resizable when the DataGrid overflow in horizontal

**Comment by Huahuafanta** [comment] 2023-06-16 05:58
When will this PR be merged? Hope for that😍

**Comment by ling1726** [comment] 2023-06-20 07:29
I need some more time to investigate deeper, I'm trying to identify the root cause of the problem this brings to the column resizing - simply adding a width on our end doesn't quite make sense to me - since there's no reason for a value like `fit-content` when users use column resizing

**Closed** 2023-08-24 11:05 UTC
Labels: Type: Bug :bug:, Status: In PR, Fluent UI react-components (v9), Component: Table
