### ISSUE TITLE
[Dropdown] Required ARIA child role not present for dropdown

### ISSUE THREAD

**Issue by sijeee** [microsoft/fluentui#19090] opened 2021-07-23 08:07 UTC
### Environment Information

- **OS** : Windows 10
- **OS Version**: 21H1 (OS Build 19043.1110)
- **Browser Version**: Microsoft Edge (93.0.933.1) (Official build)  (64-bit)

### Describe the issue:

child of an element whose role is "combobox" needs to have an aria role of textbox

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/sijeee/pen/RwVjWZd

#### Actual behavior:

Elements with an ARIA role that require child roles does not contain them 

#### Expected behavior:

Ensures elements with an ARIA role that require child roles contain them

### Documentation describing expected behavior

https://www.w3.org/TR/wai-aria-1.1/#combobox

**Comment by max-zheng** [comment] 2021-08-03 20:52
Any update on this issue? My team found this same issue using Accessibility Insights for Web FastPass scan of our website. Looking at the code, the solution may be to add the role to this [span](https://github.com/microsoft/fluentui/blob/c55f2388771a2e169c5f8cf0a1f1441e6ef28d15/packages/react/src/components/Dropdown/Dropdown.base.tsx#L379)

**Comment by smhigley** [comment] 2021-08-04 05:18
This is a false positive from Accessibility Insights, and a dupe of #17838, #17981, #18333, and #19014. The false positive has already been fixed in axe-core (where Accessibility Insights' rules set comes from): https://github.com/dequelabs/axe-core/issues/2505.

@max-zheng to your question specifically: adding textbox (whether through a role or otherwise) as a child of a combobox results in significantly worse real-world support, so I definitely wouldn't recommend adding that role to the child span :)

**Closed by smhigley** 2021-08-04 05:18 UTC
Labels: Component: Dropdown, Needs: Triage :mag:
