### ISSUE TITLE
Nav no collapse (into a skinnier) feature in Fluent 8

### ISSUE THREAD

**Issue by hadnet** [microsoft/fluentui#15964] opened 2020-11-18 00:29 UTC
I'm using the Nav component and looking for a collapse mode like this one:

![collapse-mode](https://user-images.githubusercontent.com/13828833/99466285-ebfc4880-291a-11eb-90f5-54910f0b3c79.png)

but it seems like in Fluent UI 8 (version I'm using) this feature it's not present even though this feature is mentioned in the component description [doc](https://developer.microsoft.com/en-us/fluentui#/controls/web/nav). Is this feature implemented on v8? If it is, how code this?

**Comment by paulgildea** [comment] 2020-11-20 19:18
@hadnet Thanks for filing this issue.

After looking at the documentation it seems a little misleading. The current `Nav` component does not have an inherit "compact mode" to achieve the experience you call out. I'll mark this as a feature request to include it as feedback for when we converge on a unified Nav component. Unfortunately I don't have any timelines at this time on when this will be addressed.

Also after looking a this component and chatting with the code owner - I wasn't able to come up with any straightforward workarounds to get you that desired experience.

@JustSlone FYI or any ideas on a workround.

**Comment by ecraig12345** [comment] 2020-11-20 20:27
I'll update the documentation to more clearly reflect the current capabilities.

For a workaround, I made [this codepen](https://codepen.io/ecraig12345/pen/XWKLKrO) demonstrating how to do make the nav show icons only, though you might want to make some more modifications to the styling. If you want to show or hide the nav when a "hamburger" button is clicked, I don't have a demo of that but it should be fairly straightforward to set up (the icon name is `GlobalNavButton`).

**Comment by hadnet** [comment] 2020-11-21 04:11
@ecraig12345 Oh, I already made my own side nav but thanks for the tip.
![side-nav](https://user-images.githubusercontent.com/13828833/99867036-deea8e00-2b94-11eb-8f7d-869455373d4b.gif)

**Comment by JustSlone** [comment] 2020-11-29 22:32
Looks like the issue is resolved. Marking this future consider, something to look at when we refresh the Nav component. Closing for now however as Nav is not currently in plan for refresh. 

If there is still an issue here, feel free to re-open.

**Closed by JustSlone** 2020-11-29 22:32 UTC
Labels: Component: Nav, Fluent UI react, Status: Future Consider, Type: Feature
