### ISSUE TITLE
ISemanticColors / ISemanticTextColors not updated with latest neutral colors palette

### ISSUE THREAD

**Issue by eszychli** [microsoft/fluentui#17215] opened 2021-03-01 13:47 UTC
### Describe the issue:

For example, theme.semanticColors.bodyDivider = '#EAEAEA' instead of '#EDEBE9'.
Should be aligned with [color conversion table](https://static2.sharepointonline.com/files/fabric/fabric-website/files/fabric-neutrals-web-color-conversion.pdf).

**Comment by gouttierre** [comment] 2021-03-18 14:53
@eszychli - thank you for filing this with us.

@khmakoto - Would you be able to confirm if our fabric neutral web colors are up to date?

**Comment by khmakoto** [comment] 2021-03-19 19:09
@betrue-final-final should we update the values as described above?

**Comment by khmakoto** [comment] 2021-03-19 19:48
@eszychli I've asked @betrue-final-final offline and it seems that what you are posting is based on old information. I would suggest contacting him if you need more insights on this. Because of that I'll be resolving this as `Not an issue` and `By design`.

Let me know if there's anything else we can do to help.

**Closed** 2021-03-20 22:00 UTC
Labels: Component: Theme, Fluent UI react, Resolution: By Design, Resolution: Not An Issue

**Comment by eszychli** [comment] 2021-03-22 06:30
Thank you, agree the issue was solved

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
