### ISSUE TITLE
Same id for all input types.

### ISSUE THREAD

**Issue by zandiarash** [microsoft/fluentui#30983] opened 2024-04-07 13:24 UTC
### Library

Web Components (@fluentui/web-components)

### Are you reporting Accessibility issue?

None

### Reproduction

5

### Bug Description

Please see id of controls

![image](https://github.com/microsoft/fluentui/assets/10775073/4af174a9-7583-462e-8ef9-41285f21293a)

![image](https://github.com/microsoft/fluentui/assets/10775073/c7aafddb-bf06-47d6-b46f-96514759938b)

All elements have id="control"

This message shows in console
![image](https://github.com/microsoft/fluentui/assets/10775073/0564e809-c028-472a-b37e-8f5f34d5c9c3)

Maybe this wil solve some way like [this](https://github.com/microsoft/fluentui/issues/14812)

### Logs

```shell
blazor.web.js:1 [2024-04-07T13:19:07.939Z] Information: Normalizing '_blazor' to 'http://localhost:5166/_blazor'.
blazor.web.js:1 [2024-04-07T13:19:08.005Z] Information: WebSocket connected to ws://localhost:5166/_blazor?id=kc1T5YYGj3c-Zpd9kvA51Q.
Login:1  [DOM] Found 2 elements with non-unique id #control: (More info: https://www.chromium.org/developers/design-documents/create-amazing-password-forms) <input class=​"control" part=​"control" id=​"control" placeholder=​"name@example.com" required type=​"text">​ <input class=​"control" part=​"control" id=​"control" placeholder=​"password" required type=​"password">​

        [NEW] Explain Console errors by using Copilot in Edge: click 
         to explain an error. 
        Learn more
        Don't show again
```

### Requested priority

Low

### Products/sites affected

https://github.com/microsoft/fluentui-blazor

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chrisdholt** [comment] 2024-04-07 15:56
With shadow DOM, internals like these id's are considered unique as they are technically within separate DOM structures. What specifically is reporting this as a bug? I've ran this in the latest versions of both Edge and Chrome to see if I can get a repro on the incorrect error, but I have yet to see it.

**Comment by zandiarash** [comment] 2024-04-08 05:17
> With shadow DOM, internals like these id's are considered unique as they are technically within separate DOM structures. What specifically is reporting this as a bug? I've ran this in the latest versions of both Edge and Chrome to see if I can get a repro on the incorrect error, but I have yet to see it.

I have Edge browser

First please install
`dotnet new install Microsoft.FluentUI.AspNetCore.Templates
`
Then create a new project
`dotnet new fluentblazor --name MyApplication -au individual --no-https`

Next Run your sample project and navigate to the login page
Finally you can see errors in the console

**Comment by chrisdholt** [comment] 2024-04-08 05:27
> > With shadow DOM, internals like these id's are considered unique as they are technically within separate DOM structures. What specifically is reporting this as a bug? I've ran this in the latest versions of both Edge and Chrome to see if I can get a repro on the incorrect error, but I have yet to see it.
> 
> I have Edge browser
> 
> First please install `dotnet new install Microsoft.FluentUI.AspNetCore.Templates ` Then create a new project `dotnet new fluentblazor --name MyApplication -au individual --no-https`
> 
> Next Run your sample project and navigate to the login page Finally you can see errors in the console

What version of Edge? The internals are the current stable version of the web components, so if the error is coming from Edge, it should be reproable without running a Blazor project.

**Comment by zandiarash** [comment] 2024-04-08 12:21
> > > With shadow DOM, internals like these id's are considered unique as they are technically within separate DOM structures. What specifically is reporting this as a bug? I've ran this in the latest versions of both Edge and Chrome to see if I can get a repro on the incorrect error, but I have yet to see it.
> > 
> > 
> > I have Edge browser
> > First please install `dotnet new install Microsoft.FluentUI.AspNetCore.Templates ` Then create a new project `dotnet new fluentblazor --name MyApplication -au individual --no-https`
> > Next Run your sample project and navigate to the login page Finally you can see errors in the console
> 
> What version of Edge? The internals are the current stable version of the web components, so if the error is coming from Edge, it should be reproable without running a Blazor project.

I'm using Version 123.0.2420.81 (Official build) (64-bit) which is updated version till now.

**Comment by chrisdholt** [comment] 2024-04-08 15:55
> > > > With shadow DOM, internals like these id's are considered unique as they are technically within separate DOM structures. What specifically is reporting this as a bug? I've ran this in the latest versions of both Edge and Chrome to see if I can get a repro on the incorrect error, but I have yet to see it.
> > > 
> > > 
> > > I have Edge browser
> > > First please install `dotnet new install Microsoft.FluentUI.AspNetCore.Templates ` Then create a new project `dotnet new fluentblazor --name MyApplication -au individual --no-https`
> > > Next Run your sample project and navigate to the login page Finally you can see errors in the console
> > 
> > 
> > What version of Edge? The internals are the current stable version of the web components, so if the error is coming from Edge, it should be reproable without running a Blazor project.
> 
> I'm using Version 123.0.2420.81 (Official build) (64-bit) which is updated version till now.

Do you repro on your Windows browser with this min repro? https://typescript-zjjmrc.stackblitz.io

**Comment by zandiarash** [comment] 2024-04-20 08:18
> > > > > With shadow DOM, internals like these id's are considered unique as they are technically within separate DOM structures. What specifically is reporting this as a bug? I've ran this in the latest versions of both Edge and Chrome to see if I can get a repro on the incorrect error, but I have yet to see it.
> > > > 
> > > > 
> > > > I have Edge browser
> > > > First please install `dotnet new install Microsoft.FluentUI.AspNetCore.Templates ` Then create a new project `dotnet new fluentblazor --name MyApplication -au individual --no-https`
> > > > Next Run your sample project and navigate to the login page Finally you can see errors in the console
> > > 
> > > 
> > > What version of Edge? The internals are the current stable version of the web components, so if the error is coming from Edge, it should be reproable without running a Blazor project.
> > 
> > 
> > I'm using Version 123.0.2420.81 (Official build) (64-bit) which is updated version till now.
> 
> Do you repro on your Windows browser with this min repro? https://typescript-zjjmrc.stackblitz.io

No it seems that warning will not appear here

![image](https://github.com/microsoft/fluentui/assets/10775073/218bd184-d5c2-443c-9df2-7229110ef3ba)

**Comment by chrisdholt** [comment] 2024-04-24 03:36
I've followed up with the Edge team on the issue showing up in DevTools. As this is not an issue due to the above reasons and "by design", I'm going to close this issue. Thanks!

**Closed by chrisdholt** 2024-04-24 03:36 UTC
Labels: web-components
