### ISSUE TITLE
ResponsiveMode on Dropdown not effective. Error with Panel rendering on small viewport

### ISSUE THREAD

**Issue by calwi** [microsoft/fluentui#18307] opened 2021-05-24 20:50 UTC
### Environment Information

- **Package version(s)**: ^8.6.1
- **Browser and OS versions**: Chrome, Android Samsung Galaxy Tab A

### Describe the issue:

Dropdown box is rendering 'empty' panel when display/viewport is portrait. Setting responseMode property on the dropdown to try to force normal callout behaviour has no effect.

#### Actual behavior:

Panel is opened on the right side of the viewport/screen which is empty. No list items.

#### Expected behavior:

Setting the responsiveMode property on the control to force conventional dropdown callout, instead of panel. No effect. Panel always rendered.

### If applicable, please provide a codepen repro:

Unable to provide codepen. 

#### Work around:

I have hard coded the `responsiveMode` variable in Dropdown.base.js, `onRenderContainer` function to be greater than 2 (`ResponsiveMode.medium`) to force the `isSmall` test to always return false. See Lns 150-151. This forces the desired behaviour on the tablet and renders the standard dropdown callout.

**Comment by ecraig12345** [comment] 2021-05-25 01:56
This is a duplicate of #17288, and there's a fix in progress.

**Closed by ecraig12345** 2021-05-25 01:56 UTC
Labels: Needs: Triage :mag:
