### ISSUE TITLE
@fluentui/react-northstar@0.58.0 breaks `ComponentStyleFunctionParam`

### ISSUE THREAD

**Issue by DaleyKD** [microsoft/fluentui#19814] opened 2021-09-15 21:01 UTC
### Environment Information

- **Package version(s)**: "@fluentui/react-icons-northstar": "^0.58.0", "@fluentui/react-northstar": "^0.58.0",

### Please provide a reproduction of the bug in a codepen:
``` react
function FavoriteControl(props: IFavoriteProps) {
    const iconStyle = (x: ComponentStyleFunctionParam) => {
        return {
            color: x.theme.siteVariables.colors.yellow[600],
            ":hover": {
                color: x.theme.siteVariables.colors.yellow[400]
            }
        };
    };

    const buttonStyle = () => {
        return {
            borderColor: "transparent",
            backgroundColor: "transparent",
            boxShadow: "none"
        };
    };

    return (
        <Button
            styles={buttonStyle}
            icon={<StarIcon styles={iconStyle} />}
            iconOnly
        />
    );
}
```

#### Actual behavior:
`x.theme.siteVariables` no longer has a `colors` object.  In fact, `ComponentStyleFunctionParam` sure seems barren compared to 0.57.0.

#### Expected behavior:
It should work like it did in 0.57.0

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: High

**Comment by gouttierre** [comment] 2021-09-22 14:22
@DaleyKD - Thanks for reaching out to us. 

@jurokapsiar -  Would your team be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by chassunc** [comment] 2021-09-30 11:23
HI @DaleyKD 

I am not able to reproduce this in latest version. 

![Screenshot (34)](https://user-images.githubusercontent.com/86579954/135446518-60416048-ac65-4733-be29-d737b503a88b.png)

**Comment by chassunc** [comment] 2021-10-01 11:38
I am closing this since I can't repro, please, feel free to reopen if it happens again @DaleyKD

**Closed by chassunc** 2021-10-01 11:38 UTC
Labels: Fluent UI react-northstar, Needs: Investigation
