### ISSUE TITLE
TooltipHost not working inside Choicegroup

### ISSUE THREAD

**Issue by frags51** [microsoft/fluentui#14230] opened 2020-07-29 08:58 UTC
### Environment Information

- **Package version(s)**: The version which is used by the Documentation [here](https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup) (Checked out the codepen links on that doc)
- **Browser and OS versions**: Edge, Chrome on Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/frags51/pen/ExPzBRm

#### Actual behavior:

Tooltip is NOT visible when hovering on an option of the choicegroup that has a TooltipHost.

 #### Expected behavior:

Tooltip should be visible when hovering on an option of the choicegroup, that has a TooltipHost

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: (MS Internal)

**Comment by paulgildea** [comment] 2020-07-29 16:02
Thanks for the feedback @frags51 !

@micahgodbolt - Does the `TooltipHost` support using composite controls like the `ChoiceGroup`?

I aslo noticed in the [Tooltip](https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip) documentation requires passing an id to a element to anchor to. So I'm curious if that might be an issue with the codepen you shared?

**Comment by xugao** [comment] 2020-07-29 19:05
@frags51 - your code is slightly incorrect, which i corrected it [here](https://codepen.io/xugao/pen/OJMeRvy)

**Comment by curtisj44** [comment] 2020-07-30 21:20
I noticed the same issue today when trying to achieve this UI:

<img src="https://user-images.githubusercontent.com/810231/88973401-e1cf1500-d26b-11ea-8b50-2c991502e4b1.png" />

I initially tried defining `render()` and `TooltipHost` as siblings, similar to the provided repro Codepen ([codepen.io/frags51/pen/ExPzBRm](https://codepen.io/frags51/pen/ExPzBRm)). But, as reported, the Tooltip doesn't work with this approach:

```jsx
onRenderField: (props, render) => (
  <>
    { render!(props) }
    <TooltipHost>
      <button>Test</button>
    </TooltipHost>
  </>
),
```

The "corrected" Codepen ([codepen.io/xugao/pen/OJMeRvy](https://codepen.io/xugao/pen/OJMeRvy)) shows this can be avoided by nesting `render()` inside of `TooltipHost`. But, with this approach, the tooltip content doesn't appear to be accessible via the keyboard: 

```jsx
onRenderField: (props, render) => (
  <TooltipHost>
    { render!(props) }
  </TooltipHost>
),
```



Oddly, I did notice that `render()` and `TooltipHost` can be siblings when an `IconButton` is used as well: 🤔

```jsx
onRenderField: (props, render) => (
  <>
    { render!(props) }
    <TooltipHost>
      <IconButton />
    </TooltipHost>
  </>
),
```

Here are a couple of different approaches I tried: https://codepen.io/curtisj44/pen/JjGQewy. In the end, I think the nesting `IconButton` will work for my needs, but overall using `TooltipHost` inside of `ChoiceGroup` is finicky and _seems_ broken.

It would be nice if [the `ChoiceGroup` documentation](https://developer.microsoft.com/en-us/fluentui/#/controls/web/choicegroup) provided an example and/or guidance on the "correct" usage.

**Comment by paulgildea** [comment] 2020-07-31 15:59
Thanks for the feedback on the `ChoiceGroup` component. It wasn't totally clear to me if everyone's issues were resolved with the workaround @xugao proposed. Are folks all set?

**Comment by xugao** [comment] 2020-07-31 16:14
@curtisj44 - 
1. tooltip content is by design not keyboard focusable. see ARIA guide [here](https://www.w3.org/TR/wai-aria-practices-1.1/#tooltip):
>Tooltip widgets do not receive focus. A hover that contains focusable elements can be made using a non-modal dialog.

2. I think our doc site has listed all the correct usage. that is to wrap your tooltip target with TooltipHost. Ofc there are various use cases when it comes to actual app scenarios. we only provide the most generic examples in our documentation site

**Closed** 2020-08-01 19:00 UTC
Labels: Component: Tooltip, Fluent UI react, Needs: Author Feedback, Resolution: Not An Issue

**Comment by frags51** [comment] 2020-08-02 11:55
@curtisj44 Could you get Directional Hint working properly in this use case? I have overflow mode set to parent, but it looks like TooltipHost is not respecting the DirectionalHint.
