### ISSUE TITLE
[Bug]: Inserting a V9 button in a V8 dialog container does not add all the necessary classnames to leverage the v9 utilities

### ISSUE THREAD

**Issue by katiearriagam** [microsoft/fluentui#24547] opened 2022-08-26 19:00 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 15.56 GB / 31.66 GB
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/festive-pond-4oetr1?file=/index.tsx

## Steps
1. Open the codesandbox: https://codesandbox.io/s/festive-pond-4oetr1?file=/index.tsx
2. Open the V8 dialog, use tab-navigation to navigate to the footer buttons

## Actual Behavior
Keyboard focus is not visible

This is better categorized as a v8 <-> v9 compat issue that results in an accessibility bug. In the v8 dialog, buttons never get set the fui-focus-visible class when tabbed into them (which does happen in the v9 dialog). This also limits the ability to use some utilities like createCustomFocusIndicatorStyle which depend on having said class.

## Expected Behavior
Focus should be visible. Compare by opening the v9 dialog.

### Requested priority

Normal

### Products/sites affected

Office applications

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by katiearriagam** [comment] 2022-08-26 19:02
This is better categorized as a v8 <-> v9 compat issue that results in an accessibility bug. In the v8 dialog, buttons never get set the `fui-focus-visible` class when tabbed into them (which _does_ happen in the v9 dialog). This also limits the ability to use some utilities like `createCustomFocusIndicatorStyle` which depend on having said class.

**Comment by layershifter** [comment] 2022-08-29 12:26
Duplicate of #24411?

**Comment by micahgodbolt** [comment] 2022-08-29 16:18
@ling1726 does this look like a duplicate? Or is this some other issue we should dig into?

**Comment by katiearriagam** [comment] 2022-08-31 17:21
@ling1726, @micahgodbolt, @layershifter - friendly ping on this 😄

**Comment by ling1726** [comment] 2022-09-05 13:01
as @layershifter  mentioned, this is a duplicate already tracked under #24411

**Closed by ling1726** 2022-09-05 13:01 UTC
Labels: Needs: Discussion, Needs: Backlog review, Fluent UI react-components (v9), Fluent UI react (v8), Component: Portal
