### ISSUE TITLE
[Bug]: Dropdown/Datepicker on safari appears at top of screen (different on chrome + firefox)

### ISSUE THREAD

**Issue by JohnPeterson01** [microsoft/fluentui#30084] opened 2023-12-15 12:33 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 63.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 15.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-axmzfa?file=src%2FApp.tsx

```
import {
  FluentProvider,
  webLightTheme,
  makeStyles,
  Dropdown,
  Option,
} from '@fluentui/react-components';
import { DatePicker } from '@fluentui/react-datepicker-compat';

const useStyles = makeStyles({
  root: {
    marginTop: '300px',
  },
});

const Example = () => {
  const styles = useStyles();
  const options = ['zebra', 'horse'];
  return (
    <>
      <div className={styles.root}>
        <DatePicker placeholder="Select a date..." />
        <Dropdown placeholder="Select an animal">
          {options.map((option) => (
            <Option key={option}>{option}</Option>
          ))}
        </Dropdown>
      </div>
    </>
  );
};

export const App = () => {
  return (
    <FluentProvider theme={webLightTheme}>
      <Example />
    </FluentProvider>
  );
};
```

## Actual Behavior

The dropdown + the date selector component open at the top of the screen rather than below the input fields on Safari Browser.

<img width="527" alt="image" src="https://github.com/microsoft/fluentui/assets/20837559/3c3c6467-8879-450a-afeb-59ef040915c4">

Note that it works fine for Chrome + Firefox.

## Expected Behavior

The dropdown and date selector components should open directly under the input fields on all browsers

<img width="526" alt="image" src="https://github.com/microsoft/fluentui/assets/20837559/ddee7e99-f6f5-4431-874d-bc084770a393">

## Other notes
Inspecting the css of the dropdown shows that the chrome version of the drop down is rendered with the following style properties:
```
{
    position: absolute;
    left: 0px;
    top: 0px;
    margin: 0px;
    width: 250px;
    box-sizing: border-box;
    transform: translate3d(212px, 224px, 0px);
}
```

On safari the dropdown is rendering with the following:
```
{
    position: absolute;
    left: 0px;
    top: 0px;
    margin: 0px;
    width: 250px;
    box-sizing: border-box;
}
```

Note that there's no transform on the safari css? It might just be me and I need to add the relevant `webkit` css property somewhere? I tried looking in the [fluent documentation](https://react.fluentui.dev/) everywhere but couldn't see anything?

I'm happy to raise a PR to fix this but would just need some pointers on how to fix?

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by JohnPeterson01** [comment] 2023-12-19 15:21
@sopranopillow I noticed that it's the same with the tooltip as well on safari:
```
import {
  FluentProvider,
  webLightTheme,
  makeStyles,
  Button,
  Tooltip,
} from '@fluentui/react-components';
import * as React from 'react';
import { SlideTextRegular } from '@fluentui/react-icons';

const useStyles = makeStyles({
  root: {
    marginTop: '300px',
  },
});

const Example = () => {
  const styles = useStyles();
  return (
    <>
      <div className={styles.root}>
        <Tooltip content="Example tooltip" relationship="label">
          <Button icon={<SlideTextRegular />} size="large" />
        </Tooltip>
      </div>
    </>
  );
};

export const App = () => {
  return (
    <FluentProvider theme={webLightTheme}>
      <Example />
    </FluentProvider>
  );
};
```

Screenshot:
<img width="432" alt="image" src="https://github.com/microsoft/fluentui/assets/20837559/5bd3cf0e-6143-4cce-86a7-d2dd3e907037">

I've tried looking through the fluent ui source code but can't find anything that could be causing this 🤔

**Comment by JohnPeterson01** [comment] 2023-12-19 15:22
I also checked, it's not the theme provider as the same thing happens without the theme:

```
import {
  FluentProvider,
  webLightTheme,
  makeStyles,
  Button,
  Tooltip,
} from '@fluentui/react-components';
import * as React from 'react';
import { SlideTextRegular } from '@fluentui/react-icons';

const useStyles = makeStyles({
  root: {
    marginTop: '300px',
  },
});

const Example = () => {
  const styles = useStyles();
  return (
    <>
      <div className={styles.root}>
        <Tooltip content="Example tooltip" relationship="label">
          <Button icon={<SlideTextRegular />} size="large" />
        </Tooltip>
      </div>
    </>
  );
};

export const App = () => {
  return <Example />;
};
```

<img width="291" alt="image" src="https://github.com/microsoft/fluentui/assets/20837559/26e301c2-a8b5-4c95-bfd8-ca3ce8b6a8ce">

**Comment by JohnPeterson01** [comment] 2023-12-19 19:03
I can see a transform here -> https://github.com/microsoft/fluentui/blob/91d0cd7c1a3810b4f6507c5e8007bbc94cbbc3f6/packages/react-components/react-select/src/components/Select/useSelectStyles.styles.ts#L82

Interesting if I update to add `-webkit` prefixes then the select drop opens directly below?
<img width="458" alt="image" src="https://github.com/microsoft/fluentui/assets/20837559/a7d7aa28-b75d-4ccb-9ca4-6d99b9781f85">

I updated so there was a one for one webkit transform equivalent:
```
    ".f1yk9hq::after{-webkit-transform:scaleX(0); transform:scaleX(0);}",
    ".fhwpy7i::after{-webkit-transition-property:transform; transition-property:transform;}",
    ".f14ee0xe::after{-webkit-transition-duration:var(--durationUltraFast); transition-duration:var(--durationUltraFast);}",
    ".f1xhbsuh::after{-webkit-transition-delay:var(--curveAccelerateMid); transition-delay:var(--curveAccelerateMid);}"
```

**Comment by JohnPeterson01** [comment] 2023-12-19 19:06
So for the tooltips we would need to update the relevant transforms here:
https://github.com/microsoft/fluentui/blob/91d0cd7c1a3810b4f6507c5e8007bbc94cbbc3f6/packages/web-components/src/tooltip/tooltip.styles.ts#L73

**Comment by sopranopillow** [comment] 2023-12-22 23:06
I don't see why there's a need for the transform. As a quick look, this seems to be an issue either with our positioning library or in Safari. Seeing as this is also affecting Tooltip, is this affecting Popover as well? I can't really test it on my side since I don't have an Apple computer, but I'll try to get someone from our team that has one to review after the holidays.

> So for the tooltips we would need to update the relevant transforms here:

This is not for our v9 components, you are referencing a web-component which we don't own and are not related to React components.

cc @behowell

**Comment by JohnPeterson01** [comment] 2023-12-26 18:20
> I don't see why there's a need for the transform. As a quick look, this seems to be an issue either with our positioning library or in Safari

Got it - thanks for explaining this. 

> Seeing as this is also affecting Tooltip, is this affecting Popover as well?

Yep same with the popover it seems.

<img width="443" alt="image" src="https://github.com/microsoft/fluentui/assets/20837559/6d474766-40ba-4a1c-9151-11036b53166d">

Code example:
```
import {
  FluentProvider,
  webLightTheme,
  makeStyles,
  Button,
  Popover,
  PopoverSurface,
  PopoverTrigger,
} from '@fluentui/react-components';

const useStyles = makeStyles({
  root: {
    marginTop: '300px',
  },
});

const Example = () => {
  const styles = useStyles();
  return (
    <div>
      <h3 className={styles.contentHeader}>Popover content</h3>

      <div>This is some popover content</div>
    </div>
  );
};

export const App = () => {
  const styles = useStyles();
  return (
    <FluentProvider theme={webLightTheme}>
      <div className={styles.root}>
        <Popover>
          <PopoverTrigger disableButtonEnhancement>
            <Button>Popover trigger</Button>
          </PopoverTrigger>

          <PopoverSurface tabIndex={-1}>
            <Example />
          </PopoverSurface>
        </Popover>
      </div>
    </FluentProvider>
  );
};
```

> I'll try to get someone from our team that has one to review after the holidays

This would be amazing, thanks!

**Comment by sopranopillow** [comment] 2023-12-27 17:11
This confirms it's our positioning library. Removing my assignment and setting teams-prg as the owner since it's related to our positioning library and they own it.

**Comment by JohnPeterson01** [comment] 2023-12-28 14:38
Great. Thanks for your help with this one. Do you know if there's a repo for the positioning library that I can look at at all?

**Comment by sopranopillow** [comment] 2023-12-28 18:14
we use `@floating-ui` and if you're interested, our positioning package is `react-components/react-positioning`.

**Comment by layershifter** [comment] 2024-01-19 09:27
We debugged this issue and code was throwing:

![image](https://github.com/microsoft/fluentui/assets/14183168/5d9a0df3-da2d-475b-9be6-f9a9c6fe8661)

So, this issue is a duplicate of #30165 and have been fixed already 🐱

**Closed by layershifter** 2024-01-19 09:27 UTC
Labels: Component: Dropdown, Component: Tooltip, Component: Popover, Fluent UI react-components (v9)

**Comment by JohnPeterson01** [comment] 2024-01-19 09:37
thank you all ! much appreciated :)
