### ISSUE TITLE
[Bug]: npm install fails in newly created app

### ISSUE THREAD

**Issue by dprosper** [microsoft/fluentui#22462] opened 2022-04-12 01:19 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 18.29 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Browsers:
    Brave Browser: 100.1.37.111
    Chrome: 100.0.4896.75
    Safari: 15.4
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/get-started/web

## Actual Behavior
Following the steps here to create a new app 
![image](https://user-images.githubusercontent.com/11874942/162859116-0bc6b4e8-a6ad-41c5-904f-22334123c5b5.png)

results in the following error: 

```sh
% npx create-react-app my-app --template @fluentui/cra-template

Creating a new React app in /Development/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with @fluentui/cra-template...


added 1355 packages in 31s

171 packages are looking for funding
  run `npm fund` for details

Initialized a git repository.

Installing template dependencies using npm...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=16.8.0 <18.0.0" from @fluentui/react@8.64.2
npm ERR! node_modules/@fluentui/react
npm ERR!   @fluentui/react@"^8.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## Expected Behavior

No errors.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment] 2022-04-12 18:54
This is a duplicate of #22241. We have not updated peer dependencies to support React 18. PR is up for updating our peer deps.

https://github.com/microsoft/fluentui/pull/22261

**Closed** 2022-04-12 19:07 UTC
Labels: Resolution: Duplicate
