### ISSUE TITLE
DetailsList selection is reset once a filter that does not include the selected item is cleared

### ISSUE THREAD

**Issue by avenezia** [microsoft/fluentui#13118] opened 2020-05-12 15:55 UTC
### Environment Information

- **Package version(s)**: 7.107.3
- **Browser and OS versions**: Edge version 83.0.478.18 on Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/avenezia/pen/qBOKzwZ (it corresponds to the example in the website)

1. enable modal selection
2. select an item (e.g. Lorem ipsum)
3. write lor in the filter and the selected item is still available and selected
4. write lora in the filter and the item disappears as expected
5. clear the filter and the item is not selected anymore

#### Actual behavior:
The selected item is not selected anymore once the filter that does not match it is cleared.

#### Expected behavior:
The selected item should still be selected once the filter is cleared.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Power Query Online

**Comment by aneeshack4** [comment] 2020-05-12 15:59
@avenezia Thanks for reaching out to us. I believe it is by design that we clear selection after filter. Either way, this is low priority for us and as we're focused on larger work items right now, going to resolve this as won't fix but when we schedule future work on this component, we may rethink this behavior so thanks for giving us feedback.

**Closed** 2020-05-18 01:00 UTC
Labels: Component: DetailsList, Resolution: Won't Fix, Type: Bug :bug:
