### ISSUE TITLE
ICommandBarItemProps doesn't show tooltip content unless iconOnly=true

### ISSUE THREAD

**Issue by LinnCohenMS** [microsoft/fluentui#21534] opened 2022-02-02 14:25 UTC
Hello,
We use 'CommandBar' :
![image](https://user-images.githubusercontent.com/97615298/152168203-09b5db44-187c-4981-8c9b-8884a017f296.png)
and I need the functionality of the tooltip for the 'Delete' button. 
But unfortunately, the tooltip is designed only for iconOnly=true. 
![image](https://user-images.githubusercontent.com/97615298/152167926-c736539b-d1cb-492d-8afe-0936dba73456.png)

Is it possible to add the support to display a tooltip for both modes? 
(Current state is that tooltip is enabled only if the button is an icon, and if I want tooltip for icon+text it is not possible)
I am willing to help to fix it if needed.

Thank you very much,
Linn

**Comment by paulgildea** [comment] 2022-03-09 07:36
@LinnCohenMS Thanks for the issue.

This is by design - Tooltips are shown for UI that doesn't have a textual description of the component. In the case for `CommandButtons` that have a label a Tooltip redundant. 

cc: @smhigley - to weigh in on whether this pattern. 

Closing by design for now, but if there is a specific pattern that is required to have tooltips on every `CommandButton` regardless of it's mode, we're open to a contribution.

**Closed by paulgildea** 2022-03-09 07:36 UTC
Labels: Resolution: By Design, Fluent UI react (v8), Component: CommandBarButton
