### ISSUE TITLE
[Feature]: An automatically disappearing Toast-like notification

### ISSUE THREAD

**Issue by jsancho** [microsoft/fluentui#25291] opened 2022-10-19 10:21 UTC
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

I was going to write a request for a toast-like component and found that this has already been requested at least 3 times over the years.

https://github.com/microsoft/fluentui/issues/20020  (2021)
https://github.com/microsoft/fluentui/issues/5479 (2018)
https://github.com/microsoft/fluentui/issues/865 (2017)

In the issues above, there are several mocks and examples, as well as references to office.com and Azure portal, where toasts are noticeably used.
From the comments, it can also be appreciated that this is a reasonably widespread component that would most welcome by the community.

Disappointingly, all the issues have eventually been closed for lack of activity.

@micahgodbolt I see that you've been mentioned a few times across the issues. 
Could you please shed some light on why this feature does might not get enough buy-in to be implemented? 
Could it break some Fluent design principle? 

thanks,

Jaume

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JustSlone** [comment] 2023-03-13 16:48
Agreed, this is a good candidate for a component to add. This is planned as part of our new set of components: Fluent UI React v9 (`react-components`) aligned to the updated Fluent design system. 

You can see the beginning of an implementation here in Alert: https://react.fluentui.dev/?path=/docs/preview-components-alert--default. There is more work that needs to be done here and will start next month.

**Comment by ling1726** [comment] 2023-06-01 10:55
Closing as duplicate of #26638

**Closed by ling1726** 2023-06-01 10:55 UTC
Labels: Type: Feature, Fluent UI react (v8), Component: Toast
