### ISSUE TITLE
Running `npx @fluentui/codemods` in project results in only 'Mod was a NoOp on this file' messages

### ISSUE THREAD

**Issue by MarksPoint** [microsoft/fluentui#19847] opened 2021-09-17 09:57 UTC
### Environment Information

- **Package version(s)**: Running latest version of @fluentui/codemods using `npx @fluentui/codemods`, I believe it's version 8.2.1
- **Browser and OS versions**: macOS Big Sur 11.4, node 14.17.0, npx 6.14.13

### Please provide a reproduction of the bug in a codepen:

**Some background**
- We've built a lot of modules that use various (older) versions of Fluent UI React. Most of them use some 7.x version of `office-ui-fabric-react`. We want to upgrade these solutions to the new `@fluentui/react` library
- I've tried to run `npx @fluentui/codemods` to help upgrading our solutions but nothing gets updated

**Reproduction**
I've used our Yeoman generator to build a dummy module. You can use this project ([Archive.zip](https://github.com/microsoft/fluentui/files/7184622/Archive.zip)) or you can use the generator yourself:
- Install Yeoman (`npm install -g yo`)
- Install our Yeoman generator (`npm install -g @ichicraft/generator-widgets`)
- Create a folder and go to that folder
- Run our generator (`yo @ichicraft/widgets`)
- Accept all the default answers
- Wait for npm install to finish
- Run `npx @fluentui/codemods`
- See that no updates are done to the .tsx files
- See several messages in the output of the command with 'Mod was a NoOp on this file'

#### Actual behavior:
Output

```
npx: installed 69 in 4.164s
fetching codeMod at  /Users/markvandijk/.npm/_npx/57698/lib/node_modules/@fluentui/codemods/lib/codeMods/mods/componentToCompat/componentToCompat.mod.js
fetching codeMod at  /Users/markvandijk/.npm/_npx/57698/lib/node_modules/@fluentui/codemods/lib/codeMods/mods/configMod/configMod.mod.js
fetching codeMod at  /Users/markvandijk/.npm/_npx/57698/lib/node_modules/@fluentui/codemods/lib/codeMods/mods/officeToFluentImport/officeToFluentImport.mod.js
fetching codeMod at  /Users/markvandijk/.npm/_npx/57698/lib/node_modules/@fluentui/codemods/lib/codeMods/mods/oldToNewButton/oldToNewButton.mod.js
fetching codeMod at  /Users/markvandijk/.npm/_npx/57698/lib/node_modules/@fluentui/codemods/lib/codeMods/mods/personaToAvatar/personaToAvatar.mod.js
getting configs
File index.ts has had the following mods error:
name:  configMod errorData:  {
  modName: 'configMod',
  error: 'failed to get any mods from json. Perhaps the file is missing or malformed?'
}
File index.ts has had the following mods run:
name:  RepathOfficeImportsToFluent logdata:  [ 'Mod was a NoOp on this file' ]
File typings.d.ts has had the following mods run:
name:  configMod logdata:  [ 'Mod was a NoOp on this file' ]
name:  RepathOfficeImportsToFluent logdata:  [ 'Mod was a NoOp on this file' ]
File App.tsx has had the following mods run:
name:  configMod logdata:  [ 'Mod was a NoOp on this file' ]
name:  RepathOfficeImportsToFluent logdata:  [ 'Mod was a NoOp on this file' ]
File LikeIcon.tsx has had the following mods run:
name:  configMod logdata:  [ 'Mod was a NoOp on this file' ]
name:  RepathOfficeImportsToFluent logdata:  [ 'Mod was a NoOp on this file' ]
File widget.module.scss.d.ts has had the following mods run:
name:  configMod logdata:  [ 'Mod was a NoOp on this file' ]
name:  RepathOfficeImportsToFluent logdata:  [ 'Mod was a NoOp on this file' ]
```

#### Expected behavior:

- I was expecting that all references to `office-ui-fabric-react` would be updated to the new `@fluentui/react` library
- I also expected the package.json being updated to include new (replacement) packages from the @fluentui scope instead of the old @uifabric scope.

### Priorities and help requested:

Are you willing to submit a PR to fix? > Not too familiar with this project, so preferrably no

Requested priority: Blocking (not at all working)

Products/sites affected: Our product Ichicraft Boards relies heavily on Fluent UI and it would save us a lot of time if we could upgrade/migrate somewhat automatically

**Comment by gouttierre** [comment] 2021-09-22 14:28
@MarksPoint - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@GeoffCoxMSFT  - Would you be able to assist with the stated problem (upgrading)?

**Comment by ravikiranvs** [comment] 2022-01-18 05:30
I am facing the same issue as @MarksPoint 
Any workarounds available for this?

**Comment by GeoffCoxMSFT** [comment] 2022-01-20 18:34
@Hotell - I'm not familiar with the codemods from 7 -> 8.  Are you the SME here? :)

**Comment by Hotell** [comment] 2022-02-24 12:28
> @Hotell - I'm not familiar with the codemods from 7 -> 8. Are you the SME here? :)

unfortunately I'm not

**Comment by dmitriyyepishin** [comment] 2022-03-16 18:25
We are having the same issue when upgrading from 7.x to 8.x. Is there an update?

**Comment by dmitriyyepishin** [comment] 2022-04-08 22:17
I got this to work using the following command:

npx @fluentui/codemods -n configMod -e

The problem is being caused by default "src/codeMods/mods/upgrades.json". This causes an error and that error prevents files to be output to the file system after modifications have been made. The command line above excludes "configMod" which is the one that reads upgrades.json.

This is a bug that should be fixed in the code.

**Closed** 2022-10-11 10:43 UTC
Labels: Area: Fluent, Status: In PR, Fluent UI react (v8), 🧐 Under investigation
