### ISSUE TITLE
Build: unable to use ES2019 features like `Object.fromEntries()`

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#21229] opened 2022-01-10 16:47 UTC
### Please provide a reproduction:

- Clone / check build output #21228
- That PR contains a simple change that uses `Object.fromEntries()` that is ES2019 feature:

![image](https://user-images.githubusercontent.com/14183168/148802414-518eb704-4cc3-4ef2-9b33-9e3ad49d0677.png)

- Run `yarn buildto @fluentui/react-utilities --no-cache`, it's passing ✅

![image](https://user-images.githubusercontent.com/14183168/148802647-dfef4afb-8590-45d8-8a20-e332ce0ee30e.png)

- Run `yarn workspace @fluentui/react-utilities type-check`, it fails 🚨

![image](https://user-images.githubusercontent.com/14183168/148803076-868abe2c-5f23-4d89-9c12-4b645d33cc82.png)

#### Actual behavior:

One of commands passes, other fails. Editor also doesn't show any errors. That's unpredictable.

- Option 1: Using `ES2019` in root `tsconfig.base.json` solves the problem.
- Option 2: Using `"lib": ["ES2019", "DOM"],` in `packages/react-utilities/tsconfig.spec.json` solves the problem.

I tried to trace the issue and it looks that `useUnmount.ts` in included by `tsconfig.spec.json`:

` yarn workspace @fluentui/react-utilities type-check --explainFiles`

```
src/hooks/useUnmount.ts
  Imported via './useUnmount' from file 'src/hooks/useUnmount.test.tsx'
src/hooks/useUnmount.test.tsx
  Matched by include pattern '**/*.test.tsx' in 'tsconfig.spec.json'
```

#### Expected behavior:

Both commands should use same TS config and work or fail.

**Comment by Hotell** [comment] 2022-01-10 17:39
> One of commands passes, other fails. Editor also doesn't show any errors. That's unpredictable.

yes, we know about this and pointed on it few times ( it will get better hopefully soon) - `build` is leveraging the old build approach, while `type-check` invokes `tsc` in `build` mode, which invokes tsc in solution config mode thus running programs for all environments ( test/lib/storybook/e2e)

> Editor also doesn't show any errors

Editor/tscserver behaviour is correct. as it uses solution config file - meaning in your implementation file it evaluates your code against `tsconfig.lib.json`. When you open your spec file, it evaluates it against `tsconfig.spec.json`, but because the "invalid" code does not live here there is no error - this should be probably reported to TypeScript team to cover also this situation. From DX I'd expect an generic error within whole file that would give you the same output as when running `tsc -p tsconfig.spec.json` 


> I tried to trace the issue and it looks that useUnmount.ts in included by tsconfig.spec.json:

yes that's by design/expected how `tsc` works. implementation is imported in spec file, so it will be part of program processing even it's not included in `include` glob


> 1. Using ES2019 in root tsconfig.base.json solves the problem.

Ideally I'd like us to port vNext DX to v8 as well in the future, so consumers/core team gets the best DX possible, thus having this as global setting for everyone might not be possible - v8 will not support latest ECMA, so we would not have a common way how define things

> 2. Using "lib": ["ES2019", "DOM"], in packages/react-utilities/tsconfig.spec.json solves the problem.

Regarding your solution proposal, none of those is ideal (for example - our node version might not be in match with browser versions we are supporting, thus ECMA lang feature might differ etc... ).

A bit better situation  would be use only `target` as source of truth per package within `tsconfig.json` (as we have for vNext `"target": "ES2019",` ), and use lib for more granular setting to properly differentiate environment:
- for browser code `"lib": [ "dom"],`
- for node code, no `lib` needed

but aforementioned would not work as expected ( how TSC resolves lib + target )

---

**Based on previous explanation a good enough solution for our use case might be following:** 

### 1. browser packages

in `tsconfig.json`

```
"target": ["ES2019"],
"lib": ["ES2019", "DOM"]
```

- while this is confusing for tests that run agains nodeJS via jest,  configuration of jest must include JSDOM implementation, thus making DOM global apis usage valid
- thus removing target/lib from `tsconfig.{lib,spec).json`

### 2. node packages

in `tsconfig.json`

```
"target": ["ES2019"], // or based on actual node we use/support
"lib": ["ES2019"]
```

- jest should be configured to not include JSDOM
- thus removing target/lib from `tsconfig.{lib,spec).json`

---

If we agree on this , migration generator should be updated to follow this behaviour and all vNext packages should be updated accordingly.

**Closed** 2023-08-25 19:29 UTC
Labels: Area: Build System, Priority 2: Normal, Resolution: Soft Close
