### ISSUE TITLE
[Bug]: DatePicker without a status message still renders a status message div causing an aligment issue

### ISSUE THREAD

**Issue by daric81** [microsoft/fluentui#23332] opened 2022-05-31 13:58 UTC
### Library

React Components / v8 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz     
    Memory: 4.85 GB / 23.93 GB
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codepen.io/devman81/pen/oNEqQpE

## Actual Behavior
When using the DatePicker component that will never have a text description/ status message displayed an empty status message div is still rendered which has  margin-top: 5px styling. This misaligns when displaying other input controls. 

## Expected Behavior
When there is no text description value render null instead.   The renderTextfieldDescription function from DatePicker.base.tsx could be changed to achieve this.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment] 2022-06-23 11:04
@daric81 - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@khmakoto  - Would you be able to confirm if this is a regression, or if this behavior is an issue? Then triage the priority level accordingly. Thanks

**Comment by tudorpopams** [comment] 2022-10-10 15:47
looping @microsoft/fluent-date-time on this one as they might have a better answer to the issue.

**Comment by conniec218** [comment] 2022-10-11 23:44
It looks like this issue has been here for a while, so I don't believe it's a regression. I think we *should* change `renderTextfieldDescription` to render null if there is no status message, but I'm not sure if we should get rid of the margin altogether. It would definitely impact some consumers' UI, but how much of a breaking change would that be, if at all? 

If we decide we want to keep the margin, perhaps moving it to the root datepicker element would be cleaner.

**Comment by daric81** [comment] 2022-10-28 10:44
Thanks for the review of this issue.  Sounds like we are in agreement that renderTextfieldDescription should return null when statusMessage doesn't have a value, a minor change .

**Closed** 2023-04-26 11:00 UTC
Labels: Type: Bug :bug:, Component: DatePicker, Fluent UI react (v8), Resolution: Soft Close
