### ISSUE TITLE
On hovering the choice group options in IE 11 the hover dot is retained

### ISSUE THREAD

**Issue by najeebrizvi** [microsoft/fluentui#13526] opened 2020-06-09 09:30 UTC
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.90.0"
- **Browser and OS versions**: IE11

### Please provide a reproduction of the bug in a codepen:
This issue can be easily verified here, Steps:

1. Open the URL in IE11 : https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup

2. In the "Controlled ChoiceGroup" hover on the radio buttons, you will notice hover dot is retained.

#### Actual behavior:
1. In IE Hover dot is retained even if cursor moved to another item.

#### Expected behavior:
1. Hover dot should go away once the hover is over

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)
Sharepoint
![image](https://user-images.githubusercontent.com/66671342/84131187-ddebf700-aa61-11ea-9fb2-5827c0d55a30.png)

**Comment by paulgildea** [comment] 2020-06-09 17:39
Dupe of #13475 

Is there a SharePoint example that you share so that we can understand how often customers run into this issue?

This is a won't fix for now based on the impact on our initial findings.

If you would like to submit a PR for a fix we'd happily take a look at it. 👍 

Thanks!

**Comment by ecraig12345** [comment] 2020-06-09 17:48
I just opened the website in IE 11 and can't repro this.

**Comment by najeebrizvi** [comment] 2020-06-09 18:41
Try hovering on the radio buttons a bit slow, I am still able to reproduce the issue
![image](https://user-images.githubusercontent.com/66671342/84186870-cedf6600-aaae-11ea-8e65-4056978ce01c.png)

**Comment by najeebrizvi** [comment] 2020-06-09 18:48
Here is the Sharepoint link to reproduce this issue 
https://microsoft.sharepoint.com/_layouts/15/sharepoint.aspx?q=idweb&v=search

Steps to repro: 
1. Click on the feedback button
![image](https://user-images.githubusercontent.com/66671342/84187363-90967680-aaaf-11ea-92c6-e6a11ab9c079.png)

2. Hover on the radio buttons
![image](https://user-images.githubusercontent.com/66671342/84187493-c0de1500-aaaf-11ea-85ac-98c8f4e114be.png)

Let me know if you face any issue while accessing the link

**Closed** 2020-06-18 02:00 UTC
Labels: Component: ChoiceGroup, Needs: Author Feedback, Resolution: Can't Repro, Status: No Recent Activity, Type: Bug :bug:
