### ISSUE TITLE
"Show code" in fluentui docs site hangs the browser

### ISSUE THREAD

**Issue by baurine** [microsoft/fluentui#12643] opened 2020-04-10 11:45 UTC
### Environment Information

- **Package version(s)**: don't know
- **Browser and OS versions**: Chrome/Firefox latest version, masOS 10.15

### Please provide a reproduction of the bug in a codepen:

See fluentui docs in developer site, here is an example: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist#overview, click the "Show code" tab for example.

#### Actual behavior:

The browser will hang and I can't scroll the contents.

![企业微信20200410072717](https://user-images.githubusercontent.com/1284531/78988191-ccba6300-7b62-11ea-9451-9b52f159371b.png)

![企业微信20200410072833](https://user-images.githubusercontent.com/1284531/78988198-d17f1700-7b62-11ea-8f7b-e5dc39b434ae.png)

![企业微信20200410073137](https://user-images.githubusercontent.com/1284531/78988202-d2b04400-7b62-11ea-81f6-ce943e16eefc.png)

#### Expected behavior:

I can see the example code normally.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

**Comment by joschect** [comment] 2020-04-10 18:56
@baurine Thanks for the submission! This definitely repros and is a bug. It only seems to happen in details list so I'm wondering if there is a bug in details list, or if the problem is in the code editor. @ecraig12345 do you have any ideas?

**Comment by ecraig12345** [comment] 2020-04-10 22:49
Thanks for reporting this! It may be related to #11488. Hard to say if it's actually specific to DetailsList or if it would show up in other complex scenarios as well. Unfortunately it's hard to debug because it doesn't repro in the non-minified [PR deploy site](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/12645/merge/fabric-website/dist/index.html?devhost#/controls/web/detailslist), the actual site's bundle is so big that sourcemaps don't work, and it's hard to tell which minified code is ours vs. React internals since we bundle React...

Here's what I've tried so far:
1. Load the page
2. Open the debugger
3. Open settings and uncheck "Enable JavaScript source maps"
4. Click "Show code"
5. Wait a couple seconds and then pause the debugger

It seems to be stuck in an infinite loop while rendering, but I'm not sure what's causing it.

**Comment by baurine** [comment] 2020-04-11 05:49
hi @joschect , it is not only for detail list, some other pages have same problem, for example this: https://developer.microsoft.com/en-us/fluentui#/controls/web/list (the warning text in the screenshot means: one page makes your browser slow, how do you want to handle? stop or wait)

![image](https://user-images.githubusercontent.com/1284531/79036444-d7c0d200-7bfa-11ea-965f-ad16825b0803.png)

**Comment by baurine** [comment] 2020-04-13 00:28
BTW, the DetailsList component works fine in my own project.

**Comment by joschect** [comment] 2020-04-13 22:04
@baurine Thanks for the clarification! That helps to narrow thing down. The details list relies on the list so it seems like it could be an underlying problem in the list code somewhere.

We'll add this to our backlog and get it looked at.

**Comment by ecraig12345** [comment] 2020-04-13 22:54
Until we have a chance to debug this further, we may want to disable the editor for all list examples (List, DetailsList, probably GroupedList) so that it's at least possible to view the code. There's not a built-in way to do this right now but I could think about it a bit and suggest something.

**Comment by ecraig12345** [comment] 2020-04-21 00:13
Closing in favor of duplicate #12754--that one is newer but has more discussion.

**Closed by ecraig12345** 2020-04-21 00:13 UTC
Labels: Area: Website, Component: DetailsList, Package: tsx-editor, Type: Bug :bug:
