### ISSUE TITLE
CommandBarButton primary styles

### ISSUE THREAD

**Issue by fildahui** [microsoft/fluentui#18882] opened 2021-07-09 16:15 UTC
The `CommandBarButton` component extends the `IButtonProps` interface therefore it has the `primary` prop available too.
Looking at the source code, though, its styles do not take that into consideration (eg, calling `primaryStyles(theme)` similarly to what happens for the `DefaultButton` component) but I couldn't find anything in the documentation saying that the prop is ignored for certain type of buttons, there's just "_Changes the visual presentation of the button to be emphasized._" on the prop description which reads as _"_all_ the button types can be set as primary"_.

My question then is: is it an issue (as in the primary styles are missing and should be applied)? or is it the expected way the `CommandBarButton` should work? (and so I guess the documentation should mention that somewhere?)

### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
[`https://codepen.io/fildahui/pen/RwVRzXz`](https://codepen.io/fildahui/pen/RwVRzXz)

This is the code of one of your CommandBarButton sample with just the primary prop added to it

#### Actual behavior:

`Primary` is ignored

#### Expected behavior:

Either apply the primary styles or document the CommandBarButton do not support the primary styling

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by ling1726** [comment] 2021-07-12 12:17
From what I see, `CommandBarButton` uses the `BaseButton` component which does not include the `primary` styling. The styling for `primary` is only included with `DefaultButton`

@behowell  can you consult the v8 team and see if this is a bug or by design ?

**Comment by ecraig12345** [comment] 2021-07-15 18:30
Another question, @fildahui do you have a specific use case where you need the CommandBarButton to have primary styling? Or is this just a theoretical question?

**Comment by fildahui** [comment] 2021-07-15 18:55
Hi @ecraig12345 
Well, my actual use case is that I am using those buttons in an actions bar because of their dimensions and I need to make the primary action recognisable amongst the others. 
But as I said, if that's by design that's okay (I am manually overriding the styles object at the moment) but then I'd expect to know what buttons can be primary or not

**Comment by ling1726** [comment] 2021-07-16 07:33
It seems like a narrowing of the props interface would be useful here, it is not unreasonable to think that `primary` styles would be applied if the prop exists in the interface

**Comment by ecraig12345** [comment] 2021-07-16 21:57
Thanks for the clarification! I agree that narrowing the types would make sense in theory. Unfortunately that would be a breaking change, so we wouldn't be able to do it outside a new major version, which isn't planned any time soon.

@khmakoto Can you confirm whether the CommandBarButton is intended to update its styles in response to the `primary` prop? If not, we'll probably close this as "by design" (for the styling) or "won't fix" (for the types, since it's unfortunately not feasible to fix them in the foreseeable future).

**Closed** 2022-07-13 13:01 UTC
Labels: Type: Question ❔, Needs: Discussion, Component: Button, Help Wanted ✨, Component: CommandBarButton, Resolution: Soft Close
