### ISSUE TITLE
[Bug]: List control with checkboxes for multi-select, scrolls  

### ISSUE THREAD

**Issue by gkhub** [microsoft/fluentui#32420] opened 2024-08-29 20:13 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 39.46 GB / 63.95 GB
  Browsers:
    Chrome: 128.0.6613.85
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

None

### Reproduction

Snippet in bug description

## Actual Behavior
We are using List in a callout to display mult-select list. When scroll bar is present, users are not able to select the checkbox and the clicking on the checkbox scrolls to the top of the list without selecting the item. 
This is the snippet hosted in a callout
const MultiSelectList = <TValue extends any>({ // TValue extends any is added due to JSX limitation for this function signature with generics
    items,
    selectedItems,
    className,
    showSelectAll,
    onChange,
    onSelectAll,
    styles,
}: MultiSelectListProps<TValue>): React.ReactElement => {
    const numberOfItems = items.length;
    const numberOfSelectedItems = selectedItems.filter((selectedItem) => items.some(item => selectedItem.key === item.key)).length;
    const allSelected = numberOfItems === numberOfSelectedItems;
    const noneSelected = numberOfSelectedItems === 0;
    const indeterminate = !allSelected && !noneSelected;
    const checked = indeterminate ? undefined : allSelected;
    const [version, setVersion] = useState(0);

    useEffect(() => {
        setVersion((preVersion) => ++preVersion);
    }, [selectedItems]);

    const onRenderCell = useCallback((item: Item<TValue>): React.ReactElement => {
        const checked = selectedItems.some((selectedItem) => selectedItem.key === item.key);

        return (
            <div className={styles.listRow}>
                <Checkbox
                    className={styles.checkbox}
                    label={item.text}
                    key={item.key}
                    checked={checked}
                    onChange={(_event, checked) => {
                        onChange(item, checked);
                    }} />
            </div>
        );
    }, [items, selectedItems, onChange]);

    const selectAllCheckbox = showSelectAll && (
        <div className={styles.listRow} >
            <Checkbox
                label={Resources.all}
                ariaLabel={Resources.selectAll}
                styles={{
                    label: {
                        fontWeight: "600",
                    },
                }}
                className={styles.checkbox}
                indeterminate={indeterminate}
                checked={checked}
                onChange={(_event, checked) => onSelectAll(!!checked)} />
        </div>
    );

    return (
        <div role="group" className={className}>
            <FocusZone
                direction={FocusZoneDirection.bidirectional}
                handleTabKey={FocusZoneTabbableElements.none}
                isCircularNavigation={true} >
                {selectAllCheckbox}
                <List items={items} version={version} onRenderCell={(item) => onRenderCell(item)} />
            </FocusZone>
        </div>
    );
};

I also noticed when I tried to take screenshot, when I did a new snip (snip tool), the scroll shifted to the top.

## Expected Behavior
Item must be selected rather than scrolling to the top.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment] 2024-08-30 07:40
@gkhub please provide reproduction demo via one of cloud platforms like stackblitz/codesandbox. otherwise we are not able to verify your reported issue.

ty

**Comment by Hotell** [comment] 2024-09-05 08:16
Re-posting offline convo from @gkhub:

I tracked down the root cause to this issue with FocusTrapCallout - [FocusTrapCallout with scrollable radio list: cannot select some of the items · Issue #20472 · microsoft/fluentui · GitHub](https://github.com/microsoft/fluentui/issues/20472)
 
That's the exact scroll issue we are hitting due to recent migration from Callout to FocusTrapCallout. I am trying out the suggested fix in that issue. 
 
You can close the issue I opened as the issue is not in List control but the wrapped FocusTrapCallout.

**Closed by Hotell** 2024-09-05 08:16 UTC
Labels: Status: No Recent Activity, Needs: Author Feedback, Fluent UI react (v8), Needs: Repro
