### ISSUE TITLE
Slider with Keyboard control

### ISSUE THREAD

**Issue by KludgeMaster** [microsoft/fluentui#16918] opened 2021-02-10 09:11 UTC
### Environment Information

- **Package version(s)**: 7.158.3
- **Browser and OS versions**: MS Edge (88.0.705.63) / Windows 10 Enterprise 2004

### Describe the issue:
Two scenarios but I believe they come from the same root cause:
   
-  When the slider is controlled via keyboard, setting the value via `value` prop doesn't update the UI.
   To reproduce:
   1. Tab to slider and change the value using arrow key
   2. Click on Reset button
  [_Expected_] Slider handle moves to reset position
  [_Actual_] Slider handle doesn't move

- When the slider is controlled via mouse, and value is reset, then keyboard interaction starts from last position.
   To reproduce:
      
   1. Change the value of slider using mouse (eg value: 5)
   2. Click on Reset button => Value becomes 0, and slider handle moves to reset position
   3. Tab to slider and use arrow key to change the value
   [_Expected_] Value moves from Reset value
   [_Actual_] Value moves from previous value (eg value 5)

### Please provide a reproduction of the issue in a codepen:
Please use this codepen to follow the steps above: [link](https://codepen.io/KludgeMaker/pen/rNWMGwP)

**Comment by joschect** [comment] 2021-02-17 23:19
@KludgeMaster Thanks for the submission and including that codepen! I can see the issue that you describe. This is definitely a bug and we will get it addressed.

**Comment by JustSlone** [comment] 2021-02-28 03:44
Awesome repro, thanks. 

If someone wants to jump on this and figure out what's going wrong, and propose a fix, please do!

**Comment by Augani** [comment] 2021-03-02 13:26
Hello @JustSlone I would love to look into this

**Comment by JustSlone** [comment] 2021-03-02 17:55
Thanks @Augani! :tada: 
Assigning it to you. 

Some Advice:
- Figure out what the root cause is, and update this issue (this is super helpful even if we can't fix it right now)
- Look for feedback on the proposed fix before going too deep into implementation (though an early implementation of the fix often helps) 
- Avoid breaking changes, especially in component surface, but also in DOM structure

**Comment by Shriram-Balaji** [comment] 2021-03-02 19:24
@JustSlone I was also thinking if I could take a stab at this. 

Based on initial investigation, it looks like the issue is because the `this.state.value` in the Slider doesnt seem to update properly when `onKeyDown` handler is called. Moreover I tried to tinker around, and a key step we seem to be missing inside of `onKeyDown` handler is 

```js
  private _onKeyDown = (event: KeyboardEvent): void => {
    // . . . existing code
    // Disable renderedValue override.
    this.setState({
      renderedValue: undefined,
    });
```
Resetting the `renderedValue` helps in fixing the first issue mentioned above, ie moving the slider handle to the right position.

**Comment by Augani** [comment] 2021-03-09 15:35
@Shriram-Balaji That's great!!

**Comment by JustSlone** [comment] 2021-03-10 05:53
Nice! Thank you @Shriram-Balaji for the contribution! 💯 💯 💯

**Closed by JustSlone** 2021-03-10 05:53 UTC
Labels: Help Wanted ✨, Needs: Investigation, Status: Fixed, Type: Bug :bug:
