### ISSUE TITLE
ChoiceGroup: Narrator does not narrate the text from ariaLabeledBy for Chrome Browser

### ISSUE THREAD

**Issue by DennyHo2020** [microsoft/fluentui#22479] opened 2022-04-13 00:14 UTC
### Environment Information

- **Package version(s)**: "@fluentui/react": "8.45.0",
- **Browser and OS versions**: Chrome Version 100.0.4896.88, Windows 11 Pro Version 10.0.22000 Build 22000

### Describe the issue:

Narrator does not narrate the text from the label element with the id in ariaLabeledBy for radio button option in Chrome.
** Works in Edge. **
** Also applies to the label property of the choicegroup in Chrome. Label is not narrated.**

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/dennyho2020/pen/WNdaeXP

#### Actual behavior:
When navigating, narrates only the radio button label + selected required data.
Ex: '... Option D Radio Button...'

#### Expected behavior:
Narrates the choice group arialabeledby text + the radio button name + selected required data.
'... Custom Label radio group, Option D Radio Button...'

**Comment by micahgodbolt** [comment] 2022-04-13 15:36
Can you please provide a quick codepen or codesandbox demo, and include which version of the framework, and browser you are using.

**Comment by micahgodbolt** [comment] 2022-04-14 23:01
Yeah, I can confirm that Chrome skips the aria-labelledby whether it's inside of the radiogroup or outside of the radio group. This has nothing to do with FluentUI though as the same raw HTML fails in Chrome as well. This is a Chrome/Narrator bug. 

If you can find something incorrect about our produced HTML please note it, otherwise I will mark this as an external issue.

**Comment by smhigley** [comment] 2022-04-14 23:34
Chrome and Narrator are not a recommended combination. Chrome doesn't map to the accessibility API that Narrator uses, so all accessibility information goes through an IA2 > UIA bridge in Windows. When using Narrator to browse the web, Edge is recommended since it directly supports UIA.

As @micahgodbolt mentioned, this is not a Fluent bug, so I'm going to close the issue.

**Closed by smhigley** 2022-04-14 23:34 UTC
Labels: Needs: Author Feedback, Resolution: External
