### ISSUE TITLE
[Bug]: Problem with the dialog box - only the white rectangle is displayed

### ISSUE THREAD

**Issue by necik11** [microsoft/fluentui#30542] opened 2024-02-13 16:36 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631 
Browsers:
    Edge: Chromium (121.0.2277.112)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

Create new spfx project with CommandSet , npm i @fluentui/react , gulp serve  

### Bug Description

I am using this version of fluentui in package.json:
@fluentui/react": "^8.115.6"

this is import:
import { Dialog, DialogType } from '@fluentui/react';
I even try:
import { Dialog, DialogType} from '@fluentui/react/lib/Dialog';
+
import { BaseDialog } from '@microsoft/sp-dialog';

I am using in SPFX Command set, here i am [extends BaseDialog ](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx)
```
export default class CustomDialog extends BaseDialog {
...
    public render(): void {
        ReactDOM.render(MyLoadingDialog...
}
```

## Actual Behavior
Dialog not working properly, this code return only white rectangle:
```
export const LoadingDialogContent...{
 <Dialog hidden={false}>
            <ProgressIndicator label={props.spinnerLabel} />
 </Dialog>
```
Sometimes with luck, the first load succeeds, but most of the time it's just an empty rectangle.
If the first attempt succeeds, the second opening of the dialog is always just an empty rectangle
![image](https://github.com/microsoft/fluentui/assets/25322303/eca506de-8c31-46f2-ac19-2d2e3bf9b300)

## Expected Behavior
Displaying elements in the dialog.

I have the impression that only a few hours ago this dialog was working

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment] 2024-03-04 20:57
Hi @necik11, it's not clear from your description whether this is an issue in FluentUI, SPFX, or your code. In order for us to investigate it, we need to be able to reproduce the issue (e.g. in a codepen or stackblitz), ideally using only FluentUI. You can use the "Export to CodePen" link from one of the documentation samples on https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog to get started with a repro.

**Comment by necik11** [comment] 2024-03-04 21:46
I just don't know, it was working all the time, and out of the blue, it stopped...

The entire issue is described here: [ISSUE](https://github.com/SharePoint/sp-dev-docs/issues/9515)

In short: SPFX describes how to use Custom dialog for Command Action (we should use BaseDialog). Only this dialog is probably not from FluentUI and this covers dialogs, modals from Fluent UI = all people pickers, context menu, etc.

I detached the BaseDialog and left the purely FluentUI dialog and everything works... but I don't know if it's the right solution.

Unfortunately, I cannot put this code on "CodePen" because SPFX cannot be run as a sandbox, but must be run directly to the existing SharePoint.

If it's an SPFX problem, please close it and I apologize for the question.

**Comment by behowell** [comment] 2024-03-04 22:35
If it only repros when using SPFX, then I would recommend investigating SPFX first to see if you can find where the issue is. We can't fix it on the FluentUI side unless the problem can be isolated to FluentUI code. I'll close this issue for now. If you do find a repro that uses only the FluentUI dialog, then please re-open it and include the repro. Thanks!

**Closed by behowell** 2024-03-04 22:35 UTC
Labels: Needs: Triage :mag:, Fluent UI react (v8), Needs: Repro
