### ISSUE TITLE
Click on the line of title area far from Toggle button will also change the toggle state.

### ISSUE THREAD

**Issue by zeedomD** [microsoft/fluentui#14056] opened 2020-07-16 06:17 UTC
### Environment Information

- **Package version(s)**: 7.122.0 or older
- **Browser and OS versions**: All browsers

### Please provide a reproduction of the bug in a codepen:
1. Go to Toggle Example Page. https://developer.microsoft.com/en-us/fluentui#/controls/web/toggle
2. Click any blank area on the same line with the title area.
![image](https://user-images.githubusercontent.com/20253660/87633681-60a55780-c76e-11ea-9400-4bc06967cf6b.png)
3. Click any blan area on the same line with the toggle area.
![image](https://user-images.githubusercontent.com/20253660/87633724-7d418f80-c76e-11ea-8b61-b12493116b35.png)

#### Actual behavior:
1. Click on any blank area on the same line with toggle title, will change Toggle check state
2. Clikc on any blank area on the same line with toggle button, will not change Toggle check state.

#### Expected behavior:

1. Only clicking on the toggle button should change the check state.
2. Or, only clicking on the Text area or the near area should change teh check state
![image](https://user-images.githubusercontent.com/20253660/87633973-fccf5e80-c76e-11ea-8392-a20cc2f9f209.png)
3. Or, clicking on blank area on the same line with Title and Toggle Button should keep consistant.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment] 2020-07-16 15:35
Dupe of #13721

**Closed** 2020-07-19 18:00 UTC
Labels: Component: Toggle, Resolution: Duplicate, Type: Bug :bug:
