### ISSUE TITLE
:not() pseudo-class not detecting class names using makeStyles

### ISSUE THREAD

**Issue by omri08** [microsoft/fluentui#18667] opened 2021-06-22 15:55 UTC
### Environment Information

- **Package version(s)**:  8.20.2
- **Browser and OS versions**: Windows Chrome,

### Please provide a reproduction of the bug in a codepen:
expected result with sass only:
https://codesandbox.io/s/bold-dew-qyq3m?file=/src/styles.scss
unexpected result with fluent UI using makeStyles
https://codesandbox.io/s/basic-demo-forked-xg5vt?file=/src/index.js
![image](https://user-images.githubusercontent.com/54754198/122956762-f5a2ce80-d389-11eb-89f8-cc6736769751.png)
In the picture, the parent has a class name called `hi,` which means he should not have the `background-color: blue` style. 
#### Actual behavior:
The `:not()` pseudo-class not detecting the class name that causing applying the wrong style

#### Expected behavior:
The `:not()` pseudo-class needs to detect the class name and not apply the style.

**Comment by gouttierre** [comment] 2021-08-10 14:05
@omri08 - Thanks for filing this issue with us.

@smhigley - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @layershifter

**Comment by layershifter** [comment] 2021-08-10 14:25
> * **Package version(s)**:  8.20.2

@gouttierre this issue is related to v8, not to v9. `makeStyles()` has completely different implementation there. @microsoft/cxe-red owns it 😉

**Comment by smhigley** [comment] 2021-08-10 23:57
@dzearing do you still own ThemeProvider, and if so, do you have a sense of where the issue is?

@omri08 this looks like a bug specifically around the combination of `:not()` and `::before`. If you define them separately rather than nesting them, it works:

```css
const useStyle = makeStyles(() => ({
  beginof: {
    "&:before": {
      content: '"<<>>"'
    },
    "&:not(.hi)": {
      backgroundColor: 'red',
    },
    "&:not(.hi)::before": {
      backgroundColor: "blue"
    }
  }
}));
```

Does that work for you as a workaround for now?

**Comment by khmakoto** [comment] 2021-08-11 01:39
I don't know if it's a bug or not, but if you remove the second "&" before the ":before" it works as expected:

https://codesandbox.io/s/basic-demo-forked-yws9j?file=/src/index.js

**Comment by dzearing** [comment] 2021-08-11 16:29
This isn't a ThemeProvider issue. This is likely a makeStyles issue. I thought makeStyles was based on merge-styles under the hood, but it doesn't seem to be any more. merge-styles handles this scenario correctly. @layershifter have any ideas?

**Comment by khmakoto** [comment] 2021-12-10 00:03
v8 `makeStyles` is deprecated now as it was an experimental styling solution that was not meant to be published. Closing this issue now.

**Closed by khmakoto** 2021-12-10 00:03 UTC
Labels: Platform: Chrome, Package: styling, Needs: Investigation, Fluent UI react (v8)
