### ISSUE TITLE
Focus boundary rectangle on dropdown menu items not visible from side

### ISSUE THREAD

**Issue by gulsntils** [microsoft/fluentui#16079] opened 2020-11-27 11:12 UTC
### Environment Information

- **Package version(s)**:  "office-ui-fabric-react": "7.148.0"
- **Browser and OS versions**: Chrome - 87.0.4280.66, Win 10 Enterprise

### Describe the issue:

On trying to navigate a multi-select dropdown through keyboard, the focus boundary rectangle on the menu items has missing sides.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/pen/?&prefill_data_id=efbb0b29-92da-4ae0-bd92-6d8c0409229b
Same codepen as in official fabric website, can repro there as well.

#### Actual behavior:

Focus boundary rectangle has missing sides

#### Expected behavior:

Focus boundary rectangle should be visible clearly

**Comment by dev-a11y** [comment] 2020-12-01 17:10
Duplicate of #14795

**Closed** 2021-05-24 14:00 UTC
Labels: Fluent UI react, Needs: Investigation, Resolution: Soft Close
