### ISSUE TITLE
Panel Footer is getting misaligned during overflow.

### ISSUE THREAD

**Issue by PraveenVerma17** [microsoft/fluentui#19961] opened 2021-09-24 12:43 UTC
### Environment Information

- **Package version(s)**:  8.34.1
- **Browser and OS versions**: Edge, Chrome

#### Actual behavior:

Panel footer is totally getting misaligned in 8.34.1 when we have overflow data. 

#### Expected behavior:

Panel footer should be visible at all the the time, even we have overflow data. 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: (if applicable)

**Comment by PraveenVerma17** [comment] 2021-09-24 13:17
Just to let you know panel works fine with version 8.20.1

**Comment by PraveenVerma17** [comment] 2021-09-24 16:17
here is code pen example, i just added paragraphs to overflow content. after overflow i juts scroll and this happened. 
https://codepen.io/princeindia/pen/QWgZjym

**Comment by ecraig12345** [comment] 2021-09-27 23:04
@TristanWatanabe Can you help with this since it's a regression from your PR #19811?

**Comment by PraveenVerma17** [comment] 2021-10-08 16:47
@ecraig12345  @TristanWatanabe 
Is there any update on this ?

**Comment by lucas-stanford** [comment] 2021-10-30 00:12
I believe it's fixed with this PR: https://github.com/microsoft/fluentui/issues/20135

**Comment by ecraig12345** [comment] 2021-11-01 21:28
Yes, this is fixed now. You can verify by opening the codepen link (which will use the latest version by default).

**Closed by ecraig12345** 2021-11-01 21:28 UTC
Labels: Component: Panel, Needs: Investigation, Fluent UI react (v8)
