### ISSUE TITLE
SplitButton - main action not reachable on mobile

### ISSUE THREAD

**Issue by yunicz** [microsoft/fluentui#14303] opened 2020-08-03 08:58 UTC
# Environment Information

- **Package version(s)**: 7.124.1
- **Browser and OS versions**: Chrome/Safari, iPhone - iOS13

### Describe the issue:

Main action of split button is not accessible on iOS, no matter how hard I try it is not possible to trigger it.

### Please provide a reproduction of the issue in a codepen:

This can be easily reproduced even on main doc page:
1, Open https://developer.microsoft.com/en-us/fluentui#/controls/web/button on an iOS device
2, Scroll to split button section a try to tap the main action

#### Actual behavior:

Dropdown part of the split button gets triggered.

#### Expected behavior:

After clicking the left part of button main action passed by onClick should be invoked

**Comment by fafuxa-microsoft** [comment] 2020-08-04 22:59
^Also facing this issue, which seems like a duplicate of https://github.com/microsoft/fluentui/issues/9653 where this was classified as by design because:

> 1. The split menu should have all options available including the primary action;
> 2. The touch target is not large enough to only execute the menu, so to resolve the ambiguity all split buttons react to touch this way (act as a menu button.)

I think this behavior should at least be configurable though since it makes buttons not work properly and the design is not very intuitive. Would love to discuss further to see if we can change this somehow

**Comment by khmakoto** [comment] 2020-08-04 23:13
@paulgildea it does seem like this issue comes back relatively often, should we take it up to design?

**Comment by fafuxa-microsoft** [comment] 2020-08-12 17:02
@khmakoto and @paulgildea any updates? Since theres no workaround, we're looking into writing our own internal split button to support this, which is not ideal...

Like I said, ideally this would be customizable - that way it doesnt break current scenarios and the same default design can be kept. Let me know your thoughts

**Comment by paulgildea** [comment] 2020-09-11 16:25
@khmakoto - Looks like this issue is not mobile specific. For non-mobile cases the hit target should be large enough to trigger an `onClick`

@miroslavstastny - Can you look into this issue in the mean time?

**Comment by DhirajKhot** [comment] 2020-09-16 05:33
@paulgildea @miroslavstastny 
Do we have any updates on this?

**Comment by dzearing** [comment] 2020-09-22 17:44
This is by design. Because of small touch targets, split buttons always expand the menu on touch and do not execute the action. The expectation is that the primary action should be available on the menu.

**Comment by jspurlin** [comment] 2020-09-23 02:27
@dzearing is correct although it's more than just an accessibility issue, it's a general usability issue for all touch users.

**Comment by fafuxa-microsoft** [comment] 2020-09-23 06:39
@dzearing @jspurlin I understand where you're coming from - in most cases, the side caret in the split button _is_ too small to click on a touch screen, especially in an example like the one in https://developer.microsoft.com/en-us/fluentui#/controls/web/button

However, split buttons are highly customizable, and with some CSS the button can be made much larger to the point where these usability/accessibility concerns should no longer be an issue. For example, I can make a mobile experience where the split button looks like this

![image](https://user-images.githubusercontent.com/69216748/93974503-bed05700-fd2a-11ea-8dda-31ce478ad42a.png)

I'm not too familiar with the WCAG 2.1 guidelines, but I assume the caret should be large enough in the example above (or in some other theoretical example) to consider the button clickable/compliant. So, my suggestion would be to make the default behavior the same as it is today on mobile, but add some prop to the button that makes this customizable if the consumer really does want this to work this way (named something like primaryOnClickEnabledForMobile, or something more concise).

If the stance is still that this is by design and cannot be made customizable. then we should update the docs [here ](https://developer.microsoft.com/en-us/fluentui#/controls/web/button) and clarify this. I know for me personally I spent a lot of time trying to figure out why this was happening on my custom split button until I realized it was by design.

**Closed** 2021-04-26 14:02 UTC
Labels: Component: Button, Fluent UI react, Needs: Investigation, Platform: Chrome, Platform: Microsoft Edge, Platform: Safari, Resolution: Soft Close
