### ISSUE TITLE
[Feature]: ThemeProvider should be providing fonts.

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#31331] opened 2024-05-09 23:10 UTC
### Library

React v9 (@fluentui/react-components)

### Describe the feature that you would like added

FluentProvider does register common font faces. It also has no documented guidance on how to register font faces with a theme.

It absolutely needs to manage this, or, a variant of FluentProvider should be provided that does. Consumers shouldn't need to think about font faces. Without doing this, end users using v9 will have to try and "align" fonts manually, which means that the Fluent themes can not be the source of truth on which fonts are used. Please, let's unify this so there is one "truth".

What I am observing is that different partners using Fluent v9 are using different font-face definitions and subsequently result in different end-user experiences. This goes against a lot of the reason Fluent exists - to unify our UX experiences on a common component library, token set, and design language.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by layershifter** [comment] 2024-05-10 09:03
Duplicate of #27673.

**Closed by layershifter** 2024-05-10 09:03 UTC
Labels: Type: Feature, Priority 1: High, Area: Fonts, Partner Ask, Fluent UI react-components (v9), Component: FluentProvider
