### ISSUE TITLE
[Bug]: Link focus outline style is not obvious

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#25394] opened 2022-10-26 23:24 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 17.96 GB / 31.91 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://react.fluentui.dev/?path=/docs/components-link--default

## Actual Behavior

The default outline is removed, instead, the focus style is double underline, no matter as link or as button.

This might be a different a11y requirement, but our partner has raised a11y bug that this focus is not obvious enough. 

![image](https://user-images.githubusercontent.com/39588094/198156454-551bcf65-d1cf-40c2-858b-e0cb0ead1b3c.png)

## Expected Behavior

Use original focus style:
![image](https://user-images.githubusercontent.com/39588094/198156832-5a50cadf-afe0-41be-b8fc-21b4bd77b1c5.png)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment] 2022-10-27 18:39
Duplicate of #22776.

**Closed by khmakoto** 2022-10-27 18:39 UTC
Labels: Area: Accessibility, Component: Link, Resolution: Duplicate, Fluent UI react-components (v9)
