### ISSUE TITLE
Lost Focus when scroll in ScrollablePane

### ISSUE THREAD

**Issue by breeswish** [microsoft/fluentui#13557] opened 2020-06-11 08:06 UTC
### Environment Information

- **Package version(s)**: Latest (7.118.1)
- **Browser and OS versions**: Edge 83.0, Windows

### Please provide a reproduction of the bug in a codepen:

Use the official "DetailsList Locked Header" example in https://developer.microsoft.com/en-us/fluentui#/controls/web/scrollablepane

Steps:

1. Focus the "Filter by name" input
2. Scroll the DetailsList

#### Actual behavior:

The input lose focus and you can no longer input.

#### Expected behavior:

The input still has focus.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

No

Requested priority: (Blocking, High, Normal, Low)

Low

Products/sites affected: (if applicable)

**Comment by jdhuntington** [comment] 2020-06-11 21:08
Hi @breeswish - thanks for the report.

I am able to reproduce this issue. 

The root cause is this line in `src/components/Sticky/Sticky.tsx`:

```tsx
public addSticky(stickyContent: HTMLDivElement): void {
    if (this.nonStickyContent) {
      stickyContent.appendChild(this.nonStickyContent);
    }
  }
```

Since `Sticky` works by removing things from the DOM and adding them elsewhere, focus is lost.

Unfortunately I believe a fix for this issue would require large scale changes to these components that we are unable to undertake at this point. I will leave this issue open to track the bug. In the meantime, if this is a blocking issue, I recommend you find another way to position the text box.

**Comment by breeswish** [comment] 2020-06-12 06:35
Thanks for the reply! Looks like losing focus when reparenting is a browser behaviour. I have some unverified ideas:

1. Before reparenting (both add sticky and remove sticky), check whether the active element `document.activeElement` is a child of the element to reparent (e.g. `nonStickyContent`). Keep the reference of `activeElement` if it is.
2. After reparenting, focus the last kept `activeElement` to restore the focus.

**Closed** 2022-02-04 16:02 UTC
Labels: Type: Bug :bug:, Component: ScrollablePane, Resolution: Soft Close
