### ISSUE TITLE
[Bug]: Mac - Clicking outside the context menu should only dismiss the context menu instead of onClicking the control that was clicked

### ISSUE THREAD

**Issue by SaylorTw1ft** [microsoft/fluentui#27765] opened 2023-05-04 16:23 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 18.64 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Edge: 112.0.1722.68
    Safari: 16.4
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/SaylorTw1ft/pen/xxyParR

## Actual Behavior
When you have a context menu open and click outside of it onto another component such as a button, that click goes through on the button.  This is the current behavior on all platforms, Win32, Mac, and in a browser.

## Expected Behavior
The actual behavior is expected for Win32 and browsers; however, Mac platform expects any clicks when a context menu is open to only dismiss the menu.  The click (even if on a button) shouldn't actually result in an onClick for that button control.

### Requested priority

High

### Products/sites affected

Excel

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment] 2023-06-08 16:53
I cannot repro this in Edge. In safari that contextual menu wont popup at all so maybe that's the bug you wanted to report ?

**Comment by SaylorTw1ft** [comment] 2023-06-08 21:45
I just reproed this in Safari using the above codepen by right-clicking either of the buttons and then right-clicking the other one.

**Comment by spmonahan** [comment] 2023-06-09 18:22
I'm not able to repro in Safari either but that seems to be an issue with Safari + Codepen as none of the ContextualMenu examples exported from the doc site to Codepen work reliably for me in Safari though all the ones I tested worked fine on the doc site.

I put together a [Codepen with native select menus](https://codepen.io/seanms/pen/zYMxXjr) to demonstrate the difference as I'm able to get this to work reliably in Safari + Codepen 😃

After poking around at this I agree that Windows and Mac behave differently but I'm not sure that means a web UI library like Fluent should feature detect OSes and attempt to emulate OS behavior but rather target the Web platform. Given that I see a couple ways forward here:

1. @SaylorTw1ft can you look at existing Fluent APIS like [calloutProps](https://developer.microsoft.com/en-us/fluentui#/controls/web/callout#ICalloutProps) to see if you can enable the behavior you want?
2. We can add APIs that allow users to enable this feature for themselves.

I'd also suggest we change this to a "feature request" from a "bug" since I think Fluent is behaving as intended and we won't change the existing default behavior.

**Comment by SaylorTw1ft** [comment] 2023-06-14 20:13
That sounds reasonable, I will see if calloutProps will do what we want and otherwise report back if we would need API support to do this.

**Comment by spmonahan** [comment] 2023-06-28 21:48
Closing this for now. We can reopen if this needs to be revisted later.

**Closed by spmonahan** 2023-06-28 21:48 UTC
Labels: Issue Pinged, Fluent UI react (v8), Component: Menu
