### ISSUE TITLE
[Bug]: DataGrid controlled selection broken (regression)

### ISSUE THREAD

**Issue by s-bauer** [microsoft/fluentui#27997] opened 2023-05-25 08:34 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/stf87m?file=/example.tsx

### Bug Description

A reproduction example is on your own documentation site: https://react.fluentui.dev/?path=/docs/components-datagrid--default#single-select-controlled

Selecting a row does not trigger the onSelectionChange event and therefore doesn't allow the user to make a new selection. This is a regression bug.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment] 2023-05-25 08:57
Duplicate of #27896. Have been already fixed in `master`, but was not release yet.

**Comment by s-bauer** [comment] 2023-05-25 08:58
@layershifter Ahh I only searched the active issues, sorry for that. Any eta when it's gonna be released?

**Closed** 2023-05-25 08:57 UTC
Labels: Resolution: Duplicate, Fluent UI react-components (v9)

**Comment by layershifter** [comment] 2023-05-25 12:29
@s-bauer I released it few hours ago, check `@fluentui/react-components@9.20.4`.
