### ISSUE TITLE
[Accessibility] Dialog breaks "https://dequeuniversity.com/rules/axe/3.3/aria-hidden-focus?application=axeAPI" rule 

### ISSUE THREAD

**Issue by XianghanWang** [microsoft/fluentui#14749] opened 2020-08-25 23:11 UTC
### Environment Information

- **Package version(s)**: 7.130.0
- **Browser and OS versions**: Chrome, Windows 10

When open a dialog, it contains below code which breaks **aria-hidden-focus** rule.

div **aria-hidden="true" tabindex="0"** data-is-visible="true" style="pointer-events: none; position: fixed;"></div

https://codepen.io/pen/?&editable=true=https%3A%2F%2Ffabricweb.z5.web.core.windows.net%2Foufr%2F7.130.0%2F

https://dequeuniversity.com/rules/axe/3.3/aria-hidden-focus?application=axeAPI

**Comment by XianghanWang** [comment] 2020-08-25 23:14
div aria-hidden="true" tabindex="0" data-is-visible="true" style="pointer-events: none; position: fixed;"></div

**Comment by XianghanWang** [comment] 2020-08-25 23:31
The code is in packages\office-ui-fabric-react\src\components\FocusTrapZone\FocusTrapZone.tsx

    const bumperProps = {
      **'aria-hidden': true,**
      style: {
        pointerEvents: 'none',
        position: 'fixed', // 'fixed' prevents browsers from scrolling to bumpers when viewport does not contain them
      },
      **tabIndex: disabled ? -1 : 0, // make bumpers tabbable only when enabled**
      'data-is-visible': true,
    } as React.HTMLAttributes<HTMLDivElement>;

**Comment by paulgildea** [comment] 2020-08-26 16:01
@smhigley FYI

**Comment by suvaso** [comment] 2020-10-13 21:42
Hi, is there any update on this issue? When can we expect the issue to be fixed?

**Comment by JustSlone** [comment] 2020-12-03 00:04
This is a duplicate of #15349, there is some discussion over there. Closing out

**Closed by JustSlone** 2020-12-03 00:04 UTC
Labels: Area: Accessibility, Component: Dialog, Fluent UI react, Needs: Investigation
