### ISSUE TITLE
[Bug]: DataGrid using virtualization, header bottom border does not extend to full width

### ISSUE THREAD

**Issue by logicaloud** [microsoft/fluentui#28287] opened 2023-06-21 21:11 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
"@fluentui/react-components": "9.22.0"
Chrome / Edge latest
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/goofy-bessie-jxntv3?file=/example.tsx

## Actual Behavior

In a virtualized DataGrid the header row's bottom border does not extend to the full width of the grid.

![image](https://github.com/microsoft/fluentui/assets/47704763/23320845-aad0-4d6d-aab7-5079203f0f91)

This may be associated with #28027 and #27737.

## Expected Behavior

The header's bottom border should extend to the full width of the grid regardless of whether a vertical scrollbar is shown or not.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment] 2023-07-19 13:52
Closing as duplicate of #27570

**Closed by ling1726** 2023-07-19 13:52 UTC
Labels: Type: Bug :bug:, Fluent UI react-components (v9), Component: DataGrid

**Comment by Huahuafanta** [comment] 2023-07-27 02:33
> Closing as duplicate of #27570

Where is the fix? It seems the PR is draft PR......
