### ISSUE TITLE
@fluentui/web-components: Missing FASTElement definition

### ISSUE THREAD

**Issue by hrant-ian** [microsoft/fluentui#16734] opened 2021-02-01 18:29 UTC
### Environment Information

- **Package version(s)**:
```
"@angular/animations": "~11.0.9",
"@angular/cdk": "^11.0.4",
"@angular/common": "~11.0.9",
"@angular/compiler": "~11.0.9",
"@angular/core": "~11.0.9",
"@angular/forms": "~11.0.9",
"@angular/platform-browser": "~11.0.9",
"@angular/platform-browser-dynamic": "~11.0.9",
"@angular/router": "~11.0.9",
"@fluentui/web-components": "^0.11.0", 
"@microsoft/fast-components": "^1.15.0",
"@microsoft/fast-element": "^0.22.0",
"lodash": "^4.17.20",
"lodash-es": "^4.17.20",
```

- **Browser and OS versions**: Not relevant I think

### Describe the issue:

module.ts
```
import {CUSTOM_ELEMENTS_SCHEMA, NgModule} from '@angular/core';
@NgModule({
...
schemas: [CUSTOM_ELEMENTS_SCHEMA],
...
})
```

component.html
```
<fluent-design-system-provider use-defaults>
    <fluent-button>Button</fluent-button>
  </fluent-design-system-provider>
```

component.ts
```
import { FluentDesignSystemProvider, FluentButton } from '@fluentui/web-components';

FluentDesignSystemProvider;
FluentButton;
```

Leads to the following error:
```
Uncaught TypeError: styles.isAttachedTo is not a function
    at Controller.removeStyles (controller.js:140)
    at HTMLElement.noPaintChanged (index.js:40)
    at AttributeDefinition.setValue (attributes.js:92)
    at HTMLElement.set [as noPaint] (observable.js:109)
    at new FluentDesignSystemProvider (index.js:33)
    at HTMLDocument.createElement (<anonymous>:1:1536)
    at EmulatedEncapsulationDomRenderer2.createElement (platform-browser.js:661)
    at EmulatedEncapsulationDomRenderer2.createElement (platform-browser.js:794)
    at BaseAnimationRenderer.createElement (animations.js:248)
    at createElementNode (core.js:6813)
controller.js:351 Uncaught Error: Missing FASTElement definition.
    at Function.forCustomElement (controller.js:351)
    at new <anonymous> (fast-element.js:9)
    at new <anonymous> (button.form-associated.js:10)
    at new C (form-associated.js:19)
    at new FormAssociatedButton (button.form-associated.js:8)
    at new Button (button.js:14)
    at new FluentButton (index.js:16)
    at HTMLDocument.createElement (<anonymous>:1:1536)
    at EmulatedEncapsulationDomRenderer2.createElement (platform-browser.js:661)
    at EmulatedEncapsulationDomRenderer2.createElement (platform-browser.js:794)
```

#### Actual behavior:

See above

#### Expected behavior:

I am under the assumption that I don't need to use the fast-foundation packages, based on the installation guide (https://github.com/microsoft/fluentui/tree/master/packages/web-components#installation). 
I've installed the fast-foundation and fast-element packages as well, but this still leads to the above error. 
Using the samples provided in https://www.fast.design/docs/integrations/angular work fine.

Please clarify if it's possible to use the fluentui/web-components package directly.

**Comment by hrant-ian** [comment] 2021-02-01 18:49
Just a quick update: loading the module from the CDN actually works.
The components are now properly rendered.

**Comment by chrisdholt** [comment] 2021-02-17 23:21
Thanks @hrant-ian for this issue, sorry we're just seeing this now!

Per the linked FAST issue above, this is being caused by two versions of FAST element being loaded/included as the package version for fast-element is under 1.0.0. If version 0.13.1 of Fluent UI WC's is being included in your package-lock.json you'll want v0.22.2 of fast-element. We'll work to get this fixed with a major version in FAST which should resolve this issue down the road.

**Comment by chrisdholt** [comment] 2021-02-22 18:05
@hrant-ian let us know if you run into this again - for the most part, until `fast-element` is bumped to a major version, this issue can be solved by ensuring the same instance is installed for the entire project. If you're taking a dependency on `@fluentui/web-components`, using the same version in your package.json should prevent this from happening.

**Closed by chrisdholt** 2021-02-22 18:05 UTC
Labels: web-components
