### ISSUE TITLE
[Dialog] Narrator is not announcing the secondary button text in scan mode

### ISSUE THREAD

**Issue by Bhavana-Nimma** [microsoft/fluentui#22424] opened 2022-04-08 11:06 UTC
### Environment Information

- **Package version(s)**: 8.45.0
- **Browser and OS versions**: Microsoft Edge, Windows 10

### Describe the issue:

Narrator is not announcing the secondary button text of dialog in scan mode

### Please provide a reproduction of the issue in a codepen:

Open the dialog. Enter into the scan mode of narrator and navigate through down arrow. Observe that secondary button is read just as "button" and text on button is not announced.

Code pen link - https://codepen.io/bhavana-nimma/pen/JjMvEvo

#### Actual behavior:

Narrator is not announcing the secondary button text of dialog in scan mode

#### Expected behavior:

Narrator should announce the secondary button text of dialog when navigated through down arrow in scan mode

**Comment by micahgodbolt** [comment] 2022-04-11 17:03
duplicate of #22095

**Closed by micahgodbolt** 2022-04-11 17:03 UTC
Labels: Needs: Triage :mag:
