### ISSUE TITLE
DetailsList row remounts

### ISSUE THREAD

**Issue by Drustus** [microsoft/fluentui#18361] opened 2021-05-27 14:14 UTC
### Environment Information

- **Package version(s)**: "@fluentui/react": "8.14.0"

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/drustus/pen/zYZdMYr

#### Actual behavior:

When the list contains 10 elements, the element at position 9 starts to remount. In my code, the row contains a form so the remount causes information loss. The same occurs every 10 rows.

#### Expected behavior:

Not to remount the row.

**Comment by Drustus** [comment] 2021-06-01 09:46
Any update?

**Comment by gouttierre** [comment] 2021-06-28 13:04
@Drustus - thanks for filing this issue with us.
@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by ling1726** [comment] 2021-07-19 09:48
@Drustus thanks for the great repro! From what I can see, this happens for every page. If there are more than 20 rows, row 10 and row 20 will be remounted on each new row added. 

I tried doing a first investigation in to the `DetailsList` and couldn't mitigate this issue event overriding the `onRenderRow` callback with an explicit key. Marking as high priority to at least find the cause of this problem

**Comment by Drustus** [comment] 2021-09-15 08:49
Any update?

**Comment by bsunderhus** [comment] 2021-10-21 08:20
This seems to be a problem on reordering elements, if the new element is added at the end of the list this bug doesn't happen

**Comment by bsunderhus** [comment] 2021-10-21 09:51
Ok @Drustus , I think I've found the main cause for this behavior.

`DetailsList` component uses internally the `List` component, which by default separates elements per pages of 10 elements each:

```html
<div class="ms-List" role="presentation">
  <div role="presentation" class="ms-List-surface">
    <div class="ms-List-page" role="presentation">
      <div>0</div>
      <div>1</div>
      <div>2</div>
      <div>3</div>
      <div>4</div>
      <div>5</div>
      <div>6</div>
      <div>7</div>
      <div>8</div>
      <div>9</div>
    </div>
    <div class="ms-List-page" role="presentation">
      <div>0</div>
      <div>1</div>
      <div>2</div>
      <div>3</div>
      <div>4</div>
      <div>5</div>
      <div>6</div>
      <div>7</div>
      <div>8</div>
      <div>9</div>
    </div>
    <div class="ms-List-page" role="presentation">
      <div>0</div>
      <div>1</div>
      <div>2</div>
    </div>
  </div>
</div>
```

Every time a new element is added into the initial position of a list you're pretty much shifting the first element of every page to the previous one, making a re-render on every element addition on the 10th element as soon as there's more than 1 page, on the 10th and 20th when there's more than 2 pages, and etc,.

This is not an issue per se.... is just a really difficult to explain behavior 😅
If you have no interest in using the pages you could always simply use a single page instead of multiple by providing `listProps.getPageSpecification.itemCount`


```jsx
import * as React from 'react';
import { DetailsList } from '@fluentui/react/lib/DetailsList';

export const DetailsListRerenderProblemExample = () => {
  const [items, setItems] = React.useState([]);

  const addItem = () => {
    setItems([{ key: Date.now(), value: Math.random() }, ...items]);
  };


  return (
    <>
      <button onClick={addItem}>AddItem</button>
      <DetailsList
        items={items}
        columns={[{ key: 'column', fieldName: 'value', name: 'Column' }]}
        onRowWillUnmount={() => console.log('This will not be called anymore')}
        listProps={{ getPageSpecification: () => ({ itemCount: Number.MAX_VALUE }) }}
      />
    </>
  );
};

```

**Closed** 2021-10-21 09:52 UTC
Labels: Component: DetailsList, Needs: Investigation, Fluent UI react (v8)
