### ISSUE TITLE
TimePicker with timeRange ignores defaultValue

### ISSUE THREAD

**Issue by attiqeurrehman** [microsoft/fluentui#22177] opened 2022-03-22 09:47 UTC
### Environment Information

- **Package version(s)**: 8.62.1
- **Browser**:  Microsoft Edge Version 99.0.1150.46 (Official build) (64-bit) and Windows 10 Pro 
- **OS versions**:  Windows 10 Pro Version	21H2

### Please provide a reproduction of the bug in a codepen:
Following is the [CodeSandbox](https://codesandbox.io/s/boring-bird-0udsle?file=/src/TimePickerBasicExample.js) link to reproduce the issue. 

#### Actual behavior:

TimePicker ignores the defaultValue assigned and sets the first time from the range. I think it's being set in the code here:

```js
const generateBaseDate = (increments: number, timeRange: ITimeRange | undefined, baseDate: Date) => {
  if (timeRange) {
    const clampedTimeRange = clampTimeRange(timeRange);
    baseDate.setHours(clampedTimeRange.start);
  }

  return ceilMinuteToIncrement(baseDate, increments);
};
```
More specfically `baseDate.setHours(clampedTimeRange.start);` changes the default hour to the time range start value. 

#### Expected behavior:

TimePicker should honour the defaultValue. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by micahgodbolt** [comment] 2022-04-11 21:09
duplicate of #22122 which has a draft PR out for it.

**Closed by micahgodbolt** 2022-04-11 21:09 UTC
Labels: Needs: Triage :mag:
