### ISSUE TITLE
[Bug]: Inline Toaster behaves differently in overlay drawer

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#31312] opened 2024-05-08 21:03 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 51.85 GB / 63.57 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/6zd6sn?file=src%2Fexample.tsx

## Actual Behavior

When using inline toaster on overlay drawer, the toaster is covered by contents in the drawer.

This does not happen if we use **Nextjs** with **fluentui/react-components v9.47.1**, but starts to happen on **v9.49.1**. 

An example of using **Nextjs** with **fluentui/react-components v9.47.1**: 
https://stackblitz.com/edit/stackblitz-starters-ekzfbi?file=components%2FExample.tsx
But this had issue (https://github.com/microsoft/fluentui/issues/30942) of spread warning.
![image](https://github.com/microsoft/fluentui/assets/39588094/88504c1c-3ebd-4209-8ced-2241172526b5)

An exmaple of using  **Nextjs** with **fluentui/react-components v9.49.1**: 
https://stackblitz.com/edit/stackblitz-starters-ekzfbi?file=package.json

It is happening if we use **Vite** with **fluentui/react-components v9.47.1** and higher. 
Example: https://stackblitz.com/edit/6zd6sn?file=src%2Fexample.tsx

![image](https://github.com/microsoft/fluentui/assets/39588094/23003098-b2b9-4822-99d9-38d9a4d07dc6)

## Expected Behavior

Expect the toaster not being covered by the content.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment] 2024-05-09 07:55
@flora8984461  you meant ` with fluentui/react-components v4.47.1:` v9.47.1` ? there is no version 4 of react-components

**Comment by Hotell** [comment] 2024-05-09 07:56
might be issues in both Toaster/Drawer. can you please take a look @ling1726 @marcosmoura  ? ty

**Comment by flora8984461** [comment] 2024-05-09 16:09
> @flora8984461 you meant ` with fluentui/react-components v4.47.1:` v9.47.1` ? there is no version 4 of react-components

Sorry for the confusion! It was a typo, I just updated in the description. Yes, they should be 9.

**Comment by marcosmoura** [comment] 2024-05-14 16:43
The `Toaster` is inline and it'll be rendered where it is placed. Since the code in the example declares the `Toaster` inside the `Drawer` and not inside the `DrawerBody`, the toast might get covered by the content.

The issue is that a Toast doesn't have a `z-index` defined and the `DrawerBody` needs to define that in the CSS.

@flora8984461 a simple fix for the problem would be moving the Toaster to the DrawerBody instead:
```ts
/* from */
<OverlayDrawer open={open} onOpenChange={onOpenChange} position="end">
  <DrawerBody>{props.mid}</DrawerBody>
  {props.toaster}
</OverlayDrawer>

/* to */
<OverlayDrawer open={open} onOpenChange={onOpenChange} position="end">
  <DrawerBody>
    {props.mid}      
    {props.toaster}
  </DrawerBody>
</OverlayDrawer>
```

I'm closing the issue. If there are any other concerns, please feel free to reopen :)

**Closed by marcosmoura** 2024-05-14 16:43 UTC
Labels: Type: Bug :bug:, Needs: Attention, Fluent UI react-components (v9), Component: Drawer, Component: Toast
