### ISSUE TITLE
Provide a tree component in @fluentui/react

### ISSUE THREAD

**Issue by gyz0072004** [microsoft/fluentui#21620] opened 2022-02-07 03:44 UTC
### Environment Information

- **Package version(s)**: @fluentui/react 7.170.3
- **Browser and OS versions**: Edge 98 on Windows 10

### Describe the issue:

@fluentui/react doesn't have a tree component, which is quite commonly used and available in other component libraries:
Material UI: https://mui.com/components/tree-view/
Ant Design: https://ant.design/components/tree/

#### Actual behavior:

No tree component, need to use the Nav component to simulate

#### Expected behavior:

Provide a tree component, and a tree select component if possible.

### If applicable, please provide a codepen repro:

N/A

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: N/A

**Comment by gyz0072004** [comment] 2022-02-07 04:32
After raising this issue, I found a recently closed issue on tree component #7597 . I believe this is quite a common need.

**Comment by micahgodbolt** [comment] 2022-03-02 20:01
duplicate of #7597

**Closed by micahgodbolt** 2022-03-02 20:01 UTC
Labels: Type: Feature, Resolution: Duplicate
