### ISSUE TITLE
Make ScrollablePane work with only maxHeight from parent element

### ISSUE THREAD

**Issue by artxach** [microsoft/fluentui#7909] opened 2019-02-06 12:24 UTC
### Environment Information 
 
- __Package version(s)__: 5.131.0
- __Browser and OS versions__: Windows 10, Edge

#### Actual behavior:
```
<div id='myGeneralContainer'>
 <div style={{position:'relative', maxHeight:'300px'}>
   <ScrollablePane>
      <DetailsList .../>
   </ScrollablePane>
 </div>
<div>
```
 The details list is not rendered, and actual height of scrollable pane is 0. Nothing is rendered.
#### Expected behavior:
 The details list should take its content height automatically, and if it exceeds 300px only then the scrollbars should appear. 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: High 
 
Products/sites affected: (if applicable)

**Comment by kenotron** [comment] 2019-02-06 17:20
You're actually describing the intended behavior of the `ScrollablePane` itself. Rather than taking the height of the content and using that to decide the height. It uses the height of the parent to determine the height (using the `position:absolute;top:0;left:0;right:0;bottom:0` trick). I've made a really simplified version of this scrollable pane and what it actually uses for styling:

https://codepen.io/anon/pen/JxOYZj

This is actually by design. In your scenario, probably best is to use a `min-height` or specify a `height` to "reserve" space for `ScrollablePane` to do its job.

Feel free to fork and modify that codepen to describe what you are expecting. Thanks!

**Comment by artxach** [comment] 2019-02-12 08:59
hi @kenotron . Thanks for the response. I understand the styling of ScrollablePane.
In my case, i don't know the height, and if i specify min-height, the scrollablepane will always take min-height and will not expand to its actual height. Even in your example of codepen, the content is NOT VISIBLE and the height of ScrollablePane is 0. 
![image](https://user-images.githubusercontent.com/5441923/52623574-15767d80-2ec6-11e9-8d92-89e475ec75f6.png)

**Comment by kenotron** [comment] 2019-02-16 01:32
I'm going to punt this to feature request at this point.

**Comment by artxach** [comment] 2019-03-29 10:31
hi. any updates on this?

**Comment by JustSlone** [comment] 2021-01-02 23:58
Given this is the intended behavior and we don't have current plans to make updates to DetailsList I'm going to close this out. If others hit this issue and have more data on why this should get fixed, please feel free to reopen or add additional details

**Closed by JustSlone** 2021-01-02 23:58 UTC
Labels: Component: ScrollablePane, Status: Not on Roadmap, Type: Feature
