### ISSUE TITLE
React Stack component documentation code sample intellisense cannot resolve styles/tokens

### ISSUE THREAD

**Issue by cthlo** [microsoft/fluentui#21617] opened 2022-02-04 23:19 UTC
### Environment Information

- **Package version(s)**: 8.52.3
- **Browser and OS versions**: irrelevant

#### Actual behavior:

https://developer.microsoft.com/en-us/fluentui#/controls/web/stack
![image](https://user-images.githubusercontent.com/5878412/152615533-d7f5ecc3-5065-466f-8e64-a5355ce3b438.png)

p.s. I think I have also encountered this during development on VS code, but eventually it resolved itself somehow.

#### Expected behavior:
Attributes in the sample code sections are resolved successfully.

### Priorities and help requested:

Are you willing to submit a PR to fix? No :(

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment] 2022-04-09 02:06
This is caused by #15308. Closing as a duplicate.

**Closed by ecraig12345** 2022-04-09 02:06 UTC
Labels: Needs: Triage :mag:
