### ISSUE TITLE
yarn build not working with node@13

### ISSUE THREAD

**Issue by jacargentina** [microsoft/fluentui#12655] opened 2020-04-11 15:26 UTC
Just cloned the repo, `yarn` then `yarn build`; using macOS Catalina, node 13.12.0, yarn 1.22.4

Got this:

<img width="1536" alt="Captura de Pantalla 2020-04-11 a la(s) 12 25 18" src="https://user-images.githubusercontent.com/517228/79047832-92e36e00-7bef-11ea-92f8-a0b49498c7ea.png">

**Comment by joschect** [comment] 2020-04-13 23:49
@jacargentina thanks for the submission! I am unable to reproduce this. I did both a clean (git clean -fdx) and a fresh clone and both of those built fine when I used yarn && yarn build. What version of npm and yarn do you have installed?

**Comment by jacargentina** [comment] 2020-04-14 14:14
@joschect i did:
- git pull (to update to latest sources
- git clean -fdx
- yarn
- yarn build

Same error; this time copy/paste here: 

```zsh
javiercastro@MacBook-Pro fluentui % yarn build
yarn run v1.22.4
$ lerna run build --stream
lerna notice cli v3.15.0
lerna info Executing command in 67 packages: "yarn run build"
@uifabric/build: $ node ./just-scripts.js no-op
@fluentui/digest: $ just-scripts build
@fluentui/docs-components: $ gulp bundle:package:no-umd
@fluentui/ability-attributes: $ npm run schema && gulp bundle:package:no-umd
@fluentui/ability-attributes: npm WARN lifecycle The node binary used for scripts is /var/folders/p8/jp8x98dd36j1nnc53zvpykp40000gn/T/yarn--1586873172087-0.927302978199348/node but npm is using /usr/local/Cellar/node/13.12.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
@fluentui/ability-attributes: > @fluentui/ability-attributes@0.47.0 schema /Users/javiercastro/git/fluentui/packages/fluentui/ability-attributes
@fluentui/ability-attributes: > allyschema -c "process.env.NODE_ENV !== 'production'" schema.json > ./src/schema.ts
@fluentui/docs-components: [11:06:13] Requiring external module @uifabric/build/babel/register
@fluentui/digest: [11:06:13 AM] ■ started 'build'
@fluentui/digest: [11:06:13 AM] ■ started 'ts'
@fluentui/digest: [11:06:13 AM] ■ started 'ts:esm'
@fluentui/digest: [11:06:13 AM] ■ Running /Users/javiercastro/git/fluentui/node_modules/typescript/lib/tsc.js with /Users/javiercastro/git/fluentui/packages/fluentui/digest/tsconfig.json
@fluentui/digest: [11:06:13 AM] ■ Executing: "/usr/local/Cellar/node/13.12.0/bin/node" "/Users/javiercastro/git/fluentui/node_modules/typescript/lib/tsc.js" --module esnext --outDir lib --project "/Users/javiercastro/git/fluentui/packages/fluentui/digest/tsconfig.json"
@fluentui/ability-attributes: [11:06:14] Requiring external module @uifabric/build/babel/register
@uifabric/build: [11:06:14 AM] ■ started 'no-op'
@uifabric/build: [11:06:14 AM] ■ finished 'no-op' in 0.02s
@fluentui/docs-components: internal/modules/cjs/loader.js:524
@fluentui/docs-components:   throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
@fluentui/docs-components:   ^
@fluentui/docs-components: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/javiercastro/git/fluentui/node_modules/@babel/helper-compilation-targets/package.json
@fluentui/docs-components:     at applyExports (internal/modules/cjs/loader.js:524:9)
@fluentui/docs-components:     at resolveExports (internal/modules/cjs/loader.js:541:12)
@fluentui/docs-components:     at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
@fluentui/docs-components:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
@fluentui/docs-components:     at Function.Module._load (internal/modules/cjs/loader.js:859:27)
@fluentui/docs-components:     at Module.require (internal/modules/cjs/loader.js:1036:19)
@fluentui/docs-components:     at require (internal/modules/cjs/helpers.js:72:18)
@fluentui/docs-components:     at Object.<anonymous> (/Users/javiercastro/git/fluentui/node_modules/@babel/preset-env/lib/debug.js:8:33)
@fluentui/docs-components:     at Module._compile (internal/modules/cjs/loader.js:1147:30)
@fluentui/docs-components:     at Module._compile (/Users/javiercastro/git/fluentui/node_modules/pirates/lib/index.js:99:24) {
@fluentui/docs-components:   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
@fluentui/docs-components: }
@fluentui/docs-components: error Command failed with exit code 1.
@fluentui/docs-components: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@fluentui/docs-components'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Versions**

```zsh
javiercastro@MacBook-Pro fluentui % npm -v
6.14.4
javiercastro@MacBook-Pro fluentui % yarn -v
1.22.4
javiercastro@MacBook-Pro fluentui % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287
javiercastro@MacBook-Pro fluentui % node -v
v13.12.0
```

**Comment by jacargentina** [comment] 2020-04-14 14:20
I've done a first search on the error and found this https://github.com/babel/babel/issues/11216

Maybe i'm using a very newer node?

**Comment by joschect** [comment] 2020-04-16 01:07
@jacargentina Thanks for doing that extra research, I'm glad you got things working. It looks like that was specifically a problem in node, rather than a problem with fabric and that node released an updated version that fixes this problem.

**Comment by jacargentina** [comment] 2020-04-16 14:46
@joschect Nope, I was on Node v13.12.0, and it seems that a fix is pending here https://github.com/nodejs/node/issues/32107 BUT  maybe this comment is another solution (upgrading babel) https://github.com/nodejs/node/issues/32107#issuecomment-595652358

**Comment by ecraig12345** [comment] 2021-01-18 17:53
Closing this since Node 13 is now out of support. If anyone sees similar issues with Node 14, feel free to file a new issue.

**Closed by ecraig12345** 2021-01-18 17:53 UTC
Labels: Area: Build System, Resolution: External
