### ISSUE TITLE
Tooltips are not accessible which are present in the drop-down menu items while using keyboard.

### ISSUE THREAD

**Issue by msftedad** [microsoft/fluentui#30842] opened 2024-03-21 10:52 UTC
### Library

"office-ui-fabric-react": "6.198.0",

### System Info

```shell
Environment (OS, Application, Versions): 

Windows 11
Edge version: 122.0.2365.80 (Official build) (64-bit)
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/gracious-darwin-lj3zgw?file=%2fsrc%2findex.js&from-embed=

## Repro Steps

1.Open this URL "[gracious-darwin-lj3zgw - CodeSandbox](https://codesandbox.io/p/sandbox/gracious-darwin-lj3zgw?file=%2fsrc%2findex.js&from-embed=)"
2.Tab till "preview" tab.
3.Tab till Example component dropdown.
4.Observe that "Example Component" menu items "tooltips" is not accessible while using keyboard.

## Actual Behavior
Tooltips are not accessible which are present in the drop-down menu items while using keyboard.

## Expected Behavior
Tooltips should be accessible which are present in the drop-down menu items while using keyboard.

## Attachment

https://github.com/microsoft/fluentui/assets/93735775/401c9978-b0bc-4005-91f3-b8240b980bdd

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment] 2024-03-21 22:39
You are still using OUFR v6 in this example. Have you tested in v8? Our support for N-2 versions is very limited.

**Comment by msftedad** [comment] 2024-03-26 04:39
Hi @micahgodbolt, we are following up with PO team. Once we receive information we will promptly update you. Thanks

**Comment by Leah-Xia-Microsoft** [comment] 2024-08-09 05:17
Hi @micahgodbolt  and @msftedad,
We're using v8 and facing a similar issue.
If any of the parent components are focusable, tooltip will not be displayed when navigating to the element using keyboard.
Created a sample here: https://codepen.io/Leah-Xia-Microsoft/pen/poXrZYV?editors=0010
If we comment out the `data-is-focusable` on line 91 in the sample, then tooltip will be displayed using keyboard navigation.
Similarly, the FluentUI Persona component has the same issue since it's using TooltipHost under the hood: https://codepen.io/Leah-Xia-Microsoft/pen/VwJzBRL
I saw there's a workaround provided in another issue: https://github.com/microsoft/fluentui/issues/31980, which is manually display tooltip onFocus. However in the use case above, we don't have the onFocus and onBlur event.

**Comment by smhigley** [comment] 2024-09-30 20:27
@Leah-Xia-Microsoft the issue you're running into isn't actually with the Tooltip control; the problem is that you're setting focus to the `<li>` element, and the inner `<button>` with the tooltip never actually receives keyboard focus. The `data-is-focusable` attribute is used by the wrapping `FocusZone` to determine which element to set focus to as you arrow between items.

To make this work, you must have the element that receives keyboard focus be wrapped by the TooltipHost and `aria-describedby` must also be set on that element. As a side note, it is also an antipattern to have nested interactives that perform the same action (the list item and button in this case).

Hope that helps! I'm closing this issue since it's an authoring issue and not a bug in the Fluent component.

**Closed by smhigley** 2024-09-30 20:27 UTC
Labels: Component: Tooltip, Needs: Attention, Issue Pinged, Fluent UI react (v8), Resolution: Won't Do
