### ISSUE TITLE
Modal/Dialog with isBlocking=true can be dismissed with escape 

### ISSUE THREAD

**Issue by wagnergerald** [microsoft/fluentui#14438] opened 2020-08-10 08:48 UTC
### Environment Information

- **Package version(s)**:  7.  (not sure how to extract exact version from Codepen)
- **Browser and OS versions**: Chrome  84.0.4147.105 macOS

### Codepen:

https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:

- Open Dialog
- Click on Dialog
- Press escape

**Dialog gets dismissed**

#### Expected behavior:

- Open Dialog
- Click on Dialog
- Press escape

**Comment by paulgildea** [comment] 2020-08-10 16:00
Thanks for the feedback @wagnergerald !

Looking at the documentation: https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog the `isBlocking` prop is obsolete. With a recommendation to pass through the `modalProps` prop.

The codepen appears to be empty so if you could provide an updated repro that would help us determine if this is an issue.

Thanks!

**Comment by wagnergerald** [comment] 2020-08-11 08:13
Thank you for your feedback @paulgildea.

Sorry, I posted the wrong link, this is the correct one. 
https://codepen.io/wagnergerald/pen/PoNqagr

The `isBlocking` prop is passed via the `modalProps` as you mentioned.

**Comment by khmakoto** [comment] 2020-08-11 18:30
Hi @wagnergerald this is by design. The `isBlocking` prop only disallows light dismiss by clicking outside the `Dialog` on the overlay as clearly stated in our documentation. It does not prevent dismissing via hitting the escape key nor was it ever intended to. Given this, I'll be resolving this issue as `Resolution: By Design`. Please let us know if there is anything else we can help you with!

**Closed** 2020-08-15 00:00 UTC
Labels: Component: Dialog, Component: Modal, Fluent UI react, Needs: Author Feedback, Resolution: By Design
