### ISSUE TITLE
[Bug]: Double scroller is seen in the people picker while adding recipient.

### ISSUE THREAD

**Issue by sahilkumarmaths** [microsoft/fluentui#29770] opened 2023-11-06 21:25 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.23521
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz
    Memory: 14.94 GB / 31.92 GB
  Browsers:
    Chrome: 116.0.5845.111
    Edge: Spartan (44.23521.1000.0), Chromium (116.0.1938.62), ChromiumDev (118.0.2048.1)
    Internet Explorer: 11.0.23521.1000
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/ettqpwrw-the-encoder/pen/jOdrgBg

## Actual Behavior
Double scroller is seen in the people picker while adding recipient.
![image](https://github.com/microsoft/fluentui/assets/1578304/13322c05-ab3c-4567-a239-6599b4bd7e64)

## Expected Behavior
Single scroller is seen in the people picker while adding recipient.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by patmoo** [comment] 2023-12-15 01:19
@behowell, took a quick look at this. I think it can be resolved by adding the following to both `calloutMain` and suggestions `root` styles properties: 

``` 
display: 'flex',
flexDirection: 'column',
flex: '1 1 auto',
overflow: 'hidden',
```

I have created a new codepen to illustrate the solution. Please let me know if this solution is sufficient, and if so when it might be consumable. Thanks 

https://codepen.io/patmoo/pen/ExrBgVR

**Comment by behowell** [comment] 2024-03-19 22:59
Hi @patmoo, this appears to be the result of using `directionalHintFixed: true` in `pickerCalloutProps`, which you're doing on line 119 of your codepen repro. Removing that line makes the double scrollbar go away. This doesn't repro on the documentation site, which doesn't set that prop: https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker

I'd recommend removing `directionalHintFixed: true` in your implementation. It's unlikely that we'll be able to change the behavior of `directionalHintFixed` to make it work in this case, since that will almost definitely cause a regression for other uses of that prop.

**Closed** 2024-03-27 06:08 UTC
Labels: Status: No Recent Activity, Needs: Author Feedback, Fluent UI react (v8)
