### ISSUE TITLE
The list of tree items SHOULD NOT be shown up before the treeview is displayed

### ISSUE THREAD

**Issue by sp-yang** [microsoft/fluentui#21522] opened 2022-02-01 21:40 UTC
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

Please refer to the **example** at https://docs.microsoft.com/en-us/fluent-ui/web-components/components/tree-view.

#### Actual behavior:

When the bottom right button "rerun" is clicked, a list of the items are quickly shown up first , and then the final treeview is displayed properly. This rendering behavior is not acceptable.

#### Expected behavior:

The list of the items SHOULD NOT be shown up before the treeview is displayed.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority: (High)

Products/sites affected: (if applicable)
All sites using fluent-tree-view component.

**Comment by paulgildea** [comment] 2022-03-09 07:27
cc: @chrisdholt

**Comment by chrisdholt** [comment] 2022-03-09 07:30
Thanks @sp-yang for filing this and for your patience, just seeing this now. I see this behavior on the example site, but I don't see it locally. I'm going to try and reproduce this bare bones in a few ways to see if this is just an instance of poor examples.

**Comment by chrisdholt** [comment] 2022-03-09 09:00
OK, I tried to repro this outside the example and wasn't able to do so. In terms of rendering performance, I put together the most minimal example of a tree view I could think of to illustrate rendering performance. You can see it here: https://github.com/chrisdholt/tree-view-rendering-repro. I'll leave the repo up and available for a reasonable amount of time for you to confirm.

I did notice that the closing tag seems to be broken, so I think that is most likely the underlying cause here. Thanks!

**Comment by sp-yang** [comment] 2022-03-09 19:01
@chrisdholt Thanks for getting back to me.
I tried to **refresh** the index.html file downloaded from your repo and still get the same behavior as shown below:
Firstly:
![refresh-1](https://user-images.githubusercontent.com/33505987/157512269-4045f053-0169-4003-9290-e8dc4215e24b.jpg)

Finally:
![refresh-2](https://user-images.githubusercontent.com/33505987/157512341-2b6972a3-dae5-40ab-a9eb-3107a25636ca.jpg)

**Comment by chrisdholt** [comment] 2022-03-23 21:19
@sp-yang I was able to repro the text showing up, which appears to primarily be due to the fact that it exists in the DOM prior to elements upgrading. Check out the update made here: https://github.com/chrisdholt/tree-view-rendering-repro/blob/0692967ce7de73b7f7a866420566ff23e67816f4/styles.css#L10

This appears to be content in the light DOM rendering prior to the elements being upgraded. A simple addition on any app or website should address the concern. I don't repro with the change above.

**Comment by sp-yang** [comment] 2022-03-23 21:32
@chrisdholt Thank you, the update fixes the issue.

**Comment by chrisdholt** [comment] 2022-03-23 21:48
> @chrisdholt Thank you, the update fixes the issue.

Sounds good - closing this out!

**Closed by chrisdholt** 2022-03-23 21:48 UTC
Labels: Needs: Attention, Issue Pinged, web-components, Component: Tree
