### ISSUE TITLE
Form submission succeeds when Dropdown required = true but no option is selected

### ISSUE THREAD

**Issue by isabelacmor** [microsoft/fluentui#14501] opened 2020-08-13 01:33 UTC
### Environment Information

- **Package version(s)**: 7.111.0

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/isabelacmor/pen/yLOeJQX

#### Actual behavior:

When the Dropdown is in a form and given the required prop, form submission should fail if there's no item selected. This is similar to how TextField works when in a form and required is set.

#### Expected behavior:

Instead, the form submission succeeds as if the form were valid, even when no option has been selected from the Dropdown.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Blocking

Products/sites affected: all forms using Dropdowns

**Comment by khmakoto** [comment] 2020-08-13 03:45
Duplicate of #14403.

**Closed** 2020-08-13 03:45 UTC
Labels: Resolution: Duplicate
