### ISSUE TITLE
Tooltip reappears without hover after tab switch

### ISSUE THREAD

**Issue by joshjcarrier** [microsoft/fluentui#13541] opened 2020-06-10 00:22 UTC
### Environment Information

- **Package version(s)**: 6.164.8/office-ui-fabric-react.min.js
- **Browser and OS versions**: Microsoft Edge (Chromium) Version 84.0.516.1 (Official build) Dev (64-bit)

### Please provide a reproduction of the bug in a codepen:

1. Click on [Hover over me] button on [Fluent UI docs](https://developer.microsoft.com/en-us/fluentui/#/controls/web/tooltip). Button gains focus but tooltip dismisses when mouse is moved away.
2. Click to switch to another tab
3. Click to switch back to docs tab

![fluent tooltip tab](https://user-images.githubusercontent.com/526858/84213382-5a3c0580-aa75-11ea-9c20-31df7d2c2149.gif)

#### Actual behavior:

Tooltip appears without mouse hover.

#### Expected behavior:

Tooltip should not appear.

**Comment by BrendanMcK** [comment] 2020-06-11 20:02
Hi @jdhuntington  - I'm not sure it's reasonable to say that this is *By design*. The fact that this behavior can be explained in terms of the current implementation doesn't mean that this is the _desired behavior_. 

> forcefully defocus the button when the page itself loses focus

Hard no on this option, that would introduce major accessibility issues.

My take on this is that expected behavior is that the tooltip appears only when focus initially moves into that element while on the same page. As keyboard user, I don't expect switching tabs to be considered equivalent to tabbing into that element.

**Comment by micahgodbolt** [comment] 2020-06-11 20:38
@BrendanMcK do you know if it's possible for the browser to differentiate a tab to focus vs 'browser tab' to focus? If we can test and identify the source, then we can certainly look at changing it.

**Comment by BrendanMcK** [comment] 2020-06-11 22:25
One of our focus utilities needed to ignore `blur` events due to tabs becoming inactive - we only want *real* blurs. In that specific case, the tell was that despite the element getting a `blur`, it was still returned as `document.activeElement`. Not sure if that would work here, or if it can be used to do similar to determine whether a focus is a real focus or a 'restore' focus.

**Comment by joshjcarrier** [comment] 2020-06-12 00:22
Looks like [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) determines if the tab gained/lost focus.

Alternatively, could `onFocusCapture` determine the source like [react-northstar/Tooltip?](https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar/src/components/Tooltip/Tooltip.tsx#L204)

**Comment by joshjcarrier** [comment] 2020-06-12 18:58
Here's a codepen to help demo @BrendanMcK 's suggested use of `document.activeElement`

[code](https://codepen.io/joshjcarrier/pen/PoZNGgM) | [example](https://cdpn.io/joshjcarrier/debug/PoZNGgM/PNAvYKaZxygr)


![fluent tooltip tab activeelement](https://user-images.githubusercontent.com/526858/84536762-5beb1080-aca3-11ea-86a0-9306fd437bd3.gif)

**Comment by micahgodbolt** [comment] 2020-06-12 19:35
@joshjcarrier haven't dug into it too much, but is your suggestion something we can do at the control level, or is this an app level change? If it's at the control level I can open the issue back up.

**Comment by joshjcarrier** [comment] 2020-06-12 19:43
I believe TooltipHost can handle it on its [onFocusCapture](https://github.com/microsoft/fluentui/blob/a8748bcd3616a3a7c453f5bae0960f8efb82a19a/packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.base.tsx#L96) handler.

**Comment by joshjcarrier** [comment] 2020-06-16 18:10
@micahgodbolt did we intend for the bot to close this?

**Comment by micahgodbolt** [comment] 2020-06-16 18:16
The 'by design' tag told the bot to close it. I removed the tag.

**Comment by rachitpuri95** [comment] 2021-04-05 20:39
is there a workaround for this?

**Comment by sivapalaniappan** [comment] 2021-07-02 22:27
I am seeing this as well. Is there a fix or workaround for this one ?

**Closed** 2021-07-14 23:17 UTC
Labels: Component: Tooltip, Status: In PR
