### ISSUE TITLE
TooltipHost component immediately dismisses tooltip on hover / focus

### ISSUE THREAD

**Issue by DaniloAG** [microsoft/fluentui#16398] opened 2021-01-06 19:53 UTC
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: Edge - Version 87.0.664.66 (Official build) (64-bit)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/daniloag/pen/yLaEVmN

  * Open the codepen and set your focus on the canvas that rendered the two buttons.
  * Try hovering over the first button (You can sometimes repro this with the second button).
  * Note: This seems to only happen on Chromium based browsers.

#### Actual behavior:

Tooltip immediately closes.

![TooltipHostComponent](https://user-images.githubusercontent.com/9058682/103813877-a18f7200-5015-11eb-9c86-9119b4c653e2.gif)

#### Expected behavior:

Tooltip should be rendered.

**Comment by layershifter** [comment] 2021-01-14 15:07
@DaniloAG Thanks for reporting, I was able to repro it in Chrome 87, looking into it 🔍

**Comment by layershifter** [comment] 2021-01-18 11:01
The issue is present and might be related to positioning logic... I have ported an example to CodeSandbox: https://codesandbox.io/s/fluent-ui-issue-16398-2s8gc

---

I placed a breakpoint in debugger on `_toggleTooltip` method, its call comes from `_onTooltipMouseLeave`:

![A callstack of _toggleTooltip](https://user-images.githubusercontent.com/14183168/104906296-cd024d00-5983-11eb-9aee-bf37c8d75df7.png)

An interesting thing in this `MouseEvent` is the value of `currentTarget`:
```tsx
currentTarget: div#tooltip0.ms-Tooltip-content.content-52
```

---

Then I modified CodeSandbox to ensure that it's a positioning issue (https://codesandbox.io/s/fluent-ui-issue-16398-forked-w48r6), I simply added some `margin` to a container, with this tweak a tooltip appears properly.

To confirm it finally I tried to set `pointerEvents: none` and it works: https://codesandbox.io/s/fluent-ui-issue-16398-forked-80szd?file=/src/App.js.

---

@joschect can you please check this problem? It feels that at some point `CalloutContent` appears under a cursor and then moves away.

**Comment by layershifter** [comment] 2021-01-18 11:04
> When the callout is "hidden" it sets OFF_SCREEN_STYLE which sets the opacity, but the callout can still occlude the targetElement. I'm adding pointerEvents: none to the styling that is applied in this case so that it will not fire mouse events

It also seems that it might be fixed by #16454.

**Comment by layershifter** [comment] 2021-01-20 13:46
I was indeed fixed by #16454 🎉

**Closed by layershifter** 2021-01-20 13:46 UTC
Labels: Component: Callout, Type: Bug :bug:
