### ISSUE TITLE
[Bug]: MessageBar icon props does not allow for width, height, line-height, or color overrides

### ISSUE THREAD

**Issue by tronguye** [microsoft/fluentui#23763] opened 2022-06-29 00:20 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz      
    Memory: 22.86 GB / 63.59 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.44)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codepen.io/tronguye/pen/JjLjpaL

### Bug Description

When passing font size, height, width, line height, or color to dismissIconProps.styles:

## Actual Behavior
1. Icon is black, with 10px font size, width, height, and line height

## Expected Behavior
1. The styles passed to the icon styles prop is preferred

Workaround: add !important to take higher precedence over the underlying icon button selector. Not ideal, however

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment] 2022-08-08 10:46
@tronguye - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@layershifter - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thanks

**Comment by layershifter** [comment] 2022-08-09 11:25
@tronguye this is how styling done in this component. To override this styles without `!important` you can do following:

```tsx
function App() {
  return (
    <MessageBar
      dismissIconProps={{
        iconName: "Add"
      }}
      styles={{
        dismissal: {
          "& .ms-Button-icon": {
            fontSize: "20px",
            height: "20px",
            width: "20px",
            color: "blue"
          }
        }
      }}
    />
  );
}
```

https://codesandbox.io/s/sad-wright-0xjsfl?file=/src/App.tsx:433-882

**Comment by tronguye** [comment] 2022-08-09 17:14
Thanks Oleksander!

Ideally the consumers of this component don't need to know about the underlying class `.ms-Button-icon` which could be a brittle class name not guaranteed by the public/semver contract of the package

It may be best for that class name / property to be documented at least!

**Comment by tronguye** [comment] 2022-08-09 17:23
It also looks like `dismissal` does not exist on the interface definition of `IIconProps`, so I'm getting a TS build error. Investigating further!

**Comment by layershifter** [comment] 2022-08-12 09:33
@tronguye grad that have figure out the problem.

> Ideally the consumers of this component don't need to know about the underlying class `.ms-Button-icon` which could be a brittle class name not guaranteed by the public/semver contract of the package. I'm a little surprised the styling of the dismiss icon does not live in `dismissIconProps`

Unfortunately I don't know the motivation behind that styling, but there is probably a reason. We also can't do much with it as changing selectors or removing them will be a breaking change.

I briefly checked other issues/documentation and I don't see this being documented anywhere (_please correct me if a wrong_). While it might be unobvious styles can be inspected in Chrome/Edge Devtools to code:

https://github.com/microsoft/fluentui/blob/0fa48e25fd9b173a8574c3ad3421979e627a145d/packages/react/src/components/MessageBar/MessageBar.styles.ts#L108

---

FYI: As it's not a bug I am going to close the issue.

**Closed by layershifter** 2022-08-12 09:33 UTC
Labels: Component: MessageBar, Area: Icons, Needs: Investigation, Fluent UI react (v8)
