### ISSUE TITLE
[fluentui][Modal] plotly.js scrollbar inside Modal doesn't work with mouse.

### ISSUE THREAD

**Issue by chnldw** [microsoft/fluentui#20009] opened 2021-09-28 18:08 UTC
### Environment Information

- **Package version(s)**: 8, latest.
- **Browser and OS versions**:  Win10 21H1, Chrome Version 94.0.4606.61 (Official Build) (64-bit) 

### Please provide a reproduction of the bug in a codepen:
It seems drag event handler is broken within `Modal` or `Panel`.
Similar issue for monaco editor: https://github.com/microsoft/fluentui/issues/19299

Here's a repro:
https://codepen.io/chnldw/pen/jOwXjzG

#### Actual behavior:
Use mouse to drag the scrollbar in plotly.js chart inside of Modal doesn't work, but keyboard works well.

#### Expected behavior:
Use mouse to drag the scrollbar in plotly.js chart inside of Modal should work

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: https://ml.azure.com/

**Comment by AlexandreGarino** [comment] 2021-10-07 16:57
I confirm that I can reproduce this issue w/ a Panel.

**Comment by cartacioS** [comment] 2021-11-02 21:37
Gentle ping on this, this issue is keeping one of our customer tickets open. Thanks!

**Comment by dehoward** [comment] 2021-12-01 23:31
@gouttierre this is a regression as we've seen this functionality working before in our product (Azure IoT Central, we use the Panel).

I filed [this bug](https://github.com/microsoft/monaco-editor/issues/2799) (and then closed it) on the `monaco-editor` team and some context was provided in that the `mousemove` events are not reaching the `document`.

any idea on when this could get fixed?

**Comment by AlexandreGarino** [comment] 2021-12-06 09:56
I guess this issue is related to this breaking change: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation

**Comment by Noodle-Bug** [comment] 2021-12-08 15:43
Can confirm multiple libraries are having click + drag issues inside of Panels / Modals as well.

https://codesandbox.io/s/admiring-waterfall-xx0kl?file=/src/App.js

**Comment by spmonahan** [comment] 2022-01-26 00:13
This is happening because `Layer` prevents events that propagate from within its content from bubbling to outside. Both `Modal` and `Panel` render `Layer` internally. To disable this behavior set `eventBubblingEnabled` to `true` ([docs link](https://developer.microsoft.com/en-us/fluentui#/controls/web/layer#implementation)).

@chnldw I've updated your sample to work here: https://codepen.io/seanms/pen/XWzWzLx
@Noodle-Bug I've updated your sample to work here: https://codesandbox.io/s/panel-eventbubblingenabled-q124g?file=/src/App.js

This issue appears to be related to [changes to event delegation in React 17](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation). In the case of `rc-slider` in the Codesandbox example the issue is that it attaches native DOM events to `document` to implement the click-n-drag slide behavior but because of the React 17 event delegation changes `Layer`'s behavior now prevents these events from bubbling up to `document`. I didn't look at the implementations of the other affected components but I imagine they are similar.

**Closed** 2022-02-02 05:00 UTC
Labels: Status: No Recent Activity, Component: Panel, Needs: Author Feedback, Component: Modal, Component: Layer, Fluent UI react (v8), React 17
