### ISSUE TITLE
Label for SwatchColorPicker

### ISSUE THREAD

**Issue by LukeOwlclaw** [microsoft/fluentui#11480] opened 2019-12-16 11:23 UTC
#### Describe the feature that you would like added

Descriptive ``Label`` property for ``SwatchColorPicker``, just like [ChoiceGroup has a descriptive label](https://developer.microsoft.com/en-us/fabric#/controls/web/choicegroup#IChoiceGroupProps).

#### What component or utility would this be added to

[SwatchColorPicker](https://developer.microsoft.com/en-us/fabric#/controls/web/swatchcolorpicker)

**Comment by micahgodbolt** [comment] 2019-12-18 19:29
You should be able to use our Label control and `htmlFor="pickerID"` and get the same thing without a change to the interface.

**Comment by ecraig12345** [comment] 2019-12-21 02:47
Looked at our design toolkits and SwatchColorPicker doesn't currently have a label. So we'd need to talk with design before adding one.

**Comment by ecraig12345** [comment] 2020-01-04 03:57
Another consideration related to this is that even though I fixed application of the ID in #11526, I'm not sure that alone will be adequate for getting a label associated with the region in a manner useful to screen readers, since a table generally isn't [labelable](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Form_labelable). Not the specific problem you originally called out, but something important to consider.

**Comment by khmakoto** [comment] 2020-01-13 23:06
I think this is a duplicate of #9935. @LukeOwlclaw, would you be fine with closing this issue in favor of that one?

**Comment by JustSlone** [comment] 2021-01-20 21:56
Marking this not on roadmap. We are not working on swatch color picker right now, but may consider this in the future.

**Closed** 2021-06-20 00:00 UTC
Labels: Component: SwatchColorPicker, Needs: Design, Resolution: Soft Close, Status: Not on Roadmap, Type: Feature
