### ISSUE TITLE
[Accessibility] Narrator is not reading as ‘Sorting button’ when navigated to column header of the DetailsList control

### ISSUE THREAD

**Issue by v-sagsah** [microsoft/fluentui#12894] opened 2020-04-28 06:19 UTC
**Browser Details:**
**OS:** Windows 10 (Version 10.0.18363 Build 18363)
Microsoft Edge Beta Version 81.0.416.50 (Official build) beta (64-bit)
Google Chrome Version 81.0.4044.113 (Official Build) (64-bit)
**Screen Reader:** Narrator and NVDA

**Note:** 
Similar issue has been observed in Chrome with NVDA

**Repro Steps :**

1. Start Narrator. Hit the URL "https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist".
2. Tab till any column header in the table in _**‘DetailsList with 500 documents, sorting, filtering, marquee selection, justified columns’**_ section and press enter.
3. Verify what screen reader is reading as button when focus lands on column header.

**Actual Result:**
Screen reader is not reading as ‘Sorting button’ when navigated to column header in the DetailsList control.

**Expected Result:**
Screen reader should read as ‘Sorting button’ when navigated to column header in the DetailsList component.

**User Impact:**
Screen reader users may find it difficult to understand the purpose of button when navigated to column header in the  DetailsList component..

**Comment by aneeshack4** [comment] 2020-04-28 15:36
@v-sagsah Dupe of #11564, check that out for info on this and please be sure to check for dupes before filing new issues on our repo.

**Closed by aneeshack4** 2020-04-28 15:36 UTC
Labels: Needs: Triage :mag:
