### ISSUE TITLE
Data picker control is getting activated automatically when focus reaches to that control

### ISSUE THREAD

**Issue by SyedRehmanRazvi** [microsoft/fluentui#12223] opened 2020-03-06 14:08 UTC
User Experience:
Keyboard users will face difficulty as the control is activating automatically when focus reaches to that control

Repro Steps:
Step 1: Open https://fabricweb.z5.web.core.windows.net/oufr/7.99.0/#/examples/datepicker  in edge browser
Step 2: Navigate to "Default DatePicker" control using tab and verify whether the control is activating automatically when focus reaches to it or not.

Actual:
Date picker control is activating automatically when focus reaches to that control.

Expected.
Date picker should not activate automatically when focus reaches to any control

[date picker control.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/4298682/date.picker.control.zip)

**Comment by aneeshack4** [comment] 2020-03-06 20:43
@syedrehmanrazvi thanks for reporting this! I see that it repros on Edge but not on Chrome...  on Chrome while moving focus onto the DatePicker, I still have to press ENTER after focus's already on the Select a date box to get the DatePicker callout to come up whereas on Edge, @lorejoh12 any ideas as to why it could differ like this?

**Comment by Tanddant** [comment] 2020-05-07 06:23
I'm seeing this in chrome as well (chrome build:  81.0.4044.138)

**Comment by lorejoh12** [comment] 2020-07-13 19:18
partial dupe of #8080. This is by design, because some consumers asked for this functionality. If your app does not want this, the prop disableAutoFocus turns off this functionality. As discussed in 8080, we're considering changing the default from disableAutoFocus: false to true so that customers would have to explicitly opt-in, but haven't made that change yet.

**Comment by Tanddant** [comment] 2020-07-14 05:47
That makes sense, I would have to agree that false would be a more natural default value, but we all know changing defaults breaks things.

**Comment by lorejoh12** [comment] 2020-07-20 17:27
closing as by design, given that there's a prop that can be used to change this behavior

**Closed by lorejoh12** 2020-07-20 17:27 UTC
Labels: Area: Accessibility, Component: DatePicker, Type: Bug :bug:
