### ISSUE TITLE
Fluent UI SSR CSS Problem

### ISSUE THREAD

**Issue by cubesky** [microsoft/fluentui#14201] opened 2020-07-24 19:02 UTC
### Environment Information

- **Package version(s)**: `@fluentui/react 7.123.6` `@uifabric/merge-styles 7.16.3` `@uifabric/fluent-theme 7.1.111`
- **Browser and OS versions**:  `Chrome 83.0.4103.116 on Windows 10`

### Please provide a reproduction of the bug in a codepen:
SSR Render bug, codepen not affect.

I created a theme with fluentui and Gatsby. And when I build my blog site with theme, error happened.

I use this `gatsby-ssr.js` to render SSR content.

```javascript
import { renderStatic } from "@uifabric/merge-styles/lib/server"
import { renderToString } from "react-dom/server"
import React from "react"

export const replaceRenderer = ({
  bodyComponent,
  replaceBodyHTMLString,
  setHeadComponents,
}) => {
  const { html, css } = renderStatic(() => {
    return renderToString(bodyComponent)
  })
  
  replaceBodyHTMLString(html)

  setHeadComponents([<style dangerouslySetInnerHTML={{ __html: css }} />])
}
```

But I can not see any css insert into html head. 

#### Actual behavior:
After SSR Render with Gatsby. (`gatsby build`)

![image](https://user-images.githubusercontent.com/8038511/88425160-8642f880-ce21-11ea-837d-17872e02aff0.png)

If I click any content (This page has PJAX feature), new content in this page is correct.

![image](https://user-images.githubusercontent.com/8038511/88425865-b76ff880-ce22-11ea-90bc-bcb329df0d93.png)

![image](https://user-images.githubusercontent.com/8038511/88425954-dbcbd500-ce22-11ea-8d10-7dd16f0d0bd1.png)

You can see, left side content isn't update, so it is incorrect. And after I click a blog post, it will navigate to post page and post page is correct, and then press back button or click `Home` button to go back to post list, post list is correct too.  

Record: [https://imgur.com/Ni6qtL9](https://imgur.com/Ni6qtL9)

Generated page example (too long): [https://pastebin.com/q4K8m00P](https://pastebin.com/q4K8m00P)

#### Expected behavior:
Using gatsby develop (`gatsby develop`)

![image](https://user-images.githubusercontent.com/8038511/88425299-c0ac9580-ce21-11ea-96b0-875c99c8b4b3.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) 

No, I don't know how to fix it.   

It seems `@uifabric/merge-styles` doesn't generate css to it, or load incorrect css with fluentui 7.123.6 .

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by cubesky** [comment] 2020-07-24 20:01
Repo for reproduce : https://github.com/cubesky/fluentui-issue-14201

**Comment by cubesky** [comment] 2020-07-27 08:46
Use `@fluentui/react` with `@uifabric/mergeStyles` renderStatic function will case this error. But `@fluentui/react` doesn't provide renderStatic

**Comment by paulgildea** [comment] 2020-07-27 17:03
@cubesky Thanks for the repo! That will be super helpful.

@dzearing / @micahgodbolt as FYI as this deals with SSR and Gatsby.

**Comment by cubesky** [comment] 2020-07-28 16:58
I found that import components using `office-ui-fabric-react` will solve the problem, using `@fluentui/react` and `@uifabric` (include experimental component from `https://developer.microsoft.com/en-us/fluentui#/controls/web/card` document) will cause this server side rendering problem.

**Comment by xugao** [comment] 2020-07-29 17:18
@cubesky - thanks for the detailed repro! could you push your changes which lead to resolve this issue into a branch in your [repo](https://github.com/cubesky/fluentui-issue-14201)? That will help me dig deeper. Thanks!

**Comment by cubesky** [comment] 2020-07-30 09:06
@xugao I pushed my changes to `fixed` branch at that repo.

**Comment by xugao** [comment] 2020-07-31 00:16
@cubesky - the issue is caused by multiple version of `merge-styles` are installed and used. in your repro case, `@fluentui/react` is using one `merge-styles` to register styles, then `renderStatic` is using the other `merge-styles` to get styles.  if you sync all fluentui packages to latest version the issue is resolved:
![image](https://user-images.githubusercontent.com/1207059/88986612-5912a200-d288-11ea-9f3a-c0c0f7090261.png)

**Comment by cubesky** [comment] 2020-07-31 15:22
I updated all package to latest version and remove `office-ui-fabric-react` package in package.json, everything correct. 

Thanks

**Comment by paulgildea** [comment] 2020-07-31 15:56
Awesome. Thanks for the great work @xugao and @cubesky !

I'll close this issue as fixed!

**Closed** 2020-07-31 15:57 UTC
Labels: Area: SSR, Needs: Attention :wave:, Package: merge-styles
