### ISSUE TITLE
DefaultButton shows square box around it

### ISSUE THREAD

**Issue by KshamaShrey** [microsoft/fluentui#20987] opened 2021-12-10 12:31 UTC
### Environment Information

- **Package version(s)**
  office-ui-fabric-react: "^6.189.2",
   spfx: 1.11.0

- **Browser and OS versions**: Safari iPhone 12: Original: iOS 14.1 

### Steps to reproduce:
1. Include office-ui-fabric-react DefaultButton as mentioned in the [documentation](https://docs.microsoft.com/en-us/javascript/api/react/defaultbutton?view=office-ui-fabric-react-latest)
2. The following css is added to the button to style it.
`.goToTop{
  position: fixed;
  min-width: 0px;
  min-height: 62px;
  bottom: 55px;
  right: 20px;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  border: 3px solid;
  border-radius: 50%;
  border-color:white!important;
  background-color:red!important;
  cursor: pointer;
  animation: fadeIn 0.3s;
  transition: opacity 0.4s;
  i {
    color: white;
    top: -1px;
    font-size: 25px;
    font-weight:bolder!important;
    position: relative;
    margin: 0px;
  }
}`
3. The button should display round as the border-radius is mentioned as 50% which is displayed as expected.
4. There shouldn't be a square box around the round button. As per the analysis, the issue is caused due to the fabric ui react package.
5. This issue shown below(square box around the rounded button) is visible intermittently.
<img width="954" alt="Screenshot 2021-12-10 at 3 36 36 AM" src="https://user-images.githubusercontent.com/39548087/145575554-c701c14b-4e36-45b8-a100-e84e7e70b095.png">

The square box  around the rounded button is shown in following scenarios.

1. User clicks on a button to open  ui fabric panel
<img width="412" alt="Screenshot 2021-12-10 at 4 26 01 AM" src="https://user-images.githubusercontent.com/39548087/145575590-d2ca7752-a215-4393-8b63-d20ad5c83892.png">

2. User hovers to view a tooltip.
3. Without any actions done by user.

 

#### Actual behavior:
The square box  around the rounded button is visible by default without adding any css.

#### Expected behavior:

No square box around rounded button should be visible

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High as it is a bad UI behavior

Products/sites affected: Production site is affected.

**Comment by Manjunatha123** [comment] 2021-12-10 13:25
We are also facing the same issue in our project.
Unwanted border for the button is getting added which is a bad behaviour from a user experience perspective.

**Comment by layershifter** [comment] 2021-12-13 12:19
Please follow our issue template and create Codepen or Codesandbox with a repro case 🙏

---

I created a CodeSandbox to reproduce the issue: https://codesandbox.io/s/admiring-bell-v4kwx

🔽🔽🔽

As I understood, your problem is related to the focus indicator which remains square:

![image](https://user-images.githubusercontent.com/14183168/145810468-a2fab9a5-ea28-4901-8eb2-a2b7f6c26a93.png)

Applying the same `border-radius` to it, fixes the problem:
![image](https://user-images.githubusercontent.com/14183168/145810727-ba4c9d62-cd8b-42a8-9809-b42958eb1847.png)

```scss
.goToTop:focus::after {
  border-radius: 50%;
}
```

---

Closing as it's not a library issue - there are no circular buttons by design:
https://developer.microsoft.com/en-us/fluentui?fabricVer=6#/controls/web/button

**Closed by layershifter** 2021-12-13 12:19 UTC
Labels: Needs: Triage :mag:
