### ISSUE TITLE
[Bug]:  Pressing Tab key closes the picker (both floating and base picker)

### ISSUE THREAD

**Issue by mrkushjain** [microsoft/fluentui#25373] opened 2022-10-25 18:56 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 34.70 GB / 63.66 GB
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.47)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers

### Bug Description

This is specially important, if we have put interactive elements in footer of picker using renderFooter callback.

## Actual Behavior
When we press TAB key, it closes the picker

## Expected Behavior
It should put focus on the next available focusable element

## WorkAround
For our use case we show create topic/ give feedback buttons as footer, however due to tab key event
   functioning same as the enter key, it makes the footer buttons inaccessible from keyboard. Hence copied
   the onKeyDown event from the BaseFloatingPicker class and removed the tab key case from the switch.

### Requested priority

Normal

### Products/sites affected

Topic Picker

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment] 2023-01-26 16:53
This is the correct behavior for this UI pattern. We shouldn't be adding additional interactive elements to combobox widgets.

**Comment by layershifter** [comment] 2023-01-27 14:35
> This is the correct behavior for this UI pattern. We shouldn't be adding additional interactive elements to combobox widgets.

👆 closing as it's by design.

**Closed by layershifter** 2023-01-27 14:35 UTC
Labels: Resolution: By Design, Fluent UI react (v8)
