### ISSUE TITLE
[Bug]: Fluent Tree : Background color on select / hover looks very bad when there is a scroll bar for width

### ISSUE THREAD

**Issue by dennymicrosoft** [microsoft/fluentui#32221] opened 2024-08-05 10:29 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 32.04 GB / 63.95 GB
  Browsers:
    Edge: Chromium (126.0.2592.61)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/ju1z9s-gzs9qr?file=src%2Fexample.tsx

## Actual Behavior
1. Put tree in container(div) of set width and height; and overflow scroll. 
2. Nest tree items deep enough to when all items are expanded, scroll bars will show for width
3. Scroll to far right
4. Observe that the background color is not adjusted to the full width of the container
5. Select a deeply nested tree item
6. Observe that the tree rerenders and does not maintain scroll position

![image](https://github.com/user-attachments/assets/20d46984-8506-4c6a-a989-f715471234a9)

![image](https://github.com/user-attachments/assets/19a99ca6-27ed-4429-855f-e3aef80828ae)

## Expected Behavior
Expect a better background implementation for overflow scroll trees; ideally the background color is the entire width of the container
Expect scroll position to remain the same when selecting an item

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment] 2024-08-06 07:43
Hey there @dennymicrosoft! Thanks for the bug report. I can confirm the bug on `width` 

I'm not sure if `Observe that the tree rerenders and does not maintain scroll position` is a bug though. Why would we maintain horizontal scroll position when you're modifying the width of the container by closing and opening a branch?! It's not that the scroll position modifies, the container is reducing its size!

I'll follow up on the `width` problem, but as far as I can tell, the best solution to maintain scroll position is to have fixed sizes, which is not the case of your example

**Comment by bsunderhus** [comment] 2024-08-06 16:41
Ok, after further investigations, the best solution seems to be overriding the `Tree` styles to account for the fact that it should have its `width` growing according to its container size (instead of 100% of the available space): https://github.com/microsoft/fluentui/pull/32232#issuecomment-2271706629

@dennymicrosoft , let me know if that solves your case

**Closed by bsunderhus** 2024-08-06 16:41 UTC
Labels: Type: Bug :bug:, Status: In PR, Fluent UI react-components (v9), Component: Tree
