### ISSUE TITLE
[Bug]: Down arrow key behavior on v9 Toolbar overflow item

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#27591] opened 2023-04-17 13:40 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
v9.18.9
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://react.fluentui.dev/?path=/docs/components-toolbar--default

## Actual Behavior
When focus lands on the overflow item, down arrow key move focus to the next(first) toolbar item:
<img width="218" alt="image" src="https://user-images.githubusercontent.com/28751745/232501050-89a0de2e-7dd3-4e5b-ae7b-4114109b7473.png">

## Expected Behavior
Down arrow key should open overflow menu, as in [aria example](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/examples/toolbar/)
![image](https://user-images.githubusercontent.com/28751745/232501170-802d4f48-5215-4b54-9f8e-451f814eaa8a.png)

Also v0 [menu as toolbar example](https://fluentsite.z22.web.core.windows.net/0.66.2/components/menu/definition#usage-toolbar) opens the overflow menu on down arrow key as well.

Note that this is my personal opinion. I'm creating this bug to open a discussion for what's the correct behavior.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment] 2023-04-17 15:26
Apparently there's a conflict of interest between tabster navigation and menu event handler.

By simply modifying this line of code https://github.com/microsoft/fluentui/blob/d755a63d9e2f7c46c1f0f7d96fa4b8ad8e8edc40/packages/react-components/react-toolbar/src/components/Toolbar/useToolbar.ts#L21

to `axis: 'horizontal'`, we indicate to tabster to not listen on vertical navigation, which basically solves the problem. The question is, would it be a regression if we stop support vertical navigation on `Toolbar`, @chpalac @ling1726 ?

**Comment by chpalac** [comment] 2023-04-17 16:28
@bsunderhus Initially the `axis` was defined based on the `vertical` prop. `axis: vertical ? 'vertical' : 'horizontal'`. After one round of a11y ( not sure if was @adamsamec or @kolaps33 ) it was requested to have it behaving the same because screen readers couldn't know the toolbar direction. 

If we are going to have down arrow to open the menu in the horizontal I guess that will still be true for the vertical toolbar?

**Comment by bsunderhus** [comment] 2023-04-17 16:32
> @bsunderhus Initially the `axis` was defined based on the `vertical` prop. `axis: vertical ? 'vertical' : 'horizontal'`. After one round of a11y ( not sure if was @adamsamec or @kolaps33 ) it was requested to have it behaving the same because screen readers couldn't know the toolbar direction.
> 
> If we are going to have down arrow to open the menu in the horizontal I guess that will still be true for the vertical toolbar?

Yes, that will still be true for a vertical toolbar. Ok, I'll investigate a possible solution without requiring to opt-out of both axis navigation

**Comment by bsunderhus** [comment] 2023-04-25 12:28
> @bsunderhus @chpalac it would be worth revisitng the requirement for using both vertical and horizontal arrow keys, since the WAI guidance suggests to only use one axis

According to our investigations it seems like some screen readers (VoiceOver if I'm not mistaken) doesn't make a distinction in navigation direction for a toolbar, which kind of makes it harder to support only a single direction, according to @adamsamec the ideal would be to have both directions supported for this widget, @ling1726 .

**Comment by ling1726** [comment] 2023-04-25 14:05
> > @bsunderhus @chpalac it would be worth revisitng the requirement for using both vertical and horizontal arrow keys, since the WAI guidance suggests to only use one axis
> 
> According to our investigations it seems like some screen readers (VoiceOver if I'm not mistaken) doesn't make a distinction in navigation direction for a toolbar, which kind of makes it harder to support only a single direction, according to @adamsamec the ideal would be to have both directions supported for this widget, @ling1726 .

@bsunderhus in that case, I don't think we can ever use the down arrow to open the menu since it will definitely need to be used for keyboard navigation. The two requirements directly contradict each other 👀👀.

**Comment by bsunderhus** [comment] 2023-05-15 18:50
As discussed internally the current behaviour seems to be the way we're going with for now. I'll be closing this in favor of our current implementation: down key will remain as a navigational key instead of opening the menu provided by overflow items on a toolbar

**Closed by bsunderhus** 2023-05-15 18:50 UTC
Labels: Type: Bug :bug:, Fluent UI react-components (v9), Needs: Investigation, Component: Toolbar, tabster
