### ISSUE TITLE
Can not input chinese in ComboBox

### ISSUE THREAD

**Issue by lnwu** [microsoft/fluentui#17914] opened 2021-04-22 07:59 UTC
### Environment Information

- **Package version(s)**: @fluentui/react 8.9.4
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

document home page can easily reproduce

https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox

#### Actual behavior:

Combox can not input Chinese 

![image](https://user-images.githubusercontent.com/16202655/115677415-08495900-a383-11eb-8e98-f0d2623bbf93.png)

#### Expected behavior:

can

### Priorities and help requested:

Are you willing to submit a PR to fix?  No

Requested priority: Blocking

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment] 2021-05-13 16:20
I think this is a duplicate of #18165, so I'm going to close this issue since the other one has more detailed repro detail.

**Closed by ecraig12345** 2021-05-13 16:20 UTC
Labels: Needs: Triage :mag:
