### ISSUE TITLE
hover card is not getting dismissed on page scroll

### ISSUE THREAD

**Issue by shivasai09** [microsoft/fluentui#14759] opened 2020-08-26 14:10 UTC
### Environment Information

- **Package version(s)**: all the versions
- **Browser and OS versions**: all the browser

### Describe the issue:

please go the reproduction url.

step1. via keyboard try to get the focus on the `hover button`
step 2. press `enter` key
step 3. you will notice that the hover card will get opened. now slowly scroll the page down

after the step 3, you will observe that hover card dose not dismiss , instead it stays on the page and moves along the scroll

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/ssarapu/pen/RwapmwJ?editors=0010
#### Actual behavior:

hover card is not getting dismissed once opened with keyboard, while scrolling of the page. but instead it moves along with the page scroll

#### Expected behavior:

hover card should get dismissed while scrolling of the page.

👉🏽👉🏽👉🏽[video confirmation of the bug](https://drive.google.com/file/d/14N9EhNPe-j-f6C0EZd1mPj-0_y1RIYda/view?usp=sharing)

**Comment by paulgildea** [comment] 2020-08-26 16:10
@shivasai09 Thanks for the super thorough repo and video. This is super helpful for us because it speeds up reproducing the behavior on our side. Thanks!

**Comment by khmakoto** [comment] 2021-03-19 18:50
Hi @shivasai09, this is happening because you have a dismiss delay of 300ms in your example. If you reduce this delay to 0 you don't see this problem as can be seen [in this codepen](https://codepen.io/khmakoto/pen/GRNVRxJ?editors=0010). Given that, I'll be resolving this as `Not an issue`.

Let us know if there is anything else we can do to help!

**Closed** 2021-03-20 19:00 UTC
Labels: Component: HoverCard, Fluent UI react, Resolution: Not An Issue
