### ISSUE TITLE
[Bug]: Adobe Spectrum Dialogs close Popovers outside of iFrame

### ISSUE THREAD

**Issue by Keenan-Allgood** [microsoft/fluentui#24825] opened 2022-09-16 01:07 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz
    Memory: 43.89 GB / 63.73 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.33)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/currying-platform-ndpd9t?file=/src/App.tsx Click "Publish" within iFrame, then open Fluent Popover outside of iFrame. Every time fluent popover is opened while iFrame dialog is open, it automatically closes the fluent popover after a second

## Actual Behavior
Fluent UI Popovers close when iFramed Spectrum Dialogs are open. Listening to the events fired, it looks like the fui-framefocus event is coming in as a custom even to the onOpenChange function. Was wondering if there was any further insight we could get on this.

## Expected Behavior
Modals within an iFrame shouldn't force close Fluent UI Popover controls.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment] 2022-11-10 23:31
@Keenan-Allgood thanks for logging the issue! It looks like this is happening because the Spectrum Dialog within the iframe is taking keyboard focus when it opens, which causes the Fluent Popover to blur, and therefore close.

If you don't want this to happen, I'd suggest using the `open` prop to fully control the open state within your own code. As a heads up, I think you'll have to do some document-level focus listeners to handle closing the popup when anything in the same window gets clicked or focused outside of the popup. The issue is that you'll need to make the Popover persist when focus leaves it and moves into the iframe, so to get it to dismiss when the user clicks or moves focus back into the Popover's window, you'd need to watch for those events anywhere in that window.

Let me know if that makes sense, and if you have any questions!

**Closed** 2022-11-18 05:00 UTC
Labels: Status: No Recent Activity, Needs: Author Feedback, Component: Popover, Fluent UI react-components (v9)
