### ISSUE TITLE
[Feature]: Add a host layer for portals

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#28726] opened 2023-08-03 13:55 UTC
### Library

React Components / v9 (@fluentui/react-components)

### The problem:
v9 portals are by default mounted at the bottom of the body. Teams/OWA uses persona card which can be mounted somewhere in the middle of the DOM. Both persona card and our portal have the same z-index (1M) by default. So it result in persona card being covered by our portal, but we want persona card to always be on top.

### Feature purposal
Add a configurable host layer to mount all portal similar as v8.

### Have you discussed this feature with our team

teams-prg

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by ling1726** [comment] 2023-08-31 07:36
V8 only started using a default layer host 'relatively' recently in #22295. We can't reproduce the performance factors that were the motivators for this change. Moving this back to the backlog in case in the future there is a compat case necessary.

In case we want to have some kind of compat with v8, it's quite simple to use the existing portal mount node context, to render v9 Portals inside the v8 layer host in userland.

 https://github.com/microsoft/fluentui/blob/00a6c4efa12bcdd2871e3d0e9f10c24f82ac0644/packages/react-components/react-portal/src/components/Portal/usePortalMountNode.ts#L29

https://github.com/microsoft/fluentui/blob/00a6c4efa12bcdd2871e3d0e9f10c24f82ac0644/packages/react-components/react-shared-contexts/src/PortalMountNodeContext.ts#L5-L19

**Comment by ling1726** [comment] 2024-02-22 09:29
Fixed with PortalMountNodeContext

**Closed** 2024-02-22 09:29 UTC
Labels: Type: Feature, Fluent UI react-components (v9), Resolution: Soft Close
