### ISSUE TITLE
Safari adds 2px margin: Fix in Fluent UI?

### ISSUE THREAD

**Issue by kemusag** [microsoft/fluentui#19988] opened 2021-09-27 06:58 UTC
Hi,
so first of all I want to say that I am aware that is not necessarily a Fluent UI bug. However, I still wanted to create an issue because you can and might want to fix it.

It seems like Safari adds a 2px margin to the left and right of each button. This has some strange effects that are probably not wanted. To see the issue, use Safari and go to https://developer.microsoft.com/en-us/fluentui#/controls/web/button. The layout is slightly off and there are some probably unwanted gaps. Here is one of them:

![Screenshot 2021-09-27 at 08 47 01](https://user-images.githubusercontent.com/77784146/134858945-310fd65e-4a95-4d83-aa33-5ef14e891fc6.png)

So please feel free to turn this into a feature request or even leave it up to the Safari team. However, from a developer point of view I'd appreciate it if the framework looks the same in all browsers without additional fixes.

### Environment Information

- **Browser and OS versions**:  Safari 15

**Comment by yusiflinurlan** [comment] 2021-11-11 19:40
@gouttierre Hello ! can you please assign this to me ?

**Comment by ecraig12345** [comment] 2022-01-12 19:58
It looks like all buttons have a 2px left/right margin in Safari by default, not just those particular buttons on the website. This would be a reasonable thing to add an override for within Fluent UI's Button root styles. cc @khmakoto for awareness for the v9 Button too.

**Comment by idigra** [comment] 2022-06-30 17:03
Adding that it seems bad in split button - following screenshot is from the CodePen exported directly from Fluent UI demo page:
![image](https://user-images.githubusercontent.com/42169023/176735885-9791a7b5-13b7-42a3-a274-8db011238455.png)
For some reason this is not reproduced on the main sample page, just on the CodePen.

**Closed** 2022-10-03 21:55 UTC
Labels: Component: Button, Platform: Safari, Status: In PR
