### ISSUE TITLE
[Bug]: Dialog is not working with SPFx as the model is getting added outside of the webpart context

### ISSUE THREAD

**Issue by Rahul-Trimukhe** [microsoft/fluentui#32160] opened 2024-07-30 15:08 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
SPFX Version: 1.19.0
Node Version: 18.20.3

Installed Dependencies
  "dependencies": {
    "@fluentui/react": "^8.106.4",
    "@fluentui/react-components": "^9.54.6",
    "@microsoft/sp-component-base": "1.19.0",
    "@microsoft/sp-core-library": "1.19.0",
    "@microsoft/sp-lodash-subset": "1.19.0",
    "@microsoft/sp-office-ui-fabric-core": "1.19.0",
    "@microsoft/sp-property-pane": "1.19.0",
    "@microsoft/sp-webpart-base": "1.19.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "tslib": "2.3.1"
  },

Installed Dev-Dependencies
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.20.1",
    "@microsoft/eslint-plugin-spfx": "1.20.1",
    "@microsoft/rush-stack-compiler-4.7": "0.1.0",
    "@microsoft/sp-build-web": "1.20.1",
    "@microsoft/sp-module-interfaces": "1.20.1",
    "@rushstack/eslint-config": "2.5.1",
    "@types/react": "17.0.45",
    "@types/react-dom": "17.0.17",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "eslint": "8.7.0",
    "eslint-plugin-react-hooks": "4.3.0",
    "gulp": "4.0.2",
    "typescript": "4.7.4"
  }
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://github.com/Rahul-Trimukhe/FluentV9POC

## Actual Behavior
1. Theme colors are not getting applied to the Dialog as it's getting added outside of the webpart context.
2. Types of property 'children' are incompatible With Node version 18 and its working with node version 16

        
## Expected Behavior
1. Theme colors need to be there in Dialog as its available for the rest of the webpart content.
2. Type binding need to be supported in Node 18 as well.

https://github.com/Rahul-Trimukhe/FluentV9POC

### Logs

```shell
Type '{ children: Element[]; open: boolean; onOpenChange: (event: KeyboardEvent<HTMLElement> | MouseEvent<HTMLElement, MouseEvent>, data: DialogOpenChangeData) => void; }' is not assignable to type '{ modalType?: DialogModalType | undefined; open?: boolean | undefined; defaultOpen?: boolean | undefined; onOpenChange?: DialogOpenChangeEventHandler | undefined; children: Element | [...]; inertTrapFocus?: boolean | undefined; }'.
  Types of property 'children' are incompatible.
    Type 'Element[]' is not assignable to type 'Element | [Element, Element]'.
      Type 'Element[]' is not assignable to type '[Element, Element]'.
        Target requires 2 element(s) but source may have fewer.
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Rahul-Trimukhe** [comment] 2024-07-30 15:27
Steps to execute the solution
1. Clone the repo
2. Make sure you are using the correct node version
3. Run npm install command to install all the required dependencies 
4. After successful installation of dependencies run below commands
5.  gulp build
6. gulp serve
7. Open any SharePoint site and add the debug script add to the end of the page URL
8. Add Webpart to the page
9. See the behavior

**Comment by pradeept95** [comment] 2024-07-30 17:09
Hi @Rahul-Trimukhe ,

You can check if you need to add IdPrefixProvider, see details:
https://react.fluentui.dev/?path=/docs/concepts-developer-advanced-configuration--page#idprefixprovider

I am using fluent v9 for all of my projects which indeed many are spfx webpart. I have just added link to the initial POC I created with custom theme and other features.
https://github.com/pradeept95/spfx-boilerplate/blob/main/src/webparts/spOnlineExample/SpOnlineExampleWebPart.ts

**Comment by Rahul-Trimukhe** [comment] 2024-07-30 17:23
Thanks @pradeept95 for your response. DefineI will give a try to your suggestions. 
Let me know in case you have references of using fluent UI v9 Dialog in your Spfx solutions

**Comment by spmonahan** [comment] 2024-07-30 17:40
> Open any SharePoint site and add the debug script add to the end of the page URL

Where do I find the debug script?

**Comment by Rahul-Trimukhe** [comment] 2024-07-30 17:43
Hi @spmonahan thanks for your response.

Once you run gulp serve command you can find it in terminal starts with ?debug*******

**Comment by Rahul-Trimukhe** [comment] 2024-07-30 17:47
https://contoso.sharepoint.com/sites/team-a/sitepages/news.aspx%0A%20%20?loadSPFX=true%0A%20%20&debugManifestsFile=https://localhost:4321/temp/manifests.js

**Comment by spmonahan** [comment] 2024-07-30 22:39
I'm getting an error when running `gulp serve`

> [15:38:28] Starting 'serve'...
[15:38:28] Starting gulp
[15:38:28] Starting subtask 'spfx-serve'...
[15:38:28] [spfx-serve] To load your scripts, use this query string: ?debug=true&noredir=true&debugManifestsFile=https://localhost:4321/temp/manifests.js
[15:38:28] Warning - [spfx-serve] Placeholder {tenantDomain} was found in server.json but OS variable SPFX_SERVE_TENANT_DOMAIN is not set. Either set the environment variable or update the serve.json initial page url.
[15:38:28] Error - 'spfx-serve' sub task errored after 87 ms
 No development certificate found. Generate a new certificate manually, or set the `canGenerateNewCertificate` parameter to `true` when calling `ensureCertificateAsync`.
[15:38:28] 'serve' errored after 96 ms
[15:38:28]

**Comment by Rahul-Trimukhe** [comment] 2024-07-31 01:47
@spmonahan you need to install the certificate, you can run the below command 
gulp trust-dev-cert

**Comment by Rahul-Trimukhe** [comment] 2024-07-31 03:27
> Hi @Rahul-Trimukhe ,
> 
> You can check if you need to add IdPrefixProvider, see details: https://react.fluentui.dev/?path=/docs/concepts-developer-advanced-configuration--page#idprefixprovider
> 
> I am using fluent v9 for all of my projects which indeed many are spfx webpart. I have just added link to the initial POC I created with custom theme and other features. https://github.com/pradeept95/spfx-boilerplate/blob/main/src/webparts/spOnlineExample/SpOnlineExampleWebPart.ts

Thanks @pradeept95 The solution which you suggested is working for me the only thing which needs to be addressed now is the typescript issue with the Dialog

**Comment by spmonahan** [comment] 2024-07-31 16:56
@Rahul-Trimukhe How can I see the Typescript error? This is what I seen when building:

> [09:55:44] ==================[ Finished ]==================
Warning - lint - src/webparts/fluentUiV9Poc/FluentUiV9PocWebPart.ts(37,68): error react/no-children-prop: Do not pass children as props. Instead, pass them as additional arguments to React.createElement.
Warning - lint - src/webparts/fluentUiV9Poc/components/ControllingOpenAndClose.tsx(13,40): error @typescript-eslint/explicit-function-return-type: Missing return type on function.

**Comment by spmonahan** [comment] 2024-07-31 17:24
@Rahul-Trimukhe Looking at your linked repro example I don't think the Typescript error will repro. [The types for `Dialog` specify exactly one or two children for `Dialog`](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-dialog/library/src/components/Dialog/Dialog.types.ts#L94) and the error you shared indicates there are 3 or more children (or perhaps the children are passed in a way that cannot be properly type checked?).

**Comment by Rahul-Trimukhe** [comment] 2024-08-01 07:09
![EE763305-3E3F-4C08-9C5E-CE2EA4FB11AB](https://github.com/user-attachments/assets/c086e8a9-9712-44bb-82b2-1a80f43583b9)
![CB4BFCCF-B78E-4CE4-89E0-F0B1C2A3793E_4_5005_c](https://github.com/user-attachments/assets/5814d45f-8160-4850-bf7f-4f204af474aa)
I have updated my repo and the issue exists with the typescript. I have copied as it is code from the Fluent UI documentation and added only 2 JSX elements into it. But its getting considered as JSX.Element[] and not [JSX.Element, JSX.Element]

**Comment by Rahul-Trimukhe** [comment] 2024-08-07 12:39
Hi @pradeept95 any idea about passing the SharePoint theme pallet to the FluentProvider so it should use the SharePoint theme instead of the one which Fluent V9 provides?

Any help regarding this would be appreciated. Thank you

**Comment by pradeept95** [comment] 2024-08-07 13:55
Hi @Rahul-Trimukhe 

Please check this comment: https://github.com/microsoft/fluentui/issues/32250#issuecomment-2273531793

If you interested to explore other packages, please let me know. It makes 10x faster in SPO development.

**Comment by layershifter** [comment] 2024-08-13 09:58
> @Rahul-Trimukhe Looking at your linked repro example I don't think the Typescript error will repro. [The types for `Dialog` specify exactly one or two children for `Dialog`](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-dialog/library/src/components/Dialog/Dialog.types.ts#L94) and the error you shared indicates there are 3 or more children (or perhaps the children are passed in a way that cannot be properly type checked?).
> 
> I don't think this error has anything to do with the Node version.

@spmonahan is correct, it's not related to Node version. The problem is with `lib: ["es5"]` in `tsconfig.json`, I created a simpler repro: https://stackblitz.com/edit/vitejs-vite-aeu5qc

Once `es5` is used it breaks with:

```
src/main.tsx:16:6 - error TS2322: Type '{ children: Element[]; }' is not assignable to type '{ modalType?: DialogModalType; open?: boolean; defaultOpen?: boolean; onOpenChange?: DialogOpenChangeEventHandler; children: Element | [...]; inertTrapFocus?: boolean; }'.
  Types of property 'children' are incompatible.
    Type 'Element[]' is not assignable to type 'Element | [Element, Element]'.
      Type 'Element[]' is not assignable to type '[Element, Element]'.
        Target requires 2 element(s) but source may have fewer.
```

- I don't think that it's a correct approach to use `es5` nowadays as Fluent is using `es2019` anyway. If you will do following, the error will be gone:
  ```
  // tsconfig.json
      "lib": [
       -"es5",
       +"es2019",
  ```
- If you want to keep `es5`, you can do the following:
  ```tsx
  export const App = () => {
    const children: DialogProps["children"] = [
      <DialogTrigger key="trigger" />,
      <DialogSurface key="surface" />,
    ]
  
   return <Dialog>{children}</Dialog>
  ```

As `es5` is not a supported target by our browser matrix (https://react.fluentui.dev/?path=/docs/concepts-developer-browser-support-matrix--page), closing this one.

**Closed by layershifter** 2024-08-13 09:58 UTC
Labels: Needs: Triage :mag:, Component: Dialog, Fluent UI react-components (v9)
