### ISSUE TITLE
Split button not working with touch interface

### ISSUE THREAD

**Issue by DhirajKhot** [microsoft/fluentui#14975] opened 2020-09-10 17:55 UTC
### Environment Information

- **Package version(s)**: 7.137.0
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

Check the link - 
https://developer.microsoft.com/en-us/fluentui#/controls/web/button

Go to Split button section. 
Try with mouse click on the Primary Button and drop down arrow. Primary button creates an alert with message Clicked. Drop down opens a contextual menu.
Now try with touch on Primary Button and drop down arrow. In both the cases the contextual menu is opened. Primary button should execute the functionality of click on Primary button and create an alert message Clicked.

#### Actual behavior:
Touch on Primary button opens the contextual menu
![image](https://user-images.githubusercontent.com/20378231/92775813-51ccd100-f3bc-11ea-9e88-98379a5178e2.png)

#### Expected behavior:
Touch on Primary button should create an alert message Clicked (execute the functionality of button and not the drop down)
![image](https://user-images.githubusercontent.com/20378231/92775567-25b15000-f3bc-11ea-9977-91c397f8ae3e.png)

### Priorities and help requested:

Requested priority: Blocking

Products/sites affected: Project app. [https://project.microsoft.com] Customers are not able to create Projects using touch interface.

**Comment by RoelVB** [comment] 2020-09-11 07:47
Duplicate of #14303

**Comment by paulgildea** [comment] 2020-09-11 16:26
@DhirajKhot Thanks for the feedback.

@RoelVB Thanks for the resolution!

**Closed** 2020-09-14 18:00 UTC
Labels: Component: Button, Fluent UI react, Resolution: Duplicate
