### ISSUE TITLE
CommandBar doesn't resize properly when animation present

### ISSUE THREAD

**Issue by PatoBeltran** [microsoft/fluentui#12562] opened 2020-04-06 19:22 UTC
### Environment Information

- **Package version(s)**: 7.76.2

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/PatoBeltran/pen/xxGvRWV?editors=0110

#### Actual behavior:

When an element with an animation pushes the container of the CommandBar to be smaller, the component doesn't react properly and pushes element outside of the width of the container. Notice that having the same component without the animation does resize properly (it seems like the component is reading the size to early)

If you look in the codepen when you switch the variable `WITH_ANIMATION` to false, the command bar will resize properly upon opening the sidebar. 

#### Expected behavior:

The commad bar should resize properly even if the size is modified by an animation.

### Priorities and help requested:

Requested priority: High
Products/sites affected: IoT Central

**Comment by joschect** [comment] 2020-04-07 00:20
@PatoBeltran Thanks for the submission and the codepen! I do see that the commandbar seems to have some problems with handling animating. I suspect that's because the command bar is rerendered before the animation has finished so the measurement of the amount of space that it has is incorrect. I don't believe that the commandbar itself has a good way to detect when an animation has finished.

We'll take a look!

**Comment by brandonthomas** [comment] 2020-06-30 00:38
We have this issue when expanding/collapsing a navigation. I think the primary event for OverflowSet and CommandBar are window resize which is why elements changing size don't trigger it. I think moving to a model that uses ResizeObserver is a much more robust way to do this.

**Comment by brandonthomas** [comment] 2020-06-30 00:45
We're also seeing an issue with CommandBar where the resize events seem to be triggered between frames. So the result is that the final render is based on a width that is no longer correct. Sometimes for us we see the end of our CommandBar items out of frame as a result.

I think the issue is this line of code. Because it's a hard 16ms debounce if you have some frame times between the debounce and the trigger (and another render doesn't occur) you would basically be in a place where the data that the ResizeGroup is using is bad so the widths are off.
https://github.com/microsoft/fluentui/blob/7932ae5eef247af9b914e8f05efdaac0b64914f8/packages/office-ui-fabric-react/src/components/ResizeGroup/ResizeGroup.base.tsx#L381

**Closed** 2022-02-04 17:02 UTC
Labels: Type: Bug :bug:, Component: CommandBar, Resolution: Soft Close
