### ISSUE TITLE
Missing file icon docx.svg with new CDN url

### ISSUE THREAD

**Issue by antoine-gannat** [microsoft/fluentui#13560] opened 2020-06-11 12:13 UTC
### Environment Information

- **Package version(s)**: Since 7.3.3

### Issue description:

The DEFAULT_BASE_URL in [initalizeFileTypeIcons.tsx](https://github.com/microsoft/fluentui/blob/master/packages/file-type-icons/src/initializeFileTypeIcons.tsx) has been changed in [this commit](https://github.com/microsoft/fluentui/commit/cfcf5178fb8304109274a68121c7762a91f55d5b#diff-8d86ed72cc591da3f1f463e2c06f0120).
Since then, the file icon for word documents (docx.svg) is not available in size **24**.

#### Actual behavior:

This url return a 404 error.
https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200515.001/assets/item-types/24/docx.svg

#### Expected behavior:

This url should return the docx icon.
https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200515.001/assets/item-types/24/docx.svg

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes. 

Requested priority: High

Products/sites affected: The SearchBox file suggestions in Word online.

**Comment by paulgildea** [comment] 2020-06-11 17:27
@ecraig12345 Sounds like this was a recent regression could you take a look?

**Comment by ecraig12345** [comment] 2020-06-16 01:20
This is really weird, the icon is there but the filename is in uppercase: https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200515.001/assets/item-types/24/DOCX.svg

@dmichon-msft Do you know if anything about the new deploy pipeline could possibly have made URLs case-sensitive when they weren't before?

**Comment by dmichon-msft** [comment] 2020-06-16 01:24
Ah. I had mistakenly assumed that fabric-cdn didn't need the "force lowercase everything during deployment" logic that odsp-next uses. CDN and Azure storage URLs have always been case sensitive; requesting them with uppercase letters in the past would 404, and it leads to all manner of awkward bugs.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by ecraig12345** [comment] 2020-06-16 01:26
It's also weird that this particular size of item types has some of the filenames in uppercase--on quick perusal of the asset repo (didn't do a search locally to confirm) I didn't see uppercase filenames in other folders. But that would probably be a good thing to check for and fix.

**Comment by antoine-gannat** [comment] 2020-08-14 07:21
Hi,
Is it possible to get back to this issue ? Seems like it keep happening and is causing a lot of issues.
Just got the same issue with this link: 

https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200708.002/assets/item-types/24/docx.svg

Thanks.

**Comment by ecraig12345** [comment] 2020-08-14 18:40
I thought @dmichon-msft fixed this back in June (but I guess we forgot to close the issue). @antoine-gannat When did you start seeing this issue?

**Comment by antoine-gannat** [comment] 2020-08-14 19:59
I think it's been about a month or so. But I don't think it was ever fixed. What I did to fix was to downgrade to an earlier version.

**Comment by dmichon-msft** [comment] 2020-08-14 20:22
I didn't make any changes in response to this thread. The most correct fix would be to modify (via git mv​) the casing of the files in the repo. It will require stepping through an intermediary file name if executed on Windows, since Windows is not case-sensitive.
________________________________

**Comment by dzearing** [comment] 2020-08-17 15:58
Pinging @bigbadcapers 

It seems like some of the filetypeicons that are deployed to the cdn have casing issues.

**Comment by bigbadcapers** [comment] 2020-08-17 17:11
Ah, because we've had many contributors to the icon system, the original files have a mix of capitalization. I can work to make the update in our source files but that will take a bit (about 500 artboards need to be renamed). Is there any way to ensure the CDN is configured as before where all URLs were referenced in lowercase and this all worked?

Ideally these URLs should work case-insensitive.

**Comment by dmichon-msft** [comment] 2020-08-17 17:16
We can make a change to the upload pipeline to force lowercase everything again. Might break one or more recently uploaded files if they refer to it using the exact casing.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by bigbadcapers** [comment] 2020-08-17 17:30
> We can make a change to the upload pipeline to force lowercase everything again. Might break one or more recently uploaded files if they refer to it using the exact casing.

That would be ideal as it mirrors the previous behavior. at least for filetypes i believe everything worked correct. I'm already starting to work on updating the master illustrator file but it will take me a while to generate the new PR for all the icons.

cc @Jahnp

**Comment by bigbadcapers** [comment] 2020-08-17 18:29
Update: I multitasked during 2 of my meetings and typed as fast as I could. I am generating the new icons now and will submit a PR for FabricCDN asap. Will also need to submit one for fabric itself to up the referenced CDN version, pls stand by.

side note: could someone create some sort of build-step that does that automatically when FabricCDN is deployed?

**Comment by dmichon-msft** [comment] 2020-08-17 18:57
Pr here: https://onedrive.visualstudio.com/Design/_git/fabric-cdn/pullrequest/495373


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Closed** 2020-08-17 22:31 UTC
Labels: Package: file-type-icons, Priority 1: ASAP, Status: In PR, Type: Bug :bug:
