### ISSUE TITLE
[Bug]: Combobox displays the value of an Option instead of the display text (child as string)

### ISSUE THREAD

**Issue by ParadimeWeb** [microsoft/fluentui#24937] opened 2022-09-24 00:41 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 7.05 GB / 15.67 GB
  Browsers:
    Chrome: 101.0.4951.64
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.29)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codesandbox.io/s/cocky-waterfall-goc5w8

## Actual Behavior
1- When select an Option with a value, the value is displayed in the input.
2- The matching function searches in the value.
3- When freeform, hitting the space bar makes the list box close. You cannot type something with a space.

## Expected Behavior
1- When select an Option with a value, the display text (child string value) is displayed in the input.
2- The matching function searches in the display text (child string value)
3- When freeform, you can type something that has a space in it.

```
<Combobox
    freeform
>
    <Option value="value1">This is the display text for 1</Option>
    <Option value="value2">This is the display text for 2</Option>
    <Option value="value3">This is the display text for 3</Option>
</Combobox>
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ParadimeWeb** [comment] 2022-10-05 20:05
Not sure why this bug is not going to triage? Did I miss something when submitting?
I'd like to use the dropdown in prod, but it is not ready yet.

**Comment by XFox111** [comment] 2022-10-10 16:13
Yeah, it's really frustrating that it does it that way

**Comment by chenxinyanc** [comment] 2022-10-20 08:22
I was about to open a similar issue with the following minimum repro: https://codesandbox.io/s/combobox-and-dropdown-oml8x0?file=/example.tsx

Could you please look into this ASAP? It would be a blocker for us to upgrade the Dropdown components from v8.

JSX code
```tsx
    <div>
      <div>Selected Combobox option: {selectedOption1}</div>
      <Combobox
        selectedOptions={[selectedOption1]}
        onOptionSelect={(_, e) => setSelectedOption1(e.optionValue)}
      >
        <Option value="Workspace-GUID-1">Workspace 1</Option>
        <Option value="Workspace-GUID-2">Workspace 2</Option>
        <Option value="Workspace-GUID-3">Workspace 3</Option>
      </Combobox>
      <div>Selected Dropdown option: {selectedOption2}</div>
      <Dropdown
        selectedOptions={[selectedOption2]}
        onOptionSelect={(_, e) => setSelectedOption2(e.optionValue)}
        
      >
        <Option value="Workspace-GUID-1">Workspace 1</Option>
        <Option value="Workspace-GUID-2">Workspace 2</Option>
        <Option value="Workspace-GUID-3">Workspace 3</Option>
      </Dropdown>
    </div>
```

## Actual Behavior
The option values (Workspace-GUID-x) are being rendered in the dropdown field, while the option contents (Workspace 1) are rendered in the dropdown list.
![image](https://user-images.githubusercontent.com/50703224/196894445-3164af16-13f6-4c24-91df-0290831879a3.png)

## Expected Behavior
The option contents (Workspace 1) are rendered both in the dropdown field and dropdown list.
![image](https://user-images.githubusercontent.com/50703224/196894521-ace871e6-7e30-40b9-b44b-3907f73ceef8.png)

**Comment by JustSlone** [comment] 2022-10-24 15:59
@smhigley feedback/issue with ComboBox, let's take a look quickly

**Comment by smhigley** [comment] 2022-10-24 16:24
Hi! This is actually intentional -- the `value` prop is intended to hold the string-only value that is displayed in the `<input>`'s value when the option is selected. The reason we don't use the children of the Option is because `<input>` can only take a string value, while `<Option>`s can have JSX children. We also use it for type-to-move-active-option functionality for keyboard interaction.

I'm looking at including other props (probably the `id`) in the `onOptionSelect` callback's data. If you were able to get the `id` string when an option is selected, would that resolve what you're currently using `value` for now?

**Comment by smhigley** [comment] 2022-10-24 16:49
Another option might be to rename `<Option value="string">` to something like `<Option text="string">` to avoid the confusion, though I'm hesitant to change the API unless it's a big issue.

**Comment by ParadimeWeb** [comment] 2022-10-25 16:21
It should either have "key" and "text" properties like the Dropdown and ComboBox components from version 8 or "label" and "value" properties like the Radio component in version 9.

Without those properties, the component is useless.

**Comment by chenxinyanc** [comment] 2022-11-01 10:25
> the `value` prop is intended to hold the string-only value

...but it _could_ be designed contain `any` value.

> The reason we don't use the children of the Option is because <input> can only take a string value, while <Option>s can have JSX children.

These are facts, but I didn't see why `<Dropdown>` should align with `<input>` in a way that even the type restrictions on `value` property should be the same. Again, the `value` property can be designed to contain value of type `any`.

You have already rendered the whole dropdown component by yourself, why not just render the selected item inside the dropdown field? I failed to see any blocker stopping us to render rich content inside a React element.

**Comment by ParadimeWeb** [comment] 2023-01-27 16:00
Any updates on this? Not having a key/text option makes this component pretty useless.

In the meantime, I am using the version 8 dropdown because it has a key/text option. It would be nice to start using the version 9.

**Comment by XFox111** [comment] 2023-01-27 16:18
> Any updates on this? Not having a key/text option makes this component pretty useless.
> 
> In the meantime, I am using the version 8 dropdown because it has a key/text option. It would be nice to start using the version 9.

At this time, as a workaround, I've created a dropdown wrapper component, that fixes the problem. Though I hope Microsoft will push out an update to this issue

<details>
<summary>Wrapper component example</summary>

```tsx
import React from "react";
import { Dropdown, DropdownProps, Option } from "@fluentui/react-components/unstable";

interface IProps
{
	options?: { [key: string]: string };
	onSelect?: (key: string) => void;
	selectedOption?: string;
}

export default class DropdownWrapper extends React.Component<DropdownProps & IProps>
{
	public render(): JSX.Element
	{
		let selectedOption = this.props.selectedOption ? this.props.options[this.props.selectedOption] : null;

		return (
			<Dropdown
				{ ...this.props }
				selectedOptions={ [ selectedOption ] }
				onOptionSelect={ (_, e) => this.props.onSelect(this.GetSelectedOption(e.optionValue)) }>

				{ Object.entries(this.props.options).map(([key, name]) =>
					<Option key={key}>{name}</Option>
				) }
			</Dropdown>
		);
	}

	private GetSelectedOption(key : string): string
	{
		let index = Object.values(this.props.options).indexOf(key);
		return Object.keys(this.props.options)[index];
	}
}
```

</details>

<details>
<summary>Component usage example</summary>

```tsx
<DropdownWrapper
	aria-labelledby="label-GroupSavePolicy"
	selectedOption={ opt?.GroupSavePolicy }
	onSelect={ (e) => SettingsService.Update({ GroupSavePolicy: e as GroupSavePolicy }) }
	options={ {
		"separate": "Save each group as new collection",
		"subgroups": "Preserve grouping inside one collection",
		"omit": "Omit grouping"
	} }
/>
```

</details>

**Comment by ParadimeWeb** [comment] 2023-01-27 17:28
Good idea. I wrote one that works a little differently. It transforms the data.optionValue and data.optionText and data.selectedOptions in the onOptionSelect callback.
```

type DropdownWrapperProps = DropdownProps & {
    options?: [string, string][];
};
const DropdownWrapper = (props: DropdownWrapperProps) => {
    const options = new Map(props.options);
    return <FluentDropdown
        onOptionSelect={(event, data) => {
            if (props.onOptionSelect) {
                props.onOptionSelect(event, { 
                    optionText: data.optionValue, 
                    optionValue: options.get(data.optionValue),
                    selectedOptions: data.selectedOptions.map((value) => options.get(value)) 
                });
            }
        }}
    >
        {props.options.map(value => <Option key={`Option_${value[1]}`}>{value[0]}</Option>)}
    </FluentDropdown>;
};
```

You can use it like this:

```
            <DropdownWrapper 
                onOptionSelect={(_, data) => {
                    console.log(data);
                }}
                options={[
                    ["Text 1", "value1"],
                    ["Text 2", "value2"],
                    ["Text 3", "value3"]
                ]}
            />
```

**Comment by smhigley** [comment] 2023-01-28 00:20
Forgot to update this issue, but this should be fixed in #25379

The `value` prop is now used as a key for selectedOptions, and you can put any misc string in there since it won't be displayed to the user. Now the `text` prop is used to provide a user-facing string that will be used for type-to-highlight behavior and the display text when an option is selected.

**Comment by smhigley** [comment] 2023-01-28 00:31
So now you should be able to do:

```jsx
import React from "react";
import { Dropdown, DropdownProps, Option } from "@fluentui/react-components/unstable";

const optionData = [
  ['key1', 'Display Text 1'],
  ['key2', 'Display Text 2'],
  ['key3', 'Display Text 3'],
  ...etc.
];

const [selectedOptions, setSelectedOptions] = React.useState([]);

return <Dropdown
        {...dropdownProps}
        selectedOptions={selectedOptions}
        onOptionSelect={(event, data) => {
            // data.optionValue will be e.g. 'key2'
            // data.optionText will be e.g. 'Display Text 2'
            // data.selectedOptions will be e.g. ['key1', 'key2']
            setSelectedOptions(data.selectedOptions);
        }}
    >
        {options.map((value) => <Option key={`Option_${value[1]}`} value={value[0]}>{value[1]}</Option>)}
    </Dropdown>;
```

**Comment by ParadimeWeb** [comment] 2023-01-30 14:40
@smhigley are you saying that this is implemented? Because as of version 9.12.0 your example does not work.

**Comment by ParadimeWeb** [comment] 2023-01-30 14:53
It clearly does not work like you mention.

![image](https://user-images.githubusercontent.com/89149/215510737-d175e625-c2db-4230-8a01-265c12201526.png)

The optionValue is displayed instead of the children.

**Comment by ParadimeWeb** [comment] 2023-01-30 17:17
I stopped testing this component a while ago. To help, I figured out that the component stopped working with react 18.2 starting at @fluentui/react-combobox@9.0.0-beta.12. Prior versions worked with react 8.2.0.

**Comment by ParadimeWeb** [comment] 2023-02-02 18:04
The component is now stable  in 9.13.0!!! Really?

The value is still being shown when selected instead of the text and the component does not work at all with react 8.

![image](https://user-images.githubusercontent.com/89149/216406759-654e6668-39f7-439e-b45c-1869f7e49910.png)

**Comment by smhigley** [comment] 2023-02-02 23:30
@ParadimeWeb you're right, I'd forgotten the specifics of the earlier change. The central issue is around when the parent Combobox is aware of its Options. Since they're not rendered until they're needed, setting `defaultSelectedOptions` or `selectedOptions` to the value string means that the Combobox will not be able to display anything as its value, since it can't know what the child Option's human-readable text is until it's rendered.

I think your base use case (no controlled or default selected options, only child `<Option value="x">`) is probably the one that should work though, so I've added a PR that requires authors to set `defaultValue` or `value` if using `defaultSelectedOptions` or `selectedOptions`. This means that an uncontrolled Combobox or Dropdown can use `<Option value="a">Apple</Option>` and display "Apple" when the option is selected: #26617

I'll try to make sure that's updated today, to minimize the amount of change.

Re: the React 18 issue. This is a breaking change in `useId`, not specific to combobox. As of React 18, it is returning `:r#:` instead of a usable id string. Since colons are not a valid character for id strings, it's throwing an error in combobox, and silently failing elsewhere. Thanks for finding it, and I'll investigate it as soon as the combobox change is in.

**Comment by smhigley** [comment] 2023-02-06 19:41
Oh, I forgot to mention -- one workaround right now for the React 18 issue is to specify `id`s in props, so our internal `useId` hook isn't called. In the case of Combobox, that would be on the `<Option>` components, so something like:
 ```tsx
{options.map(option => (
  <Option id={option.key} key={option.key}>{option.name}</Option>
))}
```

**Closed** 2023-02-07 01:26 UTC
Labels: Component: ComboBox, Status: In PR, Fluent UI react-components (v9)

**Comment by ParadimeWeb** [comment] 2023-02-07 19:34
@smhigley 

The third issue is not resolved. We should be able to type something with a space in it. The component does not allow that now. It ignores the space and closes the listbox.

There are many use cases where the value of the combobox will have a space in it. Especially true in freeform.

**Comment by chenxinyanc** [comment] 2023-02-08 11:20
> I also noticed that the component no longer works with react 18.2.0
> 
> ![image](https://user-images.githubusercontent.com/89149/215516145-ffd5ade9-8e8c-4764-9bcd-416233abaa5e.png)

I think #26651 describes the same bug.

**Comment by smhigley** [comment] 2023-02-08 21:29
@chenxinyanc yup, React 18's `useId` inserts colons into the generated id string, which does not work with referencing ids in CSS or JS. We've updated our implementation to strip them out in #26745.

For the space thing -- I've responded over here, to avoid splitting up the discussion :) https://github.com/microsoft/fluentui/issues/26361#issuecomment-1423263549

**Comment by D21ku** [comment] 2023-02-09 11:53
@smhigley the Combobox can only be cleared when we set the `value` as an empty string, but then typing/searching doesn't work properly. Here is an example https://codesandbox.io/s/combobox-gzhb3b-gzhb3b?file=/src/example.tsx

![combobox1](https://user-images.githubusercontent.com/124872410/217805474-b71b2060-56ea-4965-9c57-39e06970ac8e.gif)
