### ISSUE TITLE
[Bug]: Split button primary action does not work in mobile

### ISSUE THREAD

**Issue by ehynot98** [microsoft/fluentui#28798] opened 2023-08-09 21:19 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 36.84 GB / 63.95 GB
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

any split button's primary action will not trigger in mobile. instead the split button menu opens.

## Actual Behavior
1. visit https://developer.microsoft.com/en-us/fluentui#/controls/web/button in Chrome or Edge and navigate to the split button sample
2. open developer tool in browser
3. in the developer tool console, open device emulator (ctrl + shift + m)
4. click on the primary buttion of the split button
5. observe that the split button menu opens (as if the down chevron is clicked)

## Expected Behavior
when clicking on the primary button of the split button when rendered with device emulator (or in actual mobile browser), the primary action should fire instead of showing the button menu.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ehynot98** [comment] 2023-08-09 21:21
I picked the wrong library version. the correct version is v8 (updated in the comment) but the tag added (Fluent UI react-northstar (v0)) is still incorrect.

**Comment by khmakoto** [comment] 2023-08-09 22:14
Hi @ehynot98, this is by design in v8. The expectation is that a pointer event on either the menu or action part of the `SplitButton` should open the menu due to small spaces for touch interaction.

Part of the expected workflow of the `SplitButton` is that you should have your primary action as one of the options in the menu that accompanies the `Button`. Given this the workflow would be to trigger the action through the menu item.

**Comment by khmakoto** [comment] 2023-08-21 21:20
No author feedback has been provided in 2 weeks, closing.

**Closed by khmakoto** 2023-08-21 21:20 UTC
Labels: Needs: Triage :mag:, Resolution: By Design, Needs: Author Feedback, Fluent UI react (v8), Component: SplitButton

**Comment by RoelVB** [comment] 2024-04-04 09:46
For people running into this. You can override this behavior by implementing the `onTouchStart` event on your button.

Example:
```jsx
<DefaultButton
    onClick={()=>console.log('Default called')}
    onTouchStart={()=>console.log('Default called')}
    split
    menuProps={{items: [
        {
            key: 'subAction',
            text: 'Sub action',
            onClick: ()=>console.log('Sub called'),
            onTouchStart: (ev: React.TouchEvent)=>ev.stopPropagation()
        }
    ]}}
>
    My default action
</DefaultButton>
```
