### ISSUE TITLE
[a11y] Grouped List can't open and close groups with the keyboard only

### ISSUE THREAD

**Issue by fecuadri** [microsoft/fluentui#12458] opened 2020-03-27 21:30 UTC
### Environment Information

- **Package version(s)**: 7.103.0
- **Browser and OS versions**:  Edge 80.0.361.69; Chrome 80.0.3987.149. Windows 10

### Describe the issue:

When using a Grouped List component, moving around with the keyboard makes it impossible to open or close groups.

### Please provide a reproduction of the issue in a codepen:

The issue is present in the official examples, look at the GroupedList basic example:
https://developer.microsoft.com/en-us/fabric#/controls/web/groupedlist

#### Actual behavior:

Can't focus on the arrows or collapse or expand groups

#### Expected behavior:

Groups can be expanded by using only the keyboard

### Documentation describing expected behavior

Behavior is not documented, but the component is not accessible if you can't do every operation only with the keyboard

**Comment by aneeshack4** [comment] 2020-03-27 23:02
This is a dupe of #6318 and a PR has been made #11494 - it looks like it's still open waiting for sign off from partners.

**Comment by aneeshack4** [comment] 2020-03-27 23:03
I'm going to close this as dupe - status will be tracked on the original issue & PR.

**Closed by aneeshack4** 2020-03-27 23:03 UTC
Labels: Component: GroupedList, Needs: Triage :mag:
