### ISSUE TITLE
[Bug]: Clicking checkbox label inside Dialog incorrectly causes focus border to display

### ISSUE THREAD

**Issue by stevencomsft** [microsoft/fluentui#28664] opened 2023-07-27 23:51 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 15.49 GB / 31.84 GB
Browsers:
    Edge: Spartan (44.22621.2050.0), Chromium (116.0.1938.29)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/reverent-ishizaka-l7c5vn?file=/example.tsx

### Bug Description

**Description**: The focus border appears around the Checkbox incorrectly when clicking on the label to toggle the checkbox value when rendered within a Dialog. The focus border also acts weirdly and follows the mouse to incorrectly apply to sibling MenuItemCheckboxes once it has first appeared incorrectly.

**Repro steps:**
1. Open a v9 Dialog containing a v9 checkbox. 
2. Click the checkbox label (not the checkbox itself)
3. If you don't see the border appearing on first click, click the label a second time
4. See the focus border appear around the Checkbox incorrectly

**Note**: If you click the label, then click away from the checkbox, then click the label again, it does not apply the focus border. 

**Related bug repro steps**: 

1. Get the focus border to show in correctly as above
2. While the focus border is visible, hover the mouse over any MenuItemCheckbox that exists in the same dialog body
3. See the focus border shift to whatever MenuItemCheckbox you are hovering over

**Minimum repro**: https://codesandbox.io/s/reverent-ishizaka-l7c5vn?file=/example.tsx

The first/main issue is annoying for users, but the second issue could potentially be an accessibility problem, shifting focus border to elements that don't currently have focus.

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment] 2023-07-28 11:15
Duplicate of #27807.

**Closed by layershifter** 2023-07-28 11:15 UTC
Labels: Fluent UI react-components (v9)
