### ISSUE TITLE
@fluentui/react-button can't correctly handle click event with menuProps on mobile browser

### ISSUE THREAD

**Issue by flytiny** [microsoft/fluentui#15542] opened 2020-10-16 05:04 UTC
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: Sarafi / IOS14

### Please provide a reproduction of the bug in a codepen:
open[ this page](https://developer.microsoft.com/en-us/fluentui#/controls/web/button) on mobile browser, and click **Split Button**, it will trigger menu list display rather than original button click event.

#### Actual behavior:

It will trigger menu list display.

#### Expected behavior:

It will trigger original button click event.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment] 2020-10-19 17:17
@flytiny Thanks for filling this issue.

@dzearing / @khmakoto - Known issue/by design?

**Comment by dzearing** [comment] 2020-10-19 17:19
I think we need to ensure that pointer events are handled. @khmakoto can you take a look?

**Comment by dzearing** [comment] 2020-10-19 17:44
Also I believe the expectation is that a pointer event on either the menu or action part of the split button should open the menu.

**Comment by JonasDong** [comment] 2021-02-03 06:43
Had the same issue on Android Edge browser and Teams Android client (in an embedded page).

**Comment by khmakoto** [comment] 2021-03-09 00:27
The `Button` referenced on the example page is not the on in `@fluentui/react-button` but the one in `@fluentui/react`. That said, like @dzearing commented, the expectation is that a pointer event on either the menu or action part of the `SplitButton` should open the menu due to small spaces for touch interaction. Given all this, I'll be resolving this issue by design for now.

Thanks for the issue and let us know if there is anything else we can do to help!

**Comment by JonasDong** [comment] 2021-03-09 02:52
> The `Button` referenced on the example page is not the on in `@fluentui/react-button` but the one in `@fluentui/react`. That said, like @dzearing commented, the expectation is that a pointer event on either the menu or action part of the `SplitButton` should open the menu due to small spaces for touch interaction. Given all this, I'll be resolving this issue by design for now.
> 
> Thanks for the issue and let us know if there is anything else we can do to help!

Thanks @khmakoto, could you explain a bit more on what is the designed way to trigger the main button action for touch device? I think the main blocker we are facing is that there is no way to trigger the main button's onClick callback on touch screen here.

**Comment by khmakoto** [comment] 2021-03-09 02:56
@JonasDong part of the expected workflow of the `SplitButton` is that you should have your primary action as one of the options in the menu that accompanies the `Button`. Given this the workflow would be to trigger the action through the menu item.

**Closed** 2021-03-11 22:00 UTC
Labels: Component: Button, Fluent UI react, Resolution: By Design, Resolution: Not An Issue, Resolution: Won't Fix
