### ISSUE TITLE
[Bug]: Modal with an announced in a  will contain a double scrollbar

### ISSUE THREAD

**Issue by zachhats** [microsoft/fluentui#27369] opened 2023-03-29 20:41 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
C:\PowerQuery-Web>npx envinfo --system --npmPackages '{@fluent/*}' --browsers
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Memory: 8.73 GB / 23.83 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/zachhats/pen/dyqLaxG

## Actual Behavior
if you have a modal that contains an announced inside an element that has gone outside its max-height, the modal itself will contain a scrollbar

if you remove the announced from the codepen, you will see the double scrollbar go away

## Expected Behavior
there is only one scrollbar for the existing codepen

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment] 2023-04-24 17:33
might be a duplicate of #23388

**Comment by zachhats** [comment] 2023-06-30 20:38
The proposed mitigation does not work for us, it is already in the repro I linked and it does not fix the issue. Can this please be addressed?

**Closed** 2024-01-04 00:45 UTC
Labels: Component: Modal, Fluent UI react (v8), Resolution: Soft Close
