### ISSUE TITLE
Storybook: Show full source when it’s necessary

### ISSUE THREAD

**Issue by PeterDraex** [microsoft/fluentui#20046] opened 2021-09-30 14:13 UTC
For some stories, it’s not sufficient to show source code from the story function. Instead, source code from the whole file needs to be shown. This can be done by setting parameter `docs.source.code` to `__STORY__`.

For example:
```
StoryName.parameters = {
  docs: {
    description: {
      story: 'A button supports `small`, `medium` and `large` size. Default size is `medium`.',
    },
    source: {
      // @ts-ignore
      code: __STORY__,
    },
  },
};
```

We need to go through all stories in documentation and set this parameter where necessary. It is necessary, for example, for Nested Submenu story on Menu docs page.

**Comment by layershifter** [comment] 2023-01-23 10:28
Duplicate of #20367.

**Closed by layershifter** 2023-01-23 10:28 UTC
Labels: Fluent UI react-components (v9), Storybook, Resolution: Soft Close
