### ISSUE TITLE
[Bug]: Flash of outline when opening page/popover

### ISSUE THREAD

**Issue by NotWoods** [microsoft/fluentui#25432] opened 2022-10-28 16:29 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 96.31 GB / 127.71 GB
  Browsers:
    Edge: Spartan (44.22621.674.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/3f3lf5?file=/example.tsx

## Actual Behavior
When loading a page with a focusable button, or opening a popover with a focusable button, each button's outline appears for a moment before animating away. It also appears to animate layout.

![FluentOutlineFlash](https://user-images.githubusercontent.com/1782266/198686479-fc70bf3c-c0fa-4e9e-8831-e4e01e08c554.gif)

## Expected Behavior
Except to not see outline at all until focus is reached. I noticed this bug in both 9.6.0 and 9.5.0.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment] 2022-10-31 13:04
Note that this only seems to happen to the `Popover` and not the `Menu`

**Comment by bsunderhus** [comment] 2022-10-31 13:41
Seems like every single button in the page, even the ones outside of the `Popover` start having this behavior

https://codesandbox.io/s/gallant-paper-8t5ge6?file=/example.tsx

**Comment by bsunderhus** [comment] 2022-10-31 14:15
Ok, just an update on this. seems to be affecting every single Trigger

**Comment by ling1726** [comment] 2022-10-31 20:28
After some investigation the problem is more similar to #25232. The root cause is that `window.getComputedStyle` is being called during the render phase.

Our css variables are set in an effect https://github.com/microsoft/fluentui/blob/9a6f5b7a938f95518b20624f37031112ea267914/packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts#L57

Therefore the call of `getComputedStyle` ends up triggering a transition introduced in https://github.com/microsoft/fluentui/commit/755d076070dd69c0a798eb5863aadf98e76b024a.

The solution should be to refactor the usage of `getScrollParent` so that it is only called meaningfully in effects

**Comment by ling1726** [comment] 2022-10-31 20:29
This is a terrible bug and should be fixed ASAP

**Closed** 2022-11-02 11:18 UTC
Labels: Status: In PR, Fluent UI react-components (v9)
