### ISSUE TITLE
Callout - Hyperlink inside callout not Read by Windows Narrator in Chromium Edge and Dev Chromium Edge version

### ISSUE THREAD

**Issue by MdAmeerMind** [microsoft/fluentui#15236] opened 2020-09-25 07:19 UTC
### Environment Information

- **Browser and OS versions**
Microsoft Edge Version 85.0.564.51 (Official build) (64-bit)
Microsoft Edge Version 87.0.637.0 (Official build) dev (64-bit)
### Describe the issue:
Hyperlink inside Callout are not readout by Windows Narrator, but same is read out by NVDA in Chrome.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/mdameermind/pen/OJNdeWx?editors=0010

#### Actual behavior:
Hyperlink inside Callout are not readout by Windows Narrator, but same is read out by NVDA in Chrome.

#### Expected behavior:
Hyperlink inside Callout should readout by Windows Narrator, Same like read out by NVDA in Chrome.

**Comment by paulgildea** [comment] 2020-09-25 16:27
@MdAmeerMind Thanks for the issue.

@smhigley FYI

@miroslavstastny use the latest version of the library for the repro.

**Comment by miroslavstastny** [comment] 2020-09-27 19:01
Duplicate of #14942

**Closed by miroslavstastny** 2020-09-27 19:01 UTC
Labels: Area: Accessibility, Area: Narrator, Component: Callout, Platform: Microsoft Edge, Resolution: Duplicate
