### ISSUE TITLE
[v9] Adding Tooltip breaks menu trigger functionality

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#21117] opened 2021-12-23 08:51 UTC
### Environment Information

- **Package version(s)**: @fluentui/react-components beta
- **Browser and OS versions**: all

### Please provide a reproduction of the bug in a codepen:

When a button is wrapped by both Tooltip and MenuTrigger, it is not possible to open the menu.

See https://codesandbox.io/s/iv9gf?file=/example.tsx

#### Actual behavior:

Hovering on the button shows tooltip
Clicking on the button does **not** open menu
Pressing enter or space when button is focused does **not** open menu
Aria-label is applied on the button
Aria-haspopup is **not** applied on the button

#### Expected behavior:

Hovering on the button shows tooltip
Clicking on the button opens menu
Pressing enter or space when button is focused opens menu
Aria-label is applied on the button
Aria-haspopup is applied on the button

**Comment by jurokapsiar** [comment] 2021-12-23 09:22
migth be duplicate of #21115 but details the expected result

**Comment by ling1726** [comment] 2021-12-28 12:46
Closing as duplicate of #21115 which is a general problem with our element cloning pattern

**Closed by ling1726** 2021-12-28 12:46 UTC
Labels: Component: Tooltip, Fluent UI vNext, Component: Menu
