### ISSUE TITLE
RTL styling doesn't get applied to VR-Tests

### ISSUE THREAD

**Issue by makopch-ms** [microsoft/fluentui#18836] opened 2021-07-06 22:06 UTC
### Please provide a reproduction of the bug in a codepen:
1. in <fluentRepo>\apps\vr-tests\src\stories\Button.stories.tsx
2. Add the following code to the baseProps
styles: {
    label: {
      marginLeft: '30px',
      marginRight: '5px',
    },
  },
3. 'yarn start' under vr-tests
4. navigate to the Button page (see styles are correct)
5. navigate to the Button-RTL page (see styles are not correct)

#### Actual behavior:

Styles don't seem to be getting flipped when viewing a page that is in a different direction (LTR <->RTL) then the previous page

#### Expected behavior:

Styles such as margin-left/right get flipped

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking upgrade to v8

Products/sites affected: Office web

**Comment by ling1726** [comment] 2021-07-07 11:26
The problem here is that the styling memoization does not recompute with RTL changes. I don't have enough context on v8 to know whether this is a bug or not but the same thing seems to happen in v7.

```ts
// DefaultButton.styles.ts

// 👇👇👇 This will never recompute after `setRTL` without page refresh
export const getStyles = memoizeFunction(
  (theme: ITheme, customStyles?: IButtonStyles, primary?: boolean): IButtonStyles => {
    // Styles
  },
```

Here is a possible way to fix this. However, the same issue should occur in other places in v8 so I don't want to make an isolated fix for this.

```tsx
// DefaultButton.tsx

const rtl = getRTL();
// force memoization to recompute on RTL change
getStyles(theme, styles, primary, rtl)
```

@dzearing  @khmakoto please could you look into this ? Is this by design in v8 ?

**Comment by ling1726** [comment] 2021-07-07 11:31
This should not affect the actual result of VR-Tests since screener will visit each story as a new page load and each story will have the correctly computed styles

**Comment by makopch-ms** [comment] 2021-07-07 19:00
@ling1726 - This does repro on v7 too.

**Comment by ling1726** [comment] 2021-07-07 19:28
Since it does repo on v7 and isn't a new blocking issue in v8, lowering the priority

**Comment by swese44** [comment] 2021-07-22 22:11
Could FluentUI provide a styles-focused `memoizeFunctionWithRTL`? We seem to have the same issue on Yammer and it would be nice if every component didn't have to call `getRTL()` when creating its styles.

**Closed** 2022-07-13 13:01 UTC
Labels: Priority 3: Low, Help Wanted ✨, Fluent UI react (v8), Resolution: Soft Close, Fluent UI react (v7)
