### ISSUE TITLE
[Bug]: Detail List unselect the element programmatically

### ISSUE THREAD

**Issue by mohamed-isak** [microsoft/fluentui#27193] opened 2023-03-14 05:13 UTC
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
npm i
```

### Are you reporting Accessibility issue?

None

### Reproduction

ok

### Bug Description

Question; 
I have 2 Component child Component have a detail list I want to send the selection object to parent Component.
parent component have button to unselect the particular element using selection object ref. how to do that unselect the particular element? using custom button?

## Expected Behavior
```
`
// ComponentA Have unselection button I want to unselect the particular element
function componentA(){
  var selection;
   // unselection from parent component
     const unSelect = (Obselection)=>{
  // set selection reference to local variable
     selection = Obselection;
  } 
return (
<>
<Button onClick={()=>{selection.setItems([],true)}}>Unselect Element</Button>
  <ComponentB unSelect={unSelect}/>
</>
)
}

// ComponentB Have a selection object
function ComponentB({unSelect}){
     const selection = new Selection();
  useEffect(()=>{
    unSelect(selection);
},[])
return (
        <DetailsList
            items={items}
            columns={this._columns}
            setKey="set"
            layoutMode={DetailsListLayoutMode.justified}
            selection={this._selection}
            selectionPreservedOnEmptyClick={true}
            ariaLabelForSelectionColumn="Toggle selection"
            ariaLabelForSelectAllCheckbox="Toggle selection for all items"
            checkButtonAriaLabel="select row"
            onItemInvoked={this._onItemInvoked}
          />
)
}``


```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment] 2023-03-27 08:07
Duplicate of #27192

**Closed by behowell** 2023-03-27 08:07 UTC
Labels: Type: Question ❔, Component: DetailsList, Resolution: Duplicate, Fluent UI react (v8)
