### ISSUE TITLE
@fluentui/react-button: renders a useless React.Fragment render props in shorthands 

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13667] opened 2020-06-18 10:34 UTC
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
<Button
  content={{
    children: (Component, props) => <Component {...props}>Button</Component>,
    style: { border: "2px solid red" }
  }}
/>
```

https://codesandbox.io/s/magical-cori-dhpy8?file=/src/App.js

#### Actual behavior:

```tsx
<Button>
    <Fragment> {/* <=== useless Fragment */}
      <span>Button</span>
    </Fragment>
  </button>
</Button>
```

![image](https://user-images.githubusercontent.com/14183168/85010153-cf879480-b15f-11ea-855b-156a7d71efa6.png)

#### Expected behavior:

Renders without wrapping fragments.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment] 2020-06-18 20:39
This is by design and I believe ok. This is so that the resolved children can replace the container slot and that we don't render the original slot container.

The fragment does not show up in the React DOM hierarchy. 

![image](https://user-images.githubusercontent.com/1110944/85069372-d8c92f00-b168-11ea-8e4c-93d66b9d82ec.png)

**Comment by dzearing** [comment] 2020-06-18 20:39
Going to close this, but please re-activate if you see an issue with this.

**Closed** 2020-06-18 20:39 UTC
Labels: Component: Button, Fluent UI v8, Type: Bug :bug:
