### ISSUE TITLE
Spinner Shape malforms when Label is too long

### ISSUE THREAD

**Issue by daewigma** [microsoft/fluentui#15991] opened 2020-11-19 03:41 UTC
### Environment Information

- **Package version(s)**: office-ui-fabric-react: 7.150.0
- **Browser and OS versions**: Chrome 86.0.4240.198

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/daewigma/pen/RwRmPZW

#### Actual behavior:

Spinner should stay circular when label is long and overflows

#### Expected behavior:

Spinner becomes an oval when label is long and overflows when labelPosition is set to left or right

### Priorities and help requested:

Are you willing to submit a PR to fix? Not at the moment. Maybe if the issue persists and I find time.

Requested priority: Low

Products/sites affected: N/A

**Comment by paulgildea** [comment] 2020-11-20 19:42
@daewigma Thanks for filing this issue.

@behowell Please determine the root cause straightforward/non break fix for this.

**Closed** 2021-04-26 11:00 UTC
Labels: Component: Spinner, Fluent UI react, Needs: Investigation, Resolution: Soft Close
