### ISSUE TITLE
[Feature]: Need Modal component in v9

### ISSUE THREAD

**Issue by nancyz1031** [microsoft/fluentui#29888] opened 2023-11-20 23:58 UTC
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Our team is migrating to v9, and found there is no replacement for Modal component (https://developer.microsoft.com/en-us/fluentui#/controls/web/modal). Would be good to add Modal or Make v9 Dialog Draggable like v8 (https://github.com/microsoft/fluentui/issues/28359)

The Dialog component (https://react.fluentui.dev/?path=/docs/components-dialog--default) can't fulfillment our requirement, since it doesn't support drag operation

![image](https://github.com/microsoft/fluentui/assets/29285878/246f1e9c-fc73-4d3f-866e-5919797757b7)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by khmakoto** [comment] 2023-11-28 20:49
FYI @gouttierre

**Comment by tudorpopams** [comment] 2024-02-12 14:42
Hello, we are currently working on [the Draggable Dialog feature](https://github.com/microsoft/fluentui/issues/28359) and we are very close to ship it. Closing this issue since it's a duplicate of the feature request.

**Closed by tudorpopams** 2024-02-12 14:42 UTC
Labels: Type: Feature, Component: Modal, Needs: Backlog review, Fluent UI react-components (v9)
