### ISSUE TITLE
[Bug]: v8 release is causing dependency mismatches

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#28370] opened 2023-06-29 09:51 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
.
```

### Are you reporting Accessibility issue?

no

### Reproduction

- https://github.com/microsoft/fluentui/pull/28345
- https://github.com/microsoft/fluentui/pull/28366
- https://github.com/microsoft/fluentui/pull/28347

## Actual Behavior

Some packages are failing to update dependencies on v8 releases

## Expected Behavior

All packages dependencies should be updated properly

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment] 2023-07-04 09:49
Ok so after further investigations this was caused by following error that didn't throw/terminate the process

<img width="629" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/cbaaf336-efb4-475e-b093-c8194104ca11">

https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=308466&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=a5e45ad2-7904-508f-791a-1a783f6a099f


So this was caused by bad rebase which didn't remove `apps/test-bundles` -> this was fixed https://github.com/microsoft/fluentui/pull/28374


-> this should not longer occur thus closing as resolved

**Closed by Hotell** 2023-07-04 09:49 UTC
Labels: Type: Bug :bug:, Area: Build System, Fluent UI react (v8), CI
