### ISSUE TITLE
[Bug]: GroupListV2 cannot drag and drop item to group level

### ISSUE THREAD

**Issue by jarvan-jiang** [microsoft/fluentui#32041] opened 2024-07-18 05:47 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 2.61 GB / 15.73 GB
  Browsers:
    Chrome: 126.0.6478.182
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/jarvan-jiang/pen/XWLXVGm

## Actual Behavior
While using `GroupedListV2 `with drag and drop, it shows not able to drop item to group level.
But if do not use `GroupedListV2`, then it shows normal to able drop item to group level.
Please check the gif:
![Screenity video - Jul 18, 2024 (1)](https://github.com/user-attachments/assets/4ae01d08-8520-4ca1-b88f-36d2c872956c)

## Expected Behavior
Able to drop item to group level.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by jarvan-jiang** [comment] 2024-07-19 05:50
According to [this comment](https://github.com/microsoft/fluentui/issues/24797#issuecomment-1372728836), does it means drag and drop is not implemented in GroupListV2? Also I checked the code, seems in GroupListV2 there is no subscribe of dragDropHelper at all.

**Comment by sopranopillow** [comment] 2024-07-25 21:16
Hi @jarvan-jiang, you are correct, GroupedListV2 does not support drag and drop. At this point, we are not taking any feature requests for v8, so it will most than likely stay this way. Is there a chance for migrating to v9? Let me know if I can help. I'll close this since it's by design. Thanks for the issue!

**Closed by sopranopillow** 2024-07-25 21:16 UTC
Labels: Needs: Triage :mag:, Fluent UI react-northstar (v0)

**Comment by jarvan-jiang** [comment] 2024-07-26 01:45
Hi @sopranopillow , I didn't see any similar components in v9, only grid and tree, but seems they cannot merge to show as a nested grid, or am I missing something? Please guide me.

On the other hand, the temp solution for this in v8 is, overwrite the group header renderer, warp it with a `div` with drag events, then handle it manually.

**Comment by sopranopillow** [comment] 2024-07-26 16:23
@jarvan-jiang sadly, we don't have an ootb component for that :( it would involve creating the grouped behavior yourself.

**Comment by jarvan-jiang** [comment] 2024-07-29 08:00
> @jarvan-jiang sadly, we don't have an ootb component for that :( it would involve creating the grouped behavior yourself.

Well I guess that will be a huge barrier for migrating to v9...
But at least there will be some guidance of how to create by ourself.....right？
