### ISSUE TITLE
[Bug]: Coachmark's persistent beak does not point to the initial target when it expands into the teaching bubble

### ISSUE THREAD

**Issue by jayantdhawan** [microsoft/fluentui#27135] opened 2023-03-09 00:45 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 32.42 GB / 63.85 GB
  Browsers:
    Edge: Spartan (44.22621.1344.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/jayant9/pen/abaVzdx

### Bug Description

I have a coachmark next to a target that's hugging the left side of the window.

![image](https://user-images.githubusercontent.com/8561626/223886447-a3b21ea9-a484-42dc-9e02-a1ca835b3a2a.png)

The coachmark includes the following props. Note that I'm using `isPositionForced={false}` because otherwise the teaching bubble simply overshoots the window edge and part of it is then cut-off. So not setting this prop to `false` is _not_ an option.

```typescript
<Coachmark
    positioningContainerProps={{ directionalHint: DirectionalHint.bottomCenter, doNotLayer: false }}
    persistentBeak={true}
    isPositionForced={false}   
    ....
>
...
```

## Actual Behavior
When I hover over the coachmark and it expands into the teaching bubble, the persistent beak of the coachmark moves along with the teaching bubble, and no longer points to the target button.

![image](https://user-images.githubusercontent.com/8561626/223885470-5d45f37f-514e-4455-9a07-090f5cda5034.png)

## Expected Behavior
The persistent beak should not move with the expanding coachmark/teaching bubble and continue to point to the target.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment] 2023-03-27 13:13
Related to/possible duplicate of #27280.

**Closed** 2023-09-25 03:25 UTC
Labels: Type: Bug :bug:, Component: Coachmark, Needs: Investigation, Fluent UI react (v8), Resolution: Soft Close, Area: Components
