### ISSUE TITLE
[Bug]: Facepile addButtonProps does not override default addButton. 

### ISSUE THREAD

**Issue by fitzeris** [microsoft/fluentui#28099] opened 2023-06-01 20:40 UTC
### Library

v8

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 16.33 GB / 31.85 GB
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/fitzeris/pen/yLRmyEX

## Actual Behavior
- Make showAddButton true, then try to pass in a different iconProps to addButtonProps. The default addButton doesn't get replace, and both the new button and the old will be rendered. 

## Expected Behavior
The default addButton would be overwritten by the newly passed in icon. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chrisdholt** [comment] 2023-06-01 20:43
This is pretty clearly React and not Web Components. Unassigning myself and removing the web-components tag.

**Comment by Hotell** [comment] 2023-06-07 10:57
you are using the API wrong. what needs to be done is to use following `addButtonProps={{iconProps:{iconName: 'add'}}}`

which will render that add icon, although I don't think it's intended to work that way as it breaks the UI 
<img width="65" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/2586d339-7ae9-46fb-b4c6-4262e0fc1533">.

based on facepile API there is no official way how to change the icon within addButton - that's why it's called `add button` right ?

**Comment by fitzeris** [comment] 2023-06-07 18:03
So even though we can pass in iconProps through addButtonProps, it's not actually intended for us to be able to change the icon for the add button?

**Comment by sopranopillow** [comment] 2023-06-23 17:35
> @Hotell So even though we can pass in iconProps through addButtonProps within facepile, it's not actually possible to change the icon for the add button?

@fitzeris, the reason why it "supports" iconProps is because Facepile is using a BaseButton to render the add personas button:
![image](https://github.com/microsoft/fluentui/assets/5953191/1ae89ef7-13a1-4208-950d-8efe88d50091)

Now you can actually add it by doing what Martin is doing, but that is not correct since the button is a null render and you are forcing it to render the icon. I would strongly recommend against it. I'll close this as by design. You could try adding a custom Persona to mimic the behavior you want to achieve.

**Closed** 2023-06-23 17:36 UTC
Labels: Resolution: By Design, Fluent UI react (v8)
