### ISSUE TITLE
How to make select all checkbox always visible in DetailsList

### ISSUE THREAD

**Issue by Libinjoseph** [microsoft/fluentui#12975] opened 2020-05-02 07:01 UTC
I am using the DetailsList component to display a table. I am setting the prop
`checkboxVisibility={CheckboxVisibility.always}`
to make the checkboxes visible always. But this is not working for the select all checkbox which is in the header. Select All checkbox is visible only when I hover over it. I want the select all checkbox to be visible always. Any solution for this? Sample code below
`<DetailsList
    columns={this.columns}
    selectionMode={SelectionMode.single}
    items={this.items}
    checkboxVisibility={CheckboxVisibility.always}
    onRenderRow={this.renderRow}
    onRenderHeader={this.renderHeader}
/>`

**Comment by Libinjoseph** [comment] 2020-05-03 13:31
It is working in the code pen sample [https://codepen.io/libinpjoseph/pen/MWaOoYe](url), but the same code is not working in my project created from [https://developer.microsoft.com/en-us/fluentui#/get-started#option-2-create-react-app](url)

**Comment by aneeshack4** [comment] 2020-05-04 15:28
@Libinjoseph if it's working in the Codepen and not repro'ing on the isolated component, there's probably something in your project locally that's causing this. If you can provide us more details, we can maybe help you troubleshoot but this is clearly not a bug on the component.

**Comment by Libinjoseph** [comment] 2020-05-04 17:47
Updated office-ui-fabric-react version to 7 and is working now. Is it a bug in the older version?

**Comment by aneeshack4** [comment] 2020-05-05 15:33
@Libinjoseph not sure, but since it works in the latest master, going to close this isssue.

**Closed by aneeshack4** 2020-05-05 15:33 UTC
Labels: Component: DetailsList, Resolution: Not An Issue
