### ISSUE TITLE
Impossible to set default value for the time picker

### ISSUE THREAD

**Issue by manishvicky** [microsoft/fluentui#20379] opened 2021-10-27 09:04 UTC

**Comment by gouttierre** [comment] 2021-11-09 14:48
@manishvicky - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@lorejoh12  - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @khmakoto

**Comment by daniharo** [comment] 2021-11-28 18:09
Duplicate of #19554, probably solved by #20805

**Comment by CheerfulSatchel** [comment] 2021-11-29 00:25
@daniharo Thank you for linking the PR to this!

**Comment by smhigley** [comment] 2022-05-20 21:54
This was fixed in the linked PR, I verified that it is possible to set a default value now.

**Closed by smhigley** 2022-05-20 21:54 UTC
Labels: Component: DatePicker, Needs: Investigation
