### ISSUE TITLE
[Bug]: Selection is not working as expected

### ISSUE THREAD

**Issue by bhanu345-cmd** [microsoft/fluentui#25614] opened 2022-11-10 13:59 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react:^8.77.3
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/blissful-hellman-bqckm9?file=/src/App.tsx

## Actual Behavior
Selection should be available. on selection item must be selected.

## Expected Behavior
I have customdetailslist component. I am passing items, columns, selection as props to that component. on selection changed i want to keep all selected items to my state and need to display count and detailslist. Or else i need to display only details list.
For this behaviour I am rendering details list like

 

```
const CustomDetailsList: React.FC<IDetailsListProps> = (props) => {
  const [items, setItems] = React.useState<any[]>([]);
  const [columns, setColumns] = React.useState<IColumn[]>([]);
  useEffect(() => {
    if (props.items) {
      setItems(props.items);
    }
  }, [props.items]);

  useEffect(() => {
    if (props.columns) {
      setColumns(props.columns);
    }
  }, [props.columns]);

  return <DetailsList {...props} items={items} columns={columns} />;
};
export default CustomDetailsList;



export default function App() {
  const [items, setItems] = useState<IItem[]>([]);
  const [selectedItems, setSelectedItems] = useState<IItem[]>([]);
  const [columns, setColumns] = useState<IColumn[]>([
    { key: "name", fieldName: "name", minWidth: 100, name: "Name" },
    {
      key: "location",
      fieldName: "location",
      minWidth: 100,
      name: "Location"
    },
    { key: "state", fieldName: "state", minWidth: 100, name: "State" }
  ]);
  const [selection] = useState(
    new Selection({
      onSelectionChanged: () => {
        console.log("trigered");
        setSelectedItems(selection.getSelection() as IItem[]);
      }
    })
  );

  useEffect(() => {
    let newItems: IItem[] = [];
    for (let i = 0; i < 9; i++) {
      newItems.push({
        id: i,
        name: "name" + i,
        location: "Mumbai",
        state: "Mumbai"
      });
    }
    setItems(newItems);
  }, []);

  useEffect(() => {
    console.log("Selected Items", selectedItems);
  }, [selectedItems]);

  const renderDetailsList = () => {
    return (
      <CustomDetailsList
        items={items}
        setKey={"set"}
        columns={columns}
        selection={selection}
        selectionMode={SelectionMode.multiple}
        selectionPreservedOnEmptyClick={true}
        checkboxVisibility={1}
      />
    );
  };

  return (
    <div className="App">
      {selectedItems.length > 0 ? (
        <div className="side-side">
          <h1>Selected {selectedItems.length} items</h1>
          {renderDetailsList()}
        </div>
      ) : (
        renderDetailsList()
      )}
    </div>
  );
}

```

On selection intially OnSelectionChanged method is being called and setting selected items to state. Immediately after again it is making selected items empty. Since it is unmounting at one place and remounting at another place i feel OnSelectionChanged method is being triggered and making selected items empty and selection is also lost. I dont want my selected items to be empty untill we manually deselect the selection. I have added useEffect you can check in codepen as soon as selectedItems are being set immediately again it is automatically making selectedItems empty.

When we rendering details list in ui on conditional basis at different places as shown in above app component how to persist the selection.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment] 2022-11-10 14:02
This seems to be v8 @bhanu345-cmd

**Comment by bhanu345-cmd** [comment] 2022-11-15 03:57
Can any one of you look into this as soon as possible?

**Comment by ling1726** [comment] 2022-11-16 15:00
Duplicate of #25610

**Closed by ling1726** 2022-11-16 15:00 UTC
Labels: Needs: Triage :mag:, Fluent UI react (v8)
