### ISSUE TITLE
TextField's `canRevealPassword` button shows no outline on focus

### ISSUE THREAD

**Issue by ibrosen** [microsoft/fluentui#18908] opened 2021-07-12 19:19 UTC
### Environment Information

- **Package version(s)**: @fluentui/react v ~8.22 (it repro'd on a clean version of the main branch as of the posting of this issue)
- **Browser and OS versions**: Windows 10, Edge and Chrome v latest (it's not a browser / OS problem)

### Describe the issue:

When tabbing to the "Reveal Password" eye icon, no focus outline is shown.

#### Actual: (yes this is w/ the icon actually focused)
![image](https://user-images.githubusercontent.com/24663638/125331471-dfd75800-e2fc-11eb-916d-4014cc3e838a.png)

#### Expected:
![image](https://user-images.githubusercontent.com/24663638/125331428-d51cc300-e2fc-11eb-9ee3-8f3c53391b14.png)

### Documentation describing expected behavior

https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7b5ED5CC1A-4764-40CD-8F53-C8107BA0D5A2%7d&file=MAS%202.4.7%20%E2%80%93%20Focus%20Visible%20.docx&wdLOR=c651B304E-2BC4-4A72-B13D-C09B41B14249&action=default&mobileredirect=true

**Comment by ibrosen** [comment] 2021-07-12 19:23
#18909

**Comment by ecraig12345** [comment] 2021-07-12 21:22
Duplicate of #18900

**Closed by ecraig12345** 2021-07-12 21:22 UTC
Labels: Needs: Triage :mag:, Status: In PR
