### ISSUE TITLE
[Bug]: The Callout onDismiss handler is not triggered when clicking a different iframe

### ISSUE THREAD

**Issue by MemMaoxin** [microsoft/fluentui#26927] opened 2023-02-21 12:22 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Package version(s): "@fluentui/react@8.106.0"
Browser and OS versions: Microsoft edge/Version 110.0.1587.49
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/xinxinZZZ/pen/gOdPqQN?editors=1111

### Bug Description
Steps:
  1. Open codepen: https://codepen.io/xinxinZZZ/pen/gOdPqQN?editors=1111
  2. Press the show callout button. A callout should appear.
  3. Click the square box (iframe). Notice that the callout does not disappear and onDismiss handler is not called.

## Actual Behavior
When clicking inside an iframe (but outside of the callout), the callout is not dismissed.

## Expected Behavior
When clicking outside the callout, the onDismiss handler should be triggered, and the callout should disappear.

## Possible Cause
I think the reason is the method "dismissOnTargetWindowBlur" handle the evt incorrectly in https://github.com/microsoft/fluentui/blame/master/packages/react/src/components/Callout/CalloutContent.base.tsx.
![image](https://user-images.githubusercontent.com/29158151/220338504-83fc75aa-2e92-40f9-8814-dd624e0b4401.png)

When we click inside an iframe,  the result of "targetWindow.document.hasFocus()" is true, so the onDismiss method in 348 lines wouldn't be executed.
So we should add this logic as follows:
`      if (
        ((preventDismissOnEvent && !preventDismissOnEvent(ev)) ||
          (!preventDismissOnEvent && !preventDismissOnLostFocus)) &&
        (!targetWindow?.document.hasFocus() || ev.target === targetRef.current) &&
        ev.relatedTarget === null
      ) {
        onDismiss?.(ev);
      }
`

### Requested priority

Blocking

### Products/sites affected

Updates App and Approvals App in Teams

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment] 2023-02-21 16:09
Duplicate of #22133

**Comment by MemMaoxin** [comment] 2023-02-22 07:15
Hi @micahgodbolt, I have careted a pr to solve this problem: https://github.com/microsoft/fluentui/pull/26930. Please help review, thanks!

**Closed** 2023-02-25 18:00 UTC
Labels: Resolution: Duplicate, Fluent UI react (v8)
