### ISSUE TITLE
ContextualMenu item is not ellipsed

### ISSUE THREAD

**Issue by fildahui** [microsoft/fluentui#23580] opened 2022-06-16 15:23 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 15.14 GB / 31.73 GB
Browsers:
    Chrome: 102.0.5005.115
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://codesandbox.io/s/sweet-spence-tw88p4

## Actual Behavior
The contextual menu is not ellipsing its items when they exceed the available width defined by the callout container

## Expected Behavior
Items exceeding the available width should be ellipsed (their text content)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment] 2022-07-18 11:54
@fildahui - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by spmonahan** [comment] 2022-07-21 19:37
This looks like a bug. `text-overflow: ellipsis` is being applied to the text but the container itself is expanding beyond the width of the `ContextualMenu`.

![contextualmenu itemtext devtools](https://user-images.githubusercontent.com/93940821/180301025-35408e5b-16e7-4dce-a9f8-5cf9bf6fbea8.png)

**Comment by bishalkar10** [comment] 2023-05-30 21:06
Hi, I am very new to programming. I would like contribute to open source. Can someone confirm if I am eligible for this ....?

**Comment by spmonahan** [comment] 2023-05-31 14:49
If you can follow the [contributing guide](https://github.com/microsoft/fluentui/wiki/Contributing), code up a fix and file a PR I don't see why you wouldn't be eligible :)

**Comment by Shubhabrata08** [comment] 2023-08-30 18:09
<img width="857" alt="image" src="https://github.com/microsoft/fluentui/assets/35366351/11b36ac6-f366-4be7-85c5-9b7a8268110b">
Couldn't repro the issue in the latest version.... Has this issue been fixed in some other PR?

**Comment by thesharifi** [comment] 2023-10-02 04:48
@spmonahan, I am interested in contributing to this repo, what is the status of this issue, if it is not resolved yet, please assign it to me.

**Closed** 2024-04-28 01:33 UTC
Labels: Type: Bug :bug:, Good First Issue 🏆, Component: ContextualMenu, Fluent UI react (v8), Resolution: Soft Close
