### ISSUE TITLE
[Bug]: Nav focus outlines cut off for first item and nav sub items

### ISSUE THREAD

**Issue by mashenoy** [microsoft/fluentui#32880] opened 2024-09-20 17:46 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 40.38 GB / 63.95 GB
  Browsers:
    Edge: Spartan
```

### Are you reporting an Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/xryxbj?file=package.json

## Actual Behavior
Able to repro issue on Fluent Dev site:https://react.fluentui.dev/?path=/docs/preview-components-nav--docs
Stackblitz link: https://stackblitz.com/edit/xryxbj?file=package.json

Top outline cut off for first item
![image](https://github.com/user-attachments/assets/b21766dc-7c1b-49a3-b46a-a15aaf650793)

Bottom outline cut off for Nav sub items
![image](https://github.com/user-attachments/assets/9096eaeb-487d-4d12-9cd8-f17f116ac192)

## Expected Behavior
Focus outlines should not be cut off

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment] 2024-09-20 20:36
Duplicate of #31745

**Closed by mainframev** 2024-09-20 20:36 UTC
Labels: Resolution: Duplicate, Fluent UI react-components (v9)
