### ISSUE TITLE
Required ARIA child role not present: textbox showing up for Dropdown in accessibility insights fast pass

### ISSUE THREAD

**Issue by priaajais1** [microsoft/fluentui#18333] opened 2021-05-26 04:31 UTC
### Environment Information

- **Package version(s)**: 8.14.15
- **Browser and OS versions**: Chrome, Windows 10(19043.985)

### Describe the issue:

Run accessibility insights tools for web on https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown
There are error identified by [Accessibility insights for web](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni)

### Please provide a reproduction of the issue in a codepen:

- Open https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown
- run Fast pass using the extension [Accessibility insights for web](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni)

Expected: There should be no errors
#### Actual behavior:

Error as below
![image](https://user-images.githubusercontent.com/76722999/119602696-8f358b00-bda0-11eb-90fe-3d98420fe18b.png)

Path | #Dropdown3963
-- | --
&lt;div data-is-focusable="true" data-ktp-target="true" id="Dropdown3963" tabindex="0" role="combobox" aria-haspopup="listbox" aria-expanded="false" aria-label="Example theme" class="ms-Dropdown dropdown-177"&gt;
Fix the following:Required ARIA child role not present: textbox

#### Expected behavior:

No errors should show up

### Documentation describing expected behavior

https://accessibilityinsights.io/info-examples/web/aria-required-children/

**Comment by TristanWatanabe** [comment] 2021-05-26 18:57
This is a duplicate of #17838 and #17981 which ended up being a an axe-core issue (details in : https://github.com/microsoft/fluentui/issues/17838#issuecomment-824442277). Will close this now.

**Closed by TristanWatanabe** 2021-05-26 18:57 UTC
Labels: Resolution: External
