### ISSUE TITLE
Selection does not work/look correct if all items should be disabled but selected state should be kept

### ISSUE THREAD

**Issue by lukasbash** [microsoft/fluentui#12626] opened 2020-04-09 13:56 UTC
### Environment Information

- **Package version(s)**: 6.211.6
- **Browser and OS versions**: Google Chrome 81.0.4044.92 on macOS 10.15.4

### Please provide a reproduction of the bug in a codepen:

Not entirely sure if this is the correct code in the pen, but I will try to explain the behaviour below. 
https://codepen.io/lukasbash/pen/wvKvebZ?editors=0010

#### Actual behavior:

Given that **N** items have been selected in the list and I disable the items selection, the checkboxes disappear while the state is kept (IMHO correct that the selected state is kept here).
To make this work I have to use my property (which indicates that the items should be unselectable) in multiple places:

- `<MarqueeSelection ... isEnabled={this.state.canSelectItem}>`
- `<DetailsList ... disableSelectionZone={!this.state.canSelectItem} />`
- `new Selection({ ..., canSelectItem: () => this.state.canSelectItem })`

#### Expected behavior:

As all of the above mentioned usages have one reference in common (i.e. the `Selection`), every component should determine if an item can be selected by calling the `canSelectItem` method on the selection.
In addition to that I think it makes sense to display the selection checkbox regardless of the disabled state, but rather apply a style on it (e.g. reducing the opacity). Otherwise the selected items are hard to see.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by joschect** [comment] 2020-04-09 22:15
@lukasbash Thanks for submitting this! It seems that there are a few questions that I'd like to clarify.

1. How to achieve preserving selection and selection icons while disabling the ability to select an item. 
* This appears like it is already possible if, perhaps confusingly, canSelectItem always returns true. (See screenshot below and [this fork of your codepen](https://codepen.io/slimemold/pen/VwvwVVr?editors=0010) while both MarqueeSelection and Details list are disabled as you indicate.
2. What is the correct way to prevent selection?
* I agree that it seems that if canSelectItem returns false, that selection should be prevented. It seems that canSelectItem is not honored and I don't see it being checked in Selection. @dzearing might be able to chime in about expected behavior there.
3. How should disabled selected items appear if the icon still appears?
* There is likely a way to do this with styling. But I'm not quite sure since details list can be complicated.

**Comment by lukasbash** [comment] 2020-04-15 06:25
It seems like your codepen does what it actually should do. Still as you mentioned, the canSelectItem method of the selection options should be the only source of truth for all selection-related components.
You got me with the third point as well. This component is just ultra complex and I'd prefer a styling from your side.

Can I expect this to be fixed in source?

**Comment by joschect** [comment] 2020-04-17 00:41
@lukasbash We can fix it, but it depends on expected behavior. I'm not sure if it's intended that selection is preserved or if "disabled" selection means something else. We definitely don't have a notion of "disabled" selection outside of removing the selectable icon. 

We'll need to have some discussion about the expected behavior of selection first, then about how that should impact look and feel.

@dzearing Could you chime in about expected behavior about selection and canSelectItem?

**Closed** 2021-04-26 12:01 UTC
Labels: Component: MarqueeSelection, Component: Selection, Needs: Discussion, Resolution: Soft Close, Type: Bug :bug:
