### ISSUE TITLE
[Bug]: V9 Theme Designer does not use key color value in generated palette

### ISSUE THREAD

**Issue by joselarios** [microsoft/fluentui#28901] opened 2023-08-17 14:24 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: MacOS 13.4.1
    CPU: Apple M1 Max
    Memory: 64 GB
  Browsers:
    Firefox: 116.0.2 
    Google Chrome: 115.0.5790.102
    Microsoft Edge: 115.0.1901.203
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/theme-theme-designer--page

## Actual Behavior
When the Key color value is set, the generated palette does not include this Key color in any of the brand ramp values. 

## Expected Behavior
When a Key color value is set, the generated palette should include this value as one of the brand ramp values. I believe the Key color value should be the "Teams 80" value.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment] 2023-08-30 23:39
This is by design, because its not always possible to use that key color for the primary value due to how well it contrasts with the text.

So the best we can do is create an array of color values that passes through that key color, and find evenly spaced values across it that meet required contrast ratios. 

The produced palette is just a suggested starting point, so feel free to adjust the 16 palette values being passed into the theme function.

**Comment by spmonahan** [comment] 2023-08-31 16:43
Closing this since Theme Designer is working as designed.

**Closed by spmonahan** 2023-08-31 16:43 UTC
Labels: Resolution: By Design, Fluent UI react-components (v9)
