### ISSUE TITLE
Update the peerDependencies for fluent UI

### ISSUE THREAD

**Issue by sirdawidd** [microsoft/fluentui#21002] opened 2021-12-13 14:36 UTC
Some packages are still have old react version in peerDependencies   . Because of that i see a lot of warnings on my build pipeline.

npm WARN @uifabric/file-type-icons@7.8.5 requires a peer of @types/react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fluentui/theme@1.7.4 requires a peer of @types/react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uifabric/utilities@7.33.5 requires a peer of react@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.

Please update peerDependencies  to the latest React version.

**Comment by layershifter** [comment] 2021-12-13 15:08
Duplicate of #20997, see https://github.com/microsoft/fluentui/issues/20997#issuecomment-992571458.

**Closed by layershifter** 2021-12-13 15:08 UTC
Labels: Resolution: Duplicate
