### ISSUE TITLE
TagPicker suggestion text remains even after closing the suggestions list

### ISSUE THREAD

**Issue by AndrewCraswell** [microsoft/fluentui#13692] opened 2020-06-18 20:36 UTC
### Environment Information

- **Package version(s)**: 7.119.1

### Describe the issue:

When using arrow keys to navigate Tag Picker suggestions, the suggestion text is auto-filled into the input element. However, if the user presses Esc to close the the suggestions list without choosing one, the the last viewed suggestion is left in the input.

This was flagged by the HCL accessibility team during an a11y review before a release.

### Please provide a reproduction of the issue in a codepen:

This behavior can be seen directly from the Tag Picker docs page:
https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers

#### Expected behavior:

Suggestions under the Tag Picker should not get selected automatically while closing the suggestions using Esc key.
Suggestions should get selected only on pressing Enter key after navigating to the suggestions using down arrow key.

The full detailed issue filed by the HCL team can be found in our ADO. I can giveaccess permissions to anyone who wants to check. There is an attached video and screenshots.
https://worldwidelearning.visualstudio.com/Common/_sprints/taskboard/Personal%20Learner%20Graph/Common/FY20-Q4/Sprint%202012?workitem=1081461

**Comment by paulgildea** [comment] 2020-06-19 16:21
We need to determine if this can be released in the current version or if this has to be something in the next version of the library.

**Comment by joschect** [comment] 2020-06-24 22:58
@paulgildea  and @AndrewCraswell This is expected behavior and is intended, at least it was at the time of design. The Suggestion is not automatically selected, When you press escape the text is left in the textfield, but it has not been "completed". That is why the text is still highlighted as in
![image](https://user-images.githubusercontent.com/20801176/85635536-eb44dc00-b632-11ea-855a-7450b7e086fd.png)

If you tab out and tab back in, the correct text will be selected as well. Further more if the user begins typing it erases the pervious input. 

For the expected behavior, a possible alternative which makes sense in some instances would be to have escape clear out the input. But that would require some design review.

**Comment by AndrewCraswell** [comment] 2020-06-25 19:57
Thanks @joschect, I think this makes sense. After testing it again I see what you're saying. Where it looks like it's leaving the full tag text in the picker, it hasn't actually been "completed". If you don't mind, I will update the HCL accessibility testing team for feedback -- otherwise this should just be closed by next week.

**Closed** 2021-04-26 12:00 UTC
Labels: Area: Accessibility, Component: TagPicker, Needs: Behavior Breaking Change, Needs: Discussion, Priority 2: Normal, Resolution: Soft Close, Type: Bug :bug:
