### ISSUE TITLE
[Bug]: Tree - No mixed checkbox state available when using controlled selection

### ISSUE THREAD

**Issue by manufz** [microsoft/fluentui#31921] opened 2024-07-04 08:53 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Memory: 3.02 GB / 15.71 GB
Browsers:
  Edge: Chromium (126.0.2592.87)
  Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-tree--default#selection

### Bug Description

When using an uncontrolled selection state, the parent checkbox correctly displays a partially checked state if some of its child nodes are selected. However, this functionality is not automatically handled in a controlled selection state. Furthermore, the FlatTreeItem does not provide an option to manually set this partial checked state.

Added link to documentation as reproduction url but actually this scenario is missing from documentation.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment] 2024-07-08 14:19
Need to discuss with @bsunderhus

**Comment by bsunderhus** [comment] 2024-07-15 09:08
Hey @manufz. let's go by points:

> this functionality is not automatically handled in a controlled selection state

I believe this will probably never be automatically handled by the Tree. We'd need to know beforehand every single possible tree item on a tree, this would require some property like `treeItems` in the `Tree` component where the client would provide all the structure of the tree as a single object (this is not recommended for multiple cases, like virtualization and compound components splitting also makes it harder for memoization)

> Furthermore, the FlatTreeItem does not provide an option to manually set this partial checked state.

You're completely right, at the moment selection control is only supported on the root `Tree` element, through the `checkedItems` property. 

@miroslavstastny  we need to discuss the support of this on the level of the tree item instead of the tree.

**Comment by bsunderhus** [comment] 2024-07-18 14:56
> this functionality is not automatically handled in a controlled selection state

This won't be implemented by our side @manufz .

There's no way we can enforce how the controlled state is provided, there are use cases where the `mixed` checkbox are desired, and there are some on which they aren't, and it becomes the user's responsibility to assign them properly according to their logic.

> Furthermore, the FlatTreeItem does not provide an option to manually set this partial checked state.

Just to be clear, this is a Feature, not a bug.

This is also not desirable, for a few reasons:

1. every single component that support controlled checked states in multiple compound components in v9. do so by providing it on the parent component ([Menu](https://react.fluentui.dev/?path=/docs/components-menu-menu--default#controlled-checkbox-items), [List](https://react.fluentui.dev/?path=/docs/preview-components-list--default#single-action-selection-controlled), ...)
2. In the Tree itself the problem would be even bigger than the other components, as the `Tree` has a nested recursive structure that rely on it's parent recursion to make sense
3. To control selection state you need to know about all the state at once to determine the selection of each item, by splitting that state per item we're disassociating this necessity, which might lead into a lot of bugs

**Closed by bsunderhus** 2024-07-18 14:56 UTC
Labels: Needs: Discussion, Type: Feature, Fluent UI react-components (v9), Component: Tree

**Comment by bau11977** [comment] 2024-07-29 11:22
@bsunderhus I find it quite limiting that the Tree component doesn't support this with a controlled state. I don't think many real-world applications are using the uncontrolled component. I'm not asking for automatic handling but an option to control this state like any other. Is there maybe a workaround to achieve the desired scenario?
