### ISSUE TITLE
Tooltip + Dialog : ESC key has unpredictable behavior

### ISSUE THREAD

**Issue by sabintim** [microsoft/fluentui#15811] opened 2020-11-03 01:30 UTC
There was a related bug that was recently fixed: https://github.com/microsoft/fluentui/issues/14465

When I put a button with a tooltip in a dialog, one of the two things happen when I press ESC:
1. Tooltip dismisses, and the subsequent ESC key press doesn't close the dialog. Looks like the key press is swallowed even though the tooltip is gone.
2. The whole dialog dismisses when trying to dismiss the tooltip. To repro, first click on the middle part of the dialog, then hover over the button to bring up a tooltip, then press ESC.

Looks like there was confusion in other products as well about ESC key behavior, e.g., this bug filed earlier that seeks Ctrl key as an alternative: https://github.com/microsoft/fluentui/issues/14987
Although, current W3C guidance has ESC key as the tooltip dismiss key.
https://w3c.github.io/aria-practices/#tooltip

### Environment Information

- **Package version(s)**: 7.149.3
- **Browser and OS versions**: I don't think it is relevant, but Mac + Edge latest

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/sabint/pen/jOrKEyb

#### Actual behavior:
When there is a tooltip within a dialog:
ESC key dismisses the whole dialog when tooltip is visible via mouse hover.
ESC key fails to dismiss the dialog in some cases after dismissing the tooltip.

#### Expected behavior:
When there is a tooltip within a dialog:
ESC key should only close the tooltip (and not close the dialog) when tooltip is visible.
ESC key should close the dialog when tooltip is not visible.

### Priorities and help requested:

Are you willing to submit a PR to fix? Not in the near term
Requested priority: Normal

Products/sites affected: SharePoint website

**Comment by paulgildea** [comment] 2020-11-03 17:01
@sabintim Thanks for filing this issue.

@smhigley We could use some clarity/verification on the expected pattern. 

@joschect / @micahgodbolt FYI

@behowell Is it possible to find a app workaround for this type issue? Is it possible for a customer to listen for ESC, route it to the `Tooltip` when shown? That might be the best course of action in the meantime for the desired behavior.

**Comment by sabintim** [comment] 2020-11-05 16:36
Added some clarification to expected/actual behavior in the description.

**Comment by mltejera** [comment] 2020-11-16 20:38
+1 on this issue. We're seeing it manifest in our WCAG 2.1 compliant Panel wrapper and now getting MAS accessibility bugs filed on this behavior.

In our wrapper, we had to build and pass in a custom nav that wraps the close button in a ToolTip host. It was required to add a text based label for screen readers because the icon button lacks a  direct label or tool tip prop.

Since the close button is the first element focused on opening the panel, the user must now tab until something without a TooltipHost is focused before they can use esc to close the panel. Compare this to the expected behavior when hitting esc any time should close the panel.

@paulgildea, do you have any guidance on this one? Are we stuck until we can move to the buttons in V8?

**Comment by stefaniehansen** [comment] 2020-11-19 00:51
It looks like they should check if the tooltip is visible before attempting to handle the keydown event for Escape:
<img width="341" alt="Screen Shot 2020-11-18 at 4 50 32 PM" src="https://user-images.githubusercontent.com/31112980/99606271-47334700-29be-11eb-956d-7a690f8eb968.png">

**Comment by stefaniehansen** [comment] 2020-11-19 02:09
I've made an attempt at a PR.

**Comment by stefaniehansen** [comment] 2020-11-20 19:53
FYI for those that are using version 8, I have an open PR cherry-picking this change there as well. https://github.com/microsoft/fluentui/pull/16011

**Comment by ecraig12345** [comment] 2021-02-18 07:21
Closing this since it's been fixed (not sure why it didn't get closed automatically)

**Closed by ecraig12345** 2021-02-18 07:21 UTC
Labels: Component: Dialog, Component: Tooltip, Fluent UI react, Needs: Investigation, Status: Fixed
