### ISSUE TITLE
DetailsList: Focus rect does not scroll current item into view with narrator turned on

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#18869] opened 2021-07-08 18:34 UTC
### Environment Information

- **Package version(s)**: 8.22.2
- **Browser and OS versions**: Win 10 + Edge

### Describe the issue:
Turn on Narrator
Navigate to any detailsList that scrolls
Use Ctrl+alt+up/down arrows to navigate the list.
Move down such that the blue focus rect goes below the view port allocated for the list

#### Actual behavior:

See that the blue focus rect moves below the view port and does not scroll the list such that the selected item is in view.

#### Expected behavior:

The details list should scroll itself to keep the selected item in view.

**Comment by ling1726** [comment] 2021-07-09 06:31
@smhigley  I am not very aware of correct screen reader behaviour here, could you confirm if this is a bug ?

**Comment by ltackett** [comment] 2021-07-09 20:57
I'm running into a similar issue with the basic `<List />` component, and although it was initially reported to my team as an accessibility bug, we've discovered that it doesn't appear to be solely related to a11y. I am able to reproduce the issue by scrolling very slowly. In some cases, it can be quite severe:

![image](https://user-images.githubusercontent.com/12592/125134598-7537d980-e0bc-11eb-84ae-460b3e445ea0.png)

Red outline added to `div.ms-List-page` to be able to properly visualize the problem. On the left, I have scrolled very slowly, and a new `div.ms-List-page` hasn't been rendered for quite awhile. On the right, I've finally scrolled enough for the next `div.ms-List-page` to render. I've found nothing in the Fluent documentation that helps other than simply not virtualizing (not an option in our case). It would be ideal if we could always render more pages ahead and behind than we need.

Nothing about our implementation appears to be non-standard, in terms of using and configuring `<List />`, so I'm wondering if we are also experiencing some form of the issue outlined here on Github.

**Comment by smhigley** [comment] 2021-07-19 16:38
@mltejera since the focus rectangle in DetailsList isn't blue in our default styles, I'm going to guess you mean the Narrator cursor since that is blue by default.

It's a known issue that Narrator does not scroll in-page `overflow: scroll` elements based on the virtual cursor position. This isn't something we have any control over in Fluent, it'd need to be taken up with the Narrator team directly.

@ltackett does the issue you're mentioning repro on any of the examples in our List example page? (https://developer.microsoft.com/en-us/fluentui#/controls/web/list)

**Comment by smhigley** [comment] 2021-07-19 16:47
Actually, @ltackett, would you mind opening a new issue for what you're describing? It's unrelated to the Narrator virtual cursor/scroll issue, and it'd be good to have a separate issue for that one.

I'm going to close this one, since it's not an issue with Fluent, or something we have any control over.

**Closed by smhigley** 2021-07-19 16:47 UTC
Labels: Area: Accessibility, Needs: Investigation

**Comment by ltackett** [comment] 2021-07-20 21:14
@smhigley done.
https://github.com/microsoft/fluentui/issues/19030
