### ISSUE TITLE
SwatchColorPicker moves/shrinks on mouse hover

### ISSUE THREAD

**Issue by imdavidmin** [microsoft/fluentui#17974] opened 2021-04-27 16:59 UTC
### Environment Information

- **Package version(s)**: 8

### Please provide a reproduction of the bug in a codepen:
From official documentation example
[Codepen](https://codepen.io/pen/?&prefill_data_id=04cba4a6-5e06-4a66-aa8a-ba04bdad743a)

#### Actual behavior:

![image](https://user-images.githubusercontent.com/48481563/116281952-239cd580-a782-11eb-994d-b2562fa86129.png)

#### Expected behavior:
Alignment/size in the above is not affected. 

### Priorities and help requested:

Are you willing to submit a PR to fix? **No**

Requested priority: **Normal**

**Comment by ecraig12345** [comment] 2021-05-04 00:57
It looks like you've linked to a blank pen, instead of saving your work. Can you please create the pen again and be sure to click Save?

**Comment by imdavidmin** [comment] 2021-05-04 10:03
> It looks like you've linked to a blank pen, instead of saving your work. Can you please create the pen again and be sure to click Save?
It's on official docs page. 
https://developer.microsoft.com/en-us/fluentui#/controls/web/swatchcolorpicker

**Comment by imdavidmin** [comment] 2021-06-21 17:43
Is this issue being deprioritised for convergence work? Would have expected a production issue to be resolved within this leisurely time frame of 2 months... If someone could give an insight on this, would be much appreciated! Thanks.

**Comment by ecraig12345** [comment] 2021-06-21 23:57
In an ideal world we'd like to fix all the issues with all components, but we simply don't have enough resources or time, so we have to prioritize fixing issues vs. other work, such as converged components. This one didn't get prioritized when it was filed because while it's clearly not great, it's a visual-only issue (doesn't affect functionality) in a lower-usage component.

I looked at https://aka.ms/fluentdemo to figure out when this was introduced--apparently it was caused in 7.98.4 caused by #12090, basically a style simplification that didn't account for cases where the vertical-align style was actually needed. 

The fix is in `packages/react/src/components/SwatchColorPicker/ColorPickerGridCell.styles.ts`, adding a `verticalAlign: 'top'` style under `colorCell`. You can also use the `getColorGridCellStyles` prop to work around the issue in your own code (https://codepen.io/ecraig12345/pen/mdWYWMO):
```tsx
const getColorGridCellStyles = () => ({ colorCell: { verticalAlign: 'top' } })

<SwatchColorPicker getColorGridCellStyles={getColorGridCellStyles} ... />
```

**Closed** 2021-06-26 07:31 UTC
Labels: Component: SwatchColorPicker, Contribution Candidate, Good First Issue 🏆, Status: Fix Proposed, Status: In PR, Type: Bug :bug:
