### ISSUE TITLE
SSR broken with @fluentui/react

### ISSUE THREAD

**Issue by akaila** [microsoft/fluentui#16885] opened 2021-02-09 08:04 UTC
### Environment Information

- **Package version(s)**:     
```
   "@fluentui/react": "^7.158.1",
   "@fluentui/theme": "^1.7.1",
   "@uifabric/fluent-theme": "^0.16.21",
   "gatsby": "^2.32.3",
```
- **Browser and OS versions**: Chrome 88.0.4324.150 / Others

### Please provide a reproduction of the bug in a codepen:
SSR bug and hence cannot be reproduced within codepen

#### Actual behavior:
Mergestyle breaks SSR, page gets loaded with almost no CSS other than gatsby index.css. I do see that JS is loaded in the page though.

#### Expected behavior:
Page loads with all CSS from fluentUI

When I replace the packages with the following (and replace imports) everything works fine:
```
    "@uifabric/fluent-theme": "^0.16.7",
    "gatsby": "^2.4.0",
    "office-ui-fabric-react": "^6.176.0",
```

Also the problem with @fluentui/react does not happen during gatsby develop, but rather in the static page generation. When HMR is running page loads fine. Upon doing gatsby build followed by gatsby serve and then visiting the page in localhost exposes the issue. I used gatsby starter project for this.

**Comment by joschect** [comment] 2021-02-09 17:10
@akaila Thanks for the submission! @dzearing or @xugao do you have any ideas about this? Is another plugin required to generate css on server side render?

**Comment by akaila** [comment] 2021-02-09 17:12
FYI I tried [gatsby plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-fabric-ui/) for fluent ui but it still did not resolve the issue.

**Comment by xugao** [comment] 2021-02-09 22:14
I don't have full context on what might have changed between v6 and v7. @akaila - can you check instructions [here](https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing) to see if you missed any setup?

**Comment by akaila** [comment] 2021-02-09 22:41
If you just check out the gatsby starter project and then do npm build followed by npm serve and open the page you should see the issue. I have checked the instructions and my code mimics the node code that you have there. In fact, I tried using both renderStatic imports but none works.

**Comment by ecraig12345** [comment] 2021-07-28 00:09
This seems like a duplicate of #3692.

**Closed by ecraig12345** 2021-07-28 00:09 UTC
Labels: Area: SSR (server-side rendering), Community Contribution, Needs: Backlog review, Type: Bug :bug:
