### ISSUE TITLE
use modularized fluent

### ISSUE THREAD

**Issue by zerofront** [microsoft/fluentui#12199] opened 2020-03-05 07:57 UTC
### Environment Information

- **Package version(s)**: Library: Fluent-ui-react
- **Browser and OS versions**: latest

### Please provide a reproduction of the bug in a codepen:

I want to use modularized fluent-ui
```javascript
import { Box, Provider, themes } from '@fluentui/react'
```

I only need Box Component, but there are many other components  In theme Object
like AvatarStyles、DialogStyles tec

#### Actual behavior:

in fluent-ui source code 
```javascript
export const themes = { fontAwesome, teams, teamsDark, teamsHighContrast };
```

#### Expected behavior:

what can I do if I only need teams themes?
what can I do if I only need some Components?

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High

Products/sites affected: Consumers should not be penalized for code they don't use (through bundle size, perf, etc).

**Comment by aneeshack4** [comment] 2020-03-05 08:08
Hi @zerofront, there's documentation & example code on the Fluent site about the case when you want to import just a few components & use the teams theme - is this what you're looking for? https://fluentsite.z22.web.core.windows.net/theming-examples

**Comment by zerofront** [comment] 2020-03-06 01:37
Hi @aneeshack4 , Thank you for your prompt reply

```javascript
import React from 'react'
import { Button, Icon, Label, Provider, themes } from '@fluentui/react'

export default () => (
  <Provider theme={themes.teams}>
    <Button content="Button" />
    <Button icon="add" iconOnly primary />
    <Button icon="email" content="Send email" secondary />
    <Icon name="emoji" size="larger" />
    <Label content="Label with icon" icon="close" />
  </Provider>
)
```
For this example, I just want to import Button、icon、Label Component，but in theme object, therer are many style of other component which is unnecessary。

**Comment by layershifter** [comment] 2020-03-06 14:41
@zerofront I opened #12224 to fix broken exports.

Future items:
- Fix https://github.com/microsoft/fluent-ui-react/issues/2325 to do not reference components in styles, i.e. a theme will not require components
- Remove icons from themes https://github.com/microsoft/fluent-ui-react/pull/2320 to allow import only needed icons

**Comment by xugao** [comment] 2020-07-16 21:57
@layershifter - doing some housekeep here. do you think we need to leave this issue open or can be closed?

**Comment by layershifter** [comment] 2020-07-17 08:10
@xugao I think that we can close this as a duplicate and keep #12953.

**Comment by jurokapsiar** [comment] 2020-08-10 09:11
Duplicate of #12953

**Closed by jurokapsiar** 2020-08-10 09:11 UTC
Labels: Fluent UI react-northstar, Type: Question ❔
