### ISSUE TITLE
[Bug]: Charting: customDateTimeFormatter and timeFormatLocale does not display the correct date for x axis

### ISSUE THREAD

**Issue by Gabnight** [microsoft/fluentui#31345] opened 2024-05-13 09:41 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (36) x64 Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
    Memory: 33.23 GB / 63.92 GB
  Browsers:
    Chrome: 124.0.6367.119
    Edge: Chromium (123.0.2420.97), ChromiumDev (126.0.2552.0)
    Internet Explorer: 11.0.19041.3636
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/Gabnight/pen/wvZLroo

### Bug Description

When creating point in local time zone (GMT +1 in the example) for line chart or area chart.
Ex:
{
x: new Date(2020,2,4),
xAxisCalloutData: new Date(2020,2,4),
y: 284000,
},
The x axis tick is set at 1 am with GMT +1 which makes UI weird because the tick is not aligned with the point.
Moreover, the localization of the date is broken because we need a date at midnight to display the day instead of time on the customDateTimeFormatter callback method.
It seems the date passed to the chart is handled as UTC even if GMT +1 value is specified in it.

Screenshot:
![image](https://github.com/microsoft/fluentui/assets/122602310/bd2ddc73-2909-4154-8397-b4f121a8e172)

Expected Behavior
point and tick should be aligned at midnight.
ex:
![image](https://github.com/microsoft/fluentui/assets/122602310/7fd4fe74-d9ac-439b-b7d7-4064c7f6af15)

Note:
This bug is also visible in the React-charting demo website:
https://developer.microsoft.com/en-us/fluentui#/controls/web/linechart
![image](https://github.com/microsoft/fluentui/assets/122602310/f5fd4314-062e-4346-883d-ba8fb01f388b)

This regression seems to have been brought about by this change:
![image](https://github.com/microsoft/fluentui/assets/122602310/3456dba8-2542-492e-a716-0459afe44913)
in the PR:
https://github.com/microsoft/fluentui/pull/30315

### Requested priority

High

### Products/sites affected

make.powerautomate.com, https://developer.microsoft.com/en-us/fluentui#/controls/web/linechart

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Gabnight** [comment] 2024-05-13 11:34
FYI, there is also an issue in the demo website for vertical bar chart:
![image](https://github.com/microsoft/fluentui/assets/122602310/a649e46e-3857-450e-bc78-9ca01e549ba9)

Regarding the title of the graph date should be displayed and not time.
From:
https://developer.microsoft.com/en-us/fluentui#/controls/web/verticalbarchart

**Comment by AtishayMsft** [comment] 2024-05-20 05:57
Duplicate of #31269

**Closed by AtishayMsft** 2024-05-20 05:57 UTC
Labels: Fluent UI react (v8)
