### ISSUE TITLE
Add the header navbar PLS

### ISSUE THREAD

**Issue by marcosteam** [microsoft/fluentui#13409] opened 2020-05-30 10:44 UTC
#### Describe the feature that you would like added

In the Fluent UI doc, it gives a way to add a navbar on the right, but it doesn't have a way to add a navbar on the top, like this:

![image](https://user-images.githubusercontent.com/25745812/83326295-83a2a780-a2a5-11ea-81bf-232b218a8cba.png)

#### What component or utility would this be added to

It should be add to the [nav](https://developer.microsoft.com/en-us/fluentui#/controls/web/nav) component.

#### Have you discussed this feature with our team, and if so, who

I search the issue, and I see some people have discussion on why still don't have a navbar which on the top.

**Comment by jdhuntington** [comment] 2020-06-01 16:50
Hi marcosteam - thanks for the request. A header component that would work with `Nav` makes sense.
I will keep this open as a feature request for a new component, though unfortunately we will not be able to address it in the near future.
If you need a header in the immediate term, I recommend looking at a project like https://github.com/microsoft/fluentui/tree/master/packages/example-app-base and mimicking the header component from there.

**Comment by ecraig12345** [comment] 2020-06-01 23:17
This is a duplicate of #10416, though @jdhuntington's response that this is something we won't immediately be able to get to still applies.

**Closed** 2020-06-05 00:00 UTC
Labels: Resolution: Duplicate, Type: Feature
