### ISSUE TITLE
Calendar component incorrect display

### ISSUE THREAD

**Issue by ghost** [microsoft/fluentui#9544] opened 2019-06-21 15:47 UTC
### Environment Information 
 
- __Package version(s)__: Fabric React 6
- __Browser and OS versions__: Internet Samsung and Android Pie

### Please provide a reproduction of the bug in a codepen:

 The majority of codepen sources available here: https://developer.microsoft.com/en-us/fabric#/controls/web/calendar

 
#### Actual behavior:
 
Go to today positioned behind the day numbers and an unexpected vertical line shown in the right margin.
 
#### Expected behavior:
 
Go to today positioned below the day numbers and no vertical line.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No.
 
Requested priority: Low.
 
Products/sites affected: All using the calendar component.

**Comment by aftab-hassan** [comment] 2019-06-21 19:38
@enriquejr99 thanks for posting an issue.

Could you please provide us a codepen or a screenshot of the issue you are seeing. I am looking at the examples page you linked to, but am unable to see the vertical line you mention. 

Also, what browser are you on? I tried looking at it in all of the supported browsers, but I might be missing something here; a codepen would be really useful.

**Comment by enriquejr99** [comment] 2019-06-21 19:54
@aftab-hassan here you have a codepen example: https://codepen.io/enriquejr99/pen/PrpRZz?&editable=true

I'm using the default web browser that comes pre-installed with all Samsung phones (Samsung Internet Browser 9.2.10.15). You can find it on the Google Play Store. I can also attach a screenshot if you are still unable to reproduce it.

**Comment by enriquejr99** [comment] 2019-06-21 19:58
I can also confirm this happens on mobile Chrome 74.0.3729.157.

**Comment by aftab-hassan** [comment] 2019-06-21 20:56
@enriquejr99 thank you, we see it.

<img width="191" alt="calendar-bug" src="https://user-images.githubusercontent.com/8922176/59950961-49d9e780-942c-11e9-8fa4-c11df79e1eac.PNG">

Marking as `bug`. We are working on a fix for this. Thank you for providing a codepen!

**Closed** 2021-05-24 16:02 UTC
Labels: Component: Calendar, Package: date-time, Resolution: Soft Close, Screen-size: small-screen, Type: Bug :bug:
