### ISSUE TITLE
[Bug]: fluentui v9 incompatible with react strict mode

### ISSUE THREAD

**Issue by j3rrym0use** [microsoft/fluentui#23748] opened 2022-06-28 07:54 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 3.70 GB / 15.53 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.37)
    Internet Explorer: 11.0.22000.120

React Version: 18.2.0
```

### Reproduction

https://codesandbox.io/s/elegant-hertz-4g4di1

## Actual Behavior
when enable react "strictmode", fluentui doesnt render any styles.
`import { FluentProvider } from "@fluentui/react-components";`
`import { StrictMode } from "react";`
`import * as ReactDOMClient from "react-dom/client";`

`import App from "./App";`

`const rootElement = document.getElementById("root");`
`const root = ReactDOMClient.createRoot(rootElement);`

`root.render(`
`  <StrictMode>`
`    <FluentProvider>`
`      <App />`
`    </FluentProvider>`
`  </StrictMode>`
`);`

by removing <StrictMode>, everything go normal.

## Expected Behavior
when enable react "strictmode", fluentui renders properly.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment] 2022-06-28 09:54
Duplicate of #23625.

P.S. `@fluentui/react-components` does not support React 18, yet, #22581.

**Closed by layershifter** 2022-06-28 09:54 UTC
Labels: Needs: Triage :mag:

**Comment by j3rrym0use** [comment] 2022-06-29 04:08
> 

copy understood.
