### ISSUE TITLE
Errors on Server Side Render in Some Components in NextJS - 

### ISSUE THREAD

**Issue by joaojmendes** [microsoft/fluentui#18605] opened 2021-06-17 20:21 UTC
react-dom.development.js?61bb:67 Warning: Prop `className` did not match. Server: "ms-Image-image ms-Image-image--portrait is-notLoaded is-fadeIn server-image-7" Client: "ms-Image-image ms-Image-image--portrait is-notLoaded is-fadeIn image-97"
    at img
    at div
    at eval (webpack-internal:///./node_modules/@fluentui/react/lib/components/Image/Image.base.js:61:59)
    at eval (webpack-internal:///./node_modules/@fluentui/utilities/lib/styled.js:19:57)
    at div
    at ResultComponent (webpack-internal:///./node_modules/@fluentui/foundation-legacy/lib/createComponent.js:42:99)
    at div
    at ResultComponent (webpack-internal:///./node_modules/@fluentui/foundation-legacy/lib/createComponent.js:42:99)

FluentUI version  8.19.1
node version: 14.17.0
MAC OS. Big Sur 11.4

running in dev env.  

npm run dev

**Comment by gouttierre** [comment] 2021-07-22 13:58
@joaojmendes - thanks for filing this item. Would you be able to share the full log/ Code-  if it is required?

@ling1726 -  Would you be able to confirm if this is a regression, or if its a component rendering behavioral issue?

**Comment by ling1726** [comment] 2021-07-23 08:16
@joaojmendes  unfortunately hydration errors are expected from Fluent v8, and this issue is documented in our wiki: https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing, we currently don't have resources to look into this further right now, I'm really sorry 😓

Fluent v9 is intended to support SSR correctly

**Comment by ling1726** [comment] 2021-07-23 08:16
If this warning impacts your app in anyway please let us know further in this issue

**Comment by ecraig12345** [comment] 2021-07-28 00:48
Duplicate of #3692

**Closed by ecraig12345** 2021-07-28 00:48 UTC
Labels: Needs: Author Feedback, Status: No Recent Activity, v8 release: regression or todo
