### ISSUE TITLE
NVDA is announcing column header name twice when navigating using NVDA table shortcut keys

### ISSUE THREAD

**Issue by kssuresh1993** [microsoft/fluentui#15443] opened 2020-10-09 11:09 UTC
### Environment Information
OS build Version 2004 (OS Build 19559.1000)
Edge Dev: 86.0.594.1 (Official build) 
Screen reader: NVDA

### Describe the issue:
Users who rely on screen readers are impacted as NVDA is announcing column header name twice when navigating using NVDA table shortcut keys

### Repro steps

1. Go to url  https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic
2. Verify the Detail List Column headers.

#### Actual behavior:
NVDA is announcing column header name twice when navigating using NVDA table shortcut keys

#### Expected behavior:

NVDA is announcing column header name only once when navigating using NVDA table shortcut keys

### Note
We are noticed  all 'Details List' headers
![New_Issue](https://user-images.githubusercontent.com/72542051/95578338-5df68d80-0a51-11eb-8302-8fdcc2dd37c8.png)
 is announcing same

**Comment by paulgildea** [comment] 2020-10-12 16:36
@kssuresh1993 Thanks for filing an issue!

**Comment by smhigley** [comment] 2021-02-10 19:01
This looks like a dupe of #14326, I think my comment here: https://github.com/microsoft/fluentui/issues/14326#issuecomment-774390601 would also apply to this issue.

I'm also still not able to reproduce the specific behavior shown in the speech viewer screenshot using NVDA table navigation. I have NVDA 2020.1, on Edge 88 (I also can't repro with NVDA on Edge 90, Chrome 88, or Firefox 84).

@kssuresh1993 if you still see that behavior in the current version of Edge, could you add your NVDA version, or maybe a video of the behavior + the exact interactions you're using?

**Comment by jennyshushe** [comment] 2021-03-18 23:26
@smhigley I can reproduce on the Fluent UI example website. 
Go to https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns
Start narrator, 
Focus on one of the column headers, the narrator will read: "key, button, column header, column header key, "
![image](https://user-images.githubusercontent.com/80926281/111710343-bbfc7d80-8806-11eb-991d-8122637c6160.png)

**Closed** 2022-02-13 13:00 UTC
Labels: Area: Accessibility, Component: DetailsList, Needs: Investigation, Area: NVDA, Resolution: Soft Close
