### ISSUE TITLE
[Bug]: DatePicker go to day button still highlight the previous day after day passed.

### ISSUE THREAD

**Issue by dinhitcom** [microsoft/fluentui#29716] opened 2023-11-01 07:21 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 AMD EPYC 9354 32-Core Processor
    Memory: 2.89 GB / 16.00 GB
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.76)
    Internet Explorer: 11.0.19041.3570
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/dinhit/pen/wvNWpBR

## Actual Behavior
Highlight the previous day 

## Expected Behavior
Highlight the current day

## Description
Steps
1. Open a page with DatePicker component
2. Select a date in the next month so the current day isn't displayed then keep the page open until the next day.
3. Visit the page on the next day, open the datepicker and click Go to today, it still highlights the previous day. 

Can be reproduced on Fluentui docs:
![WXWorkCapture_16988222982568](https://github.com/microsoft/fluentui/assets/69104714/032c1db3-a1ae-49f0-be85-022ec0eb71dc)
_Current date is 2023/11/01 but when click Go to today it hightlighted 2023/10/31_

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by LordOfCinder2000** [comment] 2023-11-01 08:13
Any update on this?

**Comment by luongnguyen008** [comment] 2023-11-22 04:42
Has there been any development or new information related to this issue?

**Comment by sopranopillow** [comment] 2024-01-31 07:54
I wrote a partial fix for this, but as I thought more about this, I think this should be fixed by the consumer. We allow a way to provide a `today` value. This part shouldn't come from our side since as a component library we shouldn't be setting up something to check every certain amount of time if the day has changed. This is something that apps implement on their side. The fix I came up with as to check if the day is out of sync when clicking go to today and if it was, update it. This is not something that we should be doing since the root cause is still an issue. Let me know what your thoughts are on this, I could setup a codesandbox with the setup I mentioned if you would like. Thanks!

**Comment by dinhitcom** [comment] 2024-01-31 10:18
Hi @sopranopillow ,
Your idea sounds great, but I can't find any API in the docs to work with the Go to today button or change the component behaviors. A codesandbow would be great, thank you!

**Comment by sopranopillow** [comment] 2024-01-31 18:15
Here's an example of how to do this @dinhitcom. I'll close this issue, but feel free to reopen if needed.

https://codesandbox.io/p/sandbox/nifty-bohr-pmjnwm?file=%2Fsrc%2Fexample.tsx%3A37%2C8

**Closed by sopranopillow** 2024-01-31 18:15 UTC
Labels: Component: DatePicker, Needs: Attention, Fluent UI react (v8)

**Comment by dinhitcom** [comment] 2024-02-01 02:02
Sorry but the sandbox is not found, can you take a look at it please

**Comment by sopranopillow** [comment] 2024-02-01 16:26
sorry about that, here's the link: https://codesandbox.io/p/sandbox/nifty-bohr-pmjnwm?file=%2Fsrc%2Fexample.tsx

**Comment by dinhitcom** [comment] 2024-02-02 02:22
Sorry for bothering you again, but it's still not found. Looks like the link is identical with the previous one, maybe it's a permission problem?

**Comment by sopranopillow** [comment] 2024-02-05 16:18
@dinhitcom, so sorry for the issues, with the codesandbox update, all codesandboxes are now private by default. I triple checked and this time it should work 😅 [https://codesandbox.io/p/sandbox](https://codesandbox.io/p/sandbox/nifty-bohr-pmjnwm?file=%2Fsrc%2Fexample.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls21ksm200062a654reco0ki%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls21ksm200022a65q07voacx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls21ksm200032a652u683puu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls21ksm200052a65x2ycf3ui%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls21ksm200022a65q07voacx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls21ksm200012a6543a1p2eg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cls3ffwsg00022a687adbwu72%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fexample.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls21ksm200022a65q07voacx%2522%252C%2522activeTabId%2522%253A%2522cls3ffwsg00022a687adbwu72%2522%257D%252C%2522cls21ksm200052a65x2ycf3ui%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls21ksm200042a65diehpq0p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls21ksm200052a65x2ycf3ui%2522%252C%2522activeTabId%2522%253A%2522cls21ksm200042a65diehpq0p%2522%257D%252C%2522cls21ksm200032a652u683puu%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls21ksm200032a652u683puu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
