### ISSUE TITLE
[Bug]: Button missing Block property

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#28533] opened 2023-07-14 20:32 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Fluent v9
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-button-button--default

## Actual Behavior
Feature missing

## Expected Behavior
[fill this out](https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?type=design&node-id=4428-11997&mode=design&t=RbheHJAz3hcuHl53-4)

Previously available in Fluent v0 as a "Fluid" prop
https://fluentsite.z22.web.core.windows.net/0.66.2/components/button/definition
<img width="1706" alt="image" src="https://github.com/microsoft/fluentui/assets/48726002/f62f13d6-5883-4567-ab1d-286b4774b718">

cc: @jurokapsiar , @mako

### Requested priority

High

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment] 2023-07-20 22:24
The dev team decided to deprecate the `block` prop and later removed before the first stable version of `@fluentui/react-components` was released as this behavior is easily achieved via a simple style customization assigning `width: 100%` and, potentially, `flexGrow: 1` to the button.

Duplicate of #27715.

**Closed by khmakoto** 2023-07-20 22:24 UTC
Labels: Fluent UI react-components (v9)
