### ISSUE TITLE
Create website doc/examples for new buttons

### ISSUE THREAD

**Issue by xugao** [microsoft/fluentui#15154] opened 2020-09-21 19:32 UTC
Update the [Button docs](https://developer.microsoft.com/en-us/fluentui#/controls/web/button) to show the new button by default in v8.

Implement the right set of examples for new buttons.

Related: #14638 for showing compat button docs on the website, and adding a way to preview new docs.

**Comment by ecraig12345** [comment] 2020-09-22 07:55
I think this is a duplicate of #14638.

**Comment by xugao** [comment] 2020-09-22 20:27
@ecraig12345 - this issue is to track having good examples for new buttons on the website. we don't really have "website version" of examples for buttons yet. We only have [these](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/15129/merge/react-button/dist-storybook/index.html?path=/story/components--button-focus) today.
However this is definitely related to #14638.

**Comment by khmakoto** [comment] 2021-02-25 00:28
Folding into #16746

**Closed by khmakoto** 2021-02-25 00:28 UTC
Labels: Area: Website, Component: Button
