### ISSUE TITLE
ChoiceGroup doesn't look consistent with WinUI RadioButton

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/fluentui#18387] opened 2021-05-31 08:35 UTC
Seems like ChoiceGroup is using the old design where the circle was inside the border which isn't consistent with WinUI's RadioButton control.

Fluent UI React CheckGroup:
![image](https://user-images.githubusercontent.com/45227503/120165542-4f93f680-c219-11eb-813a-8937bad0f290.png)

WinUI RadioButton:
![image](https://user-images.githubusercontent.com/45227503/120165584-59b5f500-c219-11eb-8feb-e56c39c31ebf.png)
**Ignore the colour difference, that's just because of my system accent colour.**

**Comment by ecraig12345** [comment] 2021-06-03 16:32
This is a duplicate of #16258.

**Closed by ecraig12345** 2021-06-03 16:32 UTC
Labels: Needs: Triage :mag:
