### ISSUE TITLE
[Bug]: Opening the drawer in "overlay" mode removes the scrollbar of the entire page

### ISSUE THREAD

**Issue by pellea** [microsoft/fluentui#31388] opened 2024-05-16 06:23 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
https://react.fluentui.dev/?path=/docs/components-drawer--default
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/?path=/docs/components-drawer--default

## Actual Behavior
Opening the drawer in "overlay" mode removes the scrollbar of the entire page.
The bug is easily reproductible in the docs (https://react.fluentui.dev/?path=/docs/components-drawer--default).

## Expected Behavior
Being able to scroll after opening/closing the drawer.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment] 2024-05-16 08:50
Duplicate of #31369. Fixed in #31367.
I have triggered a release, so it will on NPM soon.

**Closed by layershifter** 2024-05-16 08:50 UTC
Labels: Needs: Triage :mag:, Fluent UI react-components (v9)
