### ISSUE TITLE
[Bug]: Selecting options in Combobox doesn't work when Shift key is pressed

### ISSUE THREAD

**Issue by irynakaban** [microsoft/fluentui#25631] opened 2022-11-11 06:24 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.96 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 94.0.1
    Firefox Developer Edition: 107.0
    Safari: 16.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/irynakaban/pen/rNKyPxP -- code https://drive.google.com/file/d/1ErE5wbAcDhZuEjXBn8XdttxUXQ1bYBih/view?usp=sharing -- video

### Bug Description

This reproduces consistently in Mozilla Firefox browser. Sometimes it doesn't work in Google Chrome and Safari, but it happens randomly enough I couldn't find specific steps to reproduce it. I have not tested other browsers.

onChange or onItemClick are not triggered.

1. Open Combobox menu.
2. Press Shift.
3. Try to click on some option item.

## Actual Behavior
The option item cannot be selected.

## Expected Behavior
The option item can be selected.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment] 2022-11-11 22:22
Duplicate of #25629

**Closed by khmakoto** 2022-11-11 22:22 UTC
Labels: Needs: Triage :mag:, Resolution: Duplicate, Fluent UI react (v8)
