### ISSUE TITLE
DetailsList - Details element loses ability to open/close using keyboard 

### ISSUE THREAD

**Issue by curtisj44** [microsoft/fluentui#22135] opened 2022-03-16 22:43 UTC
### Environment Information

- **Package version(s)**: 8.61.2 (latest as of today)
- **Browser and OS versions**: all

### Describe the issue:

A standard `details` element can be opened and closed with the keyboard (using either the `Enter` and `Space` keys).

However, when a `details` element is inside of `@fluentui/react`’s `DetailsList` this keyboard functionality doesn't work.

Here's a demo: https://codepen.io/curtisj44/pen/bGadKJV

#### Actual behavior:

A `details` element can be opened and closed using a mouse, but, when the `summary` element has focus, the `Enter` and `Space` keys do nothing.

#### Expected behavior:

I was expecting a `details` element to work the same inside of a `DetailsList` as outside.

### Documentation describing expected behavior

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
- https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element

**Comment by micahgodbolt** [comment] 2022-04-11 19:29
Looks like the issue is focus. When you highlight a row and press right the link and button cells get focus, but the details does not. Seems something we could fix.

**Comment by JustSlone** [comment] 2022-09-12 17:46
assigning to @microsoft/cxe-red to look into

**Closed** 2022-10-25 20:17 UTC
Labels: Type: Bug :bug:, Component: DetailsList, Status: In PR
