### ISSUE TITLE
Masked Input Cursor Control

### ISSUE THREAD

**Issue by dynamite-ready** [microsoft/fluentui#13755] opened 2020-06-23 09:25 UTC
The issue I'm raising has already been identified in the following link:

https://github.com/microsoft/fluentui/issues/11323#issue-529493331

This image best illustrates the issue:

![image](https://user-images.githubusercontent.com/1434956/69746739-cb2f5780-10f9-11ea-85d8-b844bc16734f.gif)

However, the other issue was closed without a resolution, so wondered about the change of status.

Edit - Updated to add an animated `.gif` to illustrate the issue.

**Comment by paulgildea** [comment] 2020-06-24 22:28
@dynamite-ready Thanks for bringing this back up. I looked at #11323 and I wasn't able to understand the expected behavior was supposed to be.

Could you possibly update this issue using the Bug Template: https://github.com/microsoft/fluentui/issues/new?template=bug_report.md

Thanks!

PG

**Comment by dynamite-ready** [comment] 2020-06-26 09:11
Sure. Will try to find some time.

**Comment by paulgildea** [comment] 2020-07-02 16:49
Dupe of #13820

**Closed** 2020-07-02 16:49 UTC
Labels: Component: MaskedTextField, Resolution: Duplicate, Type: Bug :bug:
