### ISSUE TITLE
[Bug]: Switch component thumb off vertical center

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#23552] opened 2022-06-14 23:10 UTC
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/components-switch--default
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/components-switch--default

### Bug Description

![image](https://user-images.githubusercontent.com/48726002/173703928-a4cf2b77-ab7e-4105-be25-a58e0f66c6d3.png)

Thumb should be vertically centered: https://www.figma.com/file/TPQVDN5cxYBqkP9urETsCp/Switch?node-id=655%3A1174

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment] 2022-06-23 22:38
Duplicate of #23470

**Closed by khmakoto** 2022-06-23 22:38 UTC
Labels: Needs: Backlog review, Fluent UI vNext, Design Pass, Component: Switch
