### ISSUE TITLE
Tooltip always labels the component that triggered it

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#20115] opened 2021-10-06 00:26 UTC
The `Tooltip` component is, by default, applying its content as the `aria-label` of its trigger. This should not happen by default and be opt-in functionality.

**Comment by jurokapsiar** [comment] 2021-11-24 10:15
@behowell, @khmakoto I think this should be closed as 'by design'. Do you think it should be changed?

**Comment by behowell** [comment] 2021-11-29 20:31
@khmakoto I'm going to close this as by design, per @jurokapsiar's comments. Let me know if you disagree.

**Closed by behowell** 2021-11-29 20:31 UTC
Labels: Priority 2: Normal, Component: Tooltip, Fluent UI vNext
