### ISSUE TITLE
Dropdown component used inside the CommandBar component is getting overlapped with the far items. (office-ui-fabric-react))

### ISSUE THREAD

**Issue by niravkapoor** [microsoft/fluentui#21063] opened 2021-12-15 13:47 UTC
### Environment Information

- **Package version(s)**: 7.121.7 (office-ui-fabric-react)
- **Browser and OS versions**: Electron 10.4.7 x64 build 10230287

### Please provide a reproduction of the bug in a codepen:
Created the sample in [codesandbox.io](https://codesandbox.io/s/formik-office-ui-fabric-react-example-forked-6gr47?file=/src/index.tsx)

#### Actual behavior:

![image](https://user-images.githubusercontent.com/19341548/146197229-97341a28-ee3f-456d-b92e-0ad891c3f199.png)

In above screenshot, we can see the dropdown is getting overlapped with the options button.

#### Expected behavior:

It should get auto adjust, overlapping dropdown should move to overflow items.

### Priorities and help requested:

Are you willing to submit a PR to fix? : No

Requested priority: High

Products/sites affected: **MS Teams App**

**Comment by layershifter** [comment] 2021-12-15 13:55
Hey, thanks for reporting. I checked the CodeSandbox and cannot repro it on the latest Chrome:

![overflow-cmd](https://user-images.githubusercontent.com/14183168/146199176-3a11cb41-d4ff-4714-9eb6-f0a501fe8710.gif)

If it reproducible only in Electron environment?

**Comment by niravkapoor** [comment] 2021-12-15 14:01
Above pasted screenshot is also from the google chrome.
Tried it again: 

![image](https://user-images.githubusercontent.com/19341548/146200233-b3039663-135c-4217-bf96-e7dfd79ecfa7.png)

**Comment by layershifter** [comment] 2021-12-15 15:40
@niravkapoor not sure that I understand how to reproduce this state. I tried different resolutions and it works properly. Can you please provide more details how to get into this state?

**Comment by niravkapoor** [comment] 2021-12-16 06:57
@layershifter Kindly refer this recording for the resolution, on which i am able to repro this. I am simply loading the codesandbox url and changing the screen resolution. We can connect offline and i can also show you the steps on Teams app

https://user-images.githubusercontent.com/19341548/146322838-3595b3e6-d77f-4952-93a9-ef5dc96eef46.mov

.

**Comment by layershifter** [comment] 2021-12-16 16:26
Sorry, I am struggling to reproduce that on CodeSandbox, but I bet that I was able to do it in evening 🙄 That's insane...
Let's chat on Teams about it.

**Comment by layershifter** [comment] 2021-12-20 10:02
I had a call with @niravkapoor, it's a bit more complex to repro.

- Open CodeSandbox app in a separate tab (https://6gr47.csb.app/)
- Open DevTools
- Resize window to something like ~800x850
- Then it happens 💥

![image](https://user-images.githubusercontent.com/14183168/146749493-f5fa0fa3-db04-4991-be06-04110002d089.png)

**Comment by layershifter** [comment] 2021-12-30 09:35
The "problem" happens in `ResizeGroup` and is present in both v7 & v8. The following CodeSandbox can be used for reference (https://6gr47.csb.app/).

## What is happening?

`ResizeGroup` relies on `.scrollWidth` computed on a hidden `div` element (it also has `position: fixed`):

https://github.com/microsoft/fluentui/blob/bba4d3be79a76530b31bdcc509253d010b7c1777/packages/office-ui-fabric-react/src/components/ResizeGroup/ResizeGroup.base.tsx#L367-L371

https://github.com/microsoft/fluentui/blob/bba4d3be79a76530b31bdcc509253d010b7c1777/packages/office-ui-fabric-react/src/components/ResizeGroup/ResizeGroup.base.tsx#L430-L432

The issue comes when `width` of elements is bigger than `width` of a `window` and all elements does not fit into page. In the same time `ResizeGroup` uses cache to store measurements permanently:

![image](https://user-images.githubusercontent.com/14183168/147489734-caac23e3-7f5a-47d3-a525-b351a0e57d89.png)

It's impossible to reset/refresh these measurements while they are not entirely correct.

## Why it is happening?

I built [a simpler demo on CodeSandbox](https://codesandbox.io/s/loving-hooks-r3g5i?file=/src/App.js) (**reload after each window resize**):

![image](https://user-images.githubusercontent.com/14183168/147738575-33409642-178a-430f-a00e-348cc5e5ba59.png)

![image](https://user-images.githubusercontent.com/14183168/147738615-5cbdb6a3-78b2-49b3-9a73-d54e8e8187b3.png)

👆 _Notice what is happening on these two screenshots: elements do not fit and buttons shrink, it's default behavior._

And it's what happening in the described issue:
- buttons shrink
- measurements are permanently cached for **shrinked buttons**
- a page is resized and buttons fit, but measurements are invalid
- collision 💥

## Workaround

The simplest workaround is to use either fixed width on items or add `whiteSpace: 'nowrap'` to `CommandBarButton` via style overrides 👇

```tsx
const getCopyLinkButton = () => ({
  key: 'calv2-copy-link',
  onRender: (props) => (
    <CommandBarButton
      style={{ border: '5px solid blue', whiteSpace: 'nowrap' }}
    >
      Copy link Copy link Copy link Copy link
    </CommandBarButton>
  )
})
```

[Complete demo on CSB](https://codesandbox.io/s/formik-office-ui-fabric-react-example-forked-075t4)

## Fix?

@gouttierre Not sure how it should be fixed as it's how `ResizeGroup` works by design. IMO:
- `CommandBarButton` should have `whiteSpace: 'nowrap'` in its styles to prevent this issue
- `ResizeGroup` and `CommandBar` has `.remeasure()` method on `componentRef` - the problem is that it does not reset cache and customers can't do anything with it. My proposal is to update the method to also reset measurements or add a new one for this specific job.

**Closed** 2022-07-04 16:00 UTC
Labels: Component: CommandBar, Needs: Backlog review, Fluent UI react (v8), Resolution: Soft Close, Fluent UI react (v7)
