### ISSUE TITLE
[Feature]: Add the ability to open or close NavCategory from outside the component (@fluentui/react-nav-preview).

### ISSUE THREAD

**Issue by kkamik** [microsoft/fluentui#32886] opened 2024-09-23 08:56 UTC
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Proposal for @fluentui/react-nav-preview:

Add the ability to open or close NavCategory from outside the component. I need a prop to control this state from the parent component.

Opened state: 
<img width="907" alt="image" src="https://github.com/user-attachments/assets/5d180fa8-6016-4b4b-a951-6589c645fdb1">

Closed state:
<img width="925" alt="image" src="https://github.com/user-attachments/assets/c50aaa1a-30f6-40d2-880e-cee2b325e1b2">

### Additional context

I have many different pages.
Since the "Layouts" of the pages are constantly changing (they're really different, and I can't use react-router "Layout"), I can't avoid re-renders.
However, because the default state is 'closed' during initialization, the `NavCategory` closes every time I switch pages, which is really frustrating.

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

High

**Comment by dmytrokirpa** [comment] 2024-09-23 13:20
Duplicate of the https://github.com/microsoft/fluentui/issues/32877, the `defaultOpenCategories` and `openCategories` are available and documented on the website https://react.fluentui.dev/?path=/docs/preview-components-nav--docs#nav-drawer-default

<img width="1773" alt="Screenshot 2024-09-23 at 15 16 50" src="https://github.com/user-attachments/assets/e9d8a0bc-fca4-42a9-a492-9ca301750d19">

**Comment by dmytrokirpa** [comment] 2024-09-23 13:21
@kkamik Feel free to reopen the issue, if the proposed solution doesn't cover your use case.

**Closed** 2024-09-23 13:20 UTC
Labels: Type: Feature, Resolution: Duplicate, Fluent UI react-components (v9)
