### ISSUE TITLE
merge-styles interferes with Dark Reader in Dynamic mode

### ISSUE THREAD

**Issue by alexanderby** [microsoft/fluentui#14735] opened 2020-08-25 14:39 UTC
### Environment Information

- **Package version(s)**: merge-styles@7.4.1

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/alexanderby/pen/abNJJYm

#### Actual behavior:

- The content of the web page is blinking.

- Merge Styles removes Dark Reader's style element, Dark Reader restores it 10 times, then detects a conflict, and repeats in 2 seconds.

#### Expected behavior:

- The background is dark, text is light.

- Dark Reader's style is preserved.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe

Requested priority: Normal

Products/sites affected: Word Online

A quick note how Dark Reader works in Dynamic mode: when it meets a style, it iterates through all CSS rules, creates another style, where color values are changed to dark backgrounds and light texts, and puts this style right after the source style element. Then it uses MutationObserver to detect if the style override was removed and restores it.

[Dark Reader](https://darkreader.org/) is an accessibility extension with 2,000,000+ users, an Editor's Pick for Edge, Chrome and Firefox. It is also available as [NPM](https://www.npmjs.com/package/darkreader) package.

**Comment by paulgildea** [comment] 2020-08-25 16:06
@alexanderby Thanks for the feedback.

At first glance, it sounds like this extension manipulates styles without the knowledge of the application which could lead to unexpected behavior. I just applied the extension while looking at something like gmail and some of my UI actually disappeared. 

I think the goal of the extension is awesome because it's providing users with customizations to serve their contrast and brightness needs, however, swapping out style elements without the apps knowledge seems like it could lead to an unpredictable user experience.

I just don't know how to proceed technically without fundamentally changing the way `merge-styles` behaves.

@dzearing Do you have any thoughts here? I'm unclear if there is generalized solution in `merge-styles` to accommodate these types of extensions that dynamically manipulate style elements without regressing the current performance of applications that leverage it today.

**Comment by Gusted** [comment] 2020-08-25 16:15
>  I just applied the extension while looking at something like gmail and some of my UI actually disappeared.

That could be fixed by a refresh as especially Gmail is pretty heavy in CSS and could lead to that kind of bugs.

> swapping out style elements

Ho, let's not get a misunderstanding right away. We are actually adding a stylesheet element after the original style position with all modified CSS from that style so it won't touch the original style.
Also it's seems to be switching styles the `--sync`(the modified stylesheet with it's CSS from previous style) ![](https://i.imgur.com/6qnPaiB.gif). It so far only occurs with `merge-style` and some other CSS libraries as I'm further investigating some other reported sites.

It's more like this issue, it could be a bug that it's touching the wrong style element and a simple check to only target it's own styles could fix this issue 🤷🏽‍♀️. 

Regards,
Gusted

**Comment by dzearing** [comment] 2020-08-25 18:45
Hey @Gusted ! This seems like a bug in darkreader's style syncing. Here's what happens:

1. DarkReader is enabled. The darkreader styles are set up.
2. `mergeStyleSets` is called, appending the white body background. A style element is inserted, and the DarkReader sync element correctly updates to render a body background of black.

![image](https://user-images.githubusercontent.com/1110944/91214304-bbb05f80-e6c7-11ea-9a1c-1c89b67256b2.png)

3. In the `setTimeout`, we call `mergeStyleSets` again, which will insert another style element after the initial merge-styles style element. However, this is where the bug is:

Expected:

DarkReader's sync element should now have 3 rules: the body plus the 2 new colors.

Resulted: the body disappeared and now the sync element only has the 2 new colors. Body is gone from the sync styling, so it falls back to the original merge-styles issue.

![image](https://user-images.githubusercontent.com/1110944/91214760-69bc0980-e6c8-11ea-92f5-9792726c16e0.png)

**Comment by dzearing** [comment] 2020-08-25 18:47
Tip: to debug this, you can increase the setTimeout to like 20 seconds, so that you have enough time to right click on the `head` element and select "break on subtree modification".

**Comment by Gusted** [comment] 2020-08-25 19:31
Well, I just recreated a case with some *stolen* code from https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/src/Stylesheet.ts#L303 and got [codepen](https://codepen.io/Gusted/pen/gOrmXeL) out of it. And it seems like Merge-Styles just gave it a good reproduce-able case with this weird bug on our side. Seems like back to debugging our code but this time having a good controllable reproduce case. Anyway thanks for the support! Even it wasn't merge-styles fault after all 😅 Sorry for taking your time.

Regards,
Gusted

**Comment by dzearing** [comment] 2020-08-25 19:36
No worries @Gusted; please feel free to leverage whatever code helps reduce the issue for you, and let us know if you run into any other issues, happy to help and keep up the good work, your plugin is great! :)

**Closed by dzearing** 2020-08-25 19:36 UTC
Labels: Fluent UI react, Needs: Investigation, Package: merge-styles

**Comment by paulgildea** [comment] 2020-08-26 16:13
@Gusted Thanks for reaching out in the first place! Glad @dzearing could help!
