### ISSUE TITLE
Narrator doesn't read out <headerText> dialog in Panel component when custom header view is passed through onRenderHeader property

### ISSUE THREAD

**Issue by chihch** [microsoft/fluentui#12704] opened 2020-04-15 16:48 UTC
### Environment Information

- **Package version(s)**: 7.94.0, but can also repo on CodePen
- **Browser and OS versions**: windows 10

### Describe the issue:

Using <Panel> component with custom header view, a simple <h1 id={'headerId'}> view with text, NVDA narrator cannot read out <headerText> dialog when panel is opened. Narrator is working fine when using default header view by just passing in headerText. I believe the issue is in Panel.base.tsx that ariaLabelledBy of <Popup> component cannot map to the id of custom passed in header view.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/chihch/pen/eYpJRJV

#### Actual behavior:

when Panel is opened, using keyboard navigation to get to panel, it only reads out "dialog"

#### Expected behavior:

it is expected to hear "<headerText> dialog"

**Comment by joschect** [comment] 2020-04-16 02:09
@chihch Thanks for the submission! It seems likely that the ariaLabelledBy mismatch is a good candidate for being the cause of this problem. We do enable you to use the id that the Panel passes down to its header through the onRenderHeader callback. Here's a modified version of your [codepen](https://codepen.io/slimemold/pen/MWaKBvQ?editors=0010) that uses the headerId that is passed through to onRenderHeader.

**Comment by chihch** [comment] 2020-04-16 16:22
Hi @joschect  Thanks for your quick reply. I did try passing an id in my custom header view down to <Panel> but it didn't work. By looking at your modified version I know where the issue was. It is because my 'onRenderHeader' doesn't have correct signature. I was using

`() => JSX.Element`

rather than using

(props, defaultRender, headerId) => JSX.Element

**Comment by joschect** [comment] 2020-05-01 18:20
@chihch I'm glad that this worked! Yes we can close this.

**Closed by joschect** 2020-05-01 18:20 UTC
Labels: Issue Pinged, Needs: Attention :wave:
