### ISSUE TITLE
Screen Reader(Narrator)  is not reading regarding sort buttons click(ascending/descending) present in DetailsList header.

### ISSUE THREAD

**Issue by v-ajrai** [microsoft/fluentui#12403] opened 2020-03-24 09:56 UTC
Screen Reader(Narrator)  is not reading regarding sort buttons click(ascending/descending) present in DetailsList header.

### Environment Information

OS: Win 10 Enterprise N
Browser:  Edge
Screen Reader: Narrator 

### Describe the issue:

Screen Reader(Narrator)  is not reading anything regarding sort buttons click(ascending/descending) present in DetailsList header. It should read once sorting is done on header column.
See attachment

![1328134_External](https://user-images.githubusercontent.com/62233982/77412639-25a89e00-6de4-11ea-9898-6332ac391d5c.png)

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/customitemcolumns

#### Actual behavior:

Screen Reader(Narrator)  is not reading anything regarding sort buttons click(ascending/descending) present in DetailsList header.

#### Expected behavior:

Screen Reader(Narrator)  should read regarding sort buttons click(ascending/descending) present in DetailsList header.

**Comment by aneeshack4** [comment] 2020-03-24 23:29
@v-ajrai There's no sort button on that custom item columns page. What are you referring to?

**Comment by v-ajrai** [comment] 2020-03-25 07:36
Hello  Aneesha,

If you change line height of div which embedded ChoiceGroup control, then you can repro it, as you can see in our shared code pen example where we changed the line height of div in HTML code

Regards
Ajeet Kumar Rai

**Comment by aneeshack4** [comment] 2020-03-31 04:09
@v-ajrai I see - this is a dupe of #11564. It works correctly in Anaheim (Chrome Edge) as reported by #12408 [comment](https://github.com/microsoft/fluentui/issues/12408#issuecomment-603560524). Old Edge didn't pick up on it as explained in this comment: #11564 (comment). Going to close as external (browser).

**Closed by aneeshack4** 2020-03-31 04:09 UTC
Labels: Component: DetailsList, Needs: Attention :wave:
