### ISSUE TITLE
Dropdown in v0.47.1 + v0.48.0: Loading displayed white in dark/HC theme

### ISSUE THREAD

**Issue by techienickb** [microsoft/fluentui#12794] opened 2020-04-21 10:28 UTC
### Environment Information

- **Package version(s)**: 0.47.1 & 0.48.0
- **Browser and OS versions**: Firefox Nightly

### Please provide a reproduction of the bug in a codepen:

Switch to 0.47.1 or 0.48.0 from 0.47.0

#### Actual behavior:
Search dropdown loading displayed in white
<img width="215" alt="Annotation 2020-04-21 111201" src="https://user-images.githubusercontent.com/14252821/79854217-0ab85200-83c1-11ea-95d7-c14060fdefa7.png">

When selecting an item onSearchQueryChange is called after onChange
<img width="100" alt="Annotation 2020-04-21 112449" src="https://user-images.githubusercontent.com/14252821/79855334-bdd57b00-83c2-11ea-8725-3c8fa3a60851.png">

#### Expected behavior:

Dropdown Loading should should use the theme provider (as per ### v0.47.0)
<img width="167" alt="Annotation 2020-04-21 111838" src="https://user-images.githubusercontent.com/14252821/79855398-d180e180-83c2-11ea-88ad-062b7047f57e.png">

onSearchQueryChange should be called before onChange is called (as per v0.47.0)
<img width="155" alt="Annotation 2020-04-21 112213" src="https://user-images.githubusercontent.com/14252821/79855105-6afbc380-83c2-11ea-96d0-f81efd047056.png">

**Comment by silviuaavram** [comment] 2020-04-27 09:26
I don't see any reason to expect an order when it comes to calling handlers. Why do you consider this to be important?

As for the style change it probably makes sense since the loading item is now a DropdownItem and not a ListItem, and styles changed as a result. We can get redlines/expected behavior from Design and make changes if necessary.

**Comment by techienickb** [comment] 2020-04-27 09:42
@silviuaavram the previous behaviour (0.47.0) meant that the onchange was after the onsearchquerychange, this is what I would expect and have used. The new behaviour means that when onchange is called the actions onchange make can be overridden by onsearchquerychange because it's called after onchange. 

The loading item is from using the loading prop, hopefully it's just a bug in the styling of the item

**Comment by silviuaavram** [comment] 2020-04-27 09:53
Well it depends how you use onChange and onSearchQueryChange. Both are called with the same parameter, so if you are executing actions that are not isolated from one another probably you should execute that part in only one handler.

**Comment by techienickb** [comment] 2020-04-27 10:07
In my code onchange looks at the selected item's header and stores that in state.  Onsearchquerychange clears that value from state to prevent a user from submitting a query with a incorrectly selected item.  Code works brilliantly in v0.47, breaks in v0.48 as onsearchquerychange is being called after onchange.

**Comment by silviuaavram** [comment] 2020-04-27 10:35
It looks like the implementation is fragile. But I think we can improve it. Is it possible to have a look at the use case via a sandbox or something similar?

**Comment by techienickb** [comment] 2020-04-27 11:10
It's an internal app, but I've put some code up on https://codesandbox.io/s/fluent-ui-example-0pgve, it's not the most elegant code, I need to clean it up a bit more.  A chuck of stuff has been removed

**Comment by silviuaavram** [comment] 2020-04-27 12:47
So I looked briefly at the code.

I would suggest to clearly separate what you expect to happen on select, and what you expect to happen on searchQuery change. Don't handle the same flow in two different handlers. That is fragile.

onSearchQueryChange is called on both changing the input and selecting an item, if that requires to put a string version of the new selected item in the input. You can distinguish this second case easily, in onSearchQueryChange, by checking in there is `value` passed to the handler. If it is, then it means the user performed selection. If not, it means the user just changed the input.

I am sure if you define your use case and have a separate action for each case, the issue will be fixed. At least in my opinion, you should not rely on the order of the calls. These will be called on the next render, if state changed, but their order should not matter.

**Comment by silviuaavram** [comment] 2020-04-27 12:51
I can help you further if you want, but I need a clear spec of what you expect to happen in each situation. :)

**Comment by techienickb** [comment] 2020-04-27 13:04
I didn't think of checking the value prop is passed, that's a good idea.

My main concern was around the change of functionality, my code used to work fine in 0.47.0 and got broke in v0.47.1, the only difference is the order the onchange events are trigged by northstar

**Comment by techienickb** [comment] 2020-04-27 13:17
That at least makes the code work but doesn't work as intended.  When you change the search value I would expect it to clear the selected item if you are only in single selection mode (which I am).  What I see at the moment is I can select an item, then change the search string, the item is still selected but the text in the dropdown text box is the search item which to an end user could be confusing

**Comment by silviuaavram** [comment] 2020-04-27 13:21
If that's the scenario you want, in onSearchQueryChange check if there is no value and if so, clear the value from your state. Should work.

With this being a general practice I am not sure I agree with. If you want to clear your value you should be explicit about the action (escape, clear all input, use X icon if dropdown is `clearable`).

But if that's your use case then I hope we found a solution :)

**Comment by techienickb** [comment] 2020-04-27 13:44
Ok, I'll adjust my code to work with the new method.  I liked the old way it worked.

Onto the other bug, the loading setting not inheriting the theme set in the provider, is that a bug?  Again worked fine in 0.47.0, 47.1 it's white regardless of the theme chosen

**Comment by silviuaavram** [comment] 2020-04-27 13:45
Yes, the styling issue is being tracked and prioritised.

**Comment by jurokapsiar** [comment] 2020-04-27 13:49
I have renamed the issue to reflect styling only, so that we can plan this part.

**Comment by techienickb** [comment] 2020-04-27 13:49
nice, I'll wait for that release :-).

northstar is a lot nicer to work with in teams than the fabric stuff

**Comment by jurokapsiar** [comment] 2020-05-10 14:33
Tracking Reference: 7400 (used for team planning)

**Comment by jurokapsiar** [comment] 2020-05-21 04:21
Fixed in https://github.com/microsoft/fluentui/pull/13108

**Closed by jurokapsiar** 2020-05-21 04:21 UTC
Labels: Fluent UI v0
