### ISSUE TITLE
Out of memory- DetailsList examples

### ISSUE THREAD

**Issue by abdollahkahne** [microsoft/fluentui#12754] opened 2020-04-17 01:34 UTC
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Linux Ubuntu-Mozilla Firefox

### Describe the issue:

When I open the page related to this component to study documentations and examples, After pressing View Code and some scrolling, Browser Crashes! I try this with two different browsers (Mozilla and Chrome) and unfortunately both of them crashed.  I think there is some performance issue related to the example over there! I will appreciate if someone test it and share the result here.
Thanks in advance

**Comment by vist0r** [comment] 2020-04-17 07:50
Yes, I have same issue, first open https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/innernavigation then ciick 'show code', the browser crashed.

**Comment by 3YH** [comment] 2020-04-17 09:51
Same issue on List https://developer.microsoft.com/en-us/fluentui#/controls/web/list

**Comment by donschaefer** [comment] 2020-04-17 20:37
Same issue on https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customgroupheaders

**Comment by dzearing** [comment] 2020-04-17 21:03
Is this on Windows or Mac? Or either?

**Comment by dzearing** [comment] 2020-04-17 21:06
Reproing!

**Comment by dzearing** [comment] 2020-04-17 23:42
useEditor=0 qs param disables the live code editor, which seems to be causing the looping issue. Looking for a fix, but if we can't find one, I'll temporarily disable this feature.

**Comment by joschect** [comment] 2020-04-18 01:01
This is a dupe of #12643

**Comment by dzearing** [comment] 2020-04-19 02:39
We've disabled the code editing, so you should be able to view the examples now. We'll investigate what's going on more deeply and re-enable the editing feature once we have the right fix. Sorry for the trouble.

**Comment by ecraig12345** [comment] 2020-04-21 01:01
The crash should be unrelated to the foreign module error in the console (that's been around for awhile and has a different cause we haven't had time to address, and doesn't prevent the editor from working). Something is causing an infinite rendering loop, possibly related to measuring/resizing. The `EditorErrorHandler` error boundary component may also be handling things incorrectly.

**Comment by abdollahkahne** [comment] 2020-04-21 02:44
Unfortunately I exprienced something similar in the following Code Which It removed after I edited my code as the second version:
The Buggy Version
```
export default class Tasks extends React.Component<ITasksProps, ITasksState> {
  protected SPClient: SPClient;
  constructor(props) {
    super(props);
    this.state = { items: [] };
    this.SPClient = new SPClient(this.props.webPartContext);
    // this._getItems();
  }
  private _getItems() {
    if (Environment.type == EnvironmentType.Local) {
      MockSPClient.get("http://").then((data: ISPListItem[]) => {
        this.setState({ items: [...data] });
      });
    } else {
      this.SPClient.getRecentItems().then((data: ISPListItem[]) => {
        this.setState({ items: [...data] });
      });
    }
  }

  private _showPanel(item: any, idx: number, e: any) {
    console.log("Panel should Open now for item with Index: ", idx);
  }

  public render(): React.ReactElement<ITasksProps> {
    this._getItems();
    const items = this.state.items;
    return (
      <div>
        <div>
          <DetailsList
            items={items}
            columns={selectedColumns}
            onActiveItemChanged={this._showPanel.bind(this)}
          />
        </div>
        <div>
          <h4>Add New Assignments</h4>
        </div>
        <NewTask
          webPartContext={this.props.webPartContext}
          onSaveCompleted={this._getItems.bind(this)}
        />
      </div>
    );
  }
}
```




The Correct Version:
```
export default class Tasks extends React.Component<ITasksProps, ITasksState> {
  protected SPClient: SPClient;
  constructor(props) {
    super(props);
    this.state = { items: [] };
    this.SPClient = new SPClient(this.props.webPartContext);
    this._getItems();
  }
  private _getItems() {
    if (Environment.type == EnvironmentType.Local) {
      MockSPClient.get("http://").then((data: ISPListItem[]) => {
        this.setState({ items: [...data] });
      });
    } else {
      this.SPClient.getRecentItems().then((data: ISPListItem[]) => {
        this.setState({ items: [...data] });
      });
    }
  }

  private _showPanel(item: any, idx: number, e: any) {
    console.log("Panel should Open now for item with Index: ", idx);
  }

  public render(): React.ReactElement<ITasksProps> {
    const items = this.state.items;
    return (
      <div>
        <div>
          <DetailsList
            items={items}
            columns={selectedColumns}
            onActiveItemChanged={this._showPanel.bind(this)}
          />
        </div>
        <div>
          <h4>Add New Assignments</h4>
        </div>
        <NewTask
          webPartContext={this.props.webPartContext}
          onSaveCompleted={this._getItems.bind(this)}
        />
      </div>
    );
  }
}
```

The diffrenece is where I initialized my items state! If I move it to constructore it works fine but at the render function it loops!
Thanks for addressing!

**Comment by abdollahkahne** [comment] 2020-04-21 02:47
I think you can test something simple considering the point where you initialized the items state and then check if you have the warning related to the kill script!

**Comment by abdollahkahne** [comment] 2020-04-21 03:12
I don't see the issue now and I could scroll smoothly. Thanks

**Closed** 2020-07-17 23:29 UTC
Labels: Area: Website, Status: In PR, Type: Bug :bug:
