### ISSUE TITLE
Fluent UI v0 inverted button text is not visible

### ISSUE THREAD

**Issue by pompomon** [microsoft/fluentui#15911] opened 2020-11-11 17:58 UTC
### Environment Information

- **Package version(s)**: 0.51.2

### Please provide a reproduction of the bug in a codepen:

`Button` component has incorrect text color for `inverted`

https://codesandbox.io/s/hopeful-dawn-7qyst?file=/example.js

#### Actual behavior:

Text is not visible for all themes `default`, `dark`, `high-contrast`

#### Expected behavior:

Text is visible and has enough contrast

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by paulgildea** [comment] 2020-11-12 16:38
@pompomon Thanks! You've got it!

**Comment by assuncaocharles** [comment] 2020-12-01 12:32
Closing it since it's not a bug, the correct usage for `inverted` button depends on its container background as in the example:

```jsx
<Flex
    gap="gap.smaller"
    styles={({ theme: { siteVariables } }) => ({
      backgroundColor: siteVariables.colorScheme.brand.background2,
      padding: '20px',
    })}
  >
    <Button inverted content="Inverted Button" />
</Flex>
```

**Closed** 2020-12-01 12:32 UTC
Labels: Component: Button, Fluent UI react-northstar, Needs: Investigation
