### ISSUE TITLE
[Bug]: Panel onDismissed never called when using React 18's createRoot

### ISSUE THREAD

**Issue by NickSevens** [microsoft/fluentui#26782] opened 2023-02-09 13:01 UTC
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 13.80 GB / 31.78 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @fluentui/react: ^8.0.0 => 8.105.5
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/nicksevens/pen/MWBMeBE

## Actual Behavior
`onDismissed` is never called when closing a `Panel` when using React 18's createRoot API. When using `ReactDOM.render` or an older version of React, it _does_ work.

## Expected Behavior
`onDismissed` should be called after closing a `Panel` when using `createRoot`, in the same way as it does when using React <=17's `ReactDOM.render`.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment] 2023-02-09 16:01
duplicate of #26256

**Closed by micahgodbolt** 2023-02-09 16:01 UTC
Labels: Needs: Triage :mag:, Fluent UI react (v8)
