### ISSUE TITLE
website bugs reporting

### ISSUE THREAD

**Issue by sagarat24** [microsoft/fluentui#23213] opened 2022-05-25 08:00 UTC
![image](https://user-images.githubusercontent.com/46018258/170211259-437725a8-2bad-4914-8dc1-128ac7b528e0.png)

Side menu bar is not visible when direct open a page URL.
I found this issue on following URL.
https://developer.microsoft.com/en-us/fluentui#/controls/crossplatform/text

**Comment by gouttierre** [comment] 2022-06-14 09:44
@sagarat24 - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance.

cc @ejlayne: React-native control documentation and site usage needs to be reviewed.

**Comment by JustSlone** [comment] 2022-10-23 21:44
Seeing repro on the first issue, but not seeing the "Back to Top" button appear (tho maybe that's a different issue) 

Tagging @micahgodbolt, @sopranopillow, and @khmakoto spiritual owners of the existing website.
CC: @tudorpopams

**Comment by sopranopillow** [comment] 2022-10-24 17:33
For further information, this link actually shouldn't be working. The first image is showing React's Text page, but the link given points to the crossplatform version. This link is the one that points to it:

![image](https://user-images.githubusercontent.com/5953191/197589585-4e161199-3130-476f-bf56-3e13aa383e3e.png)

**Comment by sopranopillow** [comment] 2022-10-24 17:56
For the second bug, it's already been fixed by #24745 and that's why @JustSlone couldn't repro.

**Comment by JustSlone** [comment] 2022-10-24 18:06
@sopranopillow, so this means both these issues are fixed or by design? If so, let's close out the issue. Thanks for pointing these out @sagarat24!

**Comment by sopranopillow** [comment] 2022-10-24 20:19
@JustSlone I have to dig deeper on the first one, so I'll investigate it. I'll assign the bug to myself.

**Comment by sopranopillow** [comment] 2022-10-30 03:06
@sagarat24 Thanks for reporting this issue! Turns out some of our links were breaking our hash routing, see the linked PR for more details :)

**Closed** 2022-10-31 19:03 UTC
Labels: Area: Documentation, Area: Website, Status: In PR, Area: React Native
