### ISSUE TITLE
Update peerDependencies for @fluentui/react-northstar

### ISSUE THREAD

**Issue by dhruvit-r** [microsoft/fluentui#21624] opened 2022-02-07 11:43 UTC
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.60.1
- **Browser and OS versions**: macOS 12.1, Brave Version 1.35.100, Chromium: 98.0.4758.87 (Official Build) (arm64)

### Describe the issue:

https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar/package.json#L63

@fluentui/react-northstar has a few outdated peerDependencies. `react` is pinned to `^16.8.0` and `react-dom` is pinned to `^16.8.0`. React 17 has been released with very few breaking changes, so this'll probably be a trivial update to the packaje.json file.

#### Actual behavior:

Peer Dependencies are not up to date.

#### Expected behavior:

Peer Dependencies should be up to date.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix?: Yes if it's a simple update to package.json and tests pass

Requested priority: Low

Products/sites affected: Not Applicable

**Comment by gouttierre** [comment] 2022-02-14 14:00
@dhruvit-r - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@jurokapsiar- Would your team be able to review this issue when bandwidth opens up? Thanks

**Comment by jurokapsiar** [comment] 2022-03-10 16:35
Duplicate of #21082

**Closed by jurokapsiar** 2022-03-10 16:35 UTC
Labels: Fluent UI react-northstar, Needs: Investigation
